### ISSUE TITLE
Caricamento metadata Regione Emilia Romagna

### ISSUE THREAD

**Issue by umbros** [italia/spid#10]
Richiesta da Lepida (Regione Emilia Romagna)

Buongiorno Umberto,
segnalo un nuovo servizio in attivazione:

Nome: Servizi Scolastici OnLine - Unione di Comuni della Romagna Forlivese
Attributi: email,familyName,fiscalNumber,name,spidCode
Livello SPID: 2

**Comment by AntonioGiovanniSchiavone** [comment]
Metadata deployato presso gli IdP
