### ISSUE TITLE
Richiesta caricamento metadata per Regione Emilia Romagna

### ISSUE THREAD

**Issue by chiaracaniggia** [italia/spid#100]
Richiesta da Lepida (Regione Emilia Romagna)

Buongiorno,
segnalo un nuovo servizio in attivazione:

Nome: Bandi di cooperazione internazionale allo sviluppo - Regione Emilia-Romagna
Attributi: dateOfBirth,familyName,fiscalNumber,name,spidCode
Livello SPID: 2

Grazie
saluti
Chiara Caniggia

**Comment by AntonioGiovanniSchiavone** [comment]
Richiesta risolta dall'issue #140
