### ISSUE TITLE
Comune di Prato - Richiesta di verifica e deploy metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#1000]
Buongiorno,
per conto del Comune di Prato chiediamo la verifica e il deploy di questi metadati: https://servizi.comune.prato.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
