### ISSUE TITLE
Richiesta di validazione dei metadati - Consorzio Ats

### ISSUE THREAD

**Issue by globogis** [italia/spid#1001]
Buongiorno,
per conto del consorzio si richiede la verifica e il deploy dei metadati esposti all'URL:
https://suap.consorzioats.it/simplesaml/module.php/saml/sp/metadata.php/consorzioats

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
