### ISSUE TITLE
Richiesta verifica metadati Comune di Marcon

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1002]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Marcon.
https://www.comune.marcon.ve.it/c027020/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
