### ISSUE TITLE
Richiesta Validazione metadati SPID per gli Istituti Raggruppati - Azienda Pubblica di Servizi alla Persona

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#1004]
Buongiorno,
per conto di  Istituti Raggruppati - Azienda Pubblica di Servizi alla Persona, si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.istitutiraggruppati.eu/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
