### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Murlo (SI)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#1005]
Buongiorno,
per conto del Comune in oggetto si richiede la verifica e il deploy dei metadati esposti all'URL: 			
http://www.comune.murlo.siena.it/spid/metadata.xml 

Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
