### ISSUE TITLE
Controllo metadata - Comune di Trino

### ISSUE THREAD

**Issue by falbesano** [italia/spid#1006]
Buongiorno,
per conto del Comune di Trino, richiediamo la verifica dei metadata pubblicati all'url:
https://sportellodigitale.comune.trino.vc.it/002148/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
