### ISSUE TITLE
ACI non ha aggiornato gli Idp SPID con LEPIDA ID

### ISSUE THREAD

**Issue by patriziasaggini** [italia/spid#1008]
Buongiorno,
molti cittadini ci hanno segnalato l’impossibilità di accedere ai servizi di ACI perchè l’IdP Lepida ID non è ancora presente nella [pagina](https://login.aci.it/simplesaml/module.php/saml/disco.php?entityID=https%3A%2F%2Flogin.aci.it%2Fsimplesaml%2Fmodule.php%2Fsaml%2Fsp%2Fmetadata.php%2Fdefault-sp&return=https%3A%2F%2Flogin.aci.it%2Fsimplesaml%2Fmodule.php%2Fsaml%2Fsp%2Fdiscoresp.php%3FAuthID%3D_74ee0704441961ec9d1a62f69bef1fe9d657e821f8%253Ahttps%253A%252F%252Flogin.aci.it%252Fsimplesaml%252Fmodule.php%252Fcore%252Fas_login.php%253FAuthId%253Ddefault-sp%2526ReturnTo%253Dhttps%25253A%25252F%25252Flogin.aci.it%25252Findex.php%25253F) che si apre per accedere ai servizi del sito di ACI;

Si può inserire anche questo Idp?

Grazie
Patrizia Saggini

Responsabile Servizio Affari Generali e Innovazione
Comune di Valsamoggia (BO)

**Comment by AntonioGiovanniSchiavone** [comment]
L'Automobile Club d'Italia ha integrato l'Identity Provider Lepida S.p.A. nella propria [piattaforma di autenticazione](https://login.aci.it/index.php?do=genNotAuth&id=login&application_key=aruisa).
