### ISSUE TITLE
Richiesta di validazione metadati - Comune di Cinisello Balsamo

### ISSUE THREAD

**Issue by globogis** [italia/spid#101]
Buonasera,
si richiede la validazione dei metadati per conto del Comune di Cinisello Balsamo:
https://suap.comune.cinisello-balsamo.mi.it/simplesaml/module.php/saml/sp/metadata.php/cinisellobalsamo

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

**Comment by pernin** [comment]
I metadata ci sono stati comunicati in data 07/12/2018:
{
            "ipaEntityCode": "c_c707",
            "entityName": "Comune di Cinisello Balsamo",
            "entityId": "https://idpcgel.crs.lombardia.it/gelmetadata/15077",
            "metadataUrl": "https://registry.spid.gov.it/metadata/sp/spid-sp-c_c707.xml",
            "metadataType": "test",
            "notes": ""
          }

Facciamo fede a questi inviatici da AgID, pertanto non corrispondendo l'Issuer con l'entityId ivi menzionato, la richiesta non viene accettata.
Posso mettermi in contatto con i tecnici che gestiscono i metadata per AgID se volete.
