### ISSUE TITLE
 Validazione metadata Comune di Cento

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1012]
Buongiorno,
per conto del  Comune di Cento

abbiamo predisposto metadata  e pubblicati all'URL

https://cento.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_cento-signed.zip](https://github.com/italia/spid/files/3165316/metadata_cento-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
