### ISSUE TITLE
Validazione metadata Comune di Cesano Boscone

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1013]
Buongiorno,
per conto del  Comune di Cesano Boscone

abbiamo predisposto metadata  e pubblicati all'URL

https://cesanoboscone.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_cesanoboscone-signed.zip](https://github.com/italia/spid/files/3165320/metadata_cesanoboscone-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
L'attributo ID deve essere di tipo NCNAME, ovvero deve iniziare con una lettera o un carattere di sottolineatura e può contenere solo lettere, cifre, caratteri di sottolineatura, trattini e punti.
Gli spazi non sono ammessi

**Comment by sfacondini** [comment]
Buon pomeriggio, 
i metadata del comune di Cesano Boscone sono stati corretti e sono pubblicati all'URL:
https://cesanoboscone.comune-online.it/serviziSPID/metadata.xml
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_cesanoboscone-signed.zip](https://github.com/italia/spid/files/3178388/metadata_cesanoboscone-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
