### ISSUE TITLE
Richiesta validazione aggiornamento metadata Comune di Casalpusterlengo

### ISSUE THREAD

**Issue by sofmir** [italia/spid#1014]
a) Nome ente: Comune di Casalpusterlengo
b) Url del metadata: https://comune.casalpusterlengo.lo.it/spid/casal.xml
c) Aggiornamento metadata

d1) Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator: 

https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1UR200.sto%3FDB_NAME%3Dcasal&SOLStwToken=4112040486431085&DB_NAME=casal&Login_Message=

d2) Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator:

https://servizionline.comune.casalpusterlengo.lo.it/cmscasalpusterlengo/login.aspx

e) Contatto tecnico: Badaracco Cristian ( ced@comune.casalpusterlengo.lo.it - Tel: 03779233225)

f) Contatto amministrativo: Badaracco Cristian ( ced@comune.casalpusterlengo.lo.it - Tel: 03779233225)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato aggiornato
