### ISSUE TITLE
Validazione metadata Comune di Castano Primo 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1016]
Buongiorno,
per conto del  Comune di Castano Primo

abbiamo predisposto metadata  e pubblicati all'URL

https://castanoprimo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_castanoprimo-signed.zip](https://github.com/italia/spid/files/3177267/metadata_castanoprimo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
