### ISSUE TITLE
Validazione metadata Comune di Brunate

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1017]
Buongiorno,
per conto del  Comune di Brunate

abbiamo predisposto metadata  e pubblicati all'URL

https://brunate.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_brunate-signed.zip](https://github.com/italia/spid/files/3178398/metadata_brunate-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Vi è un errore di digitazione nella url con cui vine valorizzato l'OrganziationUrl e l'entityID

**Comment by sfacondini** [comment]
Buon pomeriggio,
i metadata del comune di Brunate sono stati corretti e sono pubblicati all'URL:
[metadata_brunate-signed.zip](https://github.com/italia/spid/files/3203573/metadata_brunate-signed.zip)

https://brunate.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
