### ISSUE TITLE
Validazione metadata Comune di Castiglione delle Stiviere

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1018]
Buongiorno,
per conto del  Comune di Castiglione delle Stiviere

abbiamo predisposto metadata  e pubblicati all'URL

https://castiglionedellestiviere.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_castiglionedellestiviere-signed.zip](https://github.com/italia/spid/files/3178408/metadata_castiglionedellestiviere-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
