### ISSUE TITLE
Validazione metadata Comune di Chiavari

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1019]
Buongiorno,
per conto del  Comune di Chiavari

abbiamo predisposto metadata  e pubblicati all'URL

https://chiavari.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_chiavari-signed.zip](https://github.com/italia/spid/files/3178423/metadata_chiavari-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
