### ISSUE TITLE
[Configurazioni] Problemi con "nameFormat" dell'AttributeMap

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#102]
Buongiorno, non capiamo come mai impostando il nameFormat degli attibuti identificativi come "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",  funziona per Poste ma non per Register.
Mentre, impostando il nameFormat come "urn:oasis:names:tc:SAML:2.0:attrname-format:basic", (tra l'altro come da specifiche) funziona per Register ma non più per Poste.
Grazie

**Comment by Eduardo1977** [comment]
Abbiamo replicato gli attributi identificativi impostando entrambi i nameFormat  (unspecified e basic). 
In questo modo, adesso funziona con entrambi gli Idp (Poste e Register). 
E' questa la migliore soluzione?

**Comment by umbros** [comment]
Si confermo. C'è un attività di allineamento interoperabilità che verterà anche su questo aspetto.

Umberto Rosini
Agenzia per l'Italia Digitale
