### ISSUE TITLE
Validazione metadata Comune di Martignana di Po

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1020]
Buongiorno,
per conto del Comune di Martignana di Po

abbiamo predisposto metadata  e pubblicati all'URL

https://martignanadipo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_martignanadipo-signed.zip](https://github.com/italia/spid/files/3178428/metadata_martignanadipo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
