### ISSUE TITLE
Validazione metadata Comune di Val della Torre

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1021]
Buongiorno,
per conto del Comune di Val della Torre

abbiamo predisposto metadata  e pubblicati all'URL

https://valdellatorre.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_valdellatorre-signed.zip](https://github.com/italia/spid/files/3178438/metadata_valdellatorre-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
