### ISSUE TITLE
Mancata acquisizione metadata comune di Oristano IDP Poste

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1022]
Buona sera, 
i metadata del comune di Oristano sono stati acquisiti da tutti gli IDP salvo Poste 
si richiede un nuovo caricamento presso questo IDP
Cordiali saluti
Facondini Stefano 
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato ricaricato dagli IdP.
