### ISSUE TITLE
Comune di Caravaggio - Errore di login - IdP Poste

### ISSUE THREAD

**Issue by globogis** [italia/spid#1024]
Buongiorno,

il deploy dei metadati richiesto con issue #904 sembra non essere andato a buon fine per l'IdP Poste: accedendo infatti dal relativo servizio https://sportellotelematico.comune.caravaggio.bg.it/ si ottiene un errore di interazione.

Si chiede cortesemente una verifica ed eventualmente un nuovo deploy dei metadati, non variati e sempre esposti all'endpoint https://sportellotelematico.comune.caravaggio.bg.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato ricaricato dagli IdP. L'interazione con l'IdP Poste Italiane è stata ripristinata.
