### ISSUE TITLE
Lonato del Garda - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#1026]
Buongiorno,
   per conto del Comune di Lonato del Garda si chiede l'aggiornamento dei metadati attualmente deployati con quelli esposti all'endpoint: 

https://www.comune.lonato.bs.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by globogis** [comment]
Buongiorno,
   chiediamo cortesemente lo stato della richiesta.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Si prega di inviare una mail a spid.tech@agid.gov.it

**Comment by globogis** [comment]
Chiediamo delucidazioni in riferimento a quanto da voi comunicato "Si prega di inviare una mail a spid.tech@agid.gov.it"
Vorremo in particolare sapere se è cambiata la procedura, grazie.
