### ISSUE TITLE
Verifica Nuovo Metadata Università degli Studi di Sassari

### ISSUE THREAD

**Issue by UNISS-SPID** [italia/spid#1027]
Università degli Studi di Sassari - Piazza Università, 21 - 07100 - Sassari
Vi chiediamo la verifica tecnica dell'implementazione SPID eseguita sul nostro  sistema informatico.
Metadata da verificare:
https://spid.applicazioni.uniss.it/metadata/metadata.xml
URL del pulsante che verrà integrato nella pagina di autenticazione:
https://spid.applicazioni.uniss.it/idpselector/idpselector.html
URL della pagina di autenticazione nella quale verrà integrato il pulsante:
https://applicazioni.uniss.it/uniss/index.php/auth/login/

Responsabile tecnico Luca Spanu - lspanu@uniss.it
Responsabile amministrativo Daniele Tedde - dtedde@uniss.it

**Comment by lspanu** [comment]
Buongiorno, non abbiamo ricevuto notizie sulla validazione del nuovo metadata e invio ai provider SPID.
C'è qualche problema sulle informazioni da noi fornite?

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto via mail

**Comment by lspanu** [comment]
Buongiorno,
informiamo che sono state sistemate le criticità indicate nell'esito della verifica tecnica.
Si richiede la riesecuzione della stessa.
