### ISSUE TITLE
Comune di Terracina - Errore di login - IdP Poste

### ISSUE THREAD

**Issue by globogis** [italia/spid#1031]
Buongiorno,
in seguito all'aggiornamento dei metadati richiesto con issue #910 si riscontra un'anomalia di accesso con l'IdP Poste. Il servizio di riferimento è https://sportellotelematico.comune.terracina.lt.it : tentando di accedere con l'IdP Poste viene restituito l'errore `Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio`.

Si richiede cortesemente una verifica ed eventualmente un nuovo deploy dei metadati, non variati e sempre esposti all'endpoint https://sportellotelematico.comune.terracina.lt.it/sites/default/files/spid-metadata/terracina-signed.xml .

Grazie

**Comment by globogis** [comment]
Buongiorno,
   chiediamo cortesemente una verifica della problematica descritta, in quanto ad oggi l'anomalia persiste.

Buona giornata
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
L'IdP in questione adesso risponde correttamente alla vostre AuthnRequest.
