### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Chianciano Terme (SI)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#1033]
Buongiorno,
per conto del Comune in oggetto si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.chianciano-terme.siena.it/spid/metadata.xml 

Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
