### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Poggio Rusco (MN)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#1034]
Buongiorno,
per conto del Comune in oggetto si richiede la verifica e il deploy dei metadati esposti all'URL:
http://www.comune.poggiorusco.mn.it/public/G753/documenti/205201913410423.xml

Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by comuneweb** [comment]
Buongiorno,
il precedente link
http://www.comune.poggiorusco.mn.it/public/G753/documenti/205201913410423.xml

non è più direttamente raggiungibile.
Dopo l'aggiornamento del sito il link precedente fa un redirect a 
https://comune.poggiorusco.mn.it/contents/poggiorusco/205201913410423.xml (il contenuto del file xml è lo stesso).

Gradiremmo conferma che questa modifica è legittima (e quindi tutto continuerà a funzionare come prima) e che non occorre che modifichiamo nient'altro.

Grazie.
