### ISSUE TITLE
Controllo metadata - Comune di Gravellona Toce

### ISSUE THREAD

**Issue by falbesano** [italia/spid#1035]
Buongiorno,
per conto del Comune di Gravellona Toce, richiediamo la verifica dei metadata pubblicati all'url:
https://www.comune.gravellonatoce.vb.it/metadataSPID.xml

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
