### ISSUE TITLE
Validazione metadata Comune di  Castelfranco Piandiscò

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1038]
Buongiorno,
per conto del Comune di Comune di  Castelfranco Piandiscò

abbiamo predisposto metadata  e pubblicati all'URL

https://castelfrancopiandisco.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_castelfrancopiandisco-signed.zip](https://github.com/italia/spid/files/3203583/metadata_castelfrancopiandisco-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
