### ISSUE TITLE
Richiesta verifica metadati Comune di Porpetto

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1041]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Porpetto.
https://www.comune.porpetto.ud.it/c030077/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi ricaricato.
