### ISSUE TITLE
 Validazione metadata Comune di Rignano sull'Arno

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1042]
Buongiorno,
per conto del Comune di Rignano sull'Arno

abbiamo predisposto metadata  e pubblicati all'URL

https://rignanosullarno.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_rignanosullarno-signed.zip](https://github.com/italia/spid/files/3216471/metadata_rignanosullarno-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera,
la url del comune non è corretta, ed in generale l'uso dell'apostrofo nell'entityID può condurre ad un parsing errato del metadata.

**Comment by sfacondini** [comment]
Buongiorno 
i metadata del comune di Rignano sull'Arno sono stati coretti e ripubblicati 

https://rignanosullarno.comune-online.it/serviziSPID/metadata.xml
[metadata_rignanosullarno-signed.zip](https://github.com/italia/spid/files/3240969/metadata_rignanosullarno-signed.zip)

cordiali saluti
Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi ricaricato.
