### ISSUE TITLE
Comune di Castione della Presolana - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#1046]
Buongiorno,
per conto del Comune di Castione della Presolana si chiede l'aggiornamento dei metadati attualmente deployati con quelli esposti all'endpoint:
https://www.sportellotelematicocastionedellapresolana.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi ricaricato.
