### ISSUE TITLE
Validazione metadata Comune di Limido Comasco per aggiunta di un secondo SP

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1047]
Buongiorno,
per conto del Comune Limido Comasco

abbiamo aggiornato i metadata  e pubblicati all'URL

https://limidocomasco.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_limidocomasco2SP_new_signed.zip](https://github.com/italia/spid/files/3231305/metadata_limidocomasco2SP_new_signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi ricaricato.
