### ISSUE TITLE
Validazione metadata Comune di Formia

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1049]
Buongiorno,
per conto del Comune di Formia

abbiamo predisposto i metadata  e pubblicati all'URL

https://formia.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_formia-signed.zip](https://github.com/italia/spid/files/3232791/metadata_formia-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi ricaricato.
