### ISSUE TITLE
Richiesta aggiornamento metadata Comune di Tempio Pausania

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#1051]
Salve,
per conto del comune di Tempio Pausania, si richiede l'aggiornamento del metadata con quello inviatovi in data odierna via email.

Cordiali Saluti
Mariano Carta

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi ricaricato.
