### ISSUE TITLE
Validazione metadata Comune di Lodi

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1052]
Buongiorno,
per conto del Comune di Lodi

abbiamo aggiornato i metadata  con aggiunta di un terzo SP e pubblicati all'URL

https://lodi.comune-online.it/serviziSPID/metadata.xml
[metadata_lodi3SP-signed.zip](https://github.com/italia/spid/files/3240957/metadata_lodi3SP-signed.zip)

è stato mantenuto entityID

cordiali saluti
Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
