### ISSUE TITLE
Validazione metadata Comune di Concesio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1053]
Buongiorno,
per conto del Comune di Concesio

abbiamo aggiornato i metadata  con aggiunta di un secondo SP e pubblicati all'URL

https://concesio.comune-online.it/serviziSPID/metadata.xml

è stato mantenuto entityID

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_concesioGEL_2SP-signed.zip](https://github.com/italia/spid/files/3241447/metadata_concesioGEL_2SP-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
