### ISSUE TITLE
Problema con Certification Authority IDP Intesa

### ISSUE THREAD

**Issue by pmosini** [italia/spid#1055]
Salve,  avrei bisogno di sapere dove reperire la Certification Authority dell'IDP Intesa, il quale certificato di firma ("Subject: C=IT, O=IN.TE.S.A. S.p.A., DNQUALIFIER=20079797 + CN=SAML Signer") ha come issuer   "C=IT, O=IN.TE.S.A. S.p.A., CN=IN.TE.S.A. S.p.A - Certification Authority"
  
Non riesco a trovare da nessuna parte tale Certification Authority, né sul sito di Intesa né sui link messi da voi a disposizione.   In https://eidas.agid.gov.it/TL/TSL-IT.xml è presente il certificato della CA " C=IT, O=IN.TE.S.A. S.p.A., CN = IN.TE.S.A. CA - Certification Authority"  (simile come descrizione ma non corrisponde a quello di cui sopra).
Ho controllato anche che il file del metadata che ho utilizzato è quello da voi  indicato in  https://github.com/AgID/spid-registry-idp/tree/master/saml
Grazie in anticipo.

**Comment by walter-arrighetti** [comment]
Salve, il certificato elettronico in oggetto è presente sul metadata dell'IdP IN.TE.S.A. S.p.A., libearamente accessibile dal registry SPID, sotto gli IdP, all'indirizzo: https://registry.spid.gov.it/
Questo è tutto ciò che serve, nell'attuale implementazione SAML di SPID, per fidarsi dei certificati dei soggetti della federazione.
Spero di aver risposto alla sua domanda.
