### ISSUE TITLE
Errore in autenticazione con IDP di test

### ISSUE THREAD

**Issue by assistenzatop** [italia/spid#1057]
Bungiorno,

volevo chiedervi assistenza sulla comunicazione tra il mio SP e il vostro IdP di test, riporto di seguito i miei passi:
    
1) uso Ruby on Rails e la gem 'omniauth-saml', ho generato un certificato attraverso il comando "openssl req -x509 -nodes -sha256 -days 365 -newkey rsa:4096 -keyout sp-cert.key -out sp-cert.crt" e compilato gli attributi richiesti, configurato il fingerprint corrispondente insieme agli altri dati richiesti nell'apposito omniauth.rb e devise.rb;
2) ho creato il mio metadata attraverso il link "https://idp.spid.gov.it:8080"; il mio Service Provider risulta registrato come https://partecipa.formez.org ;
3) ho copiato e configurato i valori dell'IdP di test sul mio progetto di client.
Se provo a fare la chiamata su https://idp.spid.gov.it:9443 dal mio https://partecipa.formez.org al vostro IdP ottengo la schermata di login di WSO2 in cui mi vengono chieste le credenziali; ho provato ad inserire una coppia di quelle pubbliche che avete reso disponibili (cesare/password123)  o altre credenziali create appositamente per il mio Service Provider di test, ma ricevo sempre lo stesso errore: "Login failed! Please recheck the username and password and try again.".

Sul client risulta la chiamata "Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='https://partecipa.formez.org/decidim_users/auth/saml' Destination='https://idp.spid.gov.it:9443' ID='_09e4bdfb-7a28-4eb1-bc38-12b4359e57fe' IssueInstant='2019-06-03T10:47:16Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer Format='urn:oasis:names:tc:SAML:2.0:nameid-format:entity' NameQualifier='test-spid'>test-spid</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/></samlp:AuthnRequest>"

Potete per favore darmi supporto indicandomi come risolvere? 

Grazie in anticipo per la collaborazione,
Cordiali Saluti.

Gian Luca

**Comment by assistenzatop** [comment]
Ho modificato l'URL "https://idp.spid.gov.it:9443" in "https://idp.spid.gov.it/samlsso" ora ricevo "Error when processing the authentication request! " .

Sul client risulta:
Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='https://partecipa.formez.org/decidim_users/auth/saml' Destination='https://idp.spid.gov.it/samlsso' ID='_16c8188f-3eff-4d63-8eeb-3ed3961d332a' IssueInstant='2019-06-03T12:07:10Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer Format='urn:oasis:names:tc:SAML:2.0:nameid-format:entity' NameQualifier='test-spid'>test-spid</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/></samlp:AuthnRequest>

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Le AuthnRequest generate sono prive di numerosi elementi/attributi obbligatori, e alcuni di quelli presenti non sono correttamente valorizzati.

Si rimanda alle [Regole tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf)  (in particolare alle pagg. 8 - 10 e 13 -16 ) e agli [Avvisi SPID](https://www.agid.gov.it/it/piattaforme/spid/avvisi-spid) (in particolare gli avvisi n° 5 e 6) per la descrizione del formato delle AuthnRequest e la fornitura di alcuni esempi.

Inoltre, si consiglia di installare in locale ed utilizzare gli ambienti [TestEnv](https://github.com/italia/spid-testenv2) e [SPID Validator](https://github.com/italia/spid-saml-check), in quanto l'attuale IdP basato su WSO2 è in dismissione.
