### ISSUE TITLE
Validazione metadata Comune di Jesi

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1065]
Buongiorno,
per conto del Comune di Jesi

abbiamo aggiornato i metadata  con aggiunta di un secondo SP e pubblicati all'URL

https://jesi.comune-online.it/serviziSPID/metadata.xml

è stato mantenuto entityID

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_jesi-signed.zip](https://github.com/italia/spid/files/3260577/metadata_jesi-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
