### ISSUE TITLE
Richiesta verifica metadati Comune di Riva del Po

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1071]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Riva del Po.
https://www.comune.rivadelpo.fe.it/c038029/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
