### ISSUE TITLE
Richiesta verifica metadati Comune di Bolzano Vicentino

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1072]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Bolzano Vicentino.
https://www.comune.bolzanovicentino.vi.it/c024013/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
