### ISSUE TITLE
Richiesta verifica metadati Comune di Isola Rizza

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1073]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Isola Rizza.
https://servizionline.comune.isolarizza.vr.it/c023041/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
