### ISSUE TITLE
Richiesta verifica metadati Unione Comuni Destra Adige

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1074]
Buongiorno,
Si richiede la verifica dei metadati per conto dell'Unione Comuni Destra Adige.
https://servizionline.unionedxadige.it/ae00268/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
