### ISSUE TITLE
Errori interazione IDP Sielte,Lepida,Aruba e Namirial per il comune di Tempio Pausania

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#1076]
Buonasera, ll 3 giugno ci è stato comunicato che la richiesta di validazione metadata inoltrata con issue #1051 era stata inoltrata agli IDP.
Oggi abbiamo eseguito delle prove, e risultano correttamente funzionanti tutte le chiamate agli idp tranne quelli in oggetto. E' possibile che non abbiano ancora provveduto al caricamento del nuovo metadata?

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 
Abbiamo effettuato un ricarimento del metadata del SP in questione presso gli IdP. Qualora il problema persistesse, si prega di inviare una mail all'indirizzo spid.tech@agid.gov.it con il link al servizio in questione

**Comment by Saistrale** [comment]
Buon giorno,
alcuni mesi fa la ditta Arionline S.r.l. che si occupa dell'integrazione del sito web del comune di Tempio Pausania con SPID, ha aperto un ticket su github, segnalando un errore di accesso solamente con alcuni provider di identità digitale (numero ticket 1076 e 1051).
Il 17 giugno avete risposto alla segnalazione, indicando che, se il problema non fosse stato risolto, avremmo dovuto inviare un link a questo indirizzo email.

Visto che il problema persiste, trasmetto oggi il link:

Link di accesso al servizio: https://servizi.comune.tempiopausania.ot.it/login.aspx

Ringrazio e porgo cordiali saluti,

Ing. Fabrizio Milia
