### ISSUE TITLE
Richiesta verifica metadati Comune di San Pietro di Morubio

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1077]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di San Pietro di Morubio.
https://servizionline.comune.sanpietrodimorubio.vr.it/c023075/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
