### ISSUE TITLE
Richiesta di validazione metadati - Comune di Pomponesco

### ISSUE THREAD

**Issue by globogis** [italia/spid#108]
Buongiorno,
si richiede la validazione dei metadati per conto del Comune di Pomponesco:
`https://www.sportellotelematico-pomponescosabbioneta.it/simplesaml/module.php/saml/sp/metadata.php/pomponescosabbioneta`

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
