### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Noale

### ISSUE THREAD

**Issue by globogis** [italia/spid#1081]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sue.comune.noale.ve.it/simplesaml/module.php/saml/sp/metadata.php/noale
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Si prega di inviare una mail a spid.tech@agid.gov.it

**Comment by globogis** [comment]
Chiediamo delucidazioni in riferimento a quanto da voi comunicato "Si prega di inviare una mail a spid.tech@agid.gov.it"
Vorremo in particolare sapere se è cambiata la procedura, grazie.
