### ISSUE TITLE
Richiesta aggiornamento Metadata Comune di Monserrato (CA)

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#1083]
Buonasera,
per conto del comune di Monserrato (CA) si richiede la sostituzione del metadata precedentemente validato con quello la cui url è stata inoltrata via email in data odierna.
cordiali saluti
Mariano Carta

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
