### ISSUE TITLE
Richiesta di verifica tecnica e convenzione - Corpo Nazionale dei Vigili del Fuoco

### ISSUE THREAD

**Issue by VigilfuocoSpid** [italia/spid#1085]
--- TESTO DA ELIMINARE ---
Buongiorno,
con la presente si richiede la verifica tecnica sull'implementazione SPID per il Corpo Nazionale dei Vigili del Fuoco
L'URL del servizio da validare è il seguente:
https://sso.vigilfuoco.it/cas
Restiamo in attesa di un vostro riscontro
Cordiali Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto via mail
