### ISSUE TITLE
Richiesta verifica metadata Comune di Castelnuovo val di Cecina

### ISSUE THREAD

**Issue by sofmir** [italia/spid#1086]
Buongiorno,
si richiede la validazione tecnica del metadata per:

a) Nome ente: Comune di Castelnuovo Val di Cecina
b) Url del metadata: http://www.comunecastelnuovovdc.gov.it/wp-content/uploads/2019/06/n202166.xml
c) Nuovo metadata
d) Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator: 
https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1UR003.sto%3FDB_NAME%3Dn202166&SOLStwToken=2119021682591026&DB_NAME=n202166&Login_Message=

e) Contatto tecnico: Falossi Andrea 3287037253 andrea.f@comune.castelnuovo.pi.it

f) Contatto amministrativo: Valentina Vichi 058823510 valentina.v@comune.castelnuovo.pi.it

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by sofmir** [comment]
Buongiorno,
si richiede la validazione tecnica, la convenzione e il file per la compilazione dell’elenco dei servizi attivi per conto del Comune di Castelnuovo di Val di Cecina
a) Nome ente: Comune di Castelnuovo di Val di Cecina
b) Url del metadata: http://www.comunecastelnuovovdc.gov.it/wp-content/uploads/2019/06/n202166.xml
c) Nuovo metadata
d) Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator:
https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1UR003.sto%3FDB_NAME%3Dn202166&SOLStwToken=2119021682591026&DB_NAME=n202166&Login_Message=
e) Contatto tecnico: Falossi Andrea 3287037253 andrea.f@comune.castelnuovo.pi.it
f) Contatto amministrativo: Valentina Vichi 058823510 valentina.v@comune.castelnuovo.pi.it
