### ISSUE TITLE
Controllo metadata Comune di Cermenate

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#109]
Buongiorno,
Per conto del Comune di Cermenate, abbiamo predisposto i metadata e pubblicati sulla cartella
https://cermenate.comune-online.it/serviziSPID/metadata.xml
[metadata_cermenate-signed.zip](https://github.com/italia/spid/files/1840645/metadata_cermenate-signed.zip)

cordiali saluti
Facondini Stefano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
