### ISSUE TITLE
Richiesta validazione metadata Comune di Calusco d'Adda (BG)

### ISSUE THREAD

**Issue by proximalab** [italia/spid#1091]
Con la presente si richiede la validazione dei metadata per il comune di Calusco d'Adda (BG): https://www.comune.caluscodadda.bg.it/spid/module.php/saml/sp/metadata.php/default-sp

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
