### ISSUE TITLE
Richiesta Verifica Tecnica Accesso SPID - Validazione dei metadati

### ISSUE THREAD

**Issue by ldagosto** [italia/spid#1092]
Salve,
Con la presente si richiede la validazione dei metadata per Asmel Associazione:
•	Url del metadata:  https://blockchain.asmel.eu/fideiussioni/spid/metadata.php
•	Operazione: Nuovo Metadata
•	Url bottone ENTRA CON SPID: https://blockchain.asmel.eu/fideiussioni/spid/
saluti Luigi D'Agosto

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
il metadata proposto non è conforme ai requisiti definiti a pag. 20 delle Regole tecniche SPID in relazione all'elemento AssertionConsumerService:

Inoltre, il certificato x509 fornito scadrà a breve.
