### ISSUE TITLE
Lonato del Garda - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#1093]
In riferimento alla issue da voi chiusa(#1026)
chiediamo delucidazioni in riferimento a quanto da voi comunicato "Si prega di inviare una mail a spid.tech@agid.gov.it"
Vorremo in particolare sapere se è cambiata la procedura, grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Risolta tramite comunicazioni via mail
