### ISSUE TITLE
Richiesta di verifica tecnica e convenzione - Corpo Nazionale dei Vigili del Fuoco

### ISSUE THREAD

**Issue by VigilfuocoSpid** [italia/spid#1096]
Buongiorno,
con la presente si richiede una seconda  verifica tecnica sull'implementazione SPID per il Corpo Nazionale dei Vigili del Fuoco a seguito delle correzioni richieste.
L'URL del servizio da validare è il seguente:
https://sso.vigilfuoco.it/cas
Restiamo in attesa di un vostro riscontro
Cordiali Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto via mail

**Comment by VigilfuocoSpid** [comment]
Per migliore interpretazione della richiesta, aggiungiamo l'url da cui è possibile prelevare il metadata: https://sso.vigilfuoco.it/spid/metadata-firmato.xml
