### ISSUE TITLE
Richiesta verifica metadati Comune di Musile di Piave

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1097]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Musile di Piave.
https://www.comune.musile.ve.it/c027025/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
