### ISSUE TITLE
Controllo metadata Comune di Mondovì per aggiunta SP

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#110]
Buongiorno,
Per conto del Comune di Mondovì, abbiamo predisposto i metadata e pubblicati sulla cartella
https://mondovi.comune-online.it/serviziSPID/metadata.xml

come in altri contesti abbiamo aggiunto i nostri riferimenti salvaguardando entityID e i riferimenti al
[metadata_mondovi2SP-signed.zip](https://github.com/italia/spid/files/1840823/metadata_mondovi2SP-signed.zip)
 primo SP censito
cordiali saluti
Facondini Stefano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
