### ISSUE TITLE
Richiesta rinnovo validazione metadata - Comune di Montalto di Castro (VT)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#1101]
Salve, 
si richiede la rivalidazione del metadata già in esercizio per il Comune di Montalto di Castro (VT):
https://comune.montaltodicastro.vt.it/metadatiXml/n1200505.xml

Cordiali saluti
Grazie
We-COM Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
