### ISSUE TITLE
Richiesta controllo metadata - Comune di Seravezza (LU)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#1102]
Buongiorno,
con la presente si richiede la verifica del metadata presente all'url:

https://www.comune.seravezza.lucca.it/c046028/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.

In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
