### ISSUE TITLE
Problema verifica firma

### ISSUE THREAD

**Issue by gig2019** [italia/spid#1104]
Salve, mi riallaccio al thread #223 chiuso l'anno scorso per segnalare l'esatto identico problema col nostro certificato, che risulta sicuramente funzionare con tutti gli IdP di produzione, ma sul vostro ambiente di test dà sempre quel famoso errore "Signature validation for Authentication Request failed."
Dal momento che il certificato è sicuramente valido, né vogliamo generarne uno nuovo col comando openssl, è evidente che la validazione in questo ambiente segue una strada diversa da quella degli altri IdP...potreste fare una verifica in merito? Noi chiamiamo sempre "https://idp.spid.gov.it/samlsso"
Vi allego il nostro certificato (da rinominare in .crt)...se controllate i log, noi siamo Unioncamere (SVILUPPO).
Grazie
[certificate.txt](https://github.com/italia/spid/files/3335197/certificate.txt)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Il tool citato è in dismissione. 
Si consiglia di fare riferimento ai tool citati sul [sito ufficiale SPID](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), ovvero TestEnv2 e SPIDValidator
