### ISSUE TITLE
Richiesta validazione e caricamento metadata Città Metropolitana di Torino

### ISSUE THREAD

**Issue by alfonsinaarena** [italia/spid#1107]
Buongiorno,
si richiede la verifica e la validazione del metadata di Regione Piemonte per l'integrazione con SPID, con successivo caricamento da parte degli Identity Provider SPID.

Il metadata è pubblicato al seguente indirizzo:
https://www.spid.piemonte.it/spid/prod/metadata/metadata_service_provider_cmto_spid.xml

Il file metadata è pubblicato sul sito https://www.spid.piemonte.it, gestito dal CSI Piemonte, essendo il CSI Piemonte intermediario tecnologico per le intragrazioni SPID individuato dalla Città Metropolitana di Torino (e come verrà indicato successivamente anche nella relativa convenzione).

Grazie e buona giornata,
Alfonsina

**Comment by alfonsinaarena** [comment]
Buongiorno,
si richiede la verifica e la validazione del metadata di Città Metropolitana di Torino per l'integrazione con SPID, con successivo caricamento da parte degli Identity Provider SPID.

Il metadata è pubblicato al seguente indirizzo:
https://www.spid.piemonte.it/spid/prod/metadata/metadata_service_provider_cmto_spid.xml

Il file metadata è pubblicato sul sito https://www.spid.piemonte.it, gestito dal CSI Piemonte, essendo il CSI Piemonte intermediario tecnologico per le intragrazioni SPID individuato dalla Città Metropolitana di Torino (e come verrà indicato successivamente anche nella relativa convenzione).

Grazie e buona giornata,
Alfonsina

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto via mail
