### ISSUE TITLE
Aggiornamento metadata per Regione Emilia - Romagna

### ISSUE THREAD

**Issue by chiaracaniggia** [italia/spid#1109]
Buongiorno,
comunico l'attivazione di tre nuovi servizi:

Nome:Sistema informativo BANDO Social Housing 2019 - Regione Emilia-Romagna
Attributi:familyName,fiscalNumber,name,spidCode
Livello SPID:1

Nome:Autenticazione per i servizi demografici per il cittadino - Comune di Molinella
Attributi:email,familyName,fiscalNumber,name,spidCode
Livello SPID:2

Nome:Autenticazione per i servizi demografici per il cittadino - Comune di San Lazzaro di Savena
Attributi:Attributi:email,familyName,fiscalNumber,name,spidCode
Livello SPID:2

Grazie
saluti
Chiara Caniggia
Lepida ScpA

**Comment by chiaracaniggia** [comment]
Salve,
chiediamo se per questa richiesta fosse possibile aggiornare con urgenza i metadata.
Grazie mille per la collaborazione
saluti
Chiara Caniggia
Lepida ScpA

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
