### ISSUE TITLE
Richiesta validazione e caricamento metadata Città Metropolitana di Torino - firma con nuovo certificato

### ISSUE THREAD

**Issue by alfonsinaarena** [italia/spid#1111]
Buongiorno,
si richiede la verifica e la validazione del metadata di Città Metropolitana di Torino per l'integrazione con SPID, con successivo caricamento da parte degli Identity Provider SPID.

Il metadata è pubblicato al seguente indirizzo:
https://www.spid.piemonte.it/spid/prod/metadata/metadata_service_provider_cmto_spid.xml

Il file metadata è pubblicato sul sito https://www.spid.piemonte.it, gestito dal CSI Piemonte, essendo il CSI Piemonte intermediario tecnologico individuato dalla Città Metropolitana di Torino per le integrazioni SPID  (e come verrà indicato successivamente anche nella relativa convenzione).

Grazie e buona giornata,
Alfonsina

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
