### ISSUE TITLE
Validazione metadata Cassano D'Adda

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1115]
Buongiorno,
per conto del Comune di Cassano D'Adda

abbiamo aggiornato i metadata  con aggiunta di un secondo SP e pubblicati all'URL

https://cassanodadda.comune-online.it/serviziSPID/metadata.xml
[metadata_cassanodadda2SP-signed.zip](https://github.com/italia/spid/files/3359439/metadata_cassanodadda2SP-signed.zip)

 

è stato mantenuto entityID

cordiali saluti
Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
