### ISSUE TITLE
Validazione metadata Comune di Latina

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1116]
Buongiorno,
per conto del Comune di Latina 
abbiamo prodotto i metadata  e pubblicati all'URL

https://latina.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_latina-signed.zip](https://github.com/italia/spid/files/3359545/metadata_latina-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
