### ISSUE TITLE
Implementazione Spid con spid-saml-check, spid-testenv2 e Ruby on Rails

### ISSUE THREAD

**Issue by assistenzatop** [italia/spid#1117]
Buongiorno,

sto cercando di implementare lo spid all'interno di una applicazione RoR utilizzando la gem spid-rails per conto di Formez.
Per semplificare il lavoro mi sono creato un client dummy RoR al momento svincolato dalle complessità del progetto completo e ho installato spid-testenv2 e spid-saml-check come suggerito da voi per verificare le assertions e correggere eventuali configurazioni errate.

Il file metadata prodotto da spid-saml-check (che posso inviarvi qualora lo riteniate necessario) non contiene né l'attributo AssertionConsumerServiceIndex, né l'attributo AssertionConsumerServiceURL. 

Domande:
1) il metadata.xml generato da spid-saml-check è modificabile per inserire gli attibuti mancanti? o la mancanza degli attributi sopra è attesa?
2) mi aspetterei che spid-saml-check mi avverta qualora gli attributi non siano consistenti col protocollo e la verifica dei certificati non sia corretta o che mi dia un messaggio di transazione andata a buon fine, non osservo però questo tipo di comportamento, né trovo qualcosa che assomigli ad una guida o delle faq che mi aiutino ad orientarmi. Avete a disposizione materiale di questo tipo? Nel caso la request permetta la login e che quest'ultima vada a buon fine e che la response effettui il redirect verso il client senza errori il test può considerarsi superato?
3) avete mai analizzato/certificato l'efficacia delle gem spid-rails e spid-ruby nei progetti a cui vi è capitato di dare assistenza?
4) ho installato anche l'estensione per Chrome "Spid Assertion Consumer Validator", purtroppo non ne riscontro il valore aggiunto: sostanziamente in questa interazione tra client e server non segnala nulla (la mia versione di Chrome 75.0.3770.100 (Build ufficiale) (a 64 bit) ) Può trattarsi di un problema di compatibilità dell'add-on?
5) ho provato a riportare il metadata.xml già utilizzato con spid-saml-check, opportunamente integrato, su spid-testenv2 in modo da avere la possibilità di un test più verosimile, provando a riutilizzare i certificati già usati su spid-saml-check. 
Riscontro che il metadata.xml, caricato in locale, non è quello mostrato all'URL .../metadata (per esempio vengono caricati diversi attributi del tipo <saml:Attribute Name="..."/>) e che il tentativo di AuthNRequest non va a buon fine (OpenSSL::X509::CertificateError in Spid::Rails::SingleSignOnsController#new
nested asn1 error).

Insomma come si sarà intuito vedo il processo di integrazione dello Spid piuttosto farraginoso, anche con l'aiuto degli strumenti che fortunatamente avete sviluppato, vi chiedo se vi è possibile darmi una mano indicandomi una direzione.

Grazie,

Gian Luca

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

- Come indicato nel [repository del tool in oggetto](https://github.com/italia/spid-saml-check) e nel [sito ufficiale SPID](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), SPID SAML Check è una piattaforma di analisi dell'implementazione di un generico Service Provider. Tale piattaforma funziona come un generico Identity Provider a cui si deve agganciare il Service Provider in esame: difatti SPID SAML Check ha il compito di analizzare i metadata prodotto dal Service Provider in esame, di analizzare le AuthnRequest ricevute dal SP in esame, ed inviare una vasta tipologia di Response (sia corrette che volutamente errate), per valutare la conformità rispetto alla documentazione tecnica, ovvero alle [Regole Tecniche SPID, agli Avvisi SPID e allo SPID Quality Assessment Document](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid).
 
- Gli attributi AssertionConsumerServiceIndex ed  AssertionConsumerServiceURL sono tipici di una AuthnRequest e non di un metadata (nè metadata SP, nè metadata IdP).  
 
- Il tool è stato sviluppato per uso interno e al momento è rilasciato "as is": sottolineamo che comunque molti soggetti, sia pubblici che privati, hanno usato e continuano ad usare il tool in questione senza particolari difficoltà.   

- A prescindere dai tool messi a disposizione da AgID, riteniamo che una approfondita conoscenza delle regole tecniche SPID sia un elemento imprescindibile per eseguire un'integrazione al Sistema Pubblico di Identità Digitale.

- Le analisi condotte da AgID sui metadata e sulle implementazioni si basano esclusivamente sulla coerenza con la citata documentazione tecnica. Nella maggioranza dei casi lo Staff Tecnico non ha contezza di quale particolare linguaggio e/o tecnologia sono stati utilizzati nella generazione delle asserzioni SAML.

- Per domande relative ad uno specifico tool messo a disposizione da AgID, si prega di aprire issue direttamente nel repository del tool e non in questo repository generale.
