### ISSUE TITLE
Aggiornamento Metadata Regione Abruzzo

### ISSUE THREAD

**Issue by fume** [italia/spid#1118]
Salve, 
si chiede aggiornamento del metadata relativo all'organizzazione "Regione Abruzzo", con entityID = http://adfs.regione.abruzzo.it/adfs/services/trust
L'url del metadata è stata comunicata via mail.

Saluti, F.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by fume** [comment]
Salve,
al valle del deploy del metadata, stiamo ricevendo errori nr 10 dall’IdP SIELTE. Immagino ci sia stato qualche problema durante il deploy. Potete cortesemente verificare che il deploy sia avvenuto con successo per TUTTI gli IdP?

Grazie,
