### ISSUE TITLE
Aggiornamento certificato metadata Uniroma1

### ISSUE THREAD

**Issue by francoricci** [italia/spid#1120]
Sapienza, in previsione della scadenza dell'attuale certificato, ha effettuato un aggiornamento del file metadata.
Il nuovo file è raggiungibile da 
https://www.studenti.uniroma1.it/spid/metadata_sapienza2.xml

Vi prego di notificare gli idp del nuovo metadato.

Saluti
Franco Ricci

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
