### ISSUE TITLE
Richiesta rinnovo validazione metadata - Comune di Sutri (VT)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#1121]
Salve,
si richiede la rivalidazione del metadata già in esercizio per il Comune di Sutri (VT):
http://www.comune.sutri.vt.it/metadatiXml/n90375.xml

Cordiali saluti
Grazie
We-COM Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
