### ISSUE TITLE
SPID per uso professionale - rappresentante di ente pubblico // richiesta indicazioni

### ISSUE THREAD

**Issue by mspinazze** [italia/spid#1123]
ENTE RICHIEDENTE: Comune di Eraclea (VE)

stiamo cercando di ottenere uno SPID da utilizzare per il nostro comune, (la richiesta in particolare arriva dagli uffici finanziari i quali dovranno utilizzare servizi gestiti dal MEF che a breve saranno accessibili solo tramite SPID).

Abbiamo consultato vari link sull'argomento tra cui:
https://forum.italia.it/c/documenti-in-consultazione/lg-spid-rilascio-identita-digitale-uso-professionale

Poniamo 2 domande di carattere pratico:

E' corretto far ottenere SPID come persona Giuridica al rappresentante dell'Ente (Sindaco o Commissario Prefettizio nel nostro caso) con sicurezza di livello 2 per poi fare accedere tutti gli uffici con tali credenziali in presenza della persona intestataria di SPID ?

Riguardo l'eventualità di attivare un "Utenza Master" chi deve essere a ricoprire questo ruolo in un ente come il nostro formato 1 AOO con 6 aree prive di figure dirigenziali (solo posizioni organizzative) a parte il Segretario Comunale che è in servizio qui solo 2 giorni a settimana ?
  
Ringraziamo fin d'ora per le informazioni che ci farete avere.

Cordiali saluti.

Mauro Spinazzè 

Ufficio CED - Comune di Eraclea (VE) 
Mauro SPINAZZE' 
tel. 0421-234272
mail: mauro.spinazze@comune.eraclea.ve.it

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Questo canale è riservato per comunicazioni tecniche relative al processo di accreditamento dei Service Provider alla Federazione SPID.
Per comunicazioni di altra natura si prega di inviare una mail a spid.tech@agid.gov.it
