### ISSUE TITLE
Validazione metadata Comune di Fiumicino

### ISSUE THREAD

**Issue by claudioreggianimaggioli** [italia/spid#1124]
Buongiorno,
per conto del Comune di Fiumicino
abbiamo predisposto i metadata per aggiornamento di un certificato e pubblicati all'URL

https://fiumicino.comune-online.it/serviziSPID/metadata.xml

Cordiali saluti

Claudio Reggiani
Maggioli Spa

[metadata_fiumicino.xml.zip](https://github.com/italia/spid/files/3385305/metadata_fiumicino.xml.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il certificato contenuto nel secondo Keydescriptor appare corrotto o troncato

**Comment by claudioreggianimaggioli** [comment]
Buongiorno,
ha ragione, ho ricreato i metadati (che allego a questa risposta), e pubblicati al solito url:

https://fiumicino.comune-online.it/serviziSPID/metadata.xml

Cordiali Saluti
Claudio Reggiani
Maggioli Spa

[metadata_fiumicino.xml.zip](https://github.com/italia/spid/files/3407317/metadata_fiumicino.xml.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
