### ISSUE TITLE
Validazione metadata Comune di Maratea

### ISSUE THREAD

**Issue by claudioreggianimaggioli** [italia/spid#1126]
Buongiorno,
per conto del Comune di Maratea

abbiamo predisposto metadata e pubblicati all'URL

https://maratea.comune-online.it/serviziSPID/metadata.xml

Cordiali saluti
Claudio Reggiani
Maggioli Spa

[metadata_maratea.xml.zip](https://github.com/italia/spid/files/3392434/metadata_maratea.xml.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
