### ISSUE TITLE
Richiesta controllo metadata - Comune di Piana di Monte Verna (CE)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#1127]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:

https://www.comune.pianadimonteverna.ce.it/c061056/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by damikael** [comment]
Buongiorno,
come indicato sul sito SPID si chiede di inviare una email all'indirizzo spid.tech@agid.gov.it indicando le seguenti informazioni ed il riferimento alla presente issue:

- Nome ente;
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente il bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico;
- Contatto referente amministrativo;

(Rif. https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid#procedura-tecnica-5)


Grazie,
cordiali saluti
