### ISSUE TITLE
Validazione metadata Comune di Todi 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1128]
Buongiorno,
per conto del Comune di Todi 

abbiamo prodotto i metadata  e pubblicati all'URL

https://todi.comune-online.it/serviziSPID/metadata.xml
 

cordiali saluti
Facondini Stefano
Maggioli Spa
 
[metadata_todi-signed.zip](https://github.com/italia/spid/files/3396343/metadata_todi-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
