### ISSUE TITLE
Validazione metadata Comune di Lumezzane 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1129]
Buongiorno,
per conto del Comune di Lumezzane 

abbiamo prodotto i metadata  e pubblicati all'URL

https://lumezzane.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
 
[metadata_lumezzane-signed.zip](https://github.com/italia/spid/files/3405200/metadata_lumezzane-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
