### ISSUE TITLE
Validazione metadata Comune di Abbadia San Salvatore 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1131]
Buongiorno,
per conto del Comune di Abbadia San Salvatore 

abbiamo prodotto i metadata  e pubblicati all'URL

https://abbadiasansalvatore.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_abbadiasansalvatore-signed.zip](https://github.com/italia/spid/files/3410047/metadata_abbadiasansalvatore-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
