### ISSUE TITLE
Richiesta verifica metadati Comune di Casale sul Sile

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1132]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Casale sul Sile.
https://www.comunecasale.tv.it/c026009/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
