### ISSUE TITLE
Validazione metadata Comune di Montalcino 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1133]
Buongiorno,
per conto del Comune di Montalcino 

abbiamo prodotto i metadata  e pubblicati all'URL

https://montalcino.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_montalcino-signed.zip](https://github.com/italia/spid/files/3421446/metadata_montalcino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
