### ISSUE TITLE
Validazione metadata Comune di Montanaso Lombardo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1134]
Buongiorno,
per conto del Comune di Montanaso Lombardo 

abbiamo prodotto i metadata  e pubblicati all'URL

https://montanasolombardo.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
 

[metadata_montanasolombardo-signed.zip](https://github.com/italia/spid/files/3421550/metadata_montanasolombardo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
