### ISSUE TITLE
Validazione metadata Comune di Montelepre

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1135]
Buongiorno,
per conto del Comune di Montelepre 

abbiamo prodotto i metadata  e pubblicati all'URL

https://montelepre.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_montelepre-signed.zip](https://github.com/italia/spid/files/3421564/metadata_montelepre-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
