### ISSUE TITLE
Richiesta verifica metadati Comune di Carbonera

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1137]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Carbonera
https://servizionline.comune.carbonera.tv.it/c026008/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
