### ISSUE TITLE
Richiesta verifica metadati Comune di Nervesa della Battaglia

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1139]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Nervesa della Battaglia
https://www.comune.nervesa.tv.it/c026050/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
