### ISSUE TITLE
Controllo metadata - Comune di Borgomanero

### ISSUE THREAD

**Issue by falbesano** [italia/spid#114]
Buongiorno,
per conto del Comune di Borgomanero, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.borgomanero.no.it/003024/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
