### ISSUE TITLE
Controllo metadata - Comune di Santena

### ISSUE THREAD

**Issue by falbesano** [italia/spid#1141]
Buongiorno,
per conto del Comune di Santena, richiediamo la verifica dei metadata pubblicati all'url:
https://comune.santena.to.it/contents/santena/metadataSPID.xml

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
