### ISSUE TITLE
Validazione metadata Comune di Siderno

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1146]
Buongiorno,
per conto del Comune di Siderno 

abbiamo prodotto i metadata  e pubblicati all'URL

https://siderno.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_siderno-signed.zip](https://github.com/italia/spid/files/3460151/metadata_siderno-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
