### ISSUE TITLE
Validazione metadata Comune di Gandino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1147]
Buongiorno,
per conto del Comune di Gandino 

abbiamo prodotto i metadata  e pubblicati all'URL

https://gandino.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_gandino-signed.zip](https://github.com/italia/spid/files/3460157/metadata_gandino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
