### ISSUE TITLE
Richiesta verifica file metadata Azienda Zero

### ISSUE THREAD

**Issue by facimaro** [italia/spid#1150]
Buonasera,
scrivo per conto di Azienda Zero, Regione del Veneto.
Con la presente chiedo la verifica del file metadata pubblicato all'indirizzo https://salute-test.regione.veneto.it/cas/spid/sp-metadata-test.xml.
Grazie

Cordiali Saluti
Fabiano

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta che l'Azienda zer ha già comunicato ad AgID un metadata.
Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).
