### ISSUE TITLE
Richiesta validazione metadata Comune di Sotto Il Monte Giovanni XXIII (BG)

### ISSUE THREAD

**Issue by proximalab** [italia/spid#1153]
Con la presente si richiede la validazione dei metadata per il comune di Sotto il Monte Giovanni XXIII (BG): 

https://www.comune.sottoilmontegiovannixxiii.bg.it/spid/module.php/saml/sp/metadata.php/default-sp

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
