### ISSUE TITLE
Validazione metadata Comune di Montano Lucino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1155]
Buongiorno,
per conto del Comune di Montano Lucino 

abbiamo prodotto i metadata  e pubblicati all'URL

https://montanolucino.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_montanolucino-signed.zip](https://github.com/italia/spid/files/3519974/metadata_montanolucino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
