### ISSUE TITLE
Validazione metadata Comune di Ponzano Veneto

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#1156]
Buongiorno,
per conto del Comune di Ponzano Veneto 

abbiamo prodotto i metadata  e pubblicati all'URL

https://ponzanoveneto.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_ponzanoveneto-signed.zip](https://github.com/italia/spid/files/3519986/metadata_ponzanoveneto-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
