### ISSUE TITLE
Richiesta validazione aggiornamento metadata per migrazione dominio - Comune di Bastia Umbra

### ISSUE THREAD

**Issue by PaolaSo** [italia/spid#1157]
In adempimento alla Determinazione Agid n. 36/2018 il Comune di Bastia Umbra deve migrare dal dominio comunebastiaumbra.gov.it al dominio comune.bastia.pg.it. La procedura di integrazione Spid effettuata lo scorso anno si riferisce al dominio comunebastiaumbra.gov.it. Su indicazione del Dott. Rosini, per gestire le fasi di avvicendamento, abbiamo generato un nuovo metadata, da sottoporre a sola procedura tecnica di validazione, con i riferimenti ad entrambi i domini per quanto riguarda AssertionConsumerService e SingleLogoutService. Per l'EntityID, che contiene il nome del dominio .gov, la ns. softwarehouse ha un dubbio sulla necessità di sostituirlo e pertanto per ora lo ha lasciato così come era. La stessa ha inoltre replicato AttributeConsumingService (uno per ogni dominio).  Nell' OrganizationURL è stato messo il solo nuovo dominio.
Il link del metadata aggiornato è [https://www.comunebastiaumbra.gov.it/c054002/spid-bastia.xml](https://www.comunebastiaumbra.gov.it/c054002/spid-bastia.xml)
ovvero [https://www.comune.bastia.pg.it/c054002/spid-bastia.xml](https://www.comune.bastia.pg.it/c054002/spid-bastia.xml)
Si chiede pertanto la validazione del metadata aggiornato ed eventuali indicazioni qualora non fosse corretto. In attesa di riscontro porgo cordiali saluti. Paola Sorci

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
