### ISSUE TITLE
Comune di Castelli Calepio - Anomalie con IdP Register e Intesa

### ISSUE THREAD

**Issue by globogis** [italia/spid#116]
Buonasera,

il Comune di Castelli Calepio ha aperto un ticket sul vecchio helpdesk chiedendo la validazione del servizio https://sportellotelematico.comune.castellicalepio.bg.it (conforme ai nostri altri Sportelli).

Il riferimento originario è: https://helpdesk.spid.gov.it/ticket.php?track=22X-J59-3R7J&e=ced%40comune.castellicalepio.bg.it&Refresh=57097

La validazione ha avuto esito negativo a causa di problemi di interazione con gli IdP Register e Intesa, che effettivamente rifiutano le richieste di autenticazione.

A nostro avviso si tratta però di un problema nel deploy da parte degli IdP, essendo le richieste emesse dalla stessa istanza di SimpleSAMLPHP e dunque del tutto conformi a quelle degli altri servizi da noi esposti, correttamente funzionanti con gli IdP in questione.

Chiedo dunque una verifica ed eventualmente un nuovo deploy dei metadati, sempre esposti all'endpoint: https://sportellotelematico.comune.castellicalepio.bg.it/simplesaml/module.php/saml/sp/metadata.php/castellicalepio

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il server su cui è installato il sito in questione non è stato adeguato al recente passaggio all'ora legale.
Conseguentemente, le AuthnRequest vengono generate con un IssueInstant riportante un orario non corretto e quindi non accettate.

Si prega di riconfigurare l'orario di sistema del server in mdo che sia allineato con l'orario corretto.

**Comment by globogis** [comment]
Buongiorno,
le nostre AuthnRequest riportano l'orario UTC come indicato dalla Z finale (`IssueInstant="2018-03-26T13:49:19Z"`). Non dovrebbe essere influenzato dal DST ed è sempre stato accettato senza problemi. L'anomalia del caso specifico si presenta comunque da prima di domenica.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Tutti gli Idp adesso rispondono correttamente.
