### ISSUE TITLE
Richiesta rinnovo validazione metadata - Comune di San Vito Romano (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#1161]
Salve,
si richiede la rivalidazione del metadata già in esercizio per il Comune di San Vito Romano (RM):

http://static.comune.sanvitoromano.rm.it/uploads/n200438.xml

Cordiali saluti
Grazie
We-COM Srl

**Comment by wecomsrl** [comment]
Buongiorno,
il cliente ha urgenza che il metadato sia validato. Ci sono problemi?

**Comment by damikael** [comment]
Salve,

la richiesta è stata presa in carico via email. Per ulteriori richieste o segnalazioni si prega di scrivere a spid.tech@agid.gov.it

Grazie,
cordiali saluti.
