### ISSUE TITLE
Regione Veneto - richiesta aggiornamento metadata

### ISSUE THREAD

**Issue by francesco-fornasiero** [italia/spid#117]
PA: Regione Veneto
Categoria: aggiornamento metadata per aggiunta nuovo servizio

Si richiede aggiornamento del file metadata esposto da Regione Veneto per l'aggiunta di un nuovo servizio.

Url file metadata viene inviato via mail.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
