### ISSUE TITLE
problemi di accesso al sito https://idp.spid.gov.it:8080/

### ISSUE THREAD

**Issue by aspar** [italia/spid#1178]
Salve, attualmente non funziona il servizio idp di test di agid.
E' cambiato qualche cosa o è solo un problema temporaneo?

Grazie
Alfonso Sparano

**Comment by damikael** [comment]
Salve,
è stato rilasciato il nuovo ambiente di test sull'indirizzo https://idp.spid.gov.it.
Per utilizzare il nuovo ambiente occorre:

- registrare sul proprio SP il metadata dell'ambiente di test scaricabile da https://idp.spid.gov.it/metadata
- registrare il proprio metadata sull'idp di test all'indirizzo https://idp.spid.gov.it/admin/databasesprecord/

(Rif. https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid#procedura-tecnica-4)

**Comment by ddefrancesco** [comment]
Salve, 
una domanda, stante la nuova configurazione ci sono modifiche da fare al progetto spid-shibboleth-proxy-docker? 
Grazie in anticipo
Daniele De Francesco

**Comment by Antonyclar** [comment]
Come mai non è più possibile raggiungere l'indirizzo [https://idp.spid.gov.it](url) ?
Quale sarebbe il nuovo indirizzo a cui fare riferimento?

**Comment by damikael** [comment]
Buongiorno @Antonyclar ,
l'ambiente di test idp.spid.gov.it è stato dismesso in favore del nuovo ambiente demo disponibile su https://demo.spid.gov.it, basato sulla [modalità demo di spid-saml-check](https://github.com/italia/spid-saml-check#how-to-use-it-as-a-spid-demo).
Alla pagina https://demo.spid.gov.it è possibile trovare le istruzioni per l'utilizzo del nuovo ambiente.

Cordiali saluti,
Michele

**Comment by Antonyclar** [comment]
Buongiorno @damikael ,
scusami se la seguente domanda può risultarti banale, ma ho iniziato ad addentrarmi nello spid da pochi giorni e sto cercando di capirci qualcosa...

La mia idea sarebbe quella di utilizzare il progetto [https://github.com/italia/spid-dotnet-sdk](url) mettendolo in funzione sulla mia macchina in locale. Non voglio mandare nulla in produzione quindi tutto ciò che farò è finalizzato a far funzionare la WebApp e ripercorrere i passaggi per le operazioni di Login e Logout sfruttando l'applicazione stessa.

Al momento ho creato solamente i certificati così come indicato dalla procedura.
Ho creato un nuovo file metadata.xml come quello in esempio sostituendo la chiave pubblica del mio certificato SelfSigned.

Domande:
1) Una volta creati i certificati ed il file metadata come dovrei procedere? E' necessario inviare ad AgID il metadata? Come potrei assicurarmi che a quel punto le mie richieste di Login vengano correttamente accettate da Poste.it?
2) Nell'ambiente demo dice di scaricare il metadata demo e configurarlo sul mio sp, come andrebbe fatto ciò?
3) "Inviare una AuthnRequest dal proprio Service Provider all'IdP dell'ambiente Demo SPID" può essere fatto dalla WebApp che devo testare?

Cordiali saluti,
Antonio.

**Comment by damikael** [comment]
Ciao @Antonyclar ,

1. [la procedura di adesione, descritta sul sito spid.gov.it](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), prevede l'invio di una mail per la richiesta di collaudo, indicando, tra le altre informazioni, l'url al metadata e l'url alla quale è presente il bottone "Entra con SPID" con il collegamento al Validator ufficiale (https://validator.spid.gov.it).
2. dipende dal Service Provider e dal SDK utilizzato per implementare il protocollo SPID, nel tuo caso ti consiglio di chiedere sul repository di spid-dotnet-sdk.
3. deve essere fatto, per poter verificare tramite l'ambiente Demo SPID l'integrazione, e deve essere fatto con il collegamento al Validator ufficiale (https://validator.spid.gov.it) per procedere alla richiesta di collaudo AgID.

Ti consiglio inoltre di unirti al canale slack spid per ulteriore supporto da parte della community.

**Comment by Antonyclar** [comment]
Essendo un semplice test non ho un indirizzo url su cui ho messo il metadata nè tantomeno il bottone visto che cerco solo di far funzionare questa applicazione.
Volendo solo fare una prova in locale dovrei mandare questi url come "localhost" creando magari un web server (quindi http non https)? O devono essere effettivamente esposti diversamente?
