### ISSUE TITLE
Segnalazione Anomalie su sito IC Verdellino

### ISSUE THREAD

**Issue by atodaro** [italia/spid#118]
[Istituto Comprensivo di Verdellino](https://icverdellino.gov.it/)
## Segnalazione anomalie
Sito Joomla 3.8.6 - sito in fase di testing finale
Da domenica 25/03 comparsa di errori nel login su alcuni IdP come da report indicato sotto:

**TimID**: _CA Access Gateway - Error Report
Error Details
Request URI:/affwebservices/public/saml2sso
Error Type: Web server Error
Error Code: 403
Message: Forbidden. Server understood the request but is refusing to fulfill the request._

**Intesa**: Impossibile stabilire l'autenticità  della richiesta di autenticazione - Contattare il gestore del servizio

**Aruba**: Error Formato richiesta non corretto - Contattare il gestore del servizio
**Register.it**: Errore nel processo di login Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il server su cui è installato il sito in questione non è stato adeguato al recente passaggio all'ora legale.
Conseguentemente, le AuthnRequest vengono generate con un IssueInstant riportante un orario non corretto e quindi non accettate.

Si prega di riconfigurare l'orario di sistema del server in mdo che sia allineato con l'orario corretto.

**Comment by atodaro** [comment]
L'hosting mi dice che a loro risulta un settaggio corretto dell'orario.

**Comment by AntonioGiovanniSchiavone** [comment]
Ok, svolgiamo altre verifiche.

**Comment by umbros** [comment]
Inviata comunicazione a TIM.

**Comment by AntonioGiovanniSchiavone** [comment]
Tutti gli IdP rispondono correttamente alle AuthnRequest
