### ISSUE TITLE
Richiesta verifica metadati Comune di Sernaglia della Battaglia

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1180]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sernaglia della Battaglia
https://www.comune.sernaglia.tv.it/c026080/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
