### ISSUE TITLE
Errore in autenticazione con IDP di test

### ISSUE THREAD

**Issue by Antonino09** [italia/spid#1182]
Buongiorno,
avrei necessità di assistenza nella comunicazione tra il mio SP e il vostro IDP test, di seguito le operazioni eseguite:
1) Ho registrato il mio SP inserendo il mio metadata al link [https://idp.spid.gov.it/admin/databasesprecord](https://idp.spid.gov.it/admin/databasesprecord)
2) Ho provato ad inviare una richiesta da mio SP al vostro IDP al link [https://idptest.spid.gov.it/sso](https://idptest.spid.gov.it/sso)

Quello che ottengo è una pagina di errore con la seguente indicazione :
**builtins.AttributeError**
**AttributeError: 'str' object has no attribute 'decode'**

Potete darmi supporto indicandomi come risolvere?

Grazie in anticipo per la collaborazione,
Cordiali Saluti.

**Comment by damikael** [comment]
Salve,
potrebbe riprovare ad inviare nuovamente la Request?

Il problema indicato è un errore dell'ambiente di test, già segnalato
(Rif. https://github.com/italia/spid-testenv2/issues/237)

**Comment by Antonino09** [comment]
Salve,
ho provato ad effettuare la richiesta e non mi ha dato errore portandomi alla pagina di login.
Adesso ho riprovato è mi da l'errore.

Avete già individuato il problema ? Entro quanto verrà risolto ?

**Comment by Antonino09** [comment]
Salve,
adesso sembra funzionare non ricevo più la pagina di errore.
Grazie

**Comment by Antonino09** [comment]
Salve,
purtroppo si è ripresentato il problema.

**Comment by Antonino09** [comment]
Salve,
al momento sembra funzionare.
Grazie

**Comment by aspar** [comment]
Salve, anche io riscontro un problema simile. In pratica quando vengo rimandato sulla pagina di autenticazione dell'idp di test mi esce un errore del tipo:
builtins.ValueError
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Saluti
Alfonso Sparano

**Comment by fsforna** [comment]
Stesso errore:

builtins.AttributeError

AttributeError: 'str' object has no attribute 'decode'

**Comment by pladgepeople** [comment]
stesso errore :

builtins.AttributeError

AttributeError: 'str' object has no attribute 'decode'
![Schermata 2019-10-02 alle 22 02 41](https://user-images.githubusercontent.com/39263226/66146224-a55f6800-e60c-11e9-834c-87d44520f1d7.png)
