### ISSUE TITLE
Errore in autenticazione con IDP di test 

### ISSUE THREAD

**Issue by Antonino09** [italia/spid#1184]
Buongiorno,
riscontro ancora il problema definito nell'issue [1182](https://github.com/italia/spid/issues/1182)

Grazie

**Comment by aspar** [comment]
Buongiorno, ancora problemi con l'idp di test? Ottengo:
builtins.ValueError
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Grazie

**Comment by damikael** [comment]
Salve,
occorre risalvare il metadata eliminando la dichiarazione xml iniziale <?xml version="1.0" ... ?>
