### ISSUE TITLE
"Richiesta verifica tecnica e convenzione per conto del comune di San Pellegrino Terme"

### ISSUE THREAD

**Issue by Sanpellegrinoterme** [italia/spid#119]
"L’ente richiede ad AgID la verifica tecnica sull'implementazione di SPID (l'url è il seguente:https://suap.sanpellegrinoterme.gov.it/ ), la ricezione della convenzione nel formato Pdf ed il file in formato Ods per la compilazione dei servizi attivi"

**Comment by umbros** [comment]
Verifica KO errore con IDP Intesa

**Comment by globogis** [comment]
Buongiorno,
come per la issue #116 dal nostro lato non riscontriamo anomalie implementative: il Portale è conforme agli altri sportelli Globo già precedentemente validati. Riteniamo che ci sia stato un problema nel deploy dei metadati per lo specifico IdP: chiediamo dunque una verifica in merito.
Grazie

**Comment by globogis** [comment]
Buongiorno,
l’implementazione del servizio è identica a quelle già precedentemente validate da GLOBO. Riteniamo che ci sia stato invece un problema nel deploy da parte dell’IdP Intesa. Chiedo cortesemente una verifica in merito.
L’URL dei metadati, se fosse nuovamente necessario, è: https://suap.sanpellegrinoterme.gov.it/simplesaml/module.php/saml/sp/metadata.php/sanpellegrinoterme
Grazie

**Comment by globogis** [comment]
Buongiorno,
riscontriamo ora (senza alcuna modifica da parte nostro) la corretta interazione con IdP Intesa. Ritengo quindi che i metadati siano ora correttamente deployati.
chiedo dunque ad @AntonioGiovanniSchiavone se è possibile procedere con l'invio di quanto originariamente richiesto.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Chiusa per trasferimento discussione in [Issue #352](https://github.com/italia/spid/issues/352)
