### ISSUE TITLE
Aggiornamento metadata Comune di Collegno per aggiunta SP

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#12]
Buon pomeriggio, 
a seguito introduzione nuovo SP per il Comune di Collegno ("Sportello Unico Digitale"  società Technical Design) allego metadata aggiornati.
saluti
Facondini Stefano 

[metadata_collegno2SP-signed.zip](https://github.com/italia/spid/files/1767785/metadata_collegno2SP-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buon pomeriggio,

Abbiamo riscontrato i seguenti errori:

1) Nei sottoelementi dell'elemento AttributeConsumingService di indice uguale a 2 manca il prefisso md: (vedi mancata analogia con gli altri elementi AttributeConsumingService).

Si prega di modificare il metadata, rifirmarlo e ripubblicarlo.

**Comment by sfacondini** [comment]
Buongiorno, 
i metadata sono stati corretti e rifirmati come da indicazioni e condivisi 
con il secondo SP
sono pubblicati all'URL:   
https://collegno.comune-online.it/serviziSPID/metadata.xml

In allegato anche in questa mail
Cordiali saluti
Facondini Stefano 

Area Portali ed e-Government
Tel.: 0541.628399
Mob. 329 0528602
e-mail: sfacondini@maggioli.it
http://www.maggioli.it/informatica/





Da:     Antonio Giovanni Schiavone <notifications@github.com>
Per:    italia/spid <spid@noreply.github.com>
Cc:     sfacondini <sfacondini@maggioli.it>, Author 
<author@noreply.github.com>
Data:   28/02/2018 18.13
Oggetto:        Re: [italia/spid] Aggiornamento metadata Comune di 
Collegno per aggiunta SP (#12)



Buon pomeriggio,
Abbiamo riscontrato i seguenti errori:
1.      Nei sottoelementi dell'elemento AttributeConsumingService di 
indice uguale a 2 manca il prefisso md: (vedi mancata analogia con gli 
altri elementi AttributeConsumingService).
Si prega di modificare il metadata, rifirmarlo e ripubblicarlo.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il metadata è stato deployato presso gli IdP e sarà caricato entro le ore 8:00 di domani.
