### ISSUE TITLE
Richiesta di validazione metadati - Comune di Carvico

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#120]
Buongiorno,
si richiede la validazione dei metadati per conto del Comune di Carvico:
https://sportellotelematico.comune.carvico.bg.it/simplesaml/module.php/saml/sp/metadata.php/carvico
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
