### ISSUE TITLE
ATS Città Metropolitana di Milano - Aggiornamento Metadata

### ISSUE THREAD

**Issue by scubla88** [italia/spid#1228]
Buongiorno,
si richiede l'aggiornamento del metadata, per nuovo certificato, per conto dell'ATS Città Metropolitana di Milano
https://spid.ats-milano.it/metadata

Grazie,
Fabio Scubla
Invisiblefarm Srl

**Comment by scubla88** [comment]
Buongiorno,
è possibile avere un riscontro in merito? È stato distribuito agli IdP?

Grazie,
Fabio Scubla
Invisiblefarm Srl

**Comment by scubla88** [comment]
Buongiorno @AntonioGiovanniSchiavone,
abbiamo urgenza di aggiornare il metadata per garantire il servizio, riuscire a trasmetterlo agli IdP?

Grazie e buon lavoro.

**Comment by gmsesto** [comment]
buongiorno
come ATS Città Metropolitana di Milano in questo momento siamo in disservizio con tutte le applicazioni web con accesso SPID, vi chiediamo cortesemente di intervenire ridistribuendo agli IdP il nuovo metadata. 
grazie per la collaborazione

**Comment by scubla88** [comment]
Buongiorno,
siamo ancora in attesa della trasmissione del nuovo metadata verso gli IdP.

Grazie.

**Comment by scubla88** [comment]
Buongiorno @damikael ,
è possibile avere un riscontro in merito?
Grazie e cordiali saluti.

**Comment by scubla88** [comment]
Metadata trasmesso agli IdP.
