### ISSUE TITLE
Nuovi metadati Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#123]
Buongiorno
si richiede la validazione e il deploy dei nuovi metadati della Regione Puglia.
é stato aggiunto un servizio per cittadini e imprese e di conseguenza è stato aggiunto un'altro set di attributi.
In particolare:
i dati relativi alla luogo di nascita(placeOfBirth, countryOfBirt), di domicilio (address) e il documento di identità (idCard) vengono utilizzati dai servizi integrati con i servizi comunali del territorio e con l'ANPR.
Il numero telefonico serve per gli alert via SMS
i dati relativi alle imprese (ivaCode, companyName,registeredOffice) servono per l'accesso ai servizi dedicati alle imprese.
I metadati sono scaricabili da [https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml)
Saluti
Marcello Marangio
Innova Puglia s.p.a

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
