### ISSUE TITLE
Validazione Metadata CONSAP

### ISSUE THREAD

**Issue by Alec1bert** [italia/spid#1233]
Salve,
con la presente si richiede la validazione del metadata per CONSAP ( Concessionaria Servizi Assicurativi Pubblici ):
Url del metadata;  https://spid.consap.it/metadata/metadata.xml
Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;  https://spid.consap.it/idpselector/idpselector.html

Si tratta di un nuovo metadata/servizio.

Grazie
Saluti

**Comment by damikael** [comment]
Richiesta presa in carico via email
