### ISSUE TITLE
Richiesta verifica metadati Comune di Roverè Veronese

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1234]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Roverè Veronese
https://www.comune.rovereveronese.vr.it/c023067/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
