### ISSUE TITLE
Richiesta verifica metadati Comune di Maserà di Padova

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1239]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Maserà di Padova
https://www.comune.masera.pd.it/c028048/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
