### ISSUE TITLE
Richiesta verifica metadati Comune di Villafranca Padovana

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1240]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Villafranca Padovana
https://www.comune.villafranca.pd.it/c028103/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
