### ISSUE TITLE
Richiesta verifica metadati Comune di Boara Pisani

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1242]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Boara Pisani
https://www.comune.boarapisani.pd.it/c028012/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
