### ISSUE TITLE
vulnerabilità di sicurezza server

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#1243]
Buongiorno,
durante le verifiche di validazione per il metadata di un ente, è stata restituita una anomalia che indica:
"sono presenti diverse vulnerabilità di sicurezza importanti nel server esposto al suddetto URL;"

Poichè nelle regole SPID non abbiamo trovato nessuna indicazione su quali siano i controlli che vengono eseguiti su questo aspetto, abbiamo eseguito i test SSL utilizzando diversi tools, e tutti vengono passati con esito positivo. 
Potreste indicarci l'elenco delle verifiche di vulnerabilità che vengono eseguti, o indicarci dove reperire tale elenco?
Grazie,
Mariano Carta

**Comment by damikael** [comment]
Buongiorno,
il collega provvederà a risponderle via email.

Saluti
Michele D'Amico
