### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Isola del Liri (FR)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#1247]
Buongiorno,
per conto del Comune in oggetto si richiede la verifica e il deploy dei metadati esposti all'URL:
http://www.comune.isoladelliri.fr.it/spid/metadata.xml 

Grazie.

**Comment by damikael** [comment]
Salve,
per procedere con la verifica tecnica occorre seguire la procedura indicata in:
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

Ovvero inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente (se soggetto privato, denominazione o ragione sociale seguita da Codice Fiscale o P.IVA);
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Grazie,
Michele D'Amico
