### ISSUE TITLE
Richiesta verifica metadati Comune di Creazzo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#1252]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Creazzo
https://www.comune.creazzo.vi.it/c024036/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
