### ISSUE TITLE
nuovi metadati Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#1254]
Buonasera
si richiede che vengano verificati e comunicati ai gestori SPID i nuovi metadati della Regione Puglia scaricabili da [https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml)

Saluti
Marcello Marangio
InnovaPuglia S.p.A.

**Comment by damikael** [comment]
Buonasera,
come da procedura indicata sul sito SPID (Rif. https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid#procedura-tecnica-5)

si prega di inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

a) Nome ente;
b) Url del metadata;
c) che si tratta di aggiornamento;
d) Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
e) Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
f) Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Grazie
Michele D'Amico
