### ISSUE TITLE
AssertionError [ERR_ASSERTION]: id_token issued in the future

### ISSUE THREAD

**Issue by saprilespid** [italia/spid#1266]
Buongiorno a tutti, ho sviluppato una prima versione di SPID in php utilizzando le librerie disponibili su Developers Italia. In fase di test con un IDP di prova, nel momento in cui cerco di eseguire il login, mi viene visualizzato il seguente errore: 

AssertionError [ERR_ASSERTION]: id_token issued in the future

Da cosa potrebbe dipendere? Come posso risolvere il problema?
In allegato il printscreen dell'errore.

![errore](https://user-images.githubusercontent.com/60007161/72622141-ecb2ff80-3942-11ea-9061-321fd27b83cf.jpg)

Grazie in anticipo
SaprileSpid

**Comment by damikael** [comment]
Salve,

da quanto indicato, evidentemente, l'idp utilizzato era SPID Validator online.
L'utilizzo di tale ambiente è riservato esclusivamente ad AgID, pertanto l'accesso non è consentito.
Per effettuare i test, invece, è possibile utilizzare l'ambiente di test pubblico esposto su https://idp.spid.gov.it

In merito alla configurazione verso l'ambiente di test e alla procedura tecnica, è possibile trovare tutte le informazioni in: 
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

A titolo informativo, quale libreria php è stata utilizzata?

Saluti,
Michele D'Amico

**Comment by saprilespid** [comment]
Ciao Damikael, grazie per la risposta, infatti ho eseguito esattamente quello che c'è indicato al punto 5 del link che mi hai suggerito. La libreria utilizzata è "SDK per PHP" scaricabile dal link https://github.com/italia/spid-php-lib.

Comunque, stamattina ho riprovato e l'errore segnalato non risulta più, in compenso ne ho un altro, ed è il seguente: "Accesso non autorizzato. Contattare l'amministratore di sistema."

Mi sapresti indicare qualcosa?

Grazie

**Comment by damikael** [comment]
Ciao @saprilespid,
 come ti dicevo l'ambiente di validazione online è di utilizzo esclusivo di AgID, per questo riscontri "Accesso non autorizzato". 
Se vuoi, però, puoi installare in locale lo stesso ambiente (https://github.com/italia/spid-saml-check) per eseguire in autonomia le verifiche.
