### ISSUE TITLE
Verifica Tecnica SPID

### ISSUE THREAD

**Issue by dev-palmieri** [italia/spid#1296]
Buonasera,
per la mia società ho provveduto ad implementare lo SPID.
Successivamente ho inviato una richiesta di verifica tecnica, tramite mail, a spid.tech@agid.gov.it  come indicato all'URL https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid con i seguenti punti specificati:
a) Nome ente (denominazione o ragione sociale) e alternativamente:
- se soggetto pubblico, Codice IPA
- se soggetto privato, Codice Fiscale o P.IVA
b) Url del metadata;
c) Se si tratta di aggiornamento o nuovo metadata;
d) Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
e) Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
f) Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Volevo chiedere se la procedura è corretta ed eventualmente i tempi di risposta.

Grazie

**Comment by dev-palmieri** [comment]
Buongiorno,
ho ricevuto la risposta relativa alla verifica tecnica nella quale è stato richiesto, per i soggetti privati, di specificare quali servizi si intende rendere disponibili online per il cittadino.
Per "servizi" si intende gli IDP disponibili al cittadino oppure per più realisticamente le "operazioni" (pagamenti, verifiche/consultazioni) che il cittadino, una volta autenticato può eseguire?
Grazie

**Comment by damikael** [comment]
Buongiorno, 
per servizi si intende "le operazioni", ovvero ciò che il Service Provider offre al cittadino.

**Comment by dev-palmieri** [comment]
Grazie

**Comment by dev-palmieri** [comment]
Buongiorno,
come indicato nella precedente richiesta abbiamo provveduto, nella mail di richiesta della verifica, a specificare i  servizi che si intendono rendere disponibili online al cittadino tramite SPID. 
Per dare una spiegazione dettagliata abbiamo allegato un file esplicativo. Non riusciamo a capire cosa non vada nella spiegazione data.
Allego lo stesso file nella speranza di avere un ulteriore chiarimento.
[Servizi per il cittadino.pdf](https://github.com/italia/spid/files/4877350/Servizi.per.il.cittadino.pdf).

Grazie

**Comment by dev-palmieri** [comment]
Buongiorno,
se possibile volevo chiedere chiarimenti su due punti relativi alla fase di verifica dello SPID tramite l'ambiente SPID validatr che abbiamo provveduto ad istallare in locale:

1) In fase di verifica dei metadata esegundo il controllo "Check Strict" tutti i punti della verifica vanno a buon fine. 
Eseguendo poi il controllo "Check XSD"  i test si conclude con un errore "the metadata must validate against the XSD stderr: ./data/https___applicazione_fiscolocale_it_portale_homeutente/sp-metadata.xml:46: 
element Signature: Schemas validity error : Element '{http://www.w3.org/2000/09/xmldsig#}Signature': This element is not expected. Expected is one of 
( {urn:oasis:names:tc:SAML:2.0:metadata}ContactPerson, {urn:oasis:names:tc:SAML:2.0:metadata}AdditionalMetadataLocation ). stderr: ./data/https___applicazione_fiscolocale_it_portale_homeutente/sp-metadata.xml fails to validate"

Ho notato che modificando la posizione della "Signature" nei metadata il risultato cambia il controllo "Check XSD" va a buon fine mentre fallisce il "Check Strict". Quale può essere il motivo di questo comportamento?

2) Nella verifica della "Response" il test n. 40 "Assertion: - Attributo IssueInstant successivo a IssueInstant della Request" (Risultato atteso KO) non capiamo "il senso del controllo". Il programma lo SPID validator valorizza lo IssueInstant dell'Assertion
con data e ora corrente (now) quindi sarà sempre successivo alla IssueInstant della "Request". D'altronde anche nel test n. 1 "Response Corretta" lo IssueInstant dell'assertion è successivo a quello della Request ma non viene segnalato
alcun errore all'esecuzione del test.

Grazie
