### ISSUE TITLE
Richiesta supporto tecnico Regione Campania

### ISSUE THREAD

**Issue by gennaroromano** [italia/spid#130]
Regione Campania
chiede cortesemente lo stato della verifica tecnica, richiesta con email inviata a spid.tech@agid.gov.it, il giorno 22/02/2018, in cui si indicava il seguente URL del servizio da validare:

https://spidgateway.regione.campania.it/verificagel/

In oggetto si fa riferimento alla issue #5 aggiunta da Umberto Rosini per conto di Regione Campania.

Il test del servizio suddetto comporta il seguente errore, analogo per gli altri IdP:

![image](https://user-images.githubusercontent.com/37836127/37967011-5f74c1f2-31ca-11e8-86d2-f55800d0d773.png)

Saluti,
Gennaro Romano

Regione Campania
DG 10 - UNIVERSITÀ, RICERCA E INNOVAZIONE
Staff 92 - Funzioni di supporto tecnico – amministrativo

**Comment by gennaroromano** [comment]
@umbros

**Comment by AntonioGiovanniSchiavone** [comment]
Da una prima verifica si è rilevato che la firma apposta sulle AuthnRequest non soddisfa i criteri indicati a pag. 10  del **[Regolamento recante le norme tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf)**. 

Si prega di adeguare i sistemi a tali richieste.

**Comment by gennaroromano** [comment]
Stiamo verificando la firma apposta sulle AuthnRequest.
Intanto, vi chiediamo cortesemente di verificare se il metadata caricato dagli IdP è l'ultima versione comunicata da Regione Campania e validata da AgID, come da procedura, pubblicato al seguente URL
https://spidgateway.regione.campania.it/gelmetadata/r_campan

In relazione al metadata si veda il ticket alla URL sottostante:
https://helpdesk.spid.gov.it/ticket.php?track=EBG-DR3-PPP1&e=gennaro.romano%40regione.campania.it&Refresh=27100

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Gli IdP hanno da giorni caricato l'ultima versione del vostro metadata. 
Come precedentemente indicato, le vostre AuthnRequest non rispettano i criteri indicati a pag. 10 del Regolamento recante le norme tecniche SPID, che di seguito riportiamo:

_Nel caso del binding HTTP POST deve essere presente l’elemento <Signature> contenente la firma sulla richiesta apposta dal Service Provider. La firma deve essere prodotta secondo il profilo specificato per SAML (cfr [SAML-Core] cap5) utilizzando chiavi RSA almeno a 1024 bit e **algoritmo di digest SHA-256 o superiore;**_  


Le vostre AuthnRequest utilizzano un algoritmo di digest SHA-1

**Comment by AntonioGiovanniSchiavone** [comment]
Issue  Risolta
