### ISSUE TITLE
Come configurare lo SPID Validator per abilitare i controlli della response senza avere credenziali AgID

### ISSUE THREAD

**Issue by michelezinna** [italia/spid#1304]
Buongiono volevo chiedere se era possibie e come procedere per configurare lo SPID Validator per abilitare i controlli della response senza avere credenziali AgID.
Grazie

**Comment by damikael** [comment]
Buongiorno,
il codice di SPID Validator è disponibile opensource al repository:
https://github.com/italia/spid-saml-check

È possibile installarlo in locale ed utilizzarlo accedendo con le credenziali predefinite validator : validator
Per maggiori informazioni su come installare l'ambiente, fare riferimento alle indicazioni sul repository:
https://github.com/italia/spid-saml-check/blob/master/README.md

**Comment by michelezinna** [comment]
Grazie molte per la rapidissima risposta, la mia difficoltà era nella generazione di una respose utilizzando il tool. 
Quando avvio il validator a partire da una qualsiasi richiesta di uno dei service provider attualmente registrati (es. Poste) il plugin chrome intercetta la richiesta e la posso analizzare (così come posso analizzarla con il specs-compliance-tests), mentre non posso ovviamente generare la risposta in quanto non firmata dal certificato atteso. Pensavo di poter simulare le sisposte dell'IDP: https://validator.spid.gov.it/samlsso, in modo da poter effettuare tutte le validazioni richieste.
Chiedevo se era un'operazione possibile e in caso darmi l'indicazione di dove posso trovare le istruzioni. 
Saluti.

**Comment by damikael** [comment]
Per poter inviare response simulate dal Validator, non bisogna utilizzare il plugin Chrome, ma:
 - installare il validator in locale
 - configurare il metadata del proprio validator sul SP
 - inviare request al proprio validator

Sarà quindi possibile accedere alla sezione Response, selezionare la response e inviarla al SP.
Prima di inviare una response, è necessario registrare il metadata del SP sul proprio Validator.
Dopo aver inviato la response, la sessione sul Validator resterà attiva esclusivamente per salvare l'esito.
