### ISSUE TITLE
Verifica SPID Validator

### ISSUE THREAD

**Issue by dev-palmieri** [italia/spid#1308]
Buongiorno,
se possibile volevo chiedere chiarimenti su due punti relativi alla fase di verifica dello SPID tramite l'ambiente SPID validatr che abbiamo provveduto ad istallare in locale:

In fase di verifica dei metadata esegundo il controllo "Check Strict" tutti i punti della verifica vanno a buon fine.
Eseguendo poi il controllo "Check XSD" i test si conclude con un errore "the metadata must validate against the XSD stderr: ./data/https___applicazione_fiscolocale_it_portale_homeutente/sp-metadata.xml:46:
element Signature: Schemas validity error : Element '{http://www.w3.org/2000/09/xmldsig#}Signature': This element is not expected. Expected is one of
( {urn:oasis:names:tc:SAML:2.0:metadata}ContactPerson, {urn:oasis:names:tc:SAML:2.0:metadata}AdditionalMetadataLocation ). stderr: ./data/https___applicazione_fiscolocale_it_portale_homeutente/sp-metadata.xml fails to validate"
Ho notato che modificando la posizione della "Signature" nei metadata il risultato cambia il controllo "Check XSD" va a buon fine mentre fallisce il "Check Strict". Quale può essere il motivo di questo comportamento?

Nella verifica della "Response" il test n. 40 "Assertion: - Attributo IssueInstant successivo a IssueInstant della Request" (Risultato atteso KO) non capiamo "il senso del controllo". Lo SPID validator valorizza lo IssueInstant dell'Assertion
con data e ora corrente (now) quindi sarà sempre successivo alla IssueInstant della "Request". D'altronde anche nel test n. 1 "Response Corretta" lo IssueInstant dell'assertion è successivo a quello della Request ma non viene segnalato
alcun errore all'esecuzione del test.
Grazie

**Comment by damikael** [comment]
Buonasera,

gli XSD per la verifica del metadata SPID, così come gli XSD ufficiali SAML, prevedono che la firma sia posta "in testa". Per una analisi più approfondita, tuttavia, occorre avere i riferimenti del metadata in questione.

Riguardo al test Response n. 40, è da intendersi che la Response non può avere un IssueInstant _di molto_ successivo alla Request, infatti l'esempio inserito nel Validator, presenta un IssueInstant volutamente esagerato (2099-01-01T00:00:00Z).
Normalmente può essere considerata valida una Response avente un IssueInstant non superiore di 5min  dalla Request. 

Saluti,
Michele
