### ISSUE TITLE
Richiesta di validazione e deploy metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#131]
Buongiorno,
Si richiede la verifica e il deploy dei metadati per conto del Comune di Commessaggio.
https://www.sportellotelematicoterreoglio.it/simplesaml/module.php/saml/sp/metadata.php/unioneterredoglio 
Si tratta di uno Sportello conforme a quelli già precedentemente validati da Globo.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
