### ISSUE TITLE
Problema Firma sui metadati IdP Intesa ID

### ISSUE THREAD

**Issue by gfollesa** [italia/spid#1312]
Buongiorno,

scrivo per conto di Sardegna IT che si occupa della gestione del sistema di autenticazione centralizzato agganciato a SPID per la Regione Sardegna. Da qualche giorno riscontriamo un problema sui metadati forniti dall'identity provider IntesaID. La verifica della firma apposta sull'xml scaricato da https://spid.intesa.it/metadata/metadata.xml va in errore. Utilizziamo la libreria OpenSAML che a sua volta utilizza librerie xmlsec Apache Santuario per la verifica della firma. Il certificato utilizzato è quello fornito sul metadata stesso.
L'errore riportato dalle librerie sul digest:
Expected Digest: Xw21wBz3aKEZUaJhOLUcVoHk3hX3FZWQeUH4mAnFetI=        (presente nell’xml)
Actual Digest: w+1EhJJcYbEAVZ8qyNUtad7jWWLjyqvBKP+4UnueiVo=                 (calcolato dalle librerie)

Tutte le verifiche sulle firme degli altri Identity provider risultano andare a buon fine. In attesa di una soluzione al problema Vi chiediamo se è possibile disabilitare temporaneamente l'accesso con l'IdP Intesa

Possiamo chiedere di effettuare una verifica?

Saluti,
Giorgio Follesa.

**Comment by fume** [comment]
Sto riscontrato lo stesso problema...

**Comment by damikael** [comment]
La segnalazione è stata inoltrata agli uffici di competenza ed il metadata è stato aggiornato.

Grazie per la collaborazione.
Michele D'Amico
