### ISSUE TITLE
Validazione Metadata Comune di Castel d'Azzano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#132]
Buongiorno,
Si richiede cortesemente la verifica dei metadati per conto del Comune di Castel d'Azzano.
https://www.comune.castel-d-azzano.vr.it/c023021/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

**Comment by halleyveneto** [comment]
Buongiorno, Si richiede cortesemente una verifica tecnica finale per la definitiva messa in produzione e convenzione.

URL relative ai servizi da validare:

https://www.comune.castel-d-azzano.vr.it/po/po_login.php
https://www.comune.castel-d-azzano.vr.it/po/po_imlogin.php
https://www.comune.castel-d-azzano.vr.it/po/po_pr_login.php
