### ISSUE TITLE
Verifica metadata aggiornata Comune di Sarzana

### ISSUE THREAD

**Issue by paduanoa** [italia/spid#133]
Buongiorno,
a seguito della scadenza del Certificatodi sicurezza, si invia l'url conntenente il nuovo metadata da validare del nostro Ente, Comune di Sarzana.

http://www.comunesarzana.gov.it/images/sarzana/n201753.xml

Grazie
Antonio Paduano

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Come indicato dal Regolamento recante le norme tecniche SPID, l'EntityID rapprensenta un identificatore unico del soggetto definito dal metadata in oggetto (ossia il Service Provider aderente a SPID).

In quanto identificatore unico, esso , una volta definito nel primo metadata, deve essere mantenuto costante negli eventuali successivi aggiornamenti del metadata relativi allo stesso Service Provider.

Nel caso specifico del Comune di Sarzana , dai nostri sistemi risulta che all'interno del metadata precedentemente presentato  il valore dell'EntityID è stato definito come "https://spid.comunesarzana.gov.it/sp-spid/", mentre nel nuovo metadata comunicato l'EntityID è stato incorrettamente valorizzato con un valore diverso.

Si prega di ripristinare il valore originario dell'EntityID "https://spid.comunesarzana.gov.it/sp-spid/", rifirmare il metadata e  di comunicarne la disponibilità all'endpoint segnalato.

**Comment by filippoerminipadigitale** [comment]
Buongiorno, mi permetto di intervenire in quanto partner tecnologico che si occupa della gestione del sistema di autenticazione SPID per conto del comune di Sarzana. L'entityId specificato nel metadato sottoposto ("https://spid.gov.it/entities/sp/c_i449") mi è stato richiesto direttamente da Umberto Rosini, ed il metadato che avevamo inviato l'ultima volta e da voi validato riportava quel valore.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

**Comment by filippoermini-padigitale** [comment]
Buon pomeriggio, abbiamo riscontrato un problema di accesso con l'Idp di Intesa. Questo tipo di problema lo avevamo già avuto in passato e come allora mentre in tutti gli altri IDP funziona correttamente e si riesce ad accedere alla maschera di log-in, per intesa viene riportato il messaggio "_Impossibile stabilire l'autenticità  della richiesta di autenticazione - Contattare il gestore del servizio_"
L'url di accesso è la seguente:
[https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1TR011.sto%3FDB_NAME%3Dn201753&SOLStwToken=3184503005021063&DB_NAME=n201753
](url)
