### ISSUE TITLE
Nuovo aggiornamento metadata

### ISSUE THREAD

**Issue by CCMCED** [italia/spid#1336]
Buongiorno,
in data 02/12 abbiamo richiesto l'aggiornamento dei metadata con le modalità previste (mail a spid.tech)
Tuttora non siamo in grado di sapere se ci sono motivi o problemi in merito ed il nostro servizio non risulta abilitato all'accesso tramite SPID.
Abbiamo scritto altre 4 volte alla mail spid.tech senza risposta.
Spiacente di utilizzare questo canale ma non sappiamo come comportarci.

--- ATTENZIONE ---

I soggetti che vogliono entrare nella federazione SPID e i fornitori di servizi che intendono aggiornare l'elenco dei servizi accessibili tramite SPID **NON DEVONO utilizzare questo canale** ma scrivere a spid.tech@agid.gov.it. 

**Solo le richieste presentate entro il 19 novembre 2019 saranno gestite.**

**Comment by MibactIT** [comment]
Siete riusciti ad avere la validazione? e se si dopo quanto tempo?
Grazie 
MiBACT

**Comment by CCMCED** [comment]
Buongiorno!
Da ieri mattina, risultiamo operativi.
grazie mille
