### ISSUE TITLE
Validazione metadata SPID per aggiornamento

### ISSUE THREAD

**Issue by MibactIT** [italia/spid#1338]
Buongiorno, è dal 14 gennaio che ho richiesto la validazione del metadata SPID a seguito di aggiornamento tramite mail inviata a 'spid.tech@agid.gov.it' da dg-or.servizio1@beniculturali.it. Ad oggi non abbiamo ricevuto da AgID nessuna risposta.

E' possibile percorre un'altra strada per avere la validazione del metadata SPID del MiBACT?

**Comment by damikael** [comment]
Buongiorno,
le richieste su spid.tech vengono prese in carico in ordine di arrivo. Se non si riceve ancora una risposta, probabilmente, sono ancora in lavorazione richieste precedenti. Non appena la richiesta viene presa in carico si ha un riscontro e, se il metadata è corretto, occorrono poi 24/48 ore affinché il metadata sia dispiegato presso gli IdP. Occorre quindi solo attendere il proprio turno.
