### ISSUE TITLE
Problema accesso tramite IDP "TIM" 'Azienda Ospedaliera di Rilievo Nazionale "Antonio Cardarelli"

### ISSUE THREAD

**Issue by UmbertoUniDoc** [italia/spid#1340]
Buonasera,

si riscontra un problema di accesso tramite IDP "TIM" per l'ente in oggetto. Il contenuto della pagina visualizzata è il seguente:

**CA Access Gateway - Error Report**
**Error Details**

**Request URI**  :  /affwebservices/public/saml2sso
**Error Type** : Web server Error
**Error Code** : 403
**Message**  :  Forbidden. Server understood the request but is refusing to fulfill the request.

Si tratta, in effetti, dello stesso errore mostrato prima che il metadata venisse accreditato, si richiede pertanto il controllo della corretta comunicazione del metadata all'IDP TIM.
 **L'accesso attraverso gli altri IDP funziona correttamente.**

Di seguito i dati dell'Ente:

**Ente:** Azienda Ospedaliera di Rilievo Nazionale "Antonio Cardarelli"
**URL al quale è presente il  metadata:** https://auth.ospedalecardarelli.it/metadata
**URL al quale è presente la login:** https://cds.ospedalecardarelli.it

In attesa di un riscontro, Vi ringrazio in anticipo.

**Comment by MarcoTesta-EP** [comment]
Buongiorno Umberto,
anche io ho lo stesso problema con alcuni comuni: https://github.com/italia/spid/issues/1353
Avete risolto? Se si come?
Grazie!

**Comment by UmbertoUniDoc** [comment]
> Buongiorno Umberto,
> anche io ho lo stesso problema con alcuni comuni: #1353
> Avete risolto? Se si come?
> Grazie!

Ciao Marco,
nel nostro caso non abbiamo avuto alcuna risposta da AgID, ma l'idp TIM è risultato raggiungibile più o meno una settimana dopo l'apertura di questa issue. Chiudo questa issue in effetti (me ne ero dimenticato).

Saluti.
