### ISSUE TITLE
Richiesta di validazione metadati - Comunità Montana dei Laghi Bergamaschi

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#135]
Buongiorno,
si richiede la validazione dei metadati per conto della Comunità Montana dei Laghi Bergamaschi:
https://www.suap.cmlaghi.bg.it/simplesaml/module.php/saml/sp/metadata.php/cmlaghibg

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
