### ISSUE TITLE
Problema di accesso con idp TIM

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/spid#1353]
Buongiorno,
ho problemi di accesso con 5 comuni a cui abbiamo attivato SPID con l'Idp TIM, l'errore riportato (ancora prima della maschera di login) è:

CA Access Gateway - Error Report
Error Details

Request URI : /affwebservices/public/saml2sso
Error Type : Web server Error
Error Code : 403
Message : Forbidden. Server understood the request but is refusing to fulfill the request.

Ho visto anche altre segnalazioni nel forum per lo stesso problema, ma non ho visto risposte.
Penso che basti un refresh del metadato, ho fatto anche richiesta ad AGID ma anche da loro nessuna risposta.
Il problema è urgente considerato che dal 28.02 l'unico accesso ai siti deve esseretramite SPID o CIE.
Grazie!

Marco Testa

**Comment by MarcoTesta-EP** [comment]
@damikael vedo che sei l'unico attivo su questo progetto, puoi aiutarmi? O indirizzarmi a qualcuno che mi dia una risposta?
Grazie!

**Comment by damikael** [comment]
Buongiorno @MarcoTesta-EP ,
invia una nuova richiesta di verifica a spid.tech@agid.gov.it segnalando la problematica e la data di esito positivo del collaudo.

**Comment by MarcoTesta-EP** [comment]
Grazie @damikael, l'ho già fatto anche più volte, non ho mai ricevuto risposta...

**Comment by MarcoTesta-EP** [comment]
Buongiorno,
ho ricevuto risposta da AGID, il metadato stato rinfrescato in data 12.03, ad oggi però il problema è sempre, come possiamo risolverlo? Ho anche contattato TIM ma dopo un paio di telefonate mi hanno chiesto di mandare una mail (cosa che avevo già fatto) e non ho più saputo nulla. @damikael che possiamo fare?
Garzie!

**Comment by damikael** [comment]
@MarcoTesta-EP potresti inviare email con la lista di tutti i comuni per i quali viene riscontrato il problema.

Grazie
