### ISSUE TITLE
Ancora problemi di accesso con Ipd TIM

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/spid#1358]
Buongiorno,
continuo ad avere problemi di accesso (con svariati comuni a cui abbiamo attivato SPID) con l'Idp TIM, l'errore riportato (ancora prima della maschera di login) è:

CA Access Gateway - Error Report
Error Details

Request URI : /affwebservices/public/saml2sso
Error Type : Web server Error
Error Code : 403
Message : Forbidden. Server understood the request but is refusing to fulfill the request.

Per uno di questi (Comune di Volpiano) ho richiesto ad AGID un refresh del metadato che è stato fatto ma non è cambiato nulla. @damikael come possiamo capire e risolvere definitivamente il problema?
Grazie!

Marco Testa

**Comment by MarcoTesta-EP** [comment]
@arbiastefano può aiutarmi lei?
Grazie.

Marco Testa

**Comment by damikael** [comment]
Buongiorno @MarcoTesta-EP ,
la segnalazione ricevuta su spid.tech è stata presa in carico e il problema è in corso di verifica.

Michele D'Amico
