### ISSUE TITLE
Problemi di accesso con Ipd TIM

### ISSUE THREAD

**Issue by hegov** [italia/spid#1361]
Buongiorno,
ho dei problemi di accesso (con svariati comuni a cui abbiamo attivato SPID) con l'Idp TIM, l'errore riportato (ancora prima della maschera di login) è:

CA Access Gateway - Error Report
Error Details

Request URI : /affwebservices/public/saml2sso
Error Type : Web server Error
Error Code : 403
Message : Forbidden. Server understood the request but is refusing to fulfill the request.

Tutti gli altri Idp (Poste, ecc. funzionano regolarmente). @damikael come possiamo capire e risolvere definitivamente il problema?
Grazie!

Marco Nastasi

**Comment by damikael** [comment]
Buongiorno @hegov ,
probabilmente è un problema di allineamento del metadata, 
suggerisco di segnalare il problema a spid.tech@agid.gov.it facendo presente che presso gli altri IdP l'autenticazione funziona e chiedendo la rinotifica del metadata a TIM.

Saluti.
Michele D'Amico
