### ISSUE TITLE
Certificato self signed in ambiente di test

### ISSUE THREAD

**Issue by Antonyclar** [italia/spid#1375]
Avrei necessità di integrare spid in un sistema della mia azienda privata.
Non conoscendo nulla a riguardo, al momento, sto utilizzando il progetto di test disponibile su [https://github.com/italia/spid-dotnet-sdk](url) e seguendo la relativa procedura.

Al momento ho creato un certificato self signed e il relativo file metadata.xml (vedi allegato).
Una volta spedito e convalidato il metadata cosa dovrei fare per poter rendere funzionante quel progetto? Non ho capito in che modo il metadata verrebbe sfruttato da quell'applicazione e dove dovrei inserirlo per renderlo funzionante.
Inoltre nel metadata di esempio nel progetto non c'è il tag <Signature>, funzionerebbe ugualmente?

[TPCWare Metadata2.txt](https://github.com/italia/spid/files/6809865/TPCWare.Metadata2.txt)

**Comment by damikael** [comment]
Ciao @Antonyclar ,

ti consiglio di approfondire il protocollo di autenticazione SAML2 sul quale è basato SPID e leggere quanto previsto dalla [procedura di adesione](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid) descritta sul sito spid.gov.it.
Riguardo a dubbi o necessità di chiarimento sulle configurazioni e sul funzionamento del service provider implementato con spid-dotnet-sdk puoi chiedere sul relativo repository.
Ti consiglio inoltre di unirti al canale slack spid per ulteriore supporto da parte della community.
