### ISSUE TITLE
Richiesta validazione e caricamento metadata Regione Piemonte

### ISSUE THREAD

**Issue by alfonsinaarena** [italia/spid#138]
Buongiorno,
si richiede la verifica e la validazione del metatdata di Regione Piemonte per l'integrazione con SPID.

Il metadata è pubblicato al seguente indirizzo:
https://www.spid.piemonte.it/spid/prod/metadata/metadata_service_provider_regionepiemonte_spid.xml

Il file metadata è pubblicato sul sito https://www.spid.piemonte.it, gestito dal CSI Piemonte, essendo il CSI Piemonte intermediario tecnologico come indicato nella convenzione SPID di Regione Piemonte.

Grazie e buona giornata,
Alfonsina

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
