### ISSUE TITLE
Validazione Metadata Comune di Quinto di Treviso

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#141]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Quinto di Treviso.
https://www.comune.quintoditreviso.tv.it/c026064/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
