### ISSUE TITLE
Validazione Metadata Comune di San Zenone degli Ezzelini

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#144]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di San Zenone degli Ezzelini.
https://www.comune.san-zenone.tv.it/c026077/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
