### ISSUE TITLE
Validazione Metadata Comune di Mira

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#146]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Mira.
https://servizionline.comune.mira.ve.it/c027023/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
