### ISSUE TITLE
Validazione Metadata Comune di Giavera del Montello

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#147]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Giavera del Montello.
https://www.comune.giavera.tv.it/c026032/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
