### ISSUE TITLE
Controllo metadata Comune di Ferrara

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#154]
Buongiorno,
Per conto del Comune di Ferrara, abbiamo predisposto i metadata e pubblicati nella cartella
https://ferarra.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_ferrara-signed.zip](https://github.com/italia/spid/files/1860522/metadata_ferrara-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
La url risulta irraggiungibile.

**Comment by sfacondini** [comment]
Buongiorno,
un errore di digitazione   ferarra vs ferrara  i metadata sono corretti 
l'url esatto è 

https://ferrara.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
