### ISSUE TITLE
Richiesta verifica tecnica e convenzione per Provincia di Cremona / RUP

### ISSUE THREAD

**Issue by giannibassiniprovincia** [italia/spid#155]
La Provincia di Cremona richiede ad AgID 

la verifica tecnica sull'implementazione di SPID per la Provincia di Cremona Rete Unitaria Provinciale ai seguenti URL
https://www.rup.cr.it/
https://www.rup.cr.it/login.do#GEL
la ricezione della convenzione  ed
il file in formato Ods per la compilazione dei servizi attivi

i metadata della provincia sono stati pubblicati e correttamente caricati dagli IdP.
Il servizio è stato configurato e verificato internamente con successo.

Grazie
Cordiali Saluti
Gianni Bassini

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone procedere all'invio della convenzione

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by giannibassiniprovincia** [comment]
in che modo verrà inviata la convenzione?
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Si prega di inviare una mail all'indirizzo spid.tech@agid.gov.it con l'indicazione di un'indirizzo mail per la ricezione del modello di Convenzione.

**Comment by AntonioGiovanniSchiavone** [comment]
Convenzione inviata agli indirizzi indicati.

**Comment by giannibassiniprovincia** [comment]
Grazie 
Abbiamo ricevuto 


Gianni Bassini 
Ced - Provincia di Cremona 


Da: "Antonio Giovanni Schiavone" <notifications@github.com> 
A: "italia/spid" <spid@noreply.github.com> 
Cc: "Gianni Bassini" <gianni.bassini@provincia.cremona.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 17 aprile 2018 12:14:11 
Oggetto: Re: [italia/spid] Richiesta verifica tecnica e convenzione per Provincia di Cremona / RUP (#155) 



Convenzione inviata agli indirizzi indicati.

**Comment by AntonioGiovanniSchiavone** [comment]
Procedura Amministrativa conclusa
