### ISSUE TITLE
Validazione Metadata Comune di Pescantina

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#157]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Pescantina.
https://www.comune.pescantina.vr.it/c023058/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
