### ISSUE TITLE
Comunicazione URL metadata per Istituto Comprensivo "R. Franceschi" di Trezzano sul Naviglio

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid#16]
Comunicazione da Istituto Comprensivo "R. Franceschi" di Trezzano sul Naviglio

Chiedo il controllo del metadata posto all’URL
https://www.icfranceschi.gov.it/microspid_metadata

Denominazione Istituto: I.C. “R. Franceschi” di Trezzano sul Naviglio

**Comment by pagolo** [comment]
Abbiamo corretto un errore e verificato con XmlSecTool, vi preghiamo di riprovare.
Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e verrà caricanto entro le ore 15.
