### ISSUE TITLE
Validazione Metadata Comune di Sorgà

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#162]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sorgà.
https://servizionline.comune.sorga.vr.it/c023084/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

Facciamo presente che nell'elemento OrganizationName il nome del comune è troncato, cosa che si ripercuote sul nome visualizzato nella maschera di login presentata dagli Identity Provider.
