### ISSUE TITLE
Errore Regione Piemonte - IdP Namirial

### ISSUE THREAD

**Issue by alfonsinaarena** [italia/spid#163]
Buongiorno,
abbiamo riscontrato che l'integrazione tra Regione Piemonte e IdP Namirial non è andato a buon fine, come da immagine allegata.

Ipotizziamo che l'IdP indicato non abbia caricato il metadata aggiornato in data 28.03.18 ma che faccia riferimento ancora al prima metadata di Regione Piemonte (del 2016).

Potete verificare?

Grazie mille,
Alfonsina
![regione piemonte - idp namirial](https://user-images.githubusercontent.com/37371770/38140329-d21004c4-3422-11e8-83f6-0d0eaca81798.png)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 

potreste comunicarci la url del servizio in questione?
