### ISSUE TITLE
errore Regione Puglia IDP Infocert, Aruba e Intesa

### ISSUE THREAD

**Issue by marangiom** [italia/spid#165]
Salve
si richiede di verificare il motivo per cui i gestori SPID in oggetto rifiutano le richieste di login dai servizi deployati nell'ultimo metadato della Regione Puglia.
grazie
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 

potebbe fornirci la url del servizio in questione?

**Comment by marangiom** [comment]
l'ultimo è 
http://www.sistema.puglia.it/SistemaPuglia/testspid
grazie
Salluti

**Comment by marangiom** [comment]
salve
dobbiamo mettere online altri servizi e pubblicare una nuova versione dei metadati, ma sto temporeggiando per non sovrapporre le richieste ed avere altri problemi; posso procedere comunque?
Saluti
M

**Comment by marangiom** [comment]
Buongiorno
persistono le anomalie segnalate da oltre un mese.
in particolare (la x significa malfunzionamento):

 url del servizio | aruba | infocert | intesa | namirial | poste | sielte | spiditalia | tim
-- | -- | -- | -- | -- | -- | -- | -- | --
https://giava.sanita.puglia.it |   |   | x |   |   |   |   |  
https://spid.sit.puglia.it |   | x | x | x |   | x |   |  
https://www.dms.puglia.it |   |   | x |   |   |   |   |  
http://www.empulia.it/tno-a/empulia/SitePages/Home.aspx | x | x | x | x |   | x |   |  

E' possibile, in via eccezionale, contattare direttamente i gestori?

Grazie
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Le AuthnRequest per i servizi "SIT Puglia" e "Empulia" violano quanto indicato a pag.8 delle Regole Tecniche [SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf), laddove si indica deve essere indicato l’attributo ForceAuthn valorizzato a true nel caso in cui si richieda livelli di autenticazione superiori a SPID L1.

Per gli altri servizi stiamo svolgendo delle verifiche in collaborazione con gli Identity Provide coinvolti.
