### ISSUE TITLE
Comune di Borgomanero - problema con IdP Intesa

### ISSUE THREAD

**Issue by falbesano** [italia/spid#166]
Buongiorno,
segnalo che l'autenticazione con l'entityID relativo al Comune di Borgomanero effettuata tramite l'IdP Intesa produce questo risultato:

![immagine](https://user-images.githubusercontent.com/7596471/38295242-a9579b68-37ed-11e8-867d-0c950aa401a6.png)

I metadata erano stati correttamente caricati  (#114) e tutti gli altri IdP funzionano correttamente.
Inoltre segnalo che la stessa implementazione di SPID funziona correttamente con l'IdP Intesa per diversi altri entityID.

URL servizio:
https://www.pa-online.it/GisMasterWebS/SU/SU.aspx?IdCliente=003024&IdSU=Sue

Grazie e cordiali saluti
Federico Albesano

**Comment by umbros** [comment]
Segnalto ad Intesa

**Comment by falbesano** [comment]
Ciao @umbros, qualche novità da Intesa ? Il problema persiste...
Grazie e buona giornata
Federico

**Comment by AntonioGiovanniSchiavone** [comment]
Il problema ora risulta risolto.
