### ISSUE TITLE
Richiesta verifica metadati Comune di Castelcucco

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#167]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Castelcucco.
https://www.comune.castelcucco.tv.it/c026011/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
