### ISSUE TITLE
Richiesta verifica metadati Comune di Borso del Grappa

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#168]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Borso del Grappa.
https://www.comune.borsodelgrappa.tv.it/c026004/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
