### ISSUE TITLE
Comunicazione metadata per Istituto: IIS Torriani - Cremona

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid#17]
Si richiede  il controllo del metadata posto all’URL

https://www.janellotorriani.it/didattica/microspid_metadata

Denominazione Istituto: IIS Torriani - Cremona

**Comment by pagolo** [comment]
Abbiamo aggiornato il software. Vi preghiamo di riprovare.
Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP.
