### ISSUE TITLE
Richiesta verifica metadati Comune di Crespano del Grappa

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#170]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Crespano del Grappa.
https://www.comune.crespano.tv.it/c026024/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
