### ISSUE TITLE
Richiesta verifica metadati Comune di Paderno del Grappa

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#171]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Paderno del Grappa.
https://www.comune.paderno.tv.it/c026054/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
