### ISSUE TITLE
Controllo metadata - Comune di Bernezzo

### ISSUE THREAD

**Issue by falbesano** [italia/spid#174]
Buongiorno,
per conto del Comune di Bernezzo, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.bernezzo.cn.it/004022/SPID/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
