### ISSUE TITLE
Controllo metadati comune di Agrate Brianza

### ISSUE THREAD

**Issue by briviopc** [italia/spid#175]
Buongiorno, 
si richiede la varifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro 
cordiali saluti
ufficio ced

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Sembra che le url delle location siano malformate.

**Comment by briviopc** [comment]
Buongiorno,
in effetti la società che ci segue per la gestione dello SPID mi ha segnalato un errore dell’applicativodi generazione del file.
Sono in attesa della correzione e appena sarà fatta Vi rigiro il file metadati creato.
Scusate ancora per il disguido.
Cordiali saluti

**Comment by briviopc** [comment]
Buonasera,
l'errore dell'applicativo di generazione del file sembra sia stato corretto.
pertanto si richiede la verifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro
cordiali saluti
ufficio ced

**Comment by AntonioGiovanniSchiavone** [comment]
Se presente l'elemento Organization, tutti i suoi sotto elementi devono essere presenti ed adeguatamente valorizzati. Nel metadata proposto l'elemento OrganizationURL non è valorizzato (pag. 20 Regolamento recante le norme tecniche SPID).

**Comment by briviopc** [comment]
buonasera
avviso subito
grazie

**Comment by briviopc** [comment]
buongiorno,
abbiamo sistemati il metadata secondo le VS richieste.
pertanto si richiede la verifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro
cordiali saluti
ufficio ced

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
