### ISSUE TITLE
Controllo metadati - Piattaforma Dimostrativa Datanet srl

### ISSUE THREAD

**Issue by datanetsrl** [italia/spid#177]
Salve,
vorremmo eseguire dei test di login attraverso spid su una piattaforma dimostrativa alle pubbliche amministrazioni.

Abbiamo effettuato l'installazione su piattaforma Wordpress utilizzando l'apposito plugin rilasciato da Marco Milesi.

Di seguito si trasmette link dei metadati ottenuti per la piattaforma dimostrativa (https://agid.datanetsrl.eu):

https://agid.datanetsrl.eu/wp-content/plugins/wp-spid-italia/lib/www/module.php/saml/sp/metadata.php/default-sp

In attesa di riscontro, porgo distinti saluti
Dimitri De Porzio

**Comment by damikael** [comment]
Salve, 
per effettuare i test di integrazione è possibile utilizzare l'ambiente di test Spid TestEnv (https://github.com/italia/spid-testenv) disponibile tramite docker (https://github.com/italia/spid-testenv-docker) per l'installazione in locale, oppure online all'indirizzo https://idp.spid.gov.it .

L'ambiente si compone di due elementi:

- l'Identity Server vero e proprio, basato su WSO2-is;
- un backoffice web che offre un'interfaccia semplificata per la configurazione del Service Provider sull'IS e la creazione delle identità.

Per l'installazione tramite docker fare riferimento alle indicazioni riportate in https://github.com/italia/spid-testenv-docker

Per utilizzare la versione online, invece, occorre registrare il proprio SP tramite l'interfaccia di backoffice disponibile all'indirizzo https://idp.spid.gov.it:8080 e configurare sul proprio SP i dati dell'IDP scaricabili tramite relativo metadata da https://idp.spid.gov.it:8080/#/infoidp
