### ISSUE TITLE
Richiesta verifica metadati Comune di Sovizzo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#178]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sovizzo.
https://www.comune.sovizzo.vi.it/c024103/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
