### ISSUE TITLE
Controllo metadata - Comune di Vicoforte

### ISSUE THREAD

**Issue by falbesano** [italia/spid#179]
Buongiorno,
per conto del Comune di Vicoforte, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.vicoforte.cn.it/004242/SPID/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
