### ISSUE TITLE
Supporto metadata

### ISSUE THREAD

**Issue by fsofia** [italia/spid#18]
Da Agenzia per le Erogazioni in Agricoltura - AGEA
Metadata

Buongiorno,
abbiamo la necessità di sostituire il certificato che firma le AuthRequest del nostro Sistema Informativo -SIAN- che avrà impatto sulla federazione con gli IdP per l’accesso tramite SPID. A seguito della modifica dovremmo generare un nuovo metadata SAML che dovrà essere installato sui vari IdP. 
Poiché l’attività potrebbe comportare un temporaneo disservizio in fase di accesso, vorremmo sapere se è possibile creare un metadata contenente sia il nuovo che il vecchio certificato di firma. Qualora non fosse possibile vi chiediamo la disponibilità a pianificare l’attività di sostituzione insieme in modo da limitare al minimo il disservizio.
Cordiali saluti.

**Comment by umbros** [comment]
Ciao,
confermo la possibilità, sul metadata è possibile specificare più certificati di signing

` <md:KeyDescriptor use="signing">
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>xxxxxxxxxxxxx</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>`

Ovviamente nel rifirmare il metadata utilizzare un certificato aggiornato.
