### ISSUE TITLE
Richiesta verifica metadati Comune di Reana del Rojale

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#180]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Reana del Rojale.
https://www.comune.reanadelrojale.ud.it/c030090/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
