### ISSUE TITLE
Richiesta verifica metadati Comune di Povegliano Veronese

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#181]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Povegliano Veronese.
https://www.comune.poveglianoveronese.vr.it/c023060/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
