### ISSUE TITLE
Richiesta verifica metadati Comune di Badia Polesine  

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#182]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Badia Polesine.
https://www.comune.badiapolesine.ro.it/c029004/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
