### ISSUE TITLE
Richiesta verifica metadati Comune di Saonara

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#183]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Saonara.
https://www.comune.saonara.pd.it/c028085/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
