### ISSUE TITLE
Richiesta verifica metadati Comune di Massanzago

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#184]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Massanzago.
https://www.comune.massanzago.pd.it/c028050/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
