### ISSUE TITLE
Richiesta verifica metadati Comune di Noale

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#186]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Noale.
https://www.comune.noale.ve.it/c027026/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
