### ISSUE TITLE
Richiesta verifica metadati Comune di Paese

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#187]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Paese.
https://www.comune.paese.tv.it/c026055/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
