### ISSUE TITLE
Richiesta di validazione e deploy dei metadati

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#188]
Buongiorno,
Si richiede la verifica e il deploy dei metadati seguenti e  per conto del Comune di Torre d'Isola:
https://sportellotelematico.comune.torredisola.pv.it/simplesaml/module.php/saml/sp/metadata.php/torredisola
Si tratta di uno Sportello conforme a quelli già precedentemente validati da Globo.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
