### ISSUE TITLE
Controllo metadata Comune di Dolo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#19]
Buongiorno,
Per conto del Comune di Dolo, abbiamo predisposto i metadata e pubblicati sulla cartella

https://dolo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_dolo-signed.zip](https://github.com/italia/spid/files/1775542/metadata_dolo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e verrà caricanto entro le ore 15.
