### ISSUE TITLE
Controllo metadata ARPA CAMPANIA 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#191]
Buongiorno,
Per conto di ARPA Campania, abbiamo predisposto i metadata e pubblicati nella cartella
https://arpac.servizi-pa-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_arpacampania-signed.zip](https://github.com/italia/spid/files/1893165/metadata_arpacampania-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato distribuito agli IdP e da essi caricato.
