### ISSUE TITLE
Controllo metadata Comune di Ponsacco 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#192]
Buongiorno,
Per conto del comune di Ponsacco, abbiamo predisposto i metadata e pubblicati nella cartella
https://ponsacco.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_ponsacco-signed.zip](https://github.com/italia/spid/files/1893235/metadata_ponsacco-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
