### ISSUE TITLE
Richiesta verifica metadati Comune di Castelnuovo del Garda

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#193]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Castelnuovo del Garda.
https://www.comune.castelnuovodelgarda.vr.it/c023022/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
