### ISSUE TITLE
Richiesta verifica metadati Comune di Grumolo delle Abbadesse

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#194]
Buongiorno,
Si richiede la verifica dei metadati per conto del Grumolo delle Abbadesse.
https://www.comune.grumolodelleabbadesse.vi.it/c024047/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
