### ISSUE TITLE
Richiesta verifica metadati Comune di Meolo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#195]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Meolo.
https://www.comune.meolo.ve.it/c027022/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
