### ISSUE TITLE
Comunicazione metadata per San Pancrazio Salentino

### ISSUE THREAD

**Issue by francesco326** [italia/spid#199]
Buongiorno,
si richiede la validazione dei metadati per conto del comune di San Pancrazio Salentino:
https://istanzesps.parsec326.it

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il metadata proposto è privo di firma (elemento Signature). La firma deve essere prodotta secondo quanto indicato a pag. 19 del Regolemento recante le norme tecniche SPID ( http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf ).  Sull'account github dell'iniziativa Developers Italia è stato pubblicato un tool per la firma dei metadata per i sistemi operativi Linux e OSX : https://github.com/italia/spid-metadata-signer. Vi segnaliamo inoltre che alcuni Service Provider hanno utilizzato con successo un porting del citato tool per la piattaforma Windows sviluppato da terzi: https://github.com/ermannog/SPID-Metadata-Signer-Windows

Ricordiamo inoltre come  l'Avviso SPID n°6 ( http://www.agid.gov.it/agenda-digitale/infrastrutture-architetture/spid/avvisi ) suggerisca di impostare il valore dell'entityID uguale al nome di dominio registrato dalla P.A. od un suo sottodominio.

**Comment by gianluca326** [comment]
Salve, ormai è da più di 40 giorni che abbiamo provveduto ad aggiornare il metadata secondo le vs indicazioni, ma ancora non abbiamo ottenuto nessuna risposta. 
Vorremmo avere dei feedback.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by gianluca326** [comment]
Buongiorno
abbiamo precedentemente fatto effettuare la verifica del metadato con esito positivo (metadata issue #199), vi chiediamo gentilmente di verificare l'implementazione dello spid all'indirizzo https://istanzesps.parsec326.it per poter procedere alla firma della convenzione con il Comune di San Pancrazio Salentino.
Ho scritto già due email all'indirizzo spid.tech@agid.gov.it ma non ho ricevuto nessuna risposta.
Grazie
Gianluca Monte
