### ISSUE TITLE
Richiesta spid 2018

### ISSUE THREAD

**Issue by AnnaBris** [italia/spid#2]
Scrivo per conto di mia madre insegnante scuola primaria che deve creare spid per accedere al bonus dei 500 euro. L'anno scorso ha fatto richiesta tramite Poste Italiane e tutto è andato a buon fine. Quest'anno come deve procedere? Purtroppo ha perso i codici identificativi e non ha conservato le mail che li contenevano. Come procediamo?

**Comment by umbros** [comment]
Buonasera @AnnaBris, questo sistema di supporto è dedicato a soggetti che erogano servizi sia che la loro natura sia pubblica (Pubbliche Amministrazioni), sia privata (Aziende che utilizzano SPID come loro metodo di autenticazione). Per avere la risposta al tuo quesito ti invito a contattare gli helpdesk menzionati sulla pagina "Serve aiuto" del sito SPID [https://www.spid.gov.it/serve-aiuto](https://www.spid.gov.it/serve-aiuto).

Umberto Rosini
Agenzia per l'Italia Digitale
