### ISSUE TITLE
Aggiornamento Metadata Regione Marche

### ISSUE THREAD

**Issue by RegioneMarcheCirillo** [italia/spid#200]
Il metadata di Regione Marche è cambiato poiché il certificato con cui Regione Marche firmava le request SAML era in scadenza, ed è stato sostituito con un nuovo certificato emesso dalla stessa CA.
E’ disponibile allo stesso URL già comunicato in fase di avvio dei servizi SPID:

https://cohesion2.regione.marche.it/spmanager/cohesion-sp-metadata.aspx

L’unica modifica fatta rispetto alla precedente versione è la sostituzione del certificato negli elementi KeyInfo.
Cordiali saluti

Ing. Francesco Cirillo
Ragiona Marche - Giunta Regionale
P.F. Informatica e Crescita digitale
071 806.3857

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
