### ISSUE TITLE
Validazione metadata Comune di Matera

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#203]
Buongiorno,
abbiamo inviato l'url del metadata a spid.tech@agid.gov.it per l'attivazione SPID presso il Comune di Matera.
Chiediamo, gentilmente, la validazione del metadata e deploy presso gli IdP.
Grazie

Servizi Locali S.p.A.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato distribuito agli IdP e da essi caricato.
