### ISSUE TITLE
Problema di accesso Spid tramite Idp INTESA per il comune di Cigliano

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#206]
Buon pomeriggio, 
per il comune di Cigliano fino a circa una settimana fa il collegamento con i vari Idp funzionava correttamente con tutti, mentre ad oggi riscontriamo un problema solo con l'Idp di Intesa.
Il messaggio che compare è il seguente: "Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio".
Chiediamo, gentilmente, un riscontro ed eventuali indicazioni.

Grazie

**Comment by Eduardo1977** [comment]
Buongiorno, qualche novità da Intesa ? Il problema persiste...
Grazie e buona giornata

**Comment by AntonioGiovanniSchiavone** [comment]
Il problema ora risulta risolto.
