### ISSUE TITLE
Validazione Metadata Comunità Montana di Scalve (BG)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#209]
Buongiorno,
Si richiede la verifica dei metadati per conto dell'ente Comunità Montana di Scalve (BG).
https://servizi.cmscalve.bg.it/cmscalve/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
L'hash della firma sul metadata non combacia con il contenuto. Sull'account github dell'iniziativa Developers Italia è stato pubblicato un tool per la firma dei metadata per i sistemi operativi Linux e OSX : https://github.com/italia/spid-metadata-signer. Vi segnaliamo inoltre che alcuni Service Provider hanno utilizzato con successo un porting del citato tool per la piattaforma Windows sviluppato da terzi: https://github.com/ermannog/SPID-Metadata-Signer-Windows

Si prega di rifirmare il metadata e di comunicarne la disponibilità all'endpoint segnalato di quello corretto.

**Comment by HalleyInformatica** [comment]
Buongiorno, di seguito il link del nuovo metadata firmato con il tool da voi indicato 
https://servizi.cmscalve.bg.it/cmscalve/spid-metadata.xml 
Attendiamo vostro riscontro.
Saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il metadata inviato non è compliant alle regole tecniche SPID;
gli errori riscontrati sono:
1) L'elemento EntityDescriptor deve avere un attributo ID, avente valore di tipo NCName ( https://www.w3.org/TR/xmlschema-2/#NCName ).
 
Si prega di rifirmare il metadata e di comunicarne la disponibilità  di quello corretto.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
