### ISSUE TITLE
Controllo metadada Comune Pontecagnano Faiano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#21]
Buongiorno,
Per conto del Comune di Pontecagnano - Faiano , abbiamo predisposto i metadata e pubblicati sulla cartella
https://pontecagnanofaiano.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_pontecagnanofaiano-signed.zip](https://github.com/italia/spid/files/1775559/metadata_pontecagnanofaiano-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e verrà caricanto entro le ore 15.
