### ISSUE TITLE
Richiesta verifica metadati Comune di Battaglia Terme

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#211]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Battaglia Terme.
https://www.comune.battaglia-terme.pd.it/c028011/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
