### ISSUE TITLE
Nuovi metadati Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#213]
Salve
si richiede il deploy presso i gestori SPID dei nuovi metadati della Regione Puglia disponibili al link [https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml)
grazie
Marcello Marangio
Innova Puglia S.p.A.

**Comment by marangiom** [comment]
Salve
ho ricevuto il giorno 16 una mail da SPIDTech in cui ci viene comunicato che non è possibile verificare che un servizio sia in https perché la url è irraggiungibile; ho risposto che quella URL, come altre già pubblicate, sono su rete RUPAR protetta, quindi non sono raggiungibili dall'esterno.
Vorrei capire se i metadati non sono stati ancora presi in carico e pubblicati per questo motivo o se ci sono altri problemi e come possiamo fare per sbloccare la situazione.
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
