### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di San Vito Romano

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#214]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di San Vito Romano:
http://static.sanvitoromano.rm.gov.it/uploads/n200438.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

abbiamo rilevato un problema sul protocollo https associato al dominio http://static.sanvitoromano.rm.gov.it  ( Certificate Name Mismatch ).

Si prega di risolvere il problema e notificarne la risoluzione.

**Comment by wecomsrl** [comment]
Buonasera, 
il Comune di San Vito Romano, attualmente, non supporta il protocollo https. L'acquisto di un certificato valido per il dominio comunale potrà avvenire solo dopo la dismissione del dominio **.gov** che da direttiva AgID dovrà essere abbandonato. 
Come si può risolvere?

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by filippoermini-padigitale** [comment]
Buongiorno, stiamo riscontrando dei problemi con l'Idp di Sielte potete provare a far ricaricare il metadato, a fronte di una authnrequest risponde con errore 500 come se non accettasse la richiesta, non si accede neanche alla pagina del log in. Per tutti gli altri idp non ci sono problemi.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato reinoltrato verso gli IdP e da essi caricato.
Qualora il problema peristesse si prega di fornire la url del servizio in questione.
