### ISSUE TITLE
Richiesta validazione dei metadati - Comune di Sesto Calende

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#215]
Buongiorno,
si richiede la validazione dei metadati per conto del comune: 
https://sportellotelematico.comune.sesto-calende.va.it/simplesaml/module.php/saml/sp/metadata.php/sestocalende

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
