### ISSUE TITLE
Richiesta verifica metadati Comune di San Fior

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#216]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di San Fior.
https://www.comune.san-fior.tv.it/c026072/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
