### ISSUE TITLE
Richiesta validazione dei metadati - Comune di Cologno Al Serio

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#217]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.colognoalserio.bg.it/simplesaml/module.php/saml/sp/metadata.php/colognoalserio

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
