### ISSUE TITLE
Richiesta verifica metadati Comune di Fagagna

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#218]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Fagagna.
https://www.comune.fagagna.ud.it/c030106/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
