### ISSUE TITLE
Richiesta validazione dei metadati - Comune di Dalmine

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#219]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.dalmine.bg.it/simplesaml/module.php/saml/sp/metadata.php/dalmine

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
