### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Arzana

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#22]
Buongiorno,
abbiamo condotto i test interni per il Comune di Arzana con esito positivo
i servizi soggetti ad autenticazione sono erogati  dal portale:

https://arzana.comune-online.it

cordiali saluti
Facondini Stefano

**Comment by umbros** [comment]
@sfacondini implementazione verificata con successo.
@AntonioGiovanniSchiavone puoi procedere all'invio della convenzione.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione ed il  file di descrizione dei servizi per la P.A. in questione.
