### ISSUE TITLE
Verifica e validazione metadata della Comunità Montana di Valle Camonica

### ISSUE THREAD

**Issue by dfranzoni** [italia/spid#224]
Buongiorno,
si richiede la verifica e la validazione del metadata della Comunità Montana di Valle Camonica per l'integrazione con SPID.

Il metadata è pubblicato al seguente indirizzo:
https://idpcgel.crs.lombardia.it/gelmetadata/373899

Grazie mille e buona giornata

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per la P.A. in oggetto ( recuperabile all'indirizzo https://www.sportellotelematico.cmvallecamonica.bs.it/simplesaml/module.php/saml/sp/metadata.php/cmvallecamonica ).

Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).

Staff Tecnico SPID
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

la url di pubblicazione del metadata è un elemento modificabile, Quindi è possibile chiedere un aggiornamento del metadata indicando una url diversa da quella precedentemente comunicata. Quello che deve necessariamente rimanere costante è il valore dell' identificativo unico (EntityID).

**Comment by dfranzoni** [comment]
Buongiorno Sig. Giovanni Schiavone,
abbiamo notato il primo attivatore del servizio SPID per interfacciarlo con il suo specifico servizio ha dichiarato come EntityID un url del suo stesso servizio.
In questo dopo se dovesse capitare di cambiare il servizio il metadata non sarebbe più disponibile.
Come si può fare per avere un EntityID su un url istituzionale dell’ente e non collegato al servizio?

Grazie mille per la cordialità e disponibilità.

Davide Franzoni

Da: Antonio Giovanni Schiavone <notifications@github.com>
Inviato: mercoledì 18 aprile 2018 16:04
A: italia/spid <spid@noreply.github.com>
Cc: Davide Franzoni <dfranzoni@coopcsc.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/spid] Verifica e validazione metadata della Comunità Montana di Valle Camonica (#224)


Buongiorno,

la url di pubblicazione del metadata è un elemento modificabile, Quindi è possibile chiedere un aggiornamento del metadata indicando una url diversa da quella precedentemente comunicata. Quello che deve necessariamente rimanere costante è il valore dell' identificativo unico (EntityID).

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Come indicato a pag. 19 del [Regolamento recante le norme tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf):

entityID: indicante l’identificativo univoco (un URI) dell’entità

Quindi, l'entityId costituisce una chiave che rappresenta univocamente l'entità (ossia, nel caso specifico, la P.A.) all'interno dell'ecosistema SPID. Essa non ha nessuna relazione funzionale con un determinato servizio: al contrario, nell'[avviso SPID n° 6](http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf ) si consiglia, ma non si obbliga,  "di usare il nome di dominio registrato dall’ente od un suo sottodominio" , a cui non è detto che corrisponda un servizio.

Quindi, anche qualora un determinato servizio venisse dismesso o la sua url modificata, la citazione della sua url originale come entityID non avrebbe effetti sugli altri servizi espressi tramite lo stesso metadata.
