### ISSUE TITLE
Richiesta verifica metadati Comune di Cerea

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#227]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Cerea.
https://www.cerea.net/c023025/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per la P.A. in oggetto ( recuperabile all'indirizzo https://wifi.comune.cerea.vr.it/auth/module.php/saml/sp/metadata.php/comunecerea-sp ).

Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).
