### ISSUE TITLE
Richiesta verifica metadati Comune di Sesto al Reghena

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#228]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sesto al Reghena.
https://www.comune.sesto-al-reghena.pn.it/c093043/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
