### ISSUE TITLE
Richiesta verifica metadati Comune di San Pietro in Cariano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#229]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di San Pietro in Cariano.
https://www.comune.sanpietroincariano.vr.it/c023076/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
