### ISSUE TITLE
Indisponibilità Server di test SPID

### ISSUE THREAD

**Issue by more-mau** [italia/spid#234]
Buongiorno,
vorrei effettuare dei test SPID ma il server da ieri non risponde piu sia sulla porta 8080 che sulla 9443:

- https://idp.spid.gov.it:8080
- https://idp.spid.gov.it:9443

Potete darmi informazioni a riguardo?
Colgo l'occasione per chiedervi anche un'altra cosa:
Ho potuto effettuare solo 2 test prima che il server andasse off-line ma comunque ho notato che riuscivo ad effettuare il login correttamente solo che la pagina restituita non mi stampava nessun attributo dell'utente loggato. Forse dipende dall'utente con cui tento l'autenticazione? Io tentavo con uno dei vostri utenti generali messi a disposizione.

Grazie per la collaborazione,
Saluti.

**Comment by damikael** [comment]
Buongiorno,
il server è ora nuovamente online.

Nella richiesta SAML deve essere presente l'attributo AttributeConsumingServiceIndex valorizzato con l'indice del set di attributi richiesto e specificato nel metadata. In questo caso `AttributeConsumingServiceIndex="1"`.
Inoltre il valore per AuthnContextClassRef deve essere conforme ad una delle classi indicate nell'avviso n.5 (Rif. http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n5-regole-tecniche-errata-corrige.pdf)
Ad esempio, per il primo livello:
`<saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef>`

Saluti,
Michele
