### ISSUE TITLE
Richiesta verifica metadati Comune di Possagno

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#235]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Possagno.
https://www.comune.possagno.tv.it/c026061/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
