### ISSUE TITLE
Problema di accesso tramite Infocert per il comune di Agrate Brianza

### ISSUE THREAD

**Issue by filippoermini-padigitale** [italia/spid#236]
Attraverso la maschera di accesso tramite l'idp di infocert dopo aver inserito correttamente username e password non si accede alla maschera di inserimento del codice OTP, viene generato il messaggio: "Si è verificato un errore
Sembra che il browser abbia i cookie disabilitati: si prega di abilitarli prima di riprovare". 
Ovviamente i cookies sono abilitati e questa cosa accade su tutti i browser in più se si prova ad accedere da un sito diverso tramite spid il sistema funziona correttamente.
Con tutti gli altri idp l'accesso va a buon fine.

**Comment by AntonioGiovanniSchiavone** [comment]
Verificate se con l'ultimo caricamento dei metadata il problema si è risolto. Qualora persistesse è necessario esposrre e comunicarci laurl della pagine dove è presente lo SPID button.

**Comment by filippoermini-padigitale** [comment]
Siamo in contatto con i tecnici di infocert per risolvere il problema.
