### ISSUE TITLE
Richiesta verifica metadati Comune di Camponogara

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#237]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Camponogara.
https://www.comune.camponogara.ve.it/c027004/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
