### ISSUE TITLE
Richiesta verifica dei metadati - Comune di Roccamonfina

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#239]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.roccamonfina.ce.it/simplesaml/module.php/saml/sp/metadata.php/roccamonfina

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
