### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Cabras

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#24]
Buongiorno,
abbiamo condotto i test interni per il Comune di Cabras con esito positivo con tutti gli IDP
i servizi soggetti ad autenticazione sono erogati dal portale:

https://cabras.comune-online.it

cordiali saluti
Facondini Stefano

**Comment by umbros** [comment]
@sfacondini implementazione verificata con successo.
@AntonioGiovanniSchiavone puoi procedere all'invio della convenzione.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.
