### ISSUE TITLE
Richiesta verifica metadati Comune di Selvazzano Dentro.

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#240]
Buongiorno,
Si richiede la verifica dei metadati per conto del Selvazzano Dentro.
https://www.comune.selvazzano-dentro.pd.it/c028086/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
