### ISSUE TITLE
Richiesta verifica metadati Comune di Lazise

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#241]
Buongiorno,
Si richiede la verifica dei metadati per conto del Lazise.
https://www.comune.lazise.vr.it/c023043/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
