### ISSUE TITLE
Richiesta verifica metadati Comune di Legnaro

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#242]
Buongiorno,
Si richiede la verifica dei metadati per conto del Legnaro.
https://servizionline.comune.legnaro.pd.it/c028044/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
