### ISSUE TITLE
Richiesta verifica metadati Comune di Novara

### ISSUE THREAD

**Issue by fabio-scudieri** [italia/spid#243]
Buongiorno,
si richiede verifica metadati 
https://www.comune.novara.it/script/spid/spid-metadata-novara-v4-signed.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by fabio-scudieri** [comment]
Grazie.
Sto provando la comunicazione con poste italiane, è normale che restituisca il fiscalNumber preceduto da TINIT-?
fiscalNumber: TINIT-XXXXXXXXXXXXXXXX
