### ISSUE TITLE
Richiesta validazione servizio Comune di Matera

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#245]
Buongiorno,
vorremmo chiedere la verifica tecnica per il Comune di Matera.
Inviamo tramite mail a spid.tech@agid.gov.it l'url per la validazione.

Grazie. Saluti,

Servizi Locali SpA

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone procedere all'invio della convenzione

Umberto Rosini
Agenzia per l'Italia Digitale
