### ISSUE TITLE
Nuovo aggiornamento metadata per Regione Emilia Romagna

### ISSUE THREAD

**Issue by chiaracaniggia** [italia/spid#246]
Buongiorno,
segnalo l'attivazione di un nuovo servizio:

Nome: Sistema informativo BANDO BOLLO AUTO - Regione Emilia-Romagna
Attributi: familyName,fiscalNumber,name,spidCode
Livello SPID: 1

Grazie
saluti
Chiara Caniggia
LepidaSpA

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
