### ISSUE TITLE
Error Logout SPID

### ISSUE THREAD

**Issue by more-mau** [italia/spid#247]
Salve,
sto integrando la mia app con SPID.
Riesco ad autenticarmi correttamente, ricevendo tutti i dati dell'utente, ma quando tento di fare il logout ricevo sempre il seguente errore:
"Fatal error: Uncaught exception 'OneLogin_Saml2_Error' with message 'SAML LogoutRequest/LogoutResponse not found. Only supported HTTP_REDIRECT Binding' 

Potreste darmi supporto a riguardo?
Grazie in anticipo per la collaborazione

**Comment by damikael** [comment]
Ciao @more-mau,

l'attuale ambiente di test è basato su WSO Identity Server che, alla versione corrente, non implementa il logout in binding HTTP-Redirect, ma solo in HTTP-Post.
La libreria onelogin/php-saml, invece, implementa solo il logout in binding HTTP-Redirect.

È in corso di sviluppo il nuovo ambiente di test che supporterà entrambe le modalità.

Saluti.

Michele D'Amico
Collaboratore Agenzia per l'Italia Digitale

**Comment by Roby73** [comment]
Salve. Questa segnalazione è relativa ad un malfunzionamento esistente (in produzione).
Dopo aver correttamente acceduto tramite spid al sito del mio comune, ed effettuato le attività desiderate, ho premuto il tasto logout ed ho ricevuto il messaggio: 
"Errore
Formato richiesta non corretto - Contattare il gestore del servizio"
