### ISSUE TITLE
Richiesta verifica metadati Comune di Castions di Strada

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#248]
Buongiorno,
Si richiede la verifica dei metadati per conto del Castions di Strada.
https://www.comune.castionsdistrada.ud.it/c030020/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
