### ISSUE TITLE
Controllo metadata - Comune di Demonte

### ISSUE THREAD

**Issue by falbesano** [italia/spid#250]
Buongiorno,
per conto del Comune di Demonte, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.demonte.cn.it/004079/SPID/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
