### ISSUE TITLE
Richiesta verifica metadati Comune di Vigonovo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#251]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Vigonovo.
https://servizionline.comune.vigonovo.ve.it/c027043/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
