### ISSUE TITLE
Aggiornamento metadata per conto della Comunità Montana dei Laghi Bergamaschi

### ISSUE THREAD

**Issue by dfranzoni** [italia/spid#252]
Buongiorno,
l'ente richiede l'aggiornamento dei metadata ad esso associati per l'aggiunta di un nuovo servizio.
https://www.suap.cmlaghi.bg.it/sites/default/files/spid-metadata/cmlaghibg-signed.xml

Cordialmente

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Nell'arco dei vari aggiornamenti del metadata relativo ad una determinata P.A. è necessario mantenere il valore dell'identificativo unico (entityID) comunicato all'atto della prima pubblicazione del metadata. 

Nel caso specifico, è necessario ripristinare il valore entityID="https://www.suap.cmlaghi.bg.it/"

**Comment by dfranzoni** [comment]
Buongiorno,
abbiamo provveduto a ripristinare il valore precedente dell'entityID.

Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
