### ISSUE TITLE
Aggiornamento metadata per conto della Comunità Montana di Valle Camonica

### ISSUE THREAD

**Issue by dfranzoni** [italia/spid#253]
Buongiorno,
l'ente richiede l'aggiornamento dei metadata ad esso associati per l'aggiunta di un nuovo servizio.
https://www.sportellotelematico.cmvallecamonica.bs.it/sites/default/files/spid-metadata/cmvallecamonica-signed.xml

Cordialmente

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
