### ISSUE TITLE
Controllo metadata Provincia di Pavia

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#254]
Buongiorno,
Per conto della Provincia di Pavia abbiamo predisposto i metadata e pubblicati nella cartella
https://pavia.provincia-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano

**Comment by sfacondini** [comment]
[metadata_paviaprov-signed.zip](https://github.com/italia/spid/files/1951567/metadata_paviaprov-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
