### ISSUE TITLE
Richiesta verifica metadati Comune di Noventa Padovana

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#257]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Noventa Padovana.
https://servizionline.comune.noventa.pd.it/c028058/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
