### ISSUE TITLE
Controllo metadata Comune di Ronco Briantino 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#258]
Buongiorno,
Per conto del comune di Ronco Briantino, abbiamo predisposto i metadata e pubblicati nella cartella
https://roncobriantino.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_roncobriantino-signed.zip](https://github.com/italia/spid/files/1960167/metadata_roncobriantino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
L' attributo ID dell'elemento EntityDescriptor deve avere un valore di tipo NCName (https://www.w3.org/TR/xmlschema-2/#NCName ). Secondo la definizione di NCName, non sono valide stringhe che, fra l'altro, contengono uno spazio. Si prega di correggere il valore dell'attributo ID.

**Comment by sfacondini** [comment]
Buongiorno, 
corretto il problema dello spazio anomalo in ID di EntityDescriptor 

allego nuovi metadata

cordiali saluti
Facondini Stefano

[metadata_roncobriantino-signed.zip](https://github.com/italia/spid/files/1979579/metadata_roncobriantino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
