### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Brembate di Sopra

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#26]
Buongiorno,
abbiamo condotto i test interni per il Comune di Brembate di Sopra con esito positivo con tutti gli IDP
i servizi soggetti ad autenticazione sono erogati dal portale:

https://brembatedisopra.comune-online.it

cordiali saluti
Facondini Stefano

**Comment by umbros** [comment]
@sfacondini implementazione verificata con successo.
@AntonioGiovanniSchiavone puoi procedere all'invio della convenzione.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by globogis** [comment]
Buongiorno,
non so se rispondere qui è la procedura corretta o è necessario aprire una nuova issue.
Dovrei richiedere l'aggiornamento dei metadati sopra approvati con l'aggiunta dei nostri servizi. I metadati aggiornati e firmati sono pubblicati all'indirizzo: https://sportellotelematico.comune.brembatedisopra.bg.it/sites/default/files/spid-metadata/brembatedisopra-signed.xml

Chiederei sia ad AgID che a @sfacondini di verificare che i nuovi metadati non creino problemi al funzionamento degli attuali servizi Maggioli.

Grazie

**Comment by sfacondini** [comment]
Buongiorno, 
le modifiche mi sembrano corrette, purtroppo sono in treno, mi riservo un controllo approfondito  in serata/ nella mattinata di domani 
Cordiali saluti 
Stefano Facondini

**Comment by globogis** [comment]
Grazie @sfacondini , se mi confermi la correttezza procedo con la richiesta di aggiornamento.

**Comment by sfacondini** [comment]
Buona sera,
i metadata mi sembrano corretti, procediamo pure alla pubblicazione





Da:     "Globo s.r.l." <notifications@github.com>
Per:    italia/spid <spid@noreply.github.com>
Cc:     sfacondini <sfacondini@maggioli.it>, Mention 
<mention@noreply.github.com>
Data:   06/03/2018 10.58
Oggetto:        Re: [italia/spid] richiesta verifica tecnica e convenzione 
Comune di Brembate di Sopra (#26)



Grazie @sfacondini , se mi confermi la correttezza procedo con la 
richiesta di aggiornamento.
