### ISSUE TITLE
Controllo metadata Comune di Cologne 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#261]
Buongiorno,
Per conto del comune di Cologne, abbiamo predisposto i metadata e pubblicati nella cartella
https://cologne.comune-online.it/serviziSPID/metadata.xml
 

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_cologne-signed.zip](https://github.com/italia/spid/files/1966580/metadata_cologne-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
