### ISSUE TITLE
Comune di Agrate Brianza -  Aggiornamento certitificato

### ISSUE THREAD

**Issue by briviopc** [italia/spid#263]
Buongiorno,
si richiede la varifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro
cordiali saluti
ufficio ced

**Comment by AntonioGiovanniSchiavone** [comment]
L'hash della firma sul metadata non combacia con il contenuto. Sull'account github dell'iniziativa Developers Italia è stato pubblicato un tool per la firma dei metadata per i sistemi operativi Linux e OSX : https://github.com/italia/spid-metadata-signer. Vi segnaliamo inoltre che alcuni Service Provider hanno utilizzato con successo un porting del citato tool per la piattaforma Windows sviluppato da terzi: https://github.com/ermannog/SPID-Metadata-Signer-Windows

Si prega di rifirmare il metadata e di comunicarne la disponibilità all'endpoint segnalato di quello corretto.

**Comment by briviopc** [comment]
Buongiorno,
il metadato è stato aggiornato, pertanto si richiede la varifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro
cordiali saluti
ufficio ced

**Comment by briviopc** [comment]
Buongiorno,
il metadato è stato aggiornato, pertanto si richiede la varifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro
cordiali saluti
ufficio ced
