### ISSUE TITLE
Comune di Novara - Errore idp Sielte

### ISSUE THREAD

**Issue by fabio-scudieri** [italia/spid#264]
Salve, ho un problema con un singolo idp Sielte, ad ogni tentativo di accesso restituisce il codice di errore nr13.
Ho inviato una email con AuthnRequest e relativa Response.

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato nella [Tabella delle anomalie SPID](http://www.agid.gov.it/sites/default/files/regole_tecniche/spid_tabella_messaggi_di_anomalia_v1.0.pdf) , l'errore dipende da un non corretto valore dell'IssueInstant presente nell'AuthnRequest. 
Vi chiediamo quindi di verificare la correttezza dell'ora di sistema del server in questione, ricordando che 
a pag. 8 del [Regolamento recante le norme tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf )  è chiaramente indicato che l'IssueInstant deve corrispondere all'ora esatta espressa in UTC.
L'ora esatta espressa in UTC può essere anche verificata tramite vari servizi online , come ad esempio [questo](https://www.timeanddate.com/worldclock/timezone/utc)
