### ISSUE TITLE
Comune di Agrate Brianza - Aggiornamento certitificato

### ISSUE THREAD

**Issue by briviopc** [italia/spid#265]
Buongiorno, per errore ho chiuso la recente richiesta. 
il metadato è stato aggiornato, pertanto si richiede la varifica dei metadati del comune Agrate brianza al seguente link:
http://www.comune.agratebrianza.mb.it/pubblicazioni/Informazioni/Informazioni.asp?ID_M=806&ID_MacroMenu=1
in attesa di un VS riscontro
cordiali saluti
ufficio ced

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
