### ISSUE TITLE
Richiesta verifica metadati Comune di Pianezze

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#268]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Pianezze.
https://www.comune.pianezze.vi.it/c024077/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

P.S. non ho avuto riscontro su questa Issues https://github.com/italia/spid/issues/238
E' possibile sapere come poter procedere per concludere la procedura amministrativa per i Comuni attivati con SPID?

Grazie anticipatamente per la collaborazione.

Saluti
Andrea Carraro
Halley Veneto S.R.L.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
