### ISSUE TITLE
Richiesta aggiornamento metadati - Comune di Carpenedolo

### ISSUE THREAD

**Issue by globogis** [italia/spid#269]
Buongiorno,
si richiede per conto del Comune di Carpenedolo l'aggiornamento dei metadati SPID deployati. I nuovi metadati sono disponibili all'endpoint https://sportellotelematico.comune.carpenedolo.bs.it/sites/default/files/spid-metadata/carpenedolo-signed.xml
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
