### ISSUE TITLE
Richiesta verifica dei metadati - Comune di Pioltello

### ISSUE THREAD

**Issue by globogis** [italia/spid#270]
Buongiorno,
si richiede la validazione dei metadati per conto del comune di Pioltello:
https://sportellotelematico.comune.pioltello.mi.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
