### ISSUE TITLE
Controllo metadata Comune di Vico Equense 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#271]
Buongiorno,
Per conto del comune di Vico Equense, abbiamo predisposto i metadata e pubblicati nella cartella
https://vicoequense.comune-online.it/serviziSPID/metadata.xml
 

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_vicoequense-signed.zip](https://github.com/italia/spid/files/1983143/metadata_vicoequense-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by sfacondini** [comment]
L'IDP INTESA non ha ancora caricato il metadata nessun problema con gli altri 7 
cordiali saluti
Facondini Stefano 
Maggioli spa
