### ISSUE TITLE
Nuova versione metadata Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#272]
Buongiorno 
richiedo il deploy dei metadata della Regione Puglia, scaricabili da https://spid.rupar.puglia.it/regione-puglia-metadata.xml.

Rispetto alla versione precedente è stato inserito un certificato per il servizio http://www.sistema.puglia.it/SistemaPuglia/testspid (afferente all'assertion consumer service https://idplogin.rupar.puglia.it/Shibboleth.sso/SAML2/POST) che è stato erroneamente eliminato nell'ultimo deploy.

Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
