### ISSUE TITLE
errore Regione Molise POSTE

### ISSUE THREAD

**Issue by alaurenza** [italia/spid#275]
Buongiorno,

A seguito dell'aggioirnamento del certificato da parte della Regione  e della verifica del metadata tutti gli IDP funzionano eccetto Poste che restituisce l'errore "‘Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio’.
 Si chiede il deploy del file metadata https://spid.regione.molise.it/metadata.xml anche per Poste.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Discussione nella[ Issue 262](https://github.com/italia/spid/issues/262). Si chiude
