### ISSUE TITLE
Controllo metadata Comune di Erice 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#277]
Buongiorno,
Per conto del comune di Erice, abbiamo predisposto i metadata e pubblicati nella cartella
https://erice.comune-online.it/serviziSPID/metadata.xml
 

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_erice-signed.zip](https://github.com/italia/spid/files/1991372/metadata_erice-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
