### ISSUE TITLE
Richiesta validazione metadata per il comune di Baronissi ( SA )

### ISSUE THREAD

**Issue by fattanasio80** [italia/spid#280]
Per il comune in oggetto si richieda la validazione del metadata disponible alla url http://www.comune.baronissi.sa.it/metadata.xml. Il metadata è stato verificato utilizzando i tool da voi indicati spid-metadata-signer

**Comment by fattanasio80** [comment]
Inviato all'indirizzo spid.tech@agid.gov.it il metadata con le correzioni indicate.  All'indirizzo http://www.comune.baronissi.sa.it/metadata.xml è disponibile il nuovo metadata

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
