### ISSUE TITLE
Validazione metadata del Comune di Berbenno (BG)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#286]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Berbenno (BG):
https://www.comune.berbenno.bg.it/c016023/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernement Halley già validato in precedenza per altri Enti.

In attesa di vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
