### ISSUE TITLE
Richiesta di aggiornamento metadati - Comune di Pavia

### ISSUE THREAD

**Issue by globogis** [italia/spid#288]
Buongiorno,
si richiede, per conto del Comune di Pavia, l'aggiornamento dei metadati con quelli pubblicati all'endpoint:

https://sportellotelematico.comune.pv.it/sites/default/files/spid-metadata/pavia-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
