### ISSUE TITLE
Validazione Metadata del Comune di Chiuduno (BG)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#289]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Chiuduno (BG):
https://www.servizi.comune.chiuduno.bg.it/c016073/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernement Halley già validato in precedenza per altri Enti.
In attesa di vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
