### ISSUE TITLE
Nodo Cluster Regione Calabria

### ISSUE THREAD

**Issue by mirrep** [italia/spid#291]
Gentilissimi, 
la Regione Calabria ha commissionato la realizzazione di un nodo cluster, del tutto in linea con le prescrizioni di cui all'Avviso Nr. 6 del 29/07/2016 "Note sul Dispiegamento di Spid presso i gestori dei Servizi". 
A tal riguardo si sottopone il seguente esempio: 
Il nodo Cluster www.regione.calabria.it metterà a disposizione dei cittadini un insieme di servizi, basati sulla strutturazione interna dell'ente. Tra questi è stato prevista l'istituzione di un nodo denominato Ecositema Calabria Sanità. 
A breve si prevede l'istituzione di ulteriori nodi afferenti al mondo dei tributi e lavoro. 
Intenzione della Regione, per come chiarito, è pertanto l'istituzione di un nodo cluster  configurandosi l'ipotesi di un gestore di più servizi o service provider, il cui dispiegamento avrà le seguenti caratteristiche: 
A) Presenza di più nodi di erogazione (per il momento quello di specifico interesse e di immediata istituzione è da riferire al nodo Ecosistema Calabria Sanità) distribuiti geograficamente;
B) Servizi orientati al cittadino aggregati in classi in base al set di attributi per i quali si chiede la certificazione e nello specifico Classe Salute (Servizio Scelta e Revoca, Consultore, R@ro, Vaccinazioni, Esenzioni) Attributi richiesti per la Classe Salute "Codice Fiscale", e altre classi che nel presente esempio al momento non rilevano. 

Nel caso in esame si evidenzia che i servizi previsti ed afferenti al nodo Ecosistema Salute di cui alla Classe Salute indicata saranno forniti tramite un nodo in cloud. 

In sostanza il nodo geografico, con ambiente applicativo predisposto per l'erogazione dei servizi menzionati, è rappresentato da un application server che sarà raggiunto dal cittadino tramite redirect dal nodo "servizi.sanita.regione.calabria.it" ad un record DNS del tipo www.servizisanitaregionecalabria.it gestito da terzi (record non confacente con il dominio del Service Provider se non tramite puntamento dedicato). 

In funzione di quanto addotto ed al fine di rispettare tutte le condizioni utili ad implementare il servizio di autenticazione si chiede conferma delle seguenti affermazioni: 
1) tutti i nodi afferenti al Service Provider ed interessati dall'esempio devono essere certificati SSL (SSL WildCard) a partire dal service provider www.regione.calabria.it, ai singoli nodi geografici tra cui servizi.sanita.regione.calabria.it (con DNS dedicato) fino al nodo servizisanitaregionecalabria.it (portale raggiunto tramite puntamento dedicato)
2) la procedura di creazione del metadato, secondo le specifiche di cui all'Avviso 6, può interessare anche un singolo nodo geografico e nello specifico il nodo https servizi.sanita.regione.calabria.it oltre al nodo cluster www.regione.calabria.it
3) per l'eventuale attivazione di ulteriori servizi, a distanza di tempo, fatta salva la creazione di ulteriori metadati, andranno pur sempre dettagliati i servizi e gli attributi richiesti di riferimento. 
4) se non si hanno chiari i servizi, le classi e gli attributi di riferimento per tutti i servizi di cui si prevede erogazione (distinti per classi e caratterizzati da specifci attributi) non è ipotizzabile avviare una procedura di certificazione e di adesione a SPID ai fini della creazione di un nodo cluster.

Vi ringraziamo sin da ora dell'interesse che vorrete mostrare. 

Distinti saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

In risposta alle sue domande, è bene chiarire alcuni aspetti relative all'integrazione di servizi on line in SPID:

1) Per una data Pubblica Amministrazione (nel caso specifico la Regione Calabria), è possibile definire un unico metadata. Tale metadata dovrà quindi includere tutte le descrizioni dei servizi afferenti alla P.A. in questione ( nell'esempio riportato, il metadata potrà contenere le descrizioni di  servizi  relativi alla sanità,  al mondo del  lavoro etc). Quindi non è corretto parlare di "creazione di ulteriori metadati". Il medatata è unico, e può essere nel tempo aggiornato con l'inserimento di nuovi servizi. Inoltre, come indicato sul [sito ufficiale SPID nella pagina dedicata ai Service Provider] (https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), tale metadata deve essere pubblicato su una url afferente al dominio della P.A. in questione (nel caso specifico  regione.calabria.it ).

2) Come indicato nel citato [Avviso SPID n°6](http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf) , per la scelta del valore dell'elemento EntityId,  si
consiglia di usare il nome di dominio dall’ente ( nel caso specifico http://www.regione.calabria.it/ ) od un suo sottodominio ( ad esempio, http://spid.regione.calabria.it/). Tale suggerimento è ulteriormente rafforzato dalle dimensioni della P.A. in oggetto e quindi dalla prevedibile eterogeneità dei servizi offerti.
Ricordiamo che l'EntityId ha il ruolo di semplice identificativo unico della P.A., e quindi non deve necessariamente corrispondere ad una url attiva.
  
3) Nell'[Avviso SPID n° 1](http://www.agid.gov.it/sites/default/files/documentazione/spid_-_avviso_n1_-_sicurezza_canale_trasmissione_0.pdf) si chiarisce che i colloqui tra Asserting party (Identity Provider e Attribute Authority ), le Relying Party (Service Provider) e lo user agent devono avvenire tramite protocollo HTTPS, avente protocollo di crittografia TLS 1.2. Non è richiesto che la sicurezza delle comunicazioni sia definita da una unica wildcard.
  
4) Il processo di adesione a SPID (sia per quanto riguarda la procedura tecnica che quella amministrativa) richiede che sia integrato almeno un servizio online. Ulteriori servizi possono essere successivamente integrati secondo le modalità indicate nella documentazione tecnica e sul sito ufficiale SPID.

5) Nella definizione del metadata è obbligatoria la definizione di almeno un set di attributi (elemento AttributeConsumingService). Ricordiamo che il numero ed il tipo di attributi richiesti devono essere non eccedenti rispetto a quelli strettamente necessari per l'erogazione del servizio.

6) Fatta eccezione per il valore dell'identificativo unico (EntityID), qualunque altra informazione definita nel metadata può essere rimossa e/o aggiornata, purchè si rispettino i requisiti definiti nella documentazione tecnica.

7) Per qualunque altro dubbio si rimanda implictamente alla documentazione tecnica, ovvero al [Regolamento recante le regole tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf) e gli [Avvisi SPID](http://www.agid.gov.it/agenda-digitale/infrastrutture-architetture/spid/avvisi)   

Ricordiamo che, qualora fosse necessario approfondire la discussione con la descrizione di dati sensibili o configurazioni di sicurezza,è possibile inviare una email a spid.tech@agid.gov.it

**Comment by mirrep** [comment]
Gent.mo Sig. Schiavone, 
quoto il punto della nostra richiesta sul quale nutriamo ancora dei dubbi: 
`In sostanza il nodo geografico, con ambiente applicativo predisposto per l'erogazione dei servizi menzionati, è rappresentato da un application server che sarà raggiunto dal cittadino tramite redirect dal nodo "servizi.sanita.regione.calabria.it" ad un record DNS del tipo www.servizisanitaregionecalabria.it gestito da terzi (record non confacente con il dominio del Service Provider se non tramite puntamento dedicato).`
A titolo di ulteriore richiesta di chiarimento:
1. nel caso indicato una volta generato il metadato a partire dal dominio dell'ente http://www.regione.calabria.it/ (ovvero altro sottodominio) è possibile che lo stesso possa essere usato per le operazioni di autenticazione su un terzo domimio che non è afferente al dominio della P.A. in questione ?

Si specifica inoltre che il terzo dominio, www.servizisanitaregionecalabria.it, nel caso specifico è gestito su richiesta dell'ente da un privato benchè  raggiungibile tramite puntamento ad uno specifico record DNS in grado di gestire lo scambio di dati tramite TLS.

Attendiamo sue nuove e la ringraziamo per il supporto prestato.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Se abbiamo capito bene, ci state chiedendo se, all'interno di un metadata di una P.A. , sia possibile includere, fra gli altri servizi, un servizio online gestito da un fornitore esterno della P.A. in questione e per conto della P.A. stessa.
Tale scenario è possibile, ed è relativamente comune fra le p.a. di medio/piccole dimensioni.
Ovviamente l'onere di inclusione ed, in seguito ad eventuale risoluzione del contratto col fornitore, esclusione del servizio dal metadata rimane in capo alla P.A. aderente, la quale si fa garante del rapporto intercorrente fra di sè ed il fornitore.

**Comment by mirrep** [comment]
Gentilissimi,
Sollevo, fiducioso in una risoluzione tempestiva, la seguente problematica:
Abbiamo prodotto un metadata, richiedendone validazione, mediante implementazione del Docker “Spid Auth Docker” che configurato restituisce nella sezione SignatureValue un hash di firma dedicato, funzione dell’utilizzo dei certificati Saml di riferimento.

Nonostante il metadata risulti firmato otteniamo dallo staff tecnico Spid informazioni circa “la mancata corrispondenza fra hash della firma e il contenuto del documento”.

Abbiamo utilizzato al riguardo anche tutti i tool di firma suggeriti per ambienti Linux (Spid Metadata Signer) ma non riusciamo a venirne a capo in quanto il file ci risulta già firmato.

Tra l’altro utilizzando il docker suggerito non dovrebbe essere necessario ricorrere ad ulteriori strumenti di firma! Ma a questo punto ci dobbiamo ricredere.
Avremmo la necessità di essere supportati da un punto di vista tecnico.
Conoscere laddove possibile se sussistono prima dell’invio strumenti di validazione e comprendere a questo punto quale parte del metadata è corrotta o non corrispondente al resto dei contenuti.
Volendo sollevare richiesta tecnica per la risoluzione del caso quali altre informazioni è necessario trasferire? 

Grazie come sempre del vostro prezioso supporto.

Cordialmente.
