### ISSUE TITLE
Regione Veneto - richiesta validazione metadata e diffusione IDP Spid

### ISSUE THREAD

**Issue by francesco-fornasiero** [italia/spid#292]
PA: Regione Veneto
Categoria: validazione nuovo metadata e diffusione agli IDP Spid

Regione Veneto ha predisposto un secondo nodo di aggregazione in aggiunta al primo già installato e attivato.
Si richiede quindi la validazione del metadata del secondo nodo e successivo deploy agli IDP Spid.
L'url del metadata del secondo nodo di aggregazione viene inviato via mail.

**Comment by francesco-fornasiero** [comment]
Come da vostra comunicazione, si sono riportate le informazioni sul secondo nodo di aggregazione all'interno del metadata già registrato (https://myid.regione.veneto.it/gw/metadata-spid) : se ne richiede quindi la validazione e aggiornamento presso gli IDP Spid.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
