### ISSUE TITLE
Richiesta aggiornamento metadata - Comune di Novara

### ISSUE THREAD

**Issue by fabio-scudieri** [italia/spid#293]
Buongiorno,
abbiamo aggiunto un ulteriore servizio, si richiede cortesemente, venga validato e inoltrato il nuovo metadata agli idp.

[metadata aggiornato](https://www.comune.novara.it/script/spid/spid-metadata-novara-v5-signed.xml)

Grazie per la collaborazione
Distinti saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il metadata prosposto non è conforme alle regole indicate nel Regolamento recante le norme tecniche SPID.
Infatti non è possibile mischiare  la definizione di elementi del tipo SingleLogoutService, AssertionConsumerService e AttributeConsumingService, ma occorre bensì definirli seguendo il seguente ordine:

1. Sequenza di elementi di tipo SingleLogoutService
2. Sequenza di elementi di tipo AssertionConsumerService
3. Sequenza di elementi di tipo AttributeConsumingService

come illustrato dall'esempio di metadata SP presente a pagg 9/10 dell'[Avviso SPID n° 6](http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf)

**Comment by fabio-scudieri** [comment]
Salve, si è provveduto a riorganizzare le definizioni secondo le indicazioni.

[metadata](https://www.comune.novara.it/script/spid/spid-metadata-novara-v6-signed.xml)

Grazie
Distinti Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
