### ISSUE TITLE
Validazione Metadata del Comune di Montereale (AQ)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#297]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Montereale (AQ):
https://www.comune.montereale.it/c066056/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
