### ISSUE TITLE
Richiesta validazione metadata per Lazio Innova

### ISSUE THREAD

**Issue by petterutir** [italia/spid#298]
Buongiorno,
si richiede la validazione del metadata per conto di Lazio Innova:
https://gecoweb.lazioinnova.it/spidweb/module.php/saml/sp/metadata.php/login-lazioinnova

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

la url inviata non corrisponde ad un metadata. Inoltre gradiremmo l'invio ad spid.tech@agid.gov.it di una mail in cui si chiarisca di che servizio si tratta e a quale P.A. fa riferimento.

**Comment by petterutir** [comment]
Buongiorno,
il problema di accesso al metadata è stato corretto e contestualmente è stata inviata la mail richiesta.
Il metadata è disponibile qui:
https://gecoweb.lazioinnova.it/spidweb/module.php/saml/sp/metadata.php/login-lazioinnova
Grazie.

**Comment by petterutir** [comment]
Buongionro,
ci sono novità sulla validazione del metadata?

Grazie
