### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Monopoli

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#30]
Buongiorno,
abbiamo condotto i test interni per il Comune di Monopoli con esito positivo
i servizi soggetti ad autenticazione sono erogati  dal portale:

https://monopoli.comune-online.it/web/home/servizi-tributari

cordiali saluti
Facondini Stefano
Maggioli spa

**Comment by umbros** [comment]
@sfacondini implementazione verificata con successo.
@AntonioGiovanniSchiavone puoi procedere all'invio della convenzione.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.
