### ISSUE TITLE
Richiesta validazione metadata - Comune di Castelcovati

### ISSUE THREAD

**Issue by globogis** [italia/spid#300]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.castelcovati.bs.it/simplesaml/module.php/saml/sp/metadata.php/castelcovati

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
