### ISSUE TITLE
Richiesta verifica tecnica e convenzione Università degli studi di Cassino

### ISSUE THREAD

**Issue by petraccone** [italia/spid#304]
Buongiorno,
abbiamo condotto i test interni per il sistema informativo smartEDU GOMP dell'Università degli studi di Cassino (http://www.unicas.it/) con esito positivo.
I servizi soggetti ad autenticazione sono erogati dal portale:

**Pagina di invio richiesta allo IDP:**
https://gomp.unicas.it/WorkFlow2011/Logon/SpidOut.aspx
(es. https://gomp.unicas.it/WorkFlow2011/Logon/SpidOut.aspx?idp=poste)

**Pagina di ritorno e acquisizione risposta dallo IDP:**
https://gomp.unicas.it/WorkFlow2011/Logon/SpidIn.aspx

**Pagina TEST per il login:**
https://gomp.unicas.it/WorkFlow2011/Logon/spidTest.aspx
Il sito è già in produzione e dalla pagina principale non è visibile, per ora, il tasto di login con SPID.

Cordiali saluti.

Giuseppe Riccio (riccio@unicas.it)
Stefano Petraccone (petraccone@besmart.it)

**Comment by petraccone** [comment]
Buongiorno, non abbiamo avuto nessun riscontro. Sarebbe possibile avere notizie?
Grazie.

**Comment by petraccone** [comment]
Buongiorno, ancora non abbiamo saputo nulla. Possibile che i tempi siano questi?
Cordiali saluti.

**Comment by umbros** [comment]
Validazione tecnica ok. Si può procedere con l'invio della convenzione @AntonioGiovanniSchiavone

**Comment by petraccone** [comment]
Ottimo!
La documentazione da inviare me la potete mandare o va bene quella che
avevamo già usato per Adozione trasparente della PCM?
Un saluto ed a presto.

--
Stefano Petraccone
System Engineer
Be Smart s.r.l. *www.besmart.it <http://www.besmart.it/>*
via delle Sette Chiese 278
IT-00147 Roma

Phone: (+39) 06.99587.1
Mail: *petraccone@besmart.it <petraccone@besmart.it>*

2018-07-19 17:04 GMT+02:00 Umberto Rosini <notifications@github.com>:

**Comment by AntonioGiovanniSchiavone** [comment]
La documentazione specifica per l'Università' degli Studi di Cassino e del Lazio Meridionale è stata inviata al referente dell'Università Ing. Riccio.

**Comment by petraccone** [comment]
Ottimo. Grazie.

--
Stefano Petraccone
System Engineer
Be Smart s.r.l. *www.besmart.it <http://www.besmart.it/>*
via delle Sette Chiese 278
IT-00147 Roma

Phone: (+39) 06.99587.1
Mail: *petraccone@besmart.it <petraccone@besmart.it>*

Il giorno 19 luglio 2018 17:29, Antonio Giovanni Schiavone <
notifications@github.com> ha scritto:
