### ISSUE TITLE
Controllo metadata Comune di San Giuliano Milanese

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#306]
Buongiorno,
Per conto del comune di San Giuliano Milanese, abbiamo predisposto i metadata e pubblicati nella cartella
https://sangiulianomilanese.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_sangiulianomilanese-signed.zip](https://github.com/italia/spid/files/2028035/metadata_sangiulianomilanese-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per la P.A. in oggetto ( recuperabile all'indirizzo https://sportellotelematico.sangiulianonline.it/simplesaml/module.php/saml/sp/metadata.php/sangiulianomilanese ).

Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).

**Comment by sfacondini** [comment]
Buongiorno,
sono stati pubblicati nuovi metadata che tengono conto del precedente SP  (il comune non ci aveva informato).
l'url è sempre:
https://sangiulianomilanese.comune-online.it/serviziSPID/metadata.xml

[metadata_sangiuliano2SP-signed.zip](https://github.com/italia/spid/files/2062197/metadata_sangiuliano2SP-signed.zip)

cordiali saluti
Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
