### ISSUE TITLE
Controllo metadata Comune di Salerano sul Lambro

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#307]
Buongiorno,
Per conto del comune di Salerano sul Lambro, abbiamo predisposto i metadata e pubblicati nella cartella
https://saleranosullambro.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_saleranosullambro-signed.zip](https://github.com/italia/spid/files/2028046/metadata_saleranosullambro-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
