### ISSUE TITLE
Controllo metadata Comune di Lacchiarella

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#308]
Buongiorno,
Per conto del comune di Lacchiarella, abbiamo predisposto i metadata e pubblicati nella cartella

https://lacchiarella.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_lacchiarella-signed.zip](https://github.com/italia/spid/files/2028056/metadata_lacchiarella-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
