### ISSUE TITLE
Controllo metadata Comune di Bernareggio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#309]
Buongiorno,
Per conto del comune di Bernareggio, abbiamo predisposto i metadata e pubblicati nella cartella

https://bernareggio.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_bernareggio-signed.zip](https://github.com/italia/spid/files/2028067/metadata_bernareggio-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
