### ISSUE TITLE
Problem Logout

### ISSUE THREAD

**Issue by djimenezSimumak** [italia/spid#313]
Salve,
sto integrando la mia app con SPID (con PHP) e testando sul server di sviluppo https://idp.spid.gov.it..
Riesco ad autenticarmi correttamente, ricevendo tutti i dati dell'utente, ma quando tento di fare il logout, lo schermo rimane vuoto e non reindirizza all'URL che fornisco nella chiamata o gli echi che post dopo non vengono mostrati invece di reindirizzare. 
Il codice utilizzato è:
$auth = new SimpleSAML_Auth_Simple($service);
-- Elaborazione dati --
$auth->logout('http://--URL--');
o 
$auth->logout();
echo 'TEST';

Comunque se non faccio il logout e metto un reindirizzamento con PHP se funziona questo reindirizzamento

Potete aiutarmi a trovare e comprendere l'errore e correggerlo affinché il logout funzioni?

Grazie in anticipo per la collaborazione

**Comment by damikael** [comment]
Salve, 
potrebbe gentilmente indicarci l'Entity ID con il quale è stato registrato il metadata sul'IDP di test

Grazie

Michele D'Amico
Collaboratore Agenzia per l'Italia Digitale

**Comment by djimenezSimumak** [comment]
Salve,
L'Entity ID con il quale è stato registrato il metadata è: http://sntdev.simumak.com

Grazie

**Comment by damikael** [comment]
Salve,
occorre registrare il metadata sull'IdP di test con il SingleLogoutService nella seguente forma:

https://_sp.example.org_/_simplesaml_/module.php/saml/sp/saml2-logout.php/_default-sp_

specificando al posto di _sp.example.org_/_simplesaml_ e _default-sp_ rispettivamente l'url al quale risulta installata la libreria simplesamlphp e il nome del servizio, come configurato nel file authsources.php.

(Rif. https://simplesamlphp.org/docs/1.6/simplesamlphp-sp , 4 Exchange metadata with the IdP)

Quando viene chiamato il metodo logout(), infatti, la richiesta di logout viene inoltrata all'IdP, il quale provvede ad eseguire logout e ad inviare la response alla location di SingleLogoutService indicata nel metadata. Tale location deve essere l'endpoint della libreria simplesamlphp, indicato sopra, affinchè questa possa considerare il parametro ReturnTo ed eseguire il redirect richiesto.

Per correggere il metadata sull'IdP di test è sufficiente salvarlo nuovamente specificando lo stesso Entity ID.

Saluti.

Michele D'Amico
Collaboratore Agenzia per l'Italia Digitale

**Comment by RoBYCoNTe** [comment]
Buonasera,
mi ricollego allo stesso argomento anche io.
Per conto di un cliente stiamo sviluppando le procedure di login/logout tramite SPID e, purtroppo, stiamo avendo qualche problema a terminare correttamente la fase di "logout".

Attualmente ho una pagina di logout cosi composta:
```
<?php 
	require_once ("spid-sdk.php");
	require_once ("spid-app.php");

	$spidsdk = new SpidSdk();
	$referer = $_SERVER['HTTP_REFERER'];
	if ($spidsdk->isAuthenticated()) {
		$spidsdk->logout();
	}
```

Purtroppo, provando ad eseguire la stessa (avendo premura di eseguire un login con successo), otteniamo il seguente messaggio di errore:
```SimpleSAML_Error_Error: UNHANDLEDEXCEPTION```

Dove sbaglio?
