### ISSUE TITLE
Richiesta validazione metadata - Comune di Cazzago San Martino

### ISSUE THREAD

**Issue by globogis** [italia/spid#316]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.cazzago.bs.it/simplesaml/module.php/saml/sp/metadata.php/cazzagosanmartino

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
