### ISSUE TITLE
Controllo metadata - Comune di Cervasca

### ISSUE THREAD

**Issue by falbesano** [italia/spid#317]
Buongiorno,
per conto del Comune di Cervasca, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.cervasca.cn.it/004064/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
