### ISSUE TITLE
Controllo metadata - Comune di Robilante

### ISSUE THREAD

**Issue by falbesano** [italia/spid#318]
Buongiorno,
per conto del Comune di Robilante, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.robilante.cn.it/004185/SPID/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
