### ISSUE TITLE
Errore interazione con IdP Infocert

### ISSUE THREAD

**Issue by globogis** [italia/spid#326]
Buongiorno,
nel nostro servizio https://sportellotelematico.comune.ugento.le.it riscontriamo un'anomalia nell'interazione solamente con l'IdP Infocert.

Inviando la AuthnRequest il sistema restituisce il consueto errore:
```
Si è verificato un errore
Formato richiesta non corretto. Contattare il gestore del servizio.
```

Con gli altri IdP l'accesso avviene correttamente: riteniamo che ci sia stata un'anomalia nel deploy dei metadati limitatamente a questo IdP.

Vi chiedo quindi una verifica in merito e, se necessario, una nuova richiesta di deploy dei metadati verso Infocert.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo provveduto a far ricaricare il metadata. Il problema sembra adesso risolto.
