### ISSUE TITLE
Richiesta verifica metadati Comune di Cazzano di Tramigna

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#335]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Cazzano di Tramigna.
https://servizionline.comune.cazzanoditramigna.vr.it/c023024/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
