### ISSUE TITLE
Controllo metadata Comune di Scicli

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#337]
Buongiorno,
Per conto del comune di Scicli, abbiamo predisposto i metadata e pubblicati nella cartella

https://scicli.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa

[metadata_scicli-signed.zip](https://github.com/italia/spid/files/2062956/metadata_scicli-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
