### ISSUE TITLE
Controllo metadata Comune di Monsummano Terme

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#342]
Buongiorno,
Per conto del comune di Monsummano Terme, abbiamo predisposto i metadata e pubblicati nella cartella

https://monsummanoterme.comune-online.it/serviziSPID/metadata.xml
 
cordiali saluti
Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
