### ISSUE TITLE
Richiesta controllo metadata - Comune di Comazzo (LO)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#343]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:
https://www.comune.comazzo.lo.it/c098020/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
