### ISSUE TITLE
Aggiornamento metadati Istituto Zooprofilattico G. Caporale

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#344]
Salve, si richiede l'aggiornamento dei metadati del fornitore di servizi Istituto Zooprofilattico dell'Abruzzo e del Molise G. Caporale.

I nuovi metadati sono reperibili alla URL seguente (utilizzata anche in fase di registrazione)

https://sptest.izs.it/metadata.xml

In attesa di un vostro riscontro porgo cordiali saluti.
F.

**Comment by fmartelli** [comment]
Ciao, il problema TLS1.2 dovrebbe essere risolto.
Vi chiedo di verificare ed eventualmente caricare i nuovi metadati.
Grazie e buona giornata

**Comment by fmartelli** [comment]
Ci sono novità a riguardo?
Fatemi sapere se ci sono problemi.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
