### ISSUE TITLE
anomalia display name Comune San Giuliano Milanese IDP POSTE e Register.it

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#346]
Buongiorno, 
recentemente sono stati dispiegati nuovi metadata per il comune di san giuliano milanese
https://sangiulianomilanese.comune-online.it/serviziSPID/metadata.xml
![postesangiulianomilanese](https://user-images.githubusercontent.com/7039668/41024379-5dad125c-696f-11e8-918e-6e20d53fc419.JPG)
![registersangiuliano](https://user-images.githubusercontent.com/7039668/41024393-6614d8f8-696f-11e8-9585-fb2eecd723f3.JPG)

frutto dell'integrazione di un nuovo SP con metadata già pubblicati
riscontriamo un comportamento anomalo con poste e register che mostrano in sede di autenticazione non il display name ma l'organization URL
gli altri 6 IDP non presentano problemi
cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by sfacondini** [comment]
Integro la segnalazione:   Aruba sembra non aver recepito i nuovi metadata non riconosce la firma dell'asserzione
cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by sfacondini** [comment]
Mi sono confrontato con i colleghi di PosteID  questa è la diagnosi del problema:

_"il nostro idp presenta a video l'entityid, non l'Organization URL,  solo se non trova nei metadata l'OrganizationDisplayName.
nel vostro caso è solo un problema di localizzazione, perché nei vostri metadata è riportato
  <md:Organization>
    <md:OrganizationName xml:lang="en">c_h930</md:OrganizationName>
    <md:OrganizationDisplayName xml:lang="en">Comune di San Giuliano Milanese</md:OrganizationDisplayName>
    <md:OrganizationURL xml:lang="en">https://sportellotelematico.sangiulianonline.it</md:OrganizationURL>
  </md:Organization>

se fosse lang="it" verrebbe visualizzato correttamente il valore riportato nel nodo OrganizationDisplayName_

mi sembra corretta;  procediamo a modificare i metadata con localizzazione corretta?

Cordiali Saluti
Stefano Facondini 
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Si, procedete e comunicateci l'avvenuto aggiornamento del metadata.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
