### ISSUE TITLE
Richiesta verifica metadati Comune di Pincara

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#348]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Pincara.
https://www.comune.pincara.ro.it/c029036/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
