### ISSUE TITLE
Richiesta verifica tecnica e convenzione Provincia di Foggia

### ISSUE THREAD

**Issue by prfg** [italia/spid#35]
Buongiorno,
  si richiede la verifica tecnica e convenzione per la PROVINCIA DI FOGGIA:

L'url del metadata è:
https://sportellotelematico.provincia.foggia.it/simplesaml/module.php/saml/sp/metadata.php/provfoggia

Cordiali Saluti.

**Comment by umbros** [comment]
Cia @prfg la validazione del servizio è fatta sul servizio stesso. Quello inviato è il file di configurazione che @AntonioGiovanniSchiavone provvederà a pushare agli idp. Appena caricato, si può procedere con la verifica del servizio e ti chiedo di fornire la url qui o sull'email spid.tech@agid.gov.it

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by prfg** [comment]
il servizio SPID deve essere abilitato sulla url del nostro Sportello Telematico:
https://sportellotelematico.provincia.foggia.it/

**Comment by prfg** [comment]
Buongiorno,
  ci sono novità in merito ?

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

**Comment by prfg** [comment]
Perfetto grazie. Ora quali sono gli step successivi ?

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Le procedure per la l'adesione a SPID sono illustrata nel sito ufficiale SPID alla pagina: https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

**Comment by prfg** [comment]
Si. L’ho letta, e secondo la procedura amministrativa, dopo la verifica tecnica  dovrei aver ricevuto la convenzione da sottoscrivere, ma questo non è avvenuto.
Come faccio a ricevere tale convenzione ?

Cordiali Saluti.

______________________________________
Massimo Pintauro
Settore Politiche del Lavoro e Sistema informativo
Servizio Sistema informativo
Tel. :   0881.791575      Fax : 0881.315575



Da: Antonio Giovanni Schiavone [mailto:notifications@github.com]
Inviato: martedì 13 marzo 2018 17:18
A: italia/spid
Cc: Massimo Pintauro; Mention
Oggetto: [SPAM] - Re: [italia/spid] Richiesta verifica tecnica e convenzione Provincia di Foggia (#35)


Buongiorno,

Le procedure per la l'adesione a SPID sono illustrata nel sito ufficiale SPID alla pagina: https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

**Comment by AntonioGiovanniSchiavone** [comment]
Credo che vi sia un pò di confusione fra verifica della validità del metadata e verifica dell'implementazione di SPID.

Nel primo caso, si tratta di verificare se il contenuto del metadata (ovvero un file xml) è stato strutturato coerentemente con le indicazioni delle norme tecniche SPID.

Nel secondo caso, si tratta di verificare che l'interazione tra Service Provider e gli Identity Provider è corretta e coerente con le norme tecniche SPID.

Ricapitolando, in un caso si tratta dell'analisi delle correttezza un documento testuale (il metadata), nell'altro caso l'analisi della correttezza ed efficacia dell'interazione di due sistemi informatici via protocolli web.
Si tratta quindi di due verifiche diverse e distinte.

Confermiamo che per il caso della vostra P.A. è stata superata la verifica della validità del metadata, che è stato conseguentemente comunicato agli Identity Provider e caricato dagli stessi.

Per fare richiesta di verifica dell'implementazione di SPID, come indicato nella pagina citata è necessario fare esplicita richiesta tramite questo account github, indicando le url dei servizi da validare (Attenzione, non la url del metadata!)

Solo al superamento di questa seconda verifica verrà inviata la Convenzione da sottoscrivere.

**Comment by prfg** [comment]
Buongiorno,
   mi scuso ma non riesco a capire a che punto ci siamo fermati della procedura.

Ho provveduto ad inserire questa richiesta :
https://github.com/italia/spid/issues/72

ma non ho ricevuto più alcun feedback. Potrebbe essere così gentile da spiegarmi cosa devo fare ?
La ringrazio,


______________________________________
Massimo Pintauro
Settore Politiche del Lavoro e Sistema informativo
Servizio Sistema informativo
Tel. :   0881.791575      Fax : 0881.315575



Da: Antonio Giovanni Schiavone [mailto:notifications@github.com]
Inviato: martedì 13 marzo 2018 18:19
A: italia/spid
Cc: Massimo Pintauro; Mention
Oggetto: [SPAM] - Re: [italia/spid] Richiesta verifica tecnica e convenzione Provincia di Foggia (#35)


Credo che vi sia un pò di confusione fra verifica della validità del metadata e verifica dell'implementazione di SPID.

Nel primo caso, si tratta di verificare se il contenuto del metadata (ovvero un file xml) è stato strutturato coerentemente con le indicazioni delle norme tecniche SPID.

Nel secondo caso, si tratta di verificare che l'interazione tra Service Provider e gli Identity Provider è corretta e coerente con le norme tecniche SPID.

Ricapitolando, in un caso si tratta dell'analisi delle correttezza un documento testuale (il metadata), nell'altro caso l'analisi della correttezza ed efficacia dell'interazione di due sistemi informatici via protocolli web.
Si tratta quindi di due verifiche diverse e distinte.

Confermiamo che per il caso della vostra P.A. è stata superata la verifica della validità del metadata, che è stato conseguentemente comunicato agli Identity Provider e caricato dagli stessi.

Per fare richiesta di verifica dell'implementazione di SPID, come indicato nella pagina citata è necessario fare esplicita richiesta tramite questo account github, indicando le url dei servizi da validare (Attenzione, non la url del metadata!)

Solo al superamento di questa seconda verifica verrà inviata la Convenzione da sottoscrivere.
