### ISSUE TITLE
Richiesta controllo metadata - comune di Novate Milanese

### ISSUE THREAD

**Issue by globogis** [italia/spid#351]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.novate-milanese.mi.it/simplesaml/module.php/saml/sp/metadata.php/novatemilanese

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
