### ISSUE TITLE
Errore di accesso IdP Sielte - Comune di Cinisello Balsamo

### ISSUE THREAD

**Issue by globogis** [italia/spid#354]
Buongiorno,
accedendo dal nostro servizio https://suap.comune.cinisello-balsamo.mi.it/ utilizzando Sielte, l'IdP ci risponde così:

```
Status: urn:oasis:names:tc:SAML:2.0:status:Requester
SubStatus: urn:oasis:names:tc:SAML:2.0:status:RequestDenied
Message: ErrorCode nr13
```

Con gli altri IdP si accede invece correttamente.
Chiedo dunque cortesemente di eseguire un nuovo deploy dei metadati verso l'IdP Sielte, poiché il precedente non è probabilmente andato a buon fine. I metadati sono sempre esposti all'endpoint https://suap.comune.cinisello-balsamo.mi.it/simplesaml/module.php/saml/sp/metadata.php/cinisellobalsamo

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

L'errore riportato non sembra dipendere da un errore nel deploy, bensì da un problema relativo all'IssueInstant delle AuthnRequest generate. 
In particolare, il server dove è installato il servizio in questione sembra avere l'orologio di sistema settato alcuni secondi nel futuro rispetto all'ora esatta. Tale problema si evince anche da un confronto fra le marche temporali contenute nell'IssueInstant dell'AuthnRequest e della Response.
Suggeriamo quindi di correggere le impostazioni dell'orologio di sistema del server in questione, eventualmente avvalendosi di un servizio di sincronizzazione basato su protocollo ntp, come quello fornito dall' [Istituto Nazionale di Ricerca Metrologica](https://www.inrim.it/node/643)

**Comment by AntonioGiovanniSchiavone** [comment]
Il problema sembra risolto. Si chiude.
