### ISSUE TITLE
Richiesta controllo metadata -  Comune di Sergnano

### ISSUE THREAD

**Issue by globogis** [italia/spid#358]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.sergnano.cr.it/simplesaml/module.php/saml/sp/metadata.php/sergnano

**Comment by psmiraglia-agid** [comment]
Salve, i metadata risultano essere conformi alle specifiche. Il mio collega @AntonioGiovanniSchiavone provvederà alla comunicazione presso gli identity provider.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
