### ISSUE TITLE
mancata acquisizione IDP Aruba Comune San Giuliano Milanese

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#360]
Buongiorno, 
il problema del displayname con gli IDP Poste e Register (#346) si è risolto ma Aruba presenta ancora dei problemi di mancato riconoscimento dell'asserzione.
server che eroga il servizio:
https://sangiulianomilanese.comune-online.it/c/portal/login

cordiali saluti
Facondini Stefano 
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Dopo una verifica con l'IdP in questione, il problema è stato risolto.
