### ISSUE TITLE
Comunicazione metadata - Comune di Bergamo

### ISSUE THREAD

**Issue by AndreaM-bg** [italia/spid#362]
Buongiorno, 
 si chiede il caricamento del file di metadata per il Comune di Bergamo:

https://territorio.comune.bergamo.it/sites/default/files/spid-metadata/bergamo-signed.xml

Grazie.

**Comment by psmiraglia-agid** [comment]
Salve, i metadata risultano conformi alle specifiche. Il mio collega @AntonioGiovanniSchiavone provvederà alla comunicazione presso gli identity provider.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
