### ISSUE TITLE
Comunicazione nuovi metadati Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#363]
Buonasera
si richiede che vengano verificati e comunicati ai gestori SPID i nuovi metadati della Regione Puglia scaricabili da [https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml) 

Saluti
Marcello Marangio 
InnovaPuglia S.p.A.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 

l'hash della firma (Signature) del metadata non combacia con il contenuto del documento. Si prega di rifirmare il documento

**Comment by marangiom** [comment]
salve.
Il file è firmato correttamente, verificato con lo stesso tool con cui lo firmiamo xmlsectool-2.0.0:

./xmlsectool.sh --verifySignature --inFile ServiceProviderRegionePuglia-signed-20180613.xml --certificate star.rupar.puglia.it.cer
INFO  XMLSecTool - Reading XML document from file 'ServiceProviderRegionePuglia-signed-20180613.xml'
INFO  XMLSecTool - XML document parsed and is well-formed.
INFO  XMLSecTool - XML document signature verified.

Con che strumento lo verificate?

**Comment by psmiraglia-agid** [comment]
Provate ad utilizzare il comando `xmlsec1` come indicato di seguito

```.bash
$ xmlsec1 --verify --insecure --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor metadata.xml
```

Questo e' l'output che otteniamo

```
func=xmlSecOpenSSLEvpDigestVerify:file=digests.c:line=274:obj=sha256:subj=unknown:error=12:invalid data:data and digest do not match
FAIL
SignedInfo References (ok/all): 0/1
Manifests References (ok/all): 0/0
Error: failed to verify file "metadata.xml"
```

Verificate per favore che il file risultante dall'applicazione della firma sia esattamente lo stesso file che e' stato pubblicato. Potete utilizzare strumenti come `sha1-sum` o simili.

**Comment by psmiraglia-agid** [comment]
Colgo l'occasione per segnalare un warning nel vostro metadata. In particolare, riguarda l'ordine degli elementi figli di `<SPSSODescriptor>`. Secondo lo schema ufficiale, l'ordine esatto dovrebbe essere

1. `KeyDescriptor`
2. `SingleLogoutService`
3. `NameIDFormat`
4. `AssertionConsumerService`
5. `AttributeConsumingService`

mentre nel vostro metadata avete

1. `KeyDescriptor`
2. `NameIDFormat`
3. `SingleLogoutService`
4. `AssertionConsumerService`
5. `AttributeConsumingService`

Per verificare autonomamente la cosa, scaricate il file [XSD dei metadata SAML](https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd) ed eseguite il seguente comando

```.bash
xmllint --noout --schema saml-schema-metadata-2.0.xsd metadata.xsd
```

Senza modifiche ai metadata, dovreste ottenere il seguente errore

```
metadata.xml:461: element SingleLogoutService: Schemas validity error : Element '{urn:oasis:names:tc:SAML:2.0:metadata}SingleLogoutService': This element is not expected. Expected is one of ( {urn:oasis:names:tc:SAML:2.0:metadata}NameIDFormat, {urn:oasis:names:tc:SAML:2.0:metadata}AssertionConsumerService ).
metadata.xml fails to validate
```

In alternativa, potete andare su [questo sito](https://www.samltool.com/validate_xml.php) ed effettuare li la validazione. Incollando il vostro metadata e selezionando "Metadata" fra gli XSD disponibili, otterrete lo stesso risultato.

**Comment by marangiom** [comment]
Salve
ho corretto il warning; potete trovare il risultato su [https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml).
Per quanto riguarda l'errore della firma, non sono riuscito a compilare su osx il codice di xmlsec1 (mi dice che manca /usr/lib/system/libsystem_containermanager.dylib)
Noto però che questo tool è scaricabile dal sito www.aleksey.com  e a suo tempo avemmo problemi nella validazione dei metadata online su questo sito, in quanto, sebbene dichiari di supportarlo, sembra avere problemi con il tag <ds:Reference URI="#XYZ">.
qui [https://spid.rupar.puglia.it/ServiceProviderRegionePuglia-signed-noref-2180620.xml](https://spid.rupar.puglia.it/ServiceProviderRegionePuglia-signed-noref-2180620.xml) potete scaricare i metadati della regione puglia firmati senza l'indicazione del Reference, e il tool online su aleksey.com lo valida.
In passato, inoltre, abbiamo avuto lo stesso problema e Umberto Rosini ci comunicò che sembra esserci un problema col certificato utilizzato per la firma, che non è un selfsigned ma è un regolare certificato della Comodo; essendo di fatto un falso problema i nostri metadati sono sempre stati accettati e pubblicati.

Come possiamo sbloccare la situazione?
Grazie

**Comment by marangiom** [comment]
Aggiornamento:
ho compilato xmlsec1 v 1.2.26 e l'xml viene validato:

 wget https://spid.rupar.puglia.it/regione-puglia-metadata.xml
--2018-06-20 11:08:03--  https://spid.rupar.puglia.it/regione-puglia-metadata.xml
Risoluzione di spid.rupar.puglia.it (spid.rupar.puglia.it)... 138.66.39.220
Connessione a spid.rupar.puglia.it (spid.rupar.puglia.it)|138.66.39.220|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 42865 (42K) [text/xml]
Salvataggio in: "regione-puglia-metadata.xml.4"

regione-puglia-metadata.xml.4                              100%[=======================================================================================================================================>]  41,86K  --.-KB/s   in 0,005s

2018-06-20 11:08:04 (8,03 MB/s) - "regione-puglia-metadata.xml.4" salvato [42865/42865]

MacBook-Pro-di-marangio-mac:xmlsectool-2.0.0 marangio$ xmlsec1 --verify --insecure --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor regione-puglia-metadata.xml
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0

Quindi richiedo che i metadati vengano deployati.
grazie
saluti

**Comment by marangiom** [comment]
aggiornamento:
ho compilato xmlsec1 v 1.2.26 e i nostri metadati sono stati validati
MacBook-Pro-di-marangio-mac:xmlsectool-2.0.0 marangio$ wget https://spid.rupar.puglia.it/regione-puglia-metadata.xml
--2018-06-20 11:11:02--  https://spid.rupar.puglia.it/regione-puglia-metadata.xml
Risoluzione di spid.rupar.puglia.it (spid.rupar.puglia.it)... 138.66.39.220
Connessione a spid.rupar.puglia.it (spid.rupar.puglia.it)|138.66.39.220|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 42865 (42K) [text/xml]
Salvataggio in: "regione-puglia-metadata.xml.5"

regione-puglia-metadata.xml.5                              100%[=======================================================================================================================================>]  41,86K  --.-KB/s   in 0,003s

2018-06-20 11:11:02 (12,9 MB/s) - "regione-puglia-metadata.xml.5" salvato [42865/42865]

MacBook-Pro-di-marangio-mac:xmlsectool-2.0.0 marangio$ xmlsec1 --verify --insecure --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor regione-puglia-metadata.xml.5
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0

Richiedo quindi che vengano deployati presso i gestori.
grazie
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
