### ISSUE TITLE
Richiesta controllo metadata - Comune di Puegnago del Garda

### ISSUE THREAD

**Issue by globogis** [italia/spid#364]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://suap.puegnagodelgarda.bs.it/simplesaml/module.php/saml/sp/metadata.php/puegnagodelgarda

**Comment by psmiraglia-agid** [comment]
Salve, il metadata risulta conforme alle specifiche. Il mio collega @AntonioGiovanniSchiavone procederà con la comunicazione presso gli identity provider.

**NOTA:** A giudicare dal contenuto ottenuto dai seguenti endpoint, sembra che la modalità debug sia abilitata. Una volta messo in produzione, questa dovrebbe essere disabilitata.

*  https://suap.puegnagodelgarda.bs.it/simplesaml/module.php/saml/sp/saml2-logout.php/puegnagodelgarda
*  https://suap.puegnagodelgarda.bs.it/simplesaml/module.php/saml/sp/saml2-acs.php/puegnagodelgarda

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
