### ISSUE TITLE
Richiesta controllo metadata - Comune di Stezzano

### ISSUE THREAD

**Issue by globogis** [italia/spid#365]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.stezzano.bg.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by psmiraglia-agid** [comment]
Salve, anche se non previsto dalle specifiche tecniche, l'attributo `WantAsserionsSigned` dell'elemento `SPSSODescriptor` dovrebbe essere presente e settato a `true`. Si prega di modificare come riportato nell'esempio.

```.xml
<md:SPSSODescriptor
    protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"
    AuthnRequestsSigned="true"
    WantAsserionsSigned="true">
    ...
</md:SPSSODescriptor>
```

Riguardo i seguenti endpoint, pare che sia abilitata la modalità debug. Una volta messo in produzione il sistema, questa dovrebbe essere disabilitata.

* `https://sportellotelematico.comune.stezzano.bg.it/simplesaml/module.php/saml/sp/saml2-logout.php/spid`
* `https://sportellotelematico.comune.stezzano.bg.it/simplesaml/module.php/saml/sp/saml2-acs.php/spid`

**Comment by psmiraglia-agid** [comment]
> Essendo i deploy basati su un sistema automatizzato, modificare questo metadato implicherebbe la modifica di tutti gli altri, con rischio di conseguenti disallineamenti rispetto a quelli deployati. Peraltro riteniamo poco consono basare la mancata validazione su un parametro non previsto dalle specifiche.

La validazione non e' fallita, semplicemente e' stato segnalato un warning. Riguardo l'attributo in questione (`WantAssertionsSigned`) per ora potete lasciare tutto come sta ma, vi suggerisco vivamente di cominciare a pensare ad una strategia per integrarlo.

> Per quanto riguarda il debug, vi chiedo di indicarci che modifiche dobbiamo apportare alle nostre AuthnRequests per evitare che risulti attiva questa modalità.

L'abilitazione della modalita' debug dipende da come e' stato configurato e deployato is sistema (in questo caso SimpleSAML) e non impatta sulla generazione delle AuthnRequest. Dovreste riguardare la configurazione del vostro applicativo.

**Comment by globogis** [comment]
Confermo che a livello di SimpleSAML manteniamo attiva la modalità di debug per far sì che nei log vengano scritte tutte le buste SAML. I log vengono poi conservati in conformità con la normativa, che impone la conservazione delle buste da parte del Service Provider. Siete a conoscenza di soluzioni alternative in merito? In quale modo l'abilitazione della modalità debug impatta sulla fruibilità del servizio?
Grazie

**Comment by globogis** [comment]
Inoltre: l'aggiunta del parametro WantAssertionsSigned valorizzato a true richiederà la rivalidazione di tutti i metadata?

**Comment by psmiraglia-agid** [comment]
> In quale modo l'abilitazione della modalità debug impatta sulla fruibilità del servizio?

Lasciando attiva la modalita' debug, l'applicazione espone al pubblico alcuni dettagli interni (es. path di sistema, versioni di SW, ecc.). Queste informazioni potrebbero essere utilizzate per pianificare un attacco. Anche in questo caso, si tratta di un warning. Se siete certi che le informazioni ottenibili dalle pagine di errore non minano la sicurezza del vostro sistema, lasciate pure tutto come sta.

> Inoltre: l'aggiunta del parametro WantAssertionsSigned valorizzato a true richiederà la rivalidazione di tutti i metadata?

Dipende da come gestite i metadata. A giudicare dai precedenti messaggi, la gestione avviene in maniera centralizzata e modificandone uno, automaticamente vengono modificati tutti gli altri. In questo caso, andrebbero tutti validati nuovamente. Tenete presente che trattandosi di un solo attributo, mi aspetto che la nuova validazione sia un processo abbastanza rapido.

**Comment by globogis** [comment]
> Capisco il problema, ma questa e' una modifica che prima o poi verra' messa nelle specifiche.

Abbiamo in programma di deployare la modifica nella prossima release, possiamo aprire un'unica issue per richiedere la validazione di tutti i servizi una volta fatto?

> Riguardo la modalita' debug, se mi date conferma del fatto che mantenendola attiva non si va a minare la sicurezza del sistema, procediamo con la comunicazione dei vostri metadata agli identity provider.

Confermo che per come è strutturato il sistema non vediamo rischi derivanti dall'esposizione dei percorsi.

Grazie

**Comment by psmiraglia-agid** [comment]
> Abbiamo in programma di deployare la modifica nella prossima release, possiamo aprire un'unica issue per richiedere la validazione di tutti i servizi una volta fatto?

In questo caso, se la modifica riguarda **solo e solamente** i metadata, non credo ci siano problemi.

> Confermo che per come è strutturato il sistema non vediamo rischi derivanti dall'esposizione dei percorsi.

Bene. Il mio collega @AntonioGiovanniSchiavone provvedera' a comunicare i vostri metadata agli identity provider.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
