### ISSUE TITLE
Controllo metadata Comune di Capannori

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#366]
Buongiorno,
Per conto del comune di Capannori, abbiamo predisposto i metadata e pubblicati nella cartella

https://Capannori.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa
 
[metadata_capannori-signed.zip](https://github.com/italia/spid/files/2101713/metadata_capannori-signed.zip)

**Comment by psmiraglia-agid** [comment]
Salve, i metadata risultano essere conformi alle specifiche. Il mio collega @AntonioGiovanniSchiavone provvederà alla comunicazione presso gli identity provider.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
