### ISSUE TITLE
Aggiornamento Metadati Università degli Studi di Messina

### ISSUE THREAD

**Issue by falco76** [italia/spid#368]
salve
si richiede l'aggiornamento dei metadata dell'Università degli Studi di Messina

saluti e buon lavoro

**Comment by psmiraglia-agid** [comment]
Salve @falco76, dove troviamo i vostri metadata?

**Comment by falco76** [comment]
inviata mail a spid.tech@agid.gov.it
ciao

**Comment by psmiraglia-agid** [comment]
Ok grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
L'hash della firma non combacia con il contenuto del documento. Si prega di rifirmare.

**Comment by falco76** [comment]
ho rifirmato il documento, saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
