### ISSUE TITLE
Controllo metadata Comune di Lainate

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#370]
Buongiorno,
Per conto del comune di Lainate, abbiamo predisposto i metadata e pubblicati nella cartella

https://lainate.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_lainate-signed.zip](https://github.com/italia/spid/files/2111345/metadata_lainate-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
