### ISSUE TITLE
Errore verifica asserzione SAML dell'IZSAM verso Spiditalia e Aruba

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#377]
A seguito del rinnovo dei metadati, tutti gli IdP sembrano accettare correttamente le asserzioni di richiesta di autenticazione provenienti dall'istituto Zooprofilattico dell'Abruzzo e del Molise ad eccezione di Aruba e Spiditalia.

Non ottenendo indietro alcun codice d'errore, come posso individuare il problema? Inoltre, come posso essere certo che questi 2 IdP abbiano ricaricato correttamente i nostri metadati?

Grazie anticipatamente per il supporto

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Come indicato a pag. 9 delle [Regole tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf), all'interno della AuthnRequest l'elemento NameIDPolicy deve possedere l'attibuto Format valorizzato a “_urn:oasis:names:tc:SAML:2.0:nameid-format:transient_”. 

Nelle vostre AuthnRequest verso Aruba tale attibuto è incorrettamente valorizzato a "_urn:oasis:names:tc:SAML:**2.1**:nameid-format:transient_" 

Sempre nella stessa pagina, è inoltre chiaramente indicato che non deve essere presente l'attributo  IsPassive, che è invece presente nelle vostre AuthnRequest.

**Comment by fmartelli** [comment]
Ho corretto come da voi suggerito e sembrerebbe che il problema con Aruba sia rientrato.
Resta aperto il problema con Spiditalia (Register.it). Di seguito trovate la richiesta di autenticazione inviata.

<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest AssertionConsumerServiceURL="https://sptest.izs.it/cas/login?client_name=register" AttributeConsumingServiceIndex="0" Destination="https://spid.register.it/login/sso" ForceAuthn="true" ID="_oy53l5mx5rkf3lsxlkwpyf6aa5uzbqbal6gfmug" IssueInstant="2018-06-25T15:58:27.858Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" ProviderName="pac4j-saml" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="http://www.izs.it/sp" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">http://www.izs.it/sp</saml2:Issuer><saml2p:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"/><saml2p:RequestedAuthnContext Comparison="minimum" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2:AuthnContextClassRef xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://www.spid.gov.it/SpidL2</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>

**Comment by AntonioGiovanniSchiavone** [comment]
Anche Register.it sembra adesso rispondere correttamente.
