### ISSUE TITLE
Gestione elenco IdP nelle librerie

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid#378]
Salve,

lavoranto su spid-rails ho notato che praticamente tutte le librerie esistenti hanno hardcodato al loro interno un elenco degli Identity Provider al momento esistenti: Aruba, Register, Poste, ecc.

Questo potrebbe diventare un grosso problema il giorno che un nuovo ente dovesse decidere di diventare un nuovo Identity Provider in quanto sarà necessario aggiornare manualmente ogni singola applicazione/libreria che ha questo elenco (ad esempio la libreria spid-rails)

Spulciando sui repository ho trovato questo:

https://github.com/italia/spid-sp-access-button

che risolve parzialmente il problema in quanto nel codice non sono riportati i vari url dei metadata.

Quindi mi chiedo: avrebbe senso creare un repository su github del tipo ``italia/spid-idp-list``` in cui riportare un json in un formato del tipo

```
{
    "posteid": {
      "metadata_url": "http://posteid.poste.it/jod-fs/metadata/metadata.xml",
      "svg_url": "https://raw.githubusercontent.com/italia/spid-idp-list/master/img/spid-idp-posteid.svg",
      "png_url": "https://raw.githubusercontent.com/italia/spid-idp-list/master/img/spid-idp-posteid.png"
    },
    "arubaid": {
      ...
    },
    ...
}
```

In questo modo tramite qualunque linguaggio di programmazione sarebbe possibile, durante il caricamento di una qualunque pagina di un Service Provider o al caricamento del server stesso, dipendente dalla tecnologia utilizzata, con una semplice GET all'indizzo

https://raw.githubusercontent.com/italia/spid-idp-list/master/idp-list.json

avere tutto quello che serve per creare i bottoni e inizializzare tutti i client SAML.

In questo modo si avrebbe un unico collettore di informazione e nel caso di aggiunta di un nuovo IdP o di modifica a qualunque parametro degli esistenti, dover modificare un solo repository e avere tutti i servizi esistenti consistenti.

**Comment by davidlibrera** [comment]
Mi è stato segnalato che esiste questo:

https://registry.spid.gov.it/api/identity-providers

Questa è un'ottima base, ma appunto l'elenco completo delle svg/png non è presente e quello andrebbe continuamente aggiornato singolarmente.

A questo punto la domanda diventa:

è possibile e sensato integrare dentro all'xml sopra riportato anche tutte le immagini (png e svg) in modo di avere tutte queste informazioni 'esterne'?

**Comment by alexrj** [comment]
@davidlibrera stiamo lavorando su questo aspetto. A breve aggiornamenti!
(Chiudo questa issue perché questo issue tracker serve per il supporto tecnico ai Service Provider)

**Comment by davidlibrera** [comment]
https://github.com/italia/spid-smart-button
Questo verrà fornito da CDN, quindi a questo punto non c'è niente di hardcodato nel codice.

Direi che non ha più senso di esistere questa issue
