### ISSUE TITLE
Richiesta controllo metadata Corpo Nazionale Dei Vigili del Fuoco

### ISSUE THREAD

**Issue by VigilfuocoSpid** [italia/spid#379]
-Si richiede il controllo metadata per il Corpo Nazionale dei Vigili del Fuoco
utente VigilfuocoSpid.

**Comment by VigilfuocoSpid** [comment]
Per migliore interpretazione della richiesta, aggiungiamo l'url da cui è possibile prelevare il metadata: https://sso.vigilfuoco.it/spid/metadata-firmato.xml

**Comment by psmiraglia-agid** [comment]
Salve @VigilfuocoSpid,

di seguito i dettagli della validazione. Per qualsiasi chiarimento, non esitate a domandare.

**Errori**

* Nel metadata deve essere presente almeno un elemento `AssertionConsumerService` con attributo `isDefault` settato a `true`.

**Warning**

* Gli elementi `OrganizationName`, `OrganizationURL` e `OrganizationDisplayName` dovrebbero essere localizzati almeno come `it` (`xml:lang="it"`). Nel vostro caso sono `en-US`.

* La configurazione TLS per Il dominio `sso.vigilfuoco.it` ha ottenuto `C` sul test [Qualys SSL Labs](https://www.ssllabs.com/ssltest/). Dovreste fare in modo di ottenere almeno `A`.

**Comment by AntonioGiovanniSchiavone** [comment]
Chiuso nella [Issue #434](https://github.com/italia/spid/issues/434)
