### ISSUE TITLE
Richiesta di validazione e deploy metadati - Comune di Cilavegna

### ISSUE THREAD

**Issue by globogis** [italia/spid#38]
Buongiorno,
si richiede la verifica e il deploy dei metadati per conto del Comune di Cilavegna:
```
https://www.suaplomellina.info/simplesaml/module.php/saml/sp/metadata.php/suaplomellina
```

Si tratta di uno Sportello conforme a quelli già precedentemente validati da GLOBO.

Grazie

**Comment by umbros** [comment]
@globogis implementazione verificata con successo.
@AntonioGiovanniSchiavone puoi procedere all'invio della convenzione.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP.

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.

**Comment by AntonioGiovanniSchiavone** [comment]
Convenzione firmata AgID e procedura di adesione conclusa.
