### ISSUE TITLE
Controllo metadata Comune di Napoli

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#382]
Buongiorno,
Per conto del comune di Napoli, abbiamo predisposto i metadata e pubblicati nella cartella

https://refezionenapoli.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli spa

**Comment by psmiraglia-agid** [comment]
Salve @sfacondini, potreste verificare la configurazione NGINX. Otteniamo un `504 Gateway Timeout`.

**Comment by sfacondini** [comment]
Buon pomeriggio, 
mi hanno appena informato che il server di Napoli  - servizi a domanda individuale è stato oggetto di manutenzione proprio nelle ultime ore;  adesso è correttamente raggiungibile.
Ci scusiamo per il disguido

Cordiali Saluti
Facondini Stefano 
Maggioli spa

**Comment by psmiraglia-agid** [comment]
La validazione dei metadata ha prodotto un esito positivo eccetto un warning sulla configurazione del TLS per i seguenti domini

```
[B] AssertionConsumerService, https://spid.comune-online.it/AuthServiceSPID/saml/SSO/alias/napoli
[B] AssertionConsumerService, https://spid.comune-online.it/AuthServiceSPID/saml/SSO/alias/napoli
[B] AssertionConsumerService, https://spid.comune-online.it/AuthServiceSPID/saml/SSO/alias/napoli
[B] SingleLogoutService, https://spid.comune-online.it/AuthServiceSPID/saml/SingleLogout/alias/napoli
```

Il valore ottenuto e' `B` ma si dovrebbe ottenere almeno una `A`. Il test eseguito e' [Qualys SSL Labs](https://www.ssllabs.com/ssltest).

**Comment by sfacondini** [comment]
Buon pomeriggio, 
stiamo provvedendo ad aggiornare la configurazione  TSL del server spid.comune.online.it  già oggetto di precedenti segnalazioni  
a breve contiamo di portalo a livello "A" stiamo eliminando  gli algoritmi di cifratura considerati weak 
Cordiali Saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per la P.A. di oggetto.
Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).

**Comment by sfacondini** [comment]
Buon pomeriggio, 
abbiamo iniziato le procedure di integrazione tra i nostri metadata e quelli già esistenti.
Noto che nei metadata attuali  è indicato
AssertionConsumerService   con Index =0 
e
AttributeConsumingService index="1" 

è corretto?
cordiali saluti

Facondini Stefano 
Maggioli spa

**Comment by sfacondini** [comment]
Buon pomeriggio, 
abbiamo aggiornato i metadata accodando i nostri servizi agli esistenti e rispettando l'entityID
i nuovi metedata sono pubblicati nella cartella

https://refezionenapoli.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa

[metadata_napoli2SP-signed.zip](https://github.com/italia/spid/files/2145889/metadata_napoli2SP-signed.zip)

**Comment by psmiraglia-agid** [comment]
Salve @sfacondini, sembra che la firma del metadata disponibile all'indirizzo https://refezionenapoli.it/serviziSPID/metadata.xml non sia valida. Lo stesso risultato lo otteniamo verificando il metadata presente nello ZIP allegato.

```
$ xmlsec1 --verify --insecure --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor ./napoli/sp-metadata.xml
func=xmlSecOpenSSLEvpDigestVerify:file=/usr/src/ports/xmlsec1/xmlsec1-1.2.24-1.x86_64/src/xmlsec1-1.2.24/src/openssl/digests.c:line=274:obj=sha256:subj=unknown:error=12:invalid data:data and digest do not match
FAIL
SignedInfo References (ok/all): 0/1
Manifests References (ok/all): 0/0
Error: failed to verify file "./napoli/sp-metadata.xml"
```

**Comment by sfacondini** [comment]
Buongiorno 
abbiamo rifirmato  ex novo i metadata,  sono pubblicati  sulla cartella precedentemente indicata

https://refezionenapoli.it/serviziSPID/metadata.xml

la firma è emessa in modo autoamatico e ha le stesse caratteristiche delle firma poste sui metadata precedentemente inviati:  firma  con certificato autoemesso  di autenticazione.

cordiali saluti
Facondini Stefano 
Maggioli spa
[metadata_napoli2SP-signed.zip](https://github.com/italia/spid/files/2148132/metadata_napoli2SP-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by sfacondini** [comment]
buon pomeriggio,
i metadata aggiornati risultano acquisiti da tutti gli IDP salvo Intesa e Register.it

cordiali Saluti
Facondini Stefano 
Maggioli spa
