### ISSUE TITLE
Aggiornamento dei metadati - Università degli Studi di Salerno

### ISSUE THREAD

**Issue by aspar** [italia/spid#383]
Buongiorno, si richiede l'aggiornamento dei metadati associati all'ente per la modifica degli attributi richiesti ai provider.

https://auth.unisa.it/spid/metadata/metadata.xml

Saluti
Alfonso Sparano

**Comment by psmiraglia-agid** [comment]
Salve @aspar, la validazione dei metadata ha prodotto un warning. Per chiarimenti, non esitate a contattarci.

**Warning**

*   L'attributo `WantAssertionsSigned` dell'elemento `SPSSODescriptor` dovrebbe essere presente e settato a `true`.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
