### ISSUE TITLE
Richiesta controllo metadati - Agenzia Regionale per il Diritto allo Studio Universitario, Puglia

### ISSUE THREAD

**Issue by massimoianigro** [italia/spid#386]
buongiorno,

con la presente si richiede cortesemente la verifica dei metadati disponibili all'URL:

https://saml.adisupuglia.it/saml/module.php/saml/sp/metadata.php/spdsu

propedeutica all'attivazione di un Service Provider per l'ADISU Puglia.

cordiali saluti,

massimo ianigro

**Comment by psmiraglia-agid** [comment]
Salve @massimoianigro, la validazione dei metadata ha prodotto un errore e alcuni warning. Per qualsiasi chiarimento, non esitate a contattarci

**Error**

*   Uno degli elementi `AssertionConsumerService` deve essere dichiarato come default, settando l'attributo `isDefault` a `true`

**Warning**

*   L'elemento `OrganizationDisplayName` dovrebbe essere localizzato almeno come `it` ma risulta essere solo `en`.

*   L'attributo `WantAssertionsSigned` di `SPSSODescriptor` dovrebbe essere presente e settato a `true`

*   L'elemento `ServiceName` dovrebbe essere presente una sola volta e senza localizzazione

*   I domini di cui sotto hanno una configurazione TLS che ha ottenuto `B` sul test [Qualys SSL Labs](https://www.ssllabs.com/ssltest/). Dovreste ottenere almeno `A`
    ```
    [B] AssertionConsumerService, https://saml.adisupuglia.it/saml/module.php/saml/sp/saml2-acs.php/spdsu
    [B] SingleLogoutService, https://saml.adisupuglia.it/saml/module.php/saml/sp/saml2-logout.php/spdsu
    ```

**Comment by massimoianigro** [comment]
salve @psmiraglia-agid @AntonioGiovanniSchiavone ,
il test su Qualys ora mostra un grade A su saml.adisupuglia.it e sia i warning che gli error sono stati affrontati.
Per cortesia potete verificare ?
grazie
cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Nell'elemento RequestedAttribute l'attributo isRequired non è previsto dal regolamento tecnico Spid e va rimosso.
Analogamente, non è previsto l'elemento ContactPerson  e va rimosso.

**Comment by massimoianigro** [comment]
Buongiorno @AntonioGiovanniSchiavone ,
ho rimosso l'attributo e gli elementi in questione.
cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
