### ISSUE TITLE
Richiesta validazione e caricamento metadata Comune di Torino

### ISSUE THREAD

**Issue by alfonsinaarena** [italia/spid#388]
Buongiorno,
si richiede la verifica e la validazione del metatdata del Comune di Torino per l'integrazione con SPID.

E' stato aggiunto un indice per il recupero di ulteriori attributi, come richiesto dal Comune di Torino.

Il metadata è pubblicato al seguente indirizzo:
https://www.spid.piemonte.it/spid/prod/metadata/metadata_service_provider_comunetorino_spid.xml

Il file metadata è pubblicato sul sito https://www.spid.piemonte.it, gestito dal CSI Piemonte, essendo il CSI Piemonte intermediario tecnologico come indicato nella convenzione SPID della Città di Torino.

Grazie e buona giornata,
Alfonsina

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
