### ISSUE TITLE
Richiesta verifica tecnica e convenzione per ASL Roma 4

### ISSUE THREAD

**Issue by aslroma4** [italia/spid#391]
L’ASL Roma 4 richiede ad AgID lo stato della verifica tecnica finale sull'implementazione di SPID 
richiesta in data 20/6/2018 (url del metadata precedentemente approvato: 
https://certificativaccinali.aslroma4.it/spid/wp-content/plugins/wp-spid-italia/lib/www/module.php/saml/sp/metadata.php/default-sp 
url relative al servizio da validare : https://certificativaccinali.aslroma4.it/spidAuth ), 
la ricezione della convenzione nel formato Pdf ed il file in formato Ods per la compilazione dei servizi attivi

**Comment by damikael** [comment]
Salve,
si chiede di comunicarci l'indirizzo email al quale inviare l'esito della verifica tecnica.

Distinti saluti

**Comment by theorematica** [comment]
Salve,

l'indirizzo mail è n.quattrini@theorematica.it

Grazie

**Comment by damikael** [comment]
Salve,
l'esito della verifica tecnica è stato inviato all'indirizzo email indicato.
Nel caso in cui l'esito sia stato positivo, si può procedere con l'invio della documentazione per il completamento della procedura amministrativa. 
Nel caso, invece, l'esito sia stato negativo, si prega di correggere le non conformità e aprire una nuova issue per richiedere nuovamente la verifica.

Distinti saluti.
