### ISSUE TITLE
Richiesta controllo metadata - Comune di Sorisole (BG)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#392]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:
https://www.comune.sorisole.bg.it/c016202/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
