### ISSUE TITLE
Richiesta validazione metadati - Ospedali Riuniti di Ancona

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#394]
Salve, si richiede la validazione dei metadatai di cui alla URL seguente allo scopo di abilitare gli Ospedali Riuniti di Ancona come fornitori di servizi SPID.

https://www.ospedaliriuniti.marche.it/cas/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il metadata inviato presenta i seguenti errori:

1) l'elemento EntityDescriptor  deve possdere l'attributo ID, di [tipo NCName](http://www.datypic.com/sc/xsd/t-xsd_NCName.html) 

2) Va rimosso l'elemento NameIDFormat valorizzato con la stringa "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"

**Comment by fmartelli** [comment]
Ho corretto e ripubblicato. Fatemi sapere se ci son altri problemi.
Grazie e buona giornata.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
