### ISSUE TITLE
Verifica Metadata

### ISSUE THREAD

**Issue by fattanasio80** [italia/spid#396]
Si richiede la validazione del metadata pubblicato all'indirizzo http://www.comune.baronissi.sa.it/metadata.xml, già precedentemente validato con  Issue #280. 
Richiedo la validazione causa aggiornamento del certificato.
Il metadata è stato inviato anche trami mail spid.tech@agid.gov.it
Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
