### ISSUE TITLE
richiesta aggiornamento metadata Provincia autonoma di Trento

### ISSUE THREAD

**Issue by italodellanoce** [italia/spid#398]
chiedo di comunicare agli idp che abbiamo aggiunto un nuovo servizio on line
il servizio si chiama: 
"ACOP (Autorizz. Concessioni Ordinanze Pubblicità) online per la gestione front-back office interventi suolo pubblico"

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
