### ISSUE TITLE
Richiesta verifica metadata Corpo nazionale Vigili del Fuoco

### ISSUE THREAD

**Issue by VigilfuocoSpid** [italia/spid#399]
A seguito dei vostri consigli per la validazione del metadata sono state apportate le relative modifiche.
Si chiede gentilmente di ri-verificare la correttezza dell'xml e si invia l'url relativo per l'accesso:
https://sso.vigilfuoco.it/spid/metadata-firmato.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Chiuso nella [Issue #434](https://github.com/italia/spid/issues/434)
