### ISSUE TITLE
Metadata Comune di Calenzano

### ISSUE THREAD

**Issue by umbros** [italia/spid#4]
_Aggiunta per conto di GloboGis_ (pervenuta via email senza issue)

Buongiorno,

come da accordi presi telefonicamente con Umberto Rosini, vi trasmetto l’URL dei metadati aggiornati per il Comune di Calenzano, di cui si richiede il deploy

Grazie

**Comment by globogis** [comment]
Buongiorno,
vi confermo di aver aggiornato i metadati secondo le indicazioni ricevute via e-mail, e mi scuso se non ho aperto per tempo una issue in merito.

I metadati aggiornati sono disponibili all'indirizzo: https://sportellotelematico.comune.calenzano.fi.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e verrà caricanto entro le ore 15.
