### ISSUE TITLE
Aggiornamento metadata - Guardia di Finanza

### ISSUE THREAD

**Issue by servinfogdf** [italia/spid#404]
Si comunica l'avvenuto aggiornamento dei metadata all'URL https://spid.gdf.gov.it/metadata, per prossima scadenza del certificato di firma.
Alla ricezione della comunicazione di validazione degli stessi e di avvenuta comunicazione ai provider di identità, si provvederà a rendere esecutivo l'aggiornamento sui sistemi di produzione del Corpo.

Si ringrazia e si rimane in attesa di cortese riscontro
Comando Generale della Guardia di Finanza - Servizio Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
