### ISSUE TITLE
Controllo metadata Comune di Pero

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#405]
Buongiorno,
Per conto del comune di Pero, abbiamo predisposto i metadata e pubblicati nella cartella

https://pero.comune-online.it/serviziSPID/metatada.xml 

questi metadata sono frutto dell'accodamento a precedenti metadata 
e sono stati predisposti salvaguardando entityId e precedenti certificati ed endpoint
cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera,

Alcuni elementi KeyDescriptor non sono stati correttamente chiusi.

**Comment by sfacondini** [comment]
buon pomeriggio, 
abbiamo provveduto a correggere l'anomalia
i nuovi metadata sono pubblicati all'URL (non è cambiata)
https://pero.comune-online.it/serviziSPID/metadata.xml


cordiali saluti
[metadata_pero2sp-signed.zip](https://github.com/italia/spid/files/2188529/metadata_pero2sp-signed.zip)

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
