### ISSUE TITLE
Controllo metadata Comune di Abbiategrasso

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#412]
Buongiorno,
Per conto del comune di Abbiategrasso, abbiamo predisposto i metadata e pubblicati nella cartella

https://abbiategrasso.comune-online.it/serviziSPID/metadata.xml
[metadata_abbiategrasso-signed.zip](https://github.com/italia/spid/files/2188570/metadata_abbiategrasso-signed.zip)

cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
