### ISSUE TITLE
UniME - Infocert espone autenticazione livello 1

### ISSUE THREAD

**Issue by falco76** [italia/spid#415]
salve
per l'SP dell'Università di Messina infocert ci espone una autenticazione di livello 1 in luogo di una autenticazione livello 2 

gli altri idp erogano correttamente un livello 2
il problema si è presentato qualche settimana fa, prima funzionava correttamente

saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 
Potete indicarci la url del servizio in questione?

**Comment by falco76** [comment]
https://incentivodocenza.unime.it/auth/login_spid
saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

L'IdP in questione sta erroneamente mostrando il logo relativo all'identificazione di livello 1 anche agli SP che richiedono l'autorizzazione di Livello 2. Il problema sembra essere limitato alla UX, ma tentando di accedere al servizio vengono correttamente richieste le credenziali di livello 2 (password + OTP). 
Segnaleremo comunque l'anomalia.
