### ISSUE TITLE
Errore di interazione con IdP InfoCert - Comune di Roncadelle

### ISSUE THREAD

**Issue by globogis** [italia/spid#419]
Buongiorno,
si verifica un errore nell'interazione fra il servizio https://suap.comune.roncadelle.bs.it e l'Identity Provider InfoCert. Il messaggio restituito è:
```
Si è verificato un errore
Formato richiesta non corretto. Contattare il gestore del servizio.
```
La nostra implementazione è conforme agli altri Portali realizzati da GLOBO, credo quindi ci sia stato un problema nel deploy dei metadati: https://suap.comune.roncadelle.bs.it/simplesaml/module.php/saml/sp/metadata.php/roncadelle

Si richiede cortesemente una verifica in merito e, se necessario, un nuovo deploy presso l'IdP.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Il problema è stato corretto ed il servizio è adesso operativo con tutti gli Identity Provider
