### ISSUE TITLE
Richiesta aggiornamento metadati Comune di Bari

### ISSUE THREAD

**Issue by Gianluke** [italia/spid#425]
Buongiorno,
in seguito all'aggiunta di un nuovo ACS, è richiesta la verifica ed aggiornamento dei metadati relativi al Service Provider Comune di Bari.

I metadati sono raggiungibili all'indirizzo: https://www.comune.bari.it/sp/metadata.xml

Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
