### ISSUE TITLE
Comunicazione metadata Comune di Sanluri

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#426]
Salve,
Chiediamo la validazione dei metadata per il Comune di Sanluri

Come da istruzioni, comunichiamo l'url tramite email a spid.tech@agid.gov.it

cordiali saluti,

**Comment by dgpadev** [comment]
Salve,
Abbiamo aggiornato il metadata correggendo l'imprecione sulla localizzazione.

Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è  stato inoltrato verso gli IdP e da essi caricato.
