### ISSUE TITLE
Problemi con IdP Intesa

### ISSUE THREAD

**Issue by theorematica** [italia/spid#427]
Si segnala problema su IdP Intesa sul sito https://certificativaccinali.aslroma4.it/spidAuth 
Tutti gli altri IdP funzionano. 
Impossibile stabilire l'autenticità  della richiesta di autenticazione - Contattare il gestore del servizio
description Access to the specified resource has been forbidden. 

url del metadata precedentemente approvato:
https://certificativaccinali.aslroma4.it/spid/wp-content/plugins/wp-spid-italia/lib/www/module.php/saml/sp/metadata.php/default-sp

**Comment by AntonioGiovanniSchiavone** [comment]
L'IdP in questione adesso risponde correttamente alle AuthnRequest.

**Comment by theorematica** [comment]
Confermo la risoluzione della problematica.



Grazie.



*Da:* Antonio Giovanni Schiavone [mailto:notifications@github.com]
*Inviato:* venerdì 20 luglio 2018 16:00
*A:* italia/spid
*Cc:* theorematica; Author
*Oggetto:* Re: [italia/spid] Problemi con IdP Intesa (#427)



L'IdP in questione adesso risponde correttamente alle AuthnRequest.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/italia/spid/issues/427#issuecomment-406609074>, or mute
the thread
