### ISSUE TITLE
Errore di accesso - Tutti gli IdP - Comunità Montana Valtellina di Sondrio

### ISSUE THREAD

**Issue by globogis** [italia/spid#428]
Buongiorno,
i servizi precedentemente attivi per la Comunità Montana Valtellina di Sondrio hanno improvvisamente cessato di funzionare con tutti gli IdP.

I metadati sono esposti all'endpoint non variato https://www.pst.so.it/simplesaml/module.php/saml/sp/metadata.php/sondriotirano

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il servizio risulta adesso operativo con tutti gli IdP
