### ISSUE TITLE
Richiesta aggiornamento metadata Provincia autonoma di Trento

### ISSUE THREAD

**Issue by uffinformaticapat** [italia/spid#429]
Buongiorno, 
chiedo di comunicare agli idp che abbiamo aggiunto un nuovo servizio on line.
Il servizio si chiama:
"Comunica gli alloggi turistici che offri in affitto"

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
