### ISSUE TITLE
Regione Molise: Aggiornamento certificato in data 19/07

### ISSUE THREAD

**Issue by alaurenza** [italia/spid#431]
Gent.Le,

La Regione Molise ha installato un nuovo certificato digitale essendo il precedente scaduto il 19 Luglio . Abbiamo effettuato un aggiornamento del file metadata esposto all’url
https://spid.regione.molise.it/metadata.xml

Si chiede cortesemente il rideploy del file per consentire la fruizione dei servizi SPID
Grazie
Antonio

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
