### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Fiumicino (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#432]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Fiumicino:

http://www.comune.fiumicino.rm.gov.it/index.php/it/allegati-generici/1579-spid-padigitale-agid/file

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

si prega di inviare una mail a: spid.tech@agid.gov.it per discutere alcuni aspetti tecnici della richiesta.

**Comment by wecomsrl** [comment]
Salve,

come richiesto, abbiamo inviato e-mail all'indirizzo spid.tech@agid.gov.it ma non abbiamo ancora ricevuto risposta. Normalmente quali sono le tempistiche?

Grazie per la disponibilità

**Comment by AntonioGiovanniSchiavone** [comment]
Si chiude per integrazione nella [Issue 490](https://github.com/italia/spid/issues/490).
