### ISSUE TITLE
Comunicazione metadata Comune di Grottaglie

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#433]
Salve,
Chiediamo la validazione dei metadata per il Comune di Grottaglie
		
Come da istruzioni, comunichiamo l'url tramite email a spid.tech@agid.gov.it

cordiali saluti,
Datagraph SRL

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
