### ISSUE TITLE
Verifica metadata Edisu Piemonte

### ISSUE THREAD

**Issue by andreacalio** [italia/spid#435]
Buongiorno,
si richiede la verifica dei metadati per Edisu Piemonte:
[https://clio.edisu-piemonte.it/spid-auth-web/metadata](url)

grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, alla url indicata si ottiene un errore HTTP 502

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

1) Nel corso dei vari aggiornamenti del metadata è necessario mantenere costante il valore dell'EntityID comunicato nel primo metadata. Dai nostri sistemi risulta che l'entityID precedentemente indicato è entityID="https://clio.edisu-piemonte.it". Si prega di modificare il metadata ripristinando il valore precedentemente definito. 

2) L'hash della firma non combacia con il contenuto del metadata. Sull'account github dell'iniziativa Developers Italia è stato pubblicato un [tool per la firma dei metadata per i sistemi operativi Linux e OSX : ](https://github.com/italia/spid-metadata-signer). Vi segnaliamo inoltre che alcuni Service Provider hanno utilizzato con successo un porting del citato [tool per la piattaforma Windows sviluppato da terzi]( https://github.com/ermannog/SPID-Metadata-Signer-Windows)

2)

**Comment by andreacalio** [comment]
Buongiorno,
può verificare se le modifiche  che ci ha chiesto di fare ora vanno bene?
grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by andreacalio** [comment]
fatto

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
