### ISSUE TITLE
CINECA - Modalità di adesione a SPID come fornitore di servizi

### ISSUE THREAD

**Issue by angelorossini** [italia/spid#436]
Buonasera,

mi chiamo Angelo Rossini e vi scrivo per conto del Consorzio Interuniversitario CINECA.

CINECA è un Consorzio Interuniversitario senza scopo di lucro al servizio del sistema accademico nazionale; ad oggi i consorziati sono 67 Università Italiane, 9 Enti di Ricerca Nazionali e il Ministero dell’Istruzione, dell’Università e della Ricerca, di seguito denominato MIUR.

CINECA ha personalità giuridica di diritto privato ed è sottoposto alla vigilanza del MIUR.

CINECA oltre ad erogare servizi per le PA e per gli Atenei consorziati eroga per conto proprio i servizi BESTR (https://bestr.it/) e Cineca Academy (https://learn.cineca.it/) utilizzabili gratuitamente dai cittadini.

CINECA è iscritto al registro IPA in qualità di Gestore di Pubblici Servizi con codice "cci".

Considerate le precedenti caratteristiche Vi chiedo se CINECA può erogare i servizi indicati come fornitore di servizi Pubblici senza dover quindi sostenere gli oneri previsti per i fornitore di servizi Privati.

Attendiamo indicazioni.

Cordiali saluti,

Angelo Rossini.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Le caratteristiche del sistema pubblico per la gestione dell'identita' digitale di cittadini e imprese (SPID) sono definite dal [DPCM 24 ottobre 2014](https://www.agid.gov.it/sites/default/files/repository_files/leggi_decreti_direttive/dpcm_24_ottobre_2014a.pdf).

All'Art. 14 comma 2 di tale decreto si stabilisce  che 

      "Ai fini del comma 1, le pubbliche amministrazioni di cui all'art. 2, comma 2, del CAD aderiscono allo SPID, secondo le modalità' stabilite dall'Agenzia [omissis]".

L'ultima versione del CAD all'art. 2, comma 2 stabilisce  che 

       "Le disposizioni del presente Codice si applicano:

              a) alle pubbliche amministrazioni di cui all'articolo 1, comma 2, del decreto legislativo 30 marzo 2001, n. 165, nel rispetto del riparto di competenza di cui all'articolo 117 della Costituzione, ivi comprese le autorita' di sistema portuale, nonche' alle autorita' amministrative indipendenti di garanzia, vigilanza e regolazione;

              b) ai gestori di servizi pubblici, ivi comprese le societa' quotate, in relazione ai servizi di pubblico interesse;

              c) alle societa' a controllo pubblico, come definite nel decreto legislativo 19 agosto 2016, n. 175, escluse le societa' quotate di cui all'articolo 2, comma 1, lettera p), del medesimo decreto che non rientrino nella categoria di cui alla lettera b)."

Alla luce di quanto sopra citato, riteniamo che il CINECA, in qualità di Gestore di Pubblici Servizi, rientri nel novero dei soggetti individuati dall'Art. 14 comma 2 del DPCM 24 ottobre 2014, e che quindi per esso valga quanto stabilito dal comma 5 dello stesso articolo:

               "Le pubbliche amministrazioni, in qualità' di fornitori dei servizi, usufruiscono gratuitamente delle verifiche rese disponibili dai gestori di identità' digitali e dai gestori di attributi qualificati. [omissis]."
