### ISSUE TITLE
Controllo metadata Comune di Bellaria Igea Marina

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#438]
Buongiorno,
Per conto del comune di Bellaria Igea Marina , abbiamo predisposto i metadata e pubblicati nella cartella

https://bellariaigeamarina.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_bellaria-signed.zip](https://github.com/italia/spid/files/2231132/metadata_bellaria-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
