### ISSUE TITLE
Aggiornamento metadata Cittadinanza Digitale

### ISSUE THREAD

**Issue by gunzip** [italia/spid#439]
Ciao, avremmo bisogno di aggiornare i metadata per l'applicazione "Digital citizenship proxy"
(abbiamo aggiunto il numero di telefono agli attributi richiesti):

https://app-backend.k8s.test.cd.teamdigitale.it/metadata

**Comment by umbros** [comment]
Ciao @cloudify, gli IdP hanno tempi di caricamento prefissati e l'operazione non è in realtime, quindi in eventuali modifiche dell'SP dovranno essere calcolati tempi morti. Una gestione più veloce dei metadata si avrà con l'ambiente di gestione sp e la messa a disposizione di una CA per la generazione di certificati. Il metadata è andato in caricamento.

Umberto Rosini
Agenia pdf l'Italia Digitale

**Comment by cloudify** [comment]
Ciao @umbros per "tempi morti" intendi downtime? è possibile avere una situazione in cui il nuovo metadata e' in caricamento ma il vecchio e' ancora funzionante per evitare downtime del servizio?

**Comment by cloudify** [comment]
eh si eh, 6 ore di downtime sono tante
