### ISSUE TITLE
Aggiornamento metadata - Comune di Busca

### ISSUE THREAD

**Issue by falbesano** [italia/spid#440]
Buongiorno,
per conto del Comune di Busca, richiediamo l'aggiornamento dei metadata per l'inserimento di un nuovo SP.
Il metadata è pubblicato all'indirizzo:
https://www.comune.busca.cn.it/uploads/5b596de6d089c_metadata.xml

Sono stati mantenuti l'entityID e gli AssertionConsumerService, AttributeConsumingService e SingleLogoutService con i relativi indici e certificati di firma che erano presenti nei metadata precedenti.
L'SP aggiunto è già attivo per diversi altri Enti, tra cui i comuni di Cuneo e Mondovì.

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
