### ISSUE TITLE
Mancata acquisizione metadata  Comune di Bellaria da IDP Register.it

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#445]
Buongiorno, 
a seguito del dispiegamento dei metadata sono stati condotti test con esito positivo con tutti gli IDP salvo Register.it per cui si chiede un nuovo dispiegamento per questo IDP

Cordiali saluti
Facondini Stefano 

Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Abbiamo richiesto un ricaricamento del metadata. Verificate se l'IdP in questione adesso risponde correttamente alle richieste

**Comment by sfacondini** [comment]
Buongiorno, 
confermo corretto funzionamento anche di Register.it
Cordiali saluti
Facondini Stefano 
Maggioli spa
