### ISSUE TITLE
Richiesta pubblicazione secondo SP stessa organizzazione

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#446]
Buongiorno, presso l'Istituto Zooprofilattico Sperimentale dell'Abruzzo e del Molise avremmo la necessità di pubblicare due service provider distinti afferenti a dipartimenti distinti governati entrambi dallo stesso istituto. E' possibile pubblicare due metadati potenzialmente molto simili ma differenti sicuramente nella sezione descrittiva dell'organizzazione?
Grazie anticipatamente per la disponibilità.
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Non è possibile definire più metadata per una singola P.A.
Per aggiungere un nuovo servizio all'interno del metadata comunicato è necessario:

* Aggiungere un ulteriore elemento AssertionConsumerServer ,  indicante il servizio in termini di URL e relativo binding “HTTP POST”.

ed opzionalmente aggiungere:

* Un ulteriore elemento KeyDescriptor, qualora si voglia utilizzare certificati distinti  per firmare le  richieste di autenticazione relative a servizi distinti.

* Un ulteriore elemento SingleLogoutService, qualora si voglia utilizzare un diverso servizio di single logout 
 
* Un ulteriore elemento AttributeConsumingService, qualora i servizi richiedano in risposta diversi insiemi di dati, o si voglia comunque mantenere distinte le descrizioni degli insiemi di dati consumati da servizi distinti.

Il metadata va quindi rifirmato e reinviato ad AgID secondo le modalità specificate sul sito ufficiale SPID nella [pagina dedicata ai Service Provider](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid).
