### ISSUE TITLE
Controllo metadata Comune di Cattolica

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#447]
Buongiorno,
Per conto del comune di Cattolica , abbiamo predisposto i metadata e pubblicati nella cartella

https://cattolica.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by sfacondini** [comment]
[metadata_cattolica-signed.zip](https://github.com/italia/spid/files/2241665/metadata_cattolica-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
