### ISSUE TITLE
Controllo metadata Comune di Cesenatico

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#448]
Buongiorno,
Per conto del comune di Cesenatico , abbiamo predisposto i metadata e pubblicati nella cartella

https://cesenatico.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_cesenatico-signed.zip](https://github.com/italia/spid/files/2241668/metadata_cesenatico-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
