### ISSUE TITLE
[Richiesta supporto] Comune di Cigliano

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#45]
Buongiorno,
il dominio di default funziona con tutti gli IDP.
Invece, abbiamo problemi con l'altro dominio. Potremmo avere un aiuto per la config shibboleth multi dominio? Grazie

**Comment by umbros** [comment]
Ciao @Eduardo1977,
la cosa è risolvibile attraverso SPReverseProxy.
https://wiki.shibboleth.net/confluence/display/SHIB2/SPReverseProxy se può esserti di aiuto nei prossimi giorni vedrò di aggiornare la configurazione del repository https://github.com/italia/spid-sp-shibboleth

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by Eduardo1977** [comment]
Buongiorno @umbros, grazie
