### ISSUE TITLE
Richiesta controllo metadata - Comune di Trezzano sul Naviglio

### ISSUE THREAD

**Issue by globogis** [italia/spid#451]
Buongiorno,
si richiede la validazione dei metadati per conto del comune:
https://sportellotelematico.comune.trezzano-sul-naviglio.mi.it/simplesaml/module.php/saml/sp/metadata.php/trezzanosulnaviglio

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
