### ISSUE TITLE
Richiesta verifica tecnica Az. Osp. Ospedali Riuniti Marche Nord

### ISSUE THREAD

**Issue by AziendaOspedalieraMarcheNord** [italia/spid#455]
Buongiorno si richiede verifica tecnica implementazione SPID per url  https://spid.ospedalimarchenord.it/metadata/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il metadata inviato non è compliant alle regole tecniche SPID;
gli errori riscontrati sono:

1)L'hash della firma sul metadata non combacia con il contenuto. Sull'account github dell'iniziativa Developers Italia è stato pubblicato un tool per la firma dei metadata per i sistemi operativi Linux e OSX : https://github.com/italia/spid-metadata-signer. Vi segnaliamo inoltre che alcuni Service Provider hanno utilizzato con successo un porting del citato tool per la piattaforma Windows sviluppato da terzi: https://github.com/ermannog/SPID-Metadata-Signer-Windows

Si prega di rifirmare il metadata e di comunicarne la disponibilità all'endpoint segnalato di quello corretto.

Staff Tecnico SPID
Agenzia per l'Italia Digitale
