### ISSUE TITLE
AGGIORNAMENTO METADATA

### ISSUE THREAD

**Issue by ceddesenzano** [italia/spid#456]
Buongiorno,
la presente per richiedere la verifica del nostro metadata per l'aggiunta di un nuovo servizio.
Si informa inoltre che è stato variato l'URL di pubblicazione.

Il metadata è disponibile all'indirizzo:
http://comune.desenzano.brescia.it/_system/xstandard/services/desenzanodelgarda.xml

Cordiali saluti

Margherita Sgalambro

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
Si richiede di inviare una mail all'indirizzo spid.tech@agid.gov.it per ulteriori comunicazioni.
