### ISSUE TITLE
Richiesta Aggiornamento MD Università degli Studi di Messina

### ISSUE THREAD

**Issue by falco76** [italia/spid#457]
salve
vi preghiamo di procedere all'aggiornamento dei md dell'Università degli Studi di Messina
l'indirizzo dei nuovi md è stato inviato via mail a  spid.tech@agid.gov.it 

saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
