### ISSUE TITLE
Comune di Verbania - problema con IdP TIM

### ISSUE THREAD

**Issue by falbesano** [italia/spid#46]
Buongiorno,
riprendo la segnalazione fatta con il vecchio helpdesk (3PT-YM5-D1AA) perché il problema segnalato persiste. Con l'entityID realtivo al Comune di Verbania, l'IdP ritorna questa pagina di errore:

![immagine](https://user-images.githubusercontent.com/7596471/37140858-67a0ed04-22b3-11e8-8190-3048903b7923.png)

Con gli altri IdP funziona regolarmente e con altri entityID funziona anche l'IdP TIM (implementazione multitenant).

Invio via mail il link all'ambiente di test dove è possibile riprodurre il problema.

Ho visto un'altra issue con lo stesso problema, che è stato risolto.
Grazie e saluti
Federico Albesano

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone procedere all'invio della convenzione

Umberto Rosini
Agenzia per l'Italia Digitale
