### ISSUE TITLE
Aggiornamento metadata Comune di Desio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#460]
Buongiorno,
Per conto del comune di Desio, 
abbiamo aggiornato i metadata attualmente in produzione con aggiunta di nuovi servizi 
e aggiornamento del certificato di firma
i nuovi metadata sono pubblicati nella cartella 

https://desio.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_desio1-signed.zip](https://github.com/italia/spid/files/2296547/metadata_desio1-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
