### ISSUE TITLE
Richiesta verifica file metadata Azienda Zero

### ISSUE THREAD

**Issue by facimaro** [italia/spid#461]
Buonasera,
scrivo per conto di Azienda Zero, Regione del Veneto.
Con la presente chiedo la verifica del file metadata pubblicato all'indirizzo https://spid.azero.veneto.it/metadata.
Grazie

Cordiali Saluti
Fabiano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

Distinti Saluti
Staff Tecnico SPID


Il 17/08/2018 16:38, Fabiano C. ha scritto:
