### ISSUE TITLE
Errore di interazione con IdP Sielte - Comune di Brindisi

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#462]
Buongiorno,
si verifica un errore nell'interazione fra il servizio https://www.comune.brindisi.it e l'Identity Provider Sielte. Il messaggio restituito è:

Error Code: 10
Formato richiesta non corretto. 
Contattare il gestore del servizio.

La nostra implementazione è conforme agli altri Portali realizzati da Halley Informatica (ad esempio https://www.comunebastiaumbra.gov.it dove invece l'IdP Sielte funziona correttamente), credo quindi ci sia stato un problema nel deploy dei metadati: 

https://www.comune.brindisi.it/brindisi/spid-metadata.xml

Si richiede cortesemente una verifica in merito e, se necessario, un nuovo deploy presso l'IdP.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Adesso l'Identity Provider in questione risponde alle AuthnRequest del Comune di Brindisi
