### ISSUE TITLE
Verifica metadata Comune di Valdisotto

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#467]
Per conto del comune di Valdisotto
abbiamo predisposto i metadata e pubblicati all'URL

https://valdisotto.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_valdisotto-signed.zip](https://github.com/italia/spid/files/2309613/metadata_valdisotto-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
