### ISSUE TITLE
Verifica metadata Comune di Valdifurva

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#468]
Buongiorno,

Per conto del comune di Valfurva
abbiamo predisposto i metadata e pubblicati all'URL

https://valfurva.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_valfurva-signed.zip](https://github.com/italia/spid/files/2309620/metadata_valfurva-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
