### ISSUE TITLE
Verifica metadata Comune di Sondalo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#469]
Buongiorno,

Per conto del comune di Sondalo
abbiamo predisposto i metadata e pubblicati all'URL

https://sondalo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_sondalo-signed.zip](https://github.com/italia/spid/files/2309621/metadata_sondalo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
