### ISSUE TITLE
Comune di Calenzano - Errori con IdP Register, Intesa, Namirial

### ISSUE THREAD

**Issue by globogis** [italia/spid#47]
Buongiorno,
nella issue #4, aperta per nostro conto da @umbros, avevamo richiesto l'aggiornamento dei metadati per il Comune di Calenzano.

Allo stato attuale il servizio sta funzionando correttamente, ad eccezione di queste anomalie:

## IdP Register (SPID Italia)

Il login funziona correttamente, ma il logout restituisce l'errore:
```
Errore nel processo di login

Sistema di autenticazione non disponibile - Riprovare più tardi
```

## IdP Intesa

Il login non funziona: nella pagina di autenticazione non compaiono i campi per inserire username e password

## IdP Namirial

Il login non funziona, compare il seguente errore:
```
Namirial.ID - Impossibile rispondere al servizio

Impossibilità di identificare un modo per rispondere all'applicazione richiesta.
Questo è di solito dovuto a configurazioni erronee dell'applicazione.
ErrorCode nr16
```

Grazie

**Comment by umbros** [comment]
Ciao,
risulta un problema sull'issuer

`
<saml:Issuer 
        NameQualifier="&lt;saml:Issuer 
        xmlns:saml=&quot;urn:oasis:names:tc:SAML:2.0:assertion&quot; 
        NameQualifier=&quot;https://xxxyyyzzz/&quot; 
        Format=&quot;urn:oasis:names:tc:SAML:2.0:nameid-format:entity &quot;&gt;https://xxxyyyzzz/&lt;/saml:Issuer&gt;" 
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://xxxyyyzzz/
    </saml:Issuer>
`

**Comment by globogis** [comment]
Buonasera,
i problemi oggetto del ticket ci risultano tutti risolti ad eccezione del logout con Register. In realtà abbiamo notato che questo problema è presente su tutti i nostri servizi. L'unica differenza che notiamo nella LogoutRequest che viene generata da SimpleSAMLPHP è la mancanza del <samlp:SessionIndex> poiché Register non la restituisce nel login. E' il caso che apra una nuova issue specifica?

Grazie

**Comment by umbros** [comment]
No ok, il prolema del logout e in gestione.
Validazione OK @AntonioGiovanniSchiavone procedere all'invio della convenzione

Umberto Rosini
Agenzia per l'Italia Digitale
