### ISSUE TITLE
Verifica metadata Comune di Valdidentro

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#470]
Buongiorno,

Per conto del comune di Valdidentro

abbiamo predisposto i metadata e pubblicati all'URL

https://valdidentro.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_valdidentro-signed.zip](https://github.com/italia/spid/files/2309627/metadata_valdidentro-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
