### ISSUE TITLE
Verifica metadata Comune di Livigno

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#472]
Buongiorno,

Per conto del comune di Livigno

abbiamo predisposto i metadata e pubblicati all'URL

https://livigno.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_livigno-signed.zip](https://github.com/italia/spid/files/2310879/metadata_livigno-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
