### ISSUE TITLE
Controllo metadata - Comune di Loano

### ISSUE THREAD

**Issue by falbesano** [italia/spid#473]
Buongiorno,
per conto del Comune di Loano, richiediamo la verifica dei metadati pubblicati all'url:
https://www.comuneloano.it/SPID-metadata.xml

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
