### ISSUE TITLE
Richiesta aggiornamento Metadata per la Provincia autonoma di Trento

### ISSUE THREAD

**Issue by uffinformaticapat** [italia/spid#474]
chiedo di comunicare agli idp che abbiamo aggiunto un nuovo servizio on line
il servizio si chiama:
<md:ServiceName xml:lang="it">Domanda per fiinanziamenti nel PSR</md:ServiceName>
presente nei metadata

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
