### ISSUE TITLE
Comune di Peschiera Borromeo - Errore INFOCERT in fase di autenticazione

### ISSUE THREAD

**Issue by peschieraborromeo** [italia/spid#475]
buongiorno
da mesi non riusciamo ad accedere tramite INFOCERT. La loro risposta è stata la seguente:
"Ad InfoCert non è mai arrivata una richiesta di caricamento dei metadata relativi al comune di Peschiera Borromeo da parte dell'Agenzia per l'Italia Digitale, unica titolata a richiederlo. Nemmeno nel sito di riferimento, https://registry.spid.gov.it, c'è qualcosa relativo al comune in oggetto. Finché non ci arriva la richiesta formale da parte di AgID non possiamo caricare i metadata e le richieste andranno in errore"

Nonostante ieri il metadata sia stato aggiornato (issue #464), continuiamo ad avere lo stesso errore e in effetti il Comune non risulta nello SPID Registry.
Con gli altri IdP non abbiamo riscontrato problemi.

Grazie, cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
L'Identity Provider in questione adesso risponde correttamente alle vostre AuthnRequest.
