### ISSUE TITLE
Mancato recepimento aggiornamento metadata IDP Register.it per il Comune di Desio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#477]
Buongiorno,
a seguito dell'aggiornamento dei metadata del comune di Desio
sono stati riscontrate anomalie con l'IDP       Register.it  prima regolarmente funzionante.
Le anomalie per l'IDP Infocert per lo stesso comune sono state invece risolte
Cordiali Saluti

Facondini Stefano 
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
L'Identity Provider in questione adesso risponde correttamente alle vostre AuthnRequest.
