### ISSUE TITLE
Verifica metadata Comune di Civita Castellana

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#478]
Buongiorno,

Per conto del Comune di Civita Castellana

[metadata_civitacastellana-signed.zip](https://github.com/italia/spid/files/2324161/metadata_civitacastellana-signed.zip)

abbiamo predisposto i metadata e pubblicati all'URL

https://civitacastellana.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
