### ISSUE TITLE
Controllo metadata - Comune di Nichelino

### ISSUE THREAD

**Issue by falbesano** [italia/spid#479]
Buongiorno,
per conto del Comune di Nichelino, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.nichelino.to.it/001164/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
