### ISSUE TITLE
Richiesta di validazione e deploy metadati - Comune di Pralboino

### ISSUE THREAD

**Issue by globogis** [italia/spid#48]
Buongiorno,
si richiede la verifica e il deploy dei metadati per conto del Comune di Pralboino
https://sportellotelematico.comune.pralboino.bs.it/simplesaml/module.php/saml/sp/metadata.php/spid

Si tratta di uno Sportello conforme a quelli già precedentemente validati da GLOBO.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
