### ISSUE TITLE
Richiesta controllo metadata - Comune di Filago (BG)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#481]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:

https://servizi.comune.filago.bg.it/c016098/spid-metadata.xml

Il servizio in oggetto è stato realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
