### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Gallese (VT)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#485]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Gallese:
http://www.comune.gallese.vt.it/public/D870/n1200478.xml

Cordiali saluti
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
