### ISSUE TITLE
Richiesta di validazione metadati - Comune di Paullo

### ISSUE THREAD

**Issue by globogis** [italia/spid#487]
Buongiorno,
per conto del Comune di Paullo si richiede la verifica e il deploy dei metadati esposti all'URL:
```
https://sportellotelematico.comune.paullo.mi.it/simplesaml/module.php/saml/sp/metadata.php/spid
```

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
