### ISSUE TITLE
Controllo metadata - Comune di Domodossola

### ISSUE THREAD

**Issue by falbesano** [italia/spid#488]
Buongiorno,
per conto del Comune di Domodossola, richiediamo la verifica dei metadati pubblicati all'url:
https://spid.domodossola.gov.it/metadata.xml

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
