### ISSUE TITLE
Richiesta verifica URL e convenzione - comune san vito romano

### ISSUE THREAD

**Issue by cruggeri80** [italia/spid#489]
Insieme al nostro partner tecnologico, PA Digitale, abbiamo già provveduto a validare il file xml dei metadati e ad effettuare alcuni test preliminari, che sono andati a buon fine. Dobbiamo iniziare la procedure amministrativa e così invio, come richiesto, [l'url di accesso ai nostri servizi online](https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1UR200.sto%3FDB_NAME%3Dn200438&SOLStwToken=9009851311011056&DB_NAME=n200438&Login_Message=):

Si resta in attesa di invio convenzione per sottoscrizione.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
