### ISSUE TITLE
Richiesta di validazione e deploy metadati - Comune di Pregnana Milanese

### ISSUE THREAD

**Issue by globogis** [italia/spid#49]
Buongiorno,
Si richiede la verifica e il deploy dei metadati per conto del Comune di Pregnana Milanese.
https://sportellotelematico.comune.pregnana.mi.it/simplesaml/module.php/saml/sp/metadata.php/spid 

Si tratta di uno Sportello  conforme a quelli già precedentemente validati da Globo

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
