### ISSUE TITLE
ERRORE IN FASE DI LOGIN CON IDP SPID ITALIA - Comune di Peschiera Borromeo

### ISSUE THREAD

**Issue by peschieraborromeo** [italia/spid#491]
Buongiorno
accedendo al portale:
https://servizionline.comune.peschieraborromeo.mi.it/cmspeschieraborromeo/login.aspx#spid
selezionando SPID ITALIA dà il seguente errore: 
_Errore nel processo di login - Formato richiesta non corretto - Contattare il gestore del servizio_

Lo stesso IDP invece funziona accedendo dagli altri 2 nostri portali.
Potete fare una verifica?
Grazie, cordiali saluti.
Comune di Peschiera Borromeo

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Provate ad applicare i seguenti correttivi:
1) l'ora di sistema del server sembra essere erroneamente impostata alcuni minuti indietro. si prega di correggere l'orario
2) Come indicato dall'[Avviso SPID n°5 ](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n5-regole-tecniche-errata-corrige.pdf), si prega di definire il valore AuthnContextClassRef secondo il formato https://www.spid.gov.it/SpidL2
