### ISSUE TITLE
Controllo metadati - Comune di Calatabiano

### ISSUE THREAD

**Issue by datanetsrl** [italia/spid#493]
Buongiorno,
per conto del Comune di Calatabiano, richiediamo la verifica dei metadati, generati mediante plugin WP SPID Italia di Marco Milesi, pubblicati all'url: https://comune.calatabiano.ct.it/wp-content/plugins/wp-spid-italia/lib/www/module.php/saml/sp/metadata.php/default-sp

Grazie e cordiali saluti
Datanet srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
