### ISSUE TITLE
Integrazione Web Services

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#496]
Buongiorno, volevo solo sapere se è prevista una modalità di integrazione Web Services.
In pratica, abbiamo la necessità di supportare credenziali SPID nell'autenticazione tra servizi.
Grazie anticipatamente per il vostro supporto.
Cordialmente,
F.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
il quesito è posto in maniera piuttosto generica. Vi preghiamo di inviare una mail all'indirizzo spid.tech@agid.gov.it fornendo una descrizione più dettagliata del problema.
