### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Comune di Gallese (VT)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#498]
Con la presente si richiede la verifica tecnica sull'implementazione di SPID per il comune di Gallese (VT).
Di seguito la URL dei servizi da validare:

https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1TR001.sto%3FDB_NAME%3Dn1200478&SOLStwToken=4117021712441079&DB_NAME=n1200478&Login_Message=

In attesa di un vostro riscontro, cordiali saluti.
We-COM Srl

**Comment by damikael** [comment]
Si prega di inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente (se soggetto privato, denominazione o ragione sociale seguita da Codice Fiscale o P.IVA);
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Grazie
