### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Anguillara Sabazia (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#499]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Anguillara Sabazia:
http://www.comune.anguillara-sabazia.roma.it/xml/n1200704.xml

Cordiali saluti
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
