### ISSUE TITLE
Verifica servizi Regione Campania

### ISSUE THREAD

**Issue by umbros** [italia/spid#5]
Aggiunta per conto di Regione Campania (pervenuta via email senza issue)

Regione Campania richiede la verifica tecnica sulla propria implementazione di SPID.

**Comment by umbros** [comment]
@ regione campania

Request errata (dettagli per email) e IDP Intesa non integrato.

KO

@sfacondini implementazione verificata con successo.
@AntonioGiovanniSchiavone puoi procedere all'invio della convenzione.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato da Rosini, la verifica dell'implementazione ha avuto esito negativo (KO), in quanto qualunque implementazione che non includa **[tutti gli Identity Provider accreditati](http://www.agid.gov.it/infrastrutture-architetture/spid/identity-provider-accreditati)**, viene **rifiutata d'ufficio**.

Facciamo notare inoltre che, come indicato dal **[sito ufficiale SPID](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid)** , la comunicazione dei metadata agli IdP ha come obbiettivo il consentire ai Service Provider di eseguire in proprio dei test di integrazione e la messa in produzione dei propri sistemi. 

Conseguentemente, effettuare una richiesta di verifica su una implementazione che si sa non essere funzionante, oltre ad essere un errore concettuale, non consente all'AgID di fornire un'adeguato supporto alla P.A. aderente.
Il Service Provider che rilevasse problemi nell'implementazione di SPID dovrebbe fare richiesta di Supporto Tecnico, dopo aver **accuratamente** consultato la documentazione tecnica SPID:

- **[Regolamento recante le regole tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf)**
- **[Avvisi SPID](http://www.agid.gov.it/agenda-digitale/infrastrutture-architetture/spid/avvisi)**
- **[Tabella di messaggi di anomalia SPID](http://www.agid.gov.it/sites/default/files/regole_tecniche/spid_tabella_messaggi_di_anomalia_v1.0.pdf)**

**Comment by umbros** [comment]
Verifica KO

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by gennaroromano** [comment]
Chiediamo cortesemente il dettaglio del KO.

A tal proposito, segnaliamo i buoni risultati riscontrati oggi, riportando qui sotto quanto scritto nell'issue #130 .

Abbiamo integrato l'IdP Intesa come si può verificare mediante il servizio di test:
https://spidgateway.regione.campania.it/verificagel/

Inoltre, stamattina, abbiamo verificato il corretto funzionamento del servizio di test con l'IdP PosteID. Si veda l'immagine sotto riportata.

![image](https://user-images.githubusercontent.com/37836127/38304177-c994bc42-3808-11e8-8452-960581645af0.png)

Ci chiediamo se tutti gli IdP abbiano caricato il metadata di Regione Campania aggiornato in data 7 febbraio 2018, ovvero usano il vecchio metadata del 2017. Potete verificare?

Restiamo in attesa di poter completare la verifica tecnica e ricevere la Convenzione da firmare.

Grazie,
Gennaro Romano

Regione Campania

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato nell'[Issue 130](https://github.com/italia/spid/issues/5), il vostro Service Provider non svolge interazioni corrette con gli Identity Provider. 
In paricolare, viene restituito un errore dai seguenti Identity Provider: 

Aruba
Namirial
Register.it
Sielte
TI Trust Technologies

Sempre nell'Issue 130 sono state fornite indicazioni utili alla risoluzione del problema.

**Comment by gennaroromano** [comment]
Richiamiamo la Vostra attenzione sull'ultimo commento dell'issue #130 in cui specifichiamo come abbiamo risolto il problema, adeguando la piattaforma secondo le Vostre indicazioni.
D'altra parte, vogliamo evidenziare il mancato caricamento da parte di Aruba del metadata aggiornato di Regione Campania, comprovato dal fatto che solo con Aruba riscontriamo problemi sulla richiesta di autenticazione (si veda allegato nell'issue #130). A tal proposito, oggi abbiamo sollecitato Aruba, tramite email, al caricamento del metadata corretto e Vi chiediamo supporto nell'azione al fine di completare la verifica tecnica.

Saluti,
Gennaro Romano

Regione Campania

**Comment by gennaroromano** [comment]
Oggi anche Aruba risponde correttamente alla richiesta di autenticazione (si veda immagine allegata).
Con questo abbiamo verificato che il nostro Service Provider svolge interazioni corrette con tutti gli Identity Provider.

Pertanto, Regione Campania si aspetta un OK alla verifica tecnica.

Saluti,
Gennaro Romano

Regione Campania

![image](https://user-images.githubusercontent.com/37836127/39921162-2953b1be-551a-11e8-8097-9b16d1fcb5cd.png)

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.
