### ISSUE TITLE
Richiesta controllo e deploy nuovi metadati Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#50]
Salve
Si richiede che vengano controllati e deployati i nuovi metadati della Regione Puglia disponibili su:
[https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml) 
é stato aggiunto un servizio riguardante la comunicazione dei dati vaccinali delle scuole.
Vi prego di fare il possibile per comunicare entro oggi i nuovi dati ai gestori SPID, in quanto i dati vaccinali devono essere comunicati entro il 12/3.

Grazie
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
