### ISSUE TITLE
Richiesta di validazione dei metadati - Comunità Montana Castelli Romani e Prenestini (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#500]
Buongiorno,
si richiede la verifica dei metadati per conto della Comunità Montana Castelli Romani e Prenestini:
http://cmcastelli.it/xml/n1200869.xml

Cordiali saluti
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
