### ISSUE TITLE
Richiesta di Validazione Metadati - Regione Calabria

### ISSUE THREAD

**Issue by SpidCalabria** [italia/spid#506]
Per conto della Regione Calabria si richiede la verifica e il deploy dei metadati esposti all'URL: 
https://ecosanita.regione.calabria.it/metadata-regionecalabria_20180912.xml

**Comment by mirrep** [comment]
Buonasera Sig. Schiavone,
Il Metadata in esame non è quello corretto che abbiamo ricreato con l'ultima versione del Docker Auth Spid. Abbiamo sollevato alcune problematiche in quanto non riusciamo a gestire le location sia di logout che di assertion consumer servic e i metodi di Binding.
@umbros ci ha suggerito di modificare il file Shibboleth2.xml ma non riusciamo a visualizzare nel Metadata prodotto (https://spid.regione.calabria.it/metadata) quanto di nostro gradimento pur avendo effettuato l'operazione suggerita.
Stiamo ipotizzando di adeguarci ai link di redirect e post prodotti dal Docker.
Suggerite altro? Attendiamo sue considerazioni.

**Comment by mirrep** [comment]
Ho omesso una informazione! Nel nostro ultimo caso il metadata ci era stato rigettato in quanto l'hash della firma non corrispondeva al contenuto del documento! Nel caso esposto non dovremmo più incorrere in questa problematica ma non riusciamo a inserire per come accennavo binding e location di interesse!

**Comment by SpidCalabria** [comment]
Aggiungo il @umbber e @SpidCalabria per eventuali ed ulteriori integrazioni.  
A presto e grazie mille.

**Comment by SpidCalabria** [comment]
Gentili Signori,
con la presente per conto della Regione Calabria si trasmette il link da cui prelevare il metadata ai fini della relativa validazione (https://spid.regione.calabria.it/metadata)
Rimaniamo in attesa di un vostro cortese riscontro e cogliamo occasione per porgere distinti saluti.

Medesima comunicazione è stata inviata su mail spid.tech@agid.gov.it.

Massimiliano Perri

**Comment by SpidCalabria** [comment]
Gentili Signori, 
in relazione alla richiesta sollevata lo scorso 28/09 con la presente si richiede di validare il metadata reperibile al link https://spid.regione.calabria.it/metadata di cui alla mail spedita avente medesimo oggetto a spid.tech@agid.gov.it.

Certi di un vostro cortese riscontro porgiamo distinti saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Nelle url delle varie location manca il dominio di primo livello. Nello specifico è indicato il dominio "ecosanita.regione.calabria" invece che "ecosanita.regione.calabria.it"

**Comment by mirrep** [comment]
Grazie delle indicazioni, potrebbe verificare laddove possibile al medesimo indirizzo se il metadata risulta corretto! Il link è sempre https://spid.regione.calabria.it/metadata.
Le siamo grati e rimaniamo in attesa di sue nuove.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by mirrep** [comment]
Le siamo grati. Procediamo con i restanti step. 
Cordiali saluti.
