### ISSUE TITLE
Pubblicazione metadati IZSAM

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#509]
Salve, vorrei richiedere la pubblicazione dei metadati per L'Istituto Zooprofilattico dell'Abruzzo e del Molise.

Il link è il seguente.
Grazie,
F.

https://test.vetinfo.it/cas/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
