### ISSUE TITLE
Aggiornamento metadati Comune di Pavia

### ISSUE THREAD

**Issue by globogis** [italia/spid#510]
Buongiorno,
in seguito a un aggiornamento della piattaforma, si richiede il deploy dei metadati aggiornati per conto del Comune di Pavia. L'EntityID non è variato rispetto al precedente, e l'endpoint a cui sono disponibili è sempre: https://sportellotelematico.comune.pv.it/sites/default/files/spid-metadata/pavia-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
