### ISSUE TITLE
Richiesta di validazione metadati - Comune di Vibo Valentia

### ISSUE THREAD

**Issue by globogis** [italia/spid#511]
Buongiorno,
si richiede, per conto del Comune di Vibo Valentia, la validazione e il deploy dei metadati esposti all'endpoint:

https://www.sportellotelematicovibovalentia.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
