### ISSUE TITLE
controllo metadati da parte del gestore Infocert - sistema.puglia.it

### ISSUE THREAD

**Issue by marangiom** [italia/spid#513]
salve
Ci segnala un utente che da sistema.puglia.it non riesce a partecipare ad un bando perchè non riesce ad accedere via SPID tramite infocert; è l'unico gestore che restituisce una schermata di errore "formato richiesta non corretto".
Vi prego di comunicarci quanto prima qual è il problema, in modo da poterlo risolvere entro domani, in quanto il bando scade il 20/9.
i metadati sono scaricabili da https://spid.rupar.puglia.it/regione-puglia-metadata.xml
Chiedo scusa se la richiesta sarà ridondante (ho inviato già una mail a spidTech) ma è estremamente urgente.
grazie
Marcello Marangio
InnovaPuglia S.p.A.

**Comment by marangiom** [comment]
i metadati sono scaricabili da https://spid.rupar.puglia.it/regione-puglia-metadata.xml
grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Problema temporaneamente risolto.
Maggiori informazioni tecniche sono state esplicitate tramite mail inviata da spid.tech
