### ISSUE TITLE
Verifica metadata Comune di Pescara

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#514]
Buongiorno,

Per conto del Comune di Pescara

abbiamo predisposto i metadata e pubblicati all'URL

https://pescara.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_pescara-signed.zip](https://github.com/italia/spid/files/2395759/metadata_pescara-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
