### ISSUE TITLE
Verifica metadata Comune di Limido Comasco

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#515]
Buongiorno,

Per conto del Comune di Limido Comasco

abbiamo predisposto i metadata e pubblicati all'URL

https://limidocomasco.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_limidocomasco-signed.zip](https://github.com/italia/spid/files/2395768/metadata_limidocomasco-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
