### ISSUE TITLE
Verifica metadata Comune di Cisterna di Latina

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#516]
Buongiorno,

Per conto del Comune di Cisterna di Latina

abbiamo predisposto i metadata e pubblicati all'URL

https://cisternadilatina.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_cisternalatina-signed.zip](https://github.com/italia/spid/files/2395773/metadata_cisternalatina-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
