### ISSUE TITLE
Richiesta di Validazione Metadati - Comune di Piovene Rocchette

### ISSUE THREAD

**Issue by fabianopavan** [italia/spid#518]
Si chiede di cambiare il metadata del comune di piovene rocchette, il metadata da usare si può recuperare da https://www.comune.piovene-rocchette.vi.it/portal/auth/spid/sp_metadata

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
