### ISSUE TITLE
Richiesta verifica metadati Comune di San Giovanni Ilarione

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#519]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di San Giovanni Ilarione.
https://www.comune.sangiovanniilarione.vr.it/c023070/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
