### ISSUE TITLE
Richiesta verifica tecnica e convenzione Università degli Studi di Salerno

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid#52]
Richiesta dall' Università degli Studi di Salerno

Richiediamo la verifica tecnica e l'avvio delle pratiche per la convenzione volendo diventare noi SP Spid per i servizi di Ateneo.

La url del servizio di autenicazione è https://auth.unisa.it/secure

**Comment by umbros** [comment]
Duplicato #145
