### ISSUE TITLE
Richiesta verifica tecnica Az. Osp. Ospedali Riuniti Marche Nord

### ISSUE THREAD

**Issue by AziendaOspedalieraMarcheNord** [italia/spid#522]
Buongiorno si richiede verifica tecnica implementazione SPID per url https://spid.ospedalimarchenord.it/metadata/metadata.xml

**Comment by damikael** [comment]
Si prega di inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente (se soggetto privato, denominazione o ragione sociale seguita da Codice Fiscale o P.IVA);
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Grazie
