### ISSUE TITLE
Aggiornamento metadati Agenzia del Demanio

### ISSUE THREAD

**Issue by mciccozzi** [italia/spid#524]
Si chiede, cortesemente, a seguito di aggiornamento il deploy dei metadati, scaricabili da : 
https://ifte.agenziademanio.it/metadata

Cordiali saluti
Maura Ciccozzi

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
