### ISSUE TITLE
Richiesta verifica metadati Comune di San Pietro di Feletto

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#525]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di San Pietro di Feletto.
https://www.comune.sanpietrodifeletto.tv.it/c026073/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
