### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Istituto di Informatica e Telematica del Consiglio Nazionale delle Ricerche

### ISSUE THREAD

**Issue by gianpyc** [italia/spid#527]
Salve,
con la presente si richiede la verifica tecnica sull'implementazione di SPID per l'Istituto di Informatica e Telematica (IIT) del Consiglio Nazionale delle Ricerche (Cnr).
La url dei sito da validare è la seguente:
https://www.cybersecurityosservatorio.it

Per motivi tecnici il sito è raggiungile attualmente solo dalla rete Cnr e verrà reso disponibile a tutti il 12 Ottobre durante il lancio ufficiale.
Tuttavia, siccome avremmo la necessità di aprire il sito al pubblico direttamente con l'accesso ai servizi tramite SPID,
sarebbe possibile per voi  poter effettuare la validazione fornendovi l'accesso ad un vostro range di indirizzi IP?

In attesa di un vostro riscontro, cordiali saluti.

**Comment by damikael** [comment]
Salve,
per procedere con la verifica tecnica occorre seguire la procedura indicata in:
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

Ovvero inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente (se soggetto privato, denominazione o ragione sociale seguita da Codice Fiscale o P.IVA);
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

A seguito si potranno definire meglio eventuali requisiti necessari per procedere alla verifica del servizio.
Grazie
