### ISSUE TITLE
Richiesta verifica metadati Comune di Bagnaria Arsa

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#528]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Bagnaria Arsa.
https://www.comune.bagnariaarsa.ud.it/c030008/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
