### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Codogno

### ISSUE THREAD

**Issue by globogis** [italia/spid#529]
Buongiorno,
per conto del Comune di Codogno si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportelloamico.comune.codogno.lo.it/simplesaml/module.php/saml/sp/metadata.php/spid
Grazie

**Comment by globogis** [comment]
Buongiorno,
abbiamo unito i nostri metadati a quelli già esistenti, generando questi:
https://sportelloamico.comune.codogno.lo.it/sites/default/files/spid-metadata/codogno-signed.xml

Si richiede cortesemente l'aggiornamento.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
