### ISSUE TITLE
Richiesta verifica tecnica e convenzione Città metropolitana di Milano

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid#53]
Richiesta dalla Città metropolitana di Milano

Si richiede la verifica tecnica dell'implmentazione.

La pagina iniziale di accesso è la seguente http://temi.cittametropolitana.milano.it/praticheol/login.aspx

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone puoi mandare la convenzione

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.
