### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Osio Sopra

### ISSUE THREAD

**Issue by globogis** [italia/spid#530]
Buongiorno,
per conto del Comune di Osio di Sopra si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.osiosopra.bg.it/simplesaml/module.php/saml/sp/metadata.php/osiosopra
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
