### ISSUE TITLE
Richiesta verifica metadati Comune di Treppo Grande

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#532]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Treppo Grande.
https://servizionline.comune.treppogrande.ud.it/c030126/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
