### ISSUE TITLE
Richiesta verifica metadati Comune di Moruzzo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#533]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Moruzzo.
https://servizionline.comune.moruzzo.ud.it/c030063/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
