### ISSUE TITLE
Richiesta verifica metadati Comune di Campodoro

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#535]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Campodoro.
https://www.comune.campodoro.pd.it/c028018/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
