### ISSUE TITLE
Richiesta verifica tecnica e convenzione - comune di Sanluri

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#536]
Salve,
con la presente si richiede la verifica tecnica sull'implementazione di SPID per il Comune di Sanluri
Inviamo mail  contestuale con dettagli dell'implementazione.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
Cordiali saluti
