### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di San Vito Romano (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#538]
Buongiorno,

si richiede la verifica dei metadati per conto del Comune di San Vito Romano:
http://static.comune.sanvitoromano.rm.it/uploads/n200438.xml

Grazie
We-COM Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
