### ISSUE TITLE
Verifica metadata Comune di Rende

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#540]
Buongiorno,

Per conto del Comune di Rende

abbiamo predisposto i metadata e pubblicati all'URL

https://rende.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_rende-signed.zip](https://github.com/italia/spid/files/2428056/metadata_rende-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
