### ISSUE TITLE
Verifica metadata Comune di Turano Lodigiano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#541]
Buongiorno,

Per conto del Comune di Turano Lodigiano

abbiamo predisposto i metadata e pubblicati all'URL

https://turanolodigiano.comune-online.it/serviziSPID/metadata.xml 

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_turanolodigiano-signed.zip](https://github.com/italia/spid/files/2428063/metadata_turanolodigiano-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
