### ISSUE TITLE
Richiesta verifica Metadati  Comune di Musei (SU)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#546]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Musei (SU)
https://www.comune.musei.ci.it/musei/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
