### ISSUE TITLE
Verifica Amministrativa SPID San Pancrazio Salentino

### ISSUE THREAD

**Issue by gianluca326** [italia/spid#548]
Buongiorno
abbiamo precedentemente fatto effettuare la verifica del metadato con esito positivo (metadata issue #199), vi chiediamo gentilmente di verificare l'implementazione dello spid all'indirizzo https://istanzesps.parsec326.it per poter procedere alla firma della convenzione con il Comune di San Pancrazio Salentino.
Ho scritto già due email all'indirizzo spid.tech@agid.gov.it ma non ho ricevuto nessuna risposta.
Grazie
Gianluca Monte

**Comment by gianluca326** [comment]
Buongiorno
abbiamo precedentemente fatto effettuare la verifica del metadato con esito positivo (metadata issue #199), vi chiediamo gentilmente di verificare l'implementazione dello spid all'indirizzo https://istanzesps.parsec326.it per poter procedere alla firma della convenzione con il Comune di San Pancrazio Salentino.
Ho scritto già due email all'indirizzo spid.tech@agid.gov.it ma non ho ricevuto nessuna risposta.
Grazie
Gianluca Monte

**Comment by damikael** [comment]
Richiesta presa in carico via email
