### ISSUE TITLE
Richiesta verifica su SPID Registry - Comune di Torino

### ISSUE THREAD

**Issue by cervinodomenico** [italia/spid#553]
Buongiorno,
ci siamo accorti che su SPID Registry sotto la sezione "Fornitori di servizi" non è presente il nostro entityName collegato al entityId = http://www.comune.torino.it/sp. Il nostro file di metadata è stato già validato e funzionante da molti mesi.
Potreste aggiungerci oppure indicarci le modalità di inserimento?

Grazie

**Comment by damikael** [comment]
Salve,
il riferimento al SP è ora presente sulla lista visualizzata su registry.spid.gov.it.

Saluti.
