### ISSUE TITLE
Richiesta verifica metadati Comune di Gorgo al Monticano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#556]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Gorgo al Monticano.
https://www.comune.gorgoalmonticano.tv.it/c026034/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
