### ISSUE TITLE
Richiesta verifica metadati Comune di Povoletto

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#558]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Povoletto.
https://www.comune.povoletto.ud.it/c030078/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
