### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Comune di Musei (SU)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#559]
Buongiorno,
con la presente si richiede la verifica tecnica sull'implementazione di SPID per il Comune di Musei (SU).
Le url dei servizi da validare sono le seguenti:
https://www.comune.musei.ci.it/musei/po/po_login.php
https://www.comune.musei.ci.it/musei/po/po_imlogin.php
https://www.comune.musei.ci.it/musei/po/po_pr_login.php
In attesa di un vostro riscontro, cordiali saluti.

**Comment by halleysardegna** [comment]
Buongiorno,
avendo da tempo condotto i nostri test interni con esito positivo, vi chiedo cosa manchi per poter ricevere la documentazione utile per portare a termine tutta la procedura.
Saluti

**Comment by damikael** [comment]
Salve,
al fine di recuperare lo stato della pratica, vi chiediamo di inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente e codice IPA;
- Url del metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Grazie
