### ISSUE TITLE
 Richiesta verifica metadati Comune di Misterbianco (CT)

### ISSUE THREAD

**Issue by comunemisterbianco** [italia/spid#560]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Misterbianco (CT).
[https://www.misterbianco.gov.it/MetadataSPID.xml](https://www.misterbianco.gov.it/MetadataSPID.xml)

**Comment by comunemisterbianco** [comment]
salve,
abbiamo apportato le correzioni si richiede la verifica.
grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
