### ISSUE TITLE
Richiesta verifica metadati Overweb Srl - Milano

### ISSUE THREAD

**Issue by br1** [italia/spid#561]
Buongiorno,

Vi chiedo la cortesia di verificare i metadati del servizio signin.eu di Overweb Srl
https://spid.signin.eu/metadata/

grazie

br1

**Comment by damikael** [comment]
Salve,
per procedere con la verifica tecnica occorre seguire la procedura indicata in:
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

Ovvero inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente (se soggetto privato, denominazione o ragione sociale seguita da Codice Fiscale o P.IVA);
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

A seguito si potranno definire meglio eventuali requisiti necessari per procedere alla verifica del servizio.
Grazie
