### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Viadana

### ISSUE THREAD

**Issue by globogis** [italia/spid#563]
Buongiorno,
per conto del Comune di Viadana si richiede la verifica e il deploy dei metadati esposti all'URL:
https://suapsue.comune.viadana.mn.it/simplesaml/module.php/saml/sp/metadata.php/viadana

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
