### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Vellezzo Bellini 

### ISSUE THREAD

**Issue by globogis** [italia/spid#564]
Buongiorno,
per conto del Comune di Vellezzo Bellini si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.vellezzobellini.pv.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
