### ISSUE TITLE
Richiesta di validazione dei metadati - Ordine dei giornalisti del Lazio

### ISSUE THREAD

**Issue by filippoma** [italia/spid#565]
Buongiorno,
per conto dell'ordine dei Giornalisti del Lazio si richiede la verifica e il deploy dei metadati esposti all'URL:
https://albo.odg.roma.it/rest/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il metadata proposto è privo di firma.

**Comment by filippoma** [comment]
Abbiamo provveduto a firmarlo, gentilmente si richiede la verifica del metadata.
https://albo.odg.roma.it/rest/metadata-signed.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by filippoma** [comment]
Salve,
ad oggi ho ancora il seguente messaggio da parte degli Idp:
Formato richiesta non corretto - Contattare il gestore del servizio

C'è un modo per verificare che il metadata sia stato caricato?
Grazie mille

**Comment by filippoma** [comment]
Segnalo che aruba, intesa e register non danno più il messaggio di errore segnalato in precedenza. Per i restanti Idp il problema persiste

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Le vostre AuthnRequest violano i requisiti indicati a pag. 8 del [Regolamento recante le nome tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf) relativi all'elemento AssertionConsumerServiceURL

**Comment by filippoma** [comment]
Abbiamo riconfigurato il servizio si richiede la verifica del nuovo xml:
https://albo.odg.roma.it/spid-odg.html/module.php/saml/sp/metadata.php/spid-odg

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il metadata inviato non è compliant alle regole tecniche SPID;
gli errori riscontrati sono:

1) Come indicato a pag. 20 del Regolamento recante le norme tecniche SPID, l'elemento AssertionConsumerService avente indice = 0 deve possedere l'attributo isDefault valorizzato a true
2) Come indicato a pag. 20 del Regolamento recante le norme tecniche SPID, per ogni elemento AttributeConsumingService deve essere presente un unico sottoelemento ServiceName

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
