### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Morlupo (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#566]
Buongiorno,

si richiede la verifica dei metadati per conto del Comune di Morlupo
http://www.comune.morlupo.roma.it/public/F734/documenti/1010201812590426.xml

Grazie
We-COM Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
