### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Regione Calabria

### ISSUE THREAD

**Issue by SpidCalabria** [italia/spid#567]
Gentili Signori,
per conto dell’Ente Regione Calabria con la presente si richiede la verifica tecnica sull'implementazione di SPID (Progetto  Applicazione unica di accesso agli Ecosistemi Digitali Sanitari Regionali ).
Di seguito la URL dei servizi da validare: https://ecosanita.regione.calabria.it/
Si resta in attesa di un vostro riscontro inerente la verifica tecnica di che trattasi e della documentazione da compilare e firmare per la stipula della convenzione.
Distinti Saluti.

Riccardo Riccardi
Regione Calabria - Settore Agenda digitale

**Comment by mirrep** [comment]
Gentilissimi,
In merito alla richiesta in oggetto vi saremmo grati di un cortese riscontro al fine di poter procedere con la messa in produzione dei servizi indicati.
Ringraziamo sin da ora per la disponibilità e l'interesse che vorrete mostrarci ed attendiamo indicazioni sulle modalità di sottoscrizione della convenzione richiamata.
Distinti saluti.

**Comment by mirrep** [comment]
Facendo seguito alla mail del 30/11 u.s. inviata a spid.tech@agid.gov.it  ed avente ad oggetto "Fwd: Esito verifica tecnica dell'implementazione SPID - Regione Calabria" si richiede laddove possibile la validazione e pubblicazione del metadata reperibile al link https://spid.regione.calabria.it/metadata
Si solleva inoltre richiesta di assistenza tecnica per la risoluzione dei punti: 
**Request Report Section**
- Strict: Test the Compliance of NameIDPolicy element: 1 "AllowCreate Attribute" 
**Response Report Section**
- 02. Response - non firmata
- 03. Response - Assertion non firmata
- 04. Response - Firma diversa
- 18. Response - InResponseTo diverso da Request

La presente richiesta sollevata per conto delle Regione Calabria riveste carattere di estrema urgenza. 

Vi siamo grati per il supporto e l'interesse mostrato. 

Cordialmente.
