### ISSUE TITLE
Richiesta di validazione metadata - ATS Milano Città Metropolitana

### ISSUE THREAD

**Issue by scubla88** [italia/spid#568]
Buongiorno,
si richiede la verifica del metadata in ambiente di test per conto dell'ATS Milano Città Metropolitana
https://spid.ats-milano.it/metadata

Grazie,
Fabio Scubla
Invisiblefarm Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by scubla88** [comment]
@AntonioGiovanniSchiavone 
Buongiorno,
stiamo riscontrando un problema con gli IdP, l'errore è il seguente:

https://spid.ats-milano.it/error?now=Tue%20Dec%20%204%2009%3A24%3A59%202018&requestURL=https%3A%2F%2Fspid.ats-milano.it%2Fiam%2FLogin&errorType=opensaml%3A%3Asaml2md%3A%3AMetadataException&errorText=Unable%20to%20locate%20metadata%20for%20identity%20provider%20(https%3A%2F%2Fposteid.poste.it)&entityID=https%3A%2F%2Fposteid.poste.it&eventType=Login

**Unable to locate metadata for identity provider**

Il metadata è disponibile all'indirizzo https://spid.ats-milano.it/metadata e non è stato modificato. Fino a ieri sera funzionava correttamente.

Riuscite a darci assistenza?

Grazie,
Fabio Scubla
