### ISSUE TITLE
Comune di Vercelli - Problema con Idp Intesa e SpidItalia

### ISSUE THREAD

**Issue by falbesano** [italia/spid#569]
Buongiorno,
per conto del Comune di Vercelli, segnaliamo che gli IdP Intesa e SpidItalia non sembrano aver recepito l'aggiornamento ai metadata del comune, di cui all'issue #554 . 
L'SP che è stato aggiunto nell'aggiornamento non viene riconosciuto, con comportamenti diversi, verificabili all'url: https://www.pa-online.it/GisMasterWebS/SU/SU.aspx?IdCliente=002158&IdSU=SSU&IdPage=Aut&IdPageFrom=SSU&IdAzione=Login&IdRed=/GisMasterWebS/SU/SU.aspx.
Gli altri IdP funzionano correttamente.

Ringraziando per l'attenzione, saluto cordialmente
Federico Albesano

**Comment by falbesano** [comment]
Ad oggi il problema con SpidItalia sembra risolto, restano problemi con l'IdP Intesa, che non riconosce il nuovo AttributeConsumerServiceIndex, ritornando "ErrorCode nr18" all'SP precedente.

Restiamo in attesa di supporto
Cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo richiesto un ricaricamento del metadata. Qualora entro 24h la situazione non si risolvesse anche con l'IdP Intesa, procederemo ad ulteriori indagini.

**Comment by AntonioGiovanniSchiavone** [comment]
Gli IdP in questione sembrano adesso rispondere correttamente alle AuthnRequest
