### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Castel d'Azzano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#572]
Buongiorno, abbiamo condotto i test interni per il Comune di Castel d'Azzano con esito positivo.

URL relative ai servizi da validare:

https://www.comune.castel-d-azzano.vr.it/po/po_login.php
https://www.comune.castel-d-azzano.vr.it/po/po_imlogin.php
https://www.comune.castel-d-azzano.vr.it/po/po_pr_login.php

cordiali saluti
Carraro Andrea
Halley Veneto srl

**Comment by damikael** [comment]
Salve,
al fine di recuperare lo stato della pratica, vi chiediamo di inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente e codice IPA;
- Url del metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);
- Riferimento alla presente issue.

Grazie
