### ISSUE TITLE
Controllo metadata - Comune di Borgo San Dalmazzo

### ISSUE THREAD

**Issue by falbesano** [italia/spid#573]
Buongiorno,
per conto del Comune di Borgo San Dalmazzo, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.borgosandalmazzo.cn.it/004025/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
