### ISSUE TITLE
Richiesta verifica tecnica e convenzione Comune di Vellezzo Bellini 

### ISSUE THREAD

**Issue by globogis** [italia/spid#574]
L’ente richiede la verifica tecnica sull'implementazione di SPID (url metadati: https://sportellotelematico.comune.vellezzobellini.pv.it/simplesaml/module.php/saml/sp/metadata.php/spid), la convenzione e il file per la compilazione dell’elenco dei servizi attivi.

**Comment by damikael** [comment]
Salve,
al fine di recuperare lo stato della pratica e procedere con la verifica tecnica occorre seguire la procedura indicata in:
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid

Ovvero inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente e codice IPA;
- Url del metadata;
- Se si tratta di aggiornamento o nuovo metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);

Grazie
