### ISSUE TITLE
Richiesta verifica metadati Comune di Camposampiero

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#575]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Camposampiero.
https://www.comune.camposampiero.pd.it/c028019/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
