### ISSUE TITLE
Richiesta verifica metadati Comune di Majano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#576]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Majano.
https://servizionline.comune.majano.ud.it/c030053/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
