### ISSUE TITLE
Richiesta verifica metadati Unione Territoriale Intercomunale Collinare

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#578]
Buongiorno,
Si richiede la verifica dei metadati per conto dell'Unione Territoriale Intercomunale Collinare.
https://servizionline.collinare.utifvg.it/ae00953/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
