### ISSUE TITLE
Comune di Borgo San Dalmazzo - Problema con IdP Infocert

### ISSUE THREAD

**Issue by falbesano** [italia/spid#579]
Buongiorno,
per conto del Comune di Borgo San Dalmazzo, segnaliamo che l'IdP Infocert non sembra aver recepito la comunicazione dei metadata del comune, di cui all'issue #573 .
Gli altri IdP funzionano correttamente.

Cordial saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo predisposto un ricaricamento del metadata. 
Qualora l'anomalia non si risolvesse entro 24h si prega di indicare la url del servizio in questione e il messaggio di errore restituito dall'Identity Provider

**Comment by falbesano** [comment]
Buongiorno,
da una verifica odierna, il problema sembra risolto. Anche l'IdP Infocert consente l'autenticazione per l'ente in oggetto.

Ringraziando per la tempestiva assistenza, saluto cordialmente
Federico Albesano
