### ISSUE TITLE
Richiesta validazione servizio IIS Torriani di Cremona

### ISSUE THREAD

**Issue by pagolo** [italia/spid#58]
Si richiede validazione servizio e convenzione per adesione a SPID dell'IIS Torriani di Cremona.

https://www.janellotorriani.it/didattica/microspid_metadata

Il servizio è attivato all'url:

https://www.janellotorriani.it/didattica/user

Cordiali saluti.

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone puoi mandare la convenzione

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi via mail direttamente all'IIS Torriani
