### ISSUE TITLE
Richiesta verifica metadati Comune di Gallio

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#580]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Gallio.
https://www.comune.gallio.vi.it/c024042/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
