### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Comune di Vallermosa (SU)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#585]
Buongiorno,
con la presente si richiede la verifica tecnica sull'implementazione di SPID per il Comune di Vallermosa (SU).
Le url dei servizi da validare sono le seguenti:
https://www.vallermosa.gov.it/vallermosa/po/po_login.php
https://www.vallermosa.gov.it/vallermosa/po/po_imlogin.php
https://www.vallermosa.gov.it/vallermosa/po/po_pr_login.php
In attesa di un vostro riscontro, cordiali saluti.

**Comment by damikael** [comment]
Salve,
al fine di recuperare lo stato della pratica, vi chiediamo di inviare una email a spid.tech@agid.gov.it indicando le seguenti informazioni:

- Nome ente e codice IPA;
- Url del metadata;
- Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;
- Contatto riferimento tecnico (nominativo, e-mail, num. di telefono);
- Contatto referente amministrativo (nominativo, e-mail, num. di telefono);
- Riferimento alla presente issue.

Grazie
