### ISSUE TITLE
Richiesta verifica metadati Comune di Valvasone Arzene

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#586]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Valvasone Arzene.
https://servizionline.valvasonearzene.it/ae00813/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
