### ISSUE TITLE
Richiesta verifica metadati Comune di Monselice

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#587]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Monselice.
https://www.comune.monselice.padova.it/c028055/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
