### ISSUE TITLE
Verifica metadata Comune di Striano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#589]
Buongiorno,

Per conto del Comune di Striano

abbiamo predisposto i metadata e pubblicati all'URL

https://striano.comune-online.it/serviziSPID/metadata.xml 

cordiali saluti

Facondini Stefano
Maggioli spa

[metadata_striano-signed.zip](https://github.com/italia/spid/files/2501666/metadata_striano-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
