### ISSUE TITLE
Controllo metadata Comune di Carovigno

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#59]
Buongiorno,
Per conto del Comune di Carovigno, abbiamo predisposto i metadata e pubblicati sulla cartella
https://carovigno.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_carovigno-signed.zip](https://github.com/italia/spid/files/1801832/metadata_carovigno-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
