### ISSUE TITLE
Verifica metadata Comune di Paceco

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#590]
Buongiorno,

Per conto del Comune di Paceco

abbiamo predisposto i metadata e pubblicati all'URL

https://paceco.comune-online.it/serviziSPID/metadata.xml 

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_paceco-signed.zip](https://github.com/italia/spid/files/2501687/metadata_paceco-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
