### ISSUE TITLE
Errore di interazione con IdP

### ISSUE THREAD

**Issue by filippoma** [italia/spid#591]
Salve,
volevo segnalare che abbiamo per sielte il seguente errore:
Error Code: 10
Formato richiesta non corretto.
Contattare il gestore del servizio.

E per Tim schermata bianca.

Il login può essere testato dalla seguente pagina:
https://albo.odg.roma.it/#/areariservataspid

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il problema dovrebbe dipendere dallo spazio posto alla fine del valore dell'attributo Format dell'elemento Issuer presente nell'AuthnRequest:

    Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity "> 

Rimuovendo tale spazio gli Identity Provider dovrebbero rispondere correttamente.

**Comment by filippoma** [comment]
Buongiorno,
grazie mille per il suggerimento. Confermo che per Tim abbiamo risolto il problema ma continua a persistere per Sielte.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 

il suggerimento era quello di rimuovere lo spazio. 

Nelle attuali AuthnRequest risultano rimossi tutti gli attributi dell'elemento Issuer, violando così i requisiti indicati alle pagg. 8-11 del [Regolamento recante le norme tecniche SPID ](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf)

**Comment by filippoma** [comment]
Grazie mille,
ho riscontrato un bug nella libreria https://github.com/italia/spid-sp-simplesamlphp
Abbiamo corretto ed ora funzionano tutti correttamente.
