### ISSUE TITLE
Spid e nuovo dominio EDU.IT

### ISSUE THREAD

**Issue by Mozartino74** [italia/spid#592]
Salve.
La nostra scuola ha implementato SPID sul sito comprensivomontemurlo.gov.it.

Dal 05 ottobre il sito scolastico ha effettuato la migrazione da comprensivomontemurlo.gov.it a icmontemurlo.edu.it (determina n. 36 del 12 febbraio 2018 emanata dall’Agenzia per l’Italia Digitale) e il modulo SPID non risulta funzionante né sul primo sito né sul secondo (saranno entrambi raggiungibili fino all'inizio di luglio 2019) perché quando si prova ad utilizzarlo visualizziamo questo messaggio:

**Errore:
Formato richiesta non corretto - Contattare il gestore del servizio**

Per quanto riguarda il Sistema Pubblico di Identità Digitale è prevista una procedura semplificata? Sarà possibile semplicemente aggiornare l'elenco delle url dei servizi da validare?

Attendo vostre notizie in merito e saluto cordialmente.

**Comment by damikael** [comment]
Salve,
se doveste riscontrare ancora problemi in merito, vi preghiamo di segnalarlo inviando una email all'indirizzo spid.tech@agid.gov.it

Saluti,
Michele D'Amico
