### ISSUE TITLE
 Verifica metadata Comune di Lastra a Signa

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#594]
Buongiorno,

Per conto del Comune di Lastra a Signa

abbiamo predisposto i metadata e pubblicati all'URL

https://lastraasigna.comune-online.it/serviziSPID/metadata.xml 

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_lastraasigna-signed.zip](https://github.com/italia/spid/files/2505821/metadata_lastraasigna-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
