### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Ordine dei giornalisti del Lazio

### ISSUE THREAD

**Issue by filippoma** [italia/spid#595]
Buongiorno,
con la presente si richiede la verifica tecnica sull'implementazione di SPID per l'ordine dei giornalisti del Lazio.

https://albo.odg.roma.it/#/areariservataspid

Grazie mille

**Comment by filippoma** [comment]
Buonasera,
quali sono i tempi per la verifica tecnica?

Grazie mille

**Comment by filippoma** [comment]
Buongiorno,
abbiamo corretto le problematiche riscontrate con la prima verifica, richiediamo la verifica tecnica per la convenzione.
https://albo.odg.roma.it/#/areariservataspid
Grazie mille

**Comment by filippoma** [comment]
Salve,
come da voi suggerito abbiamo utilizzato il progetto di  @damikael  aggiornato all'ulitma verisone disponibile ad oggi.

Potete eseguire i test
https://albo.odg.roma.it/#/areariservataspid

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto via mail
