### ISSUE TITLE
Comunità Montana dei Laghi Bergamaschi - Errore di autenticazione nr16 con IdP Sielte

### ISSUE THREAD

**Issue by globogis** [italia/spid#596]
Buonasera,
si riscontra un errore di autenticazione sul nostro servizio https://www.suap.cmlaghi.bg.it, limitatamente all'Identity Provider Sielte.

L'errore restituito è il nr16.

Si richiede cortesemente una verifica e un nuovo deploy verso Sielte dei metadati, non variati ed esposti all'endpoint https://www.suap.cmlaghi.bg.it/sites/default/files/spid-metadata/cmlaghibg-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Adesso l'IdP in questione risponde correttamente alle AuthnRequest.
