### ISSUE TITLE
Richiesta validazione metadata per l'ASL NAPOLI 2 NORD

### ISSUE THREAD

**Issue by MimmoDany** [italia/spid#597]
Buongiorno,
con la presente si richiede la verifica tecnica dell'implementazione di SPID per  l'ASL NAPOLI 2 NORD.
Le url dei servizi da validare sono le seguenti:

https://portaleservizi.aslnapoli2nord.it/
https://portaleservizi.aslnapoli2nord.it/spid-metadata

In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

come indicato sul [sito ufficiale SPID nella pagina dedicata ai Service Provider](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), la verifica dell'implementazione può essere richiesta solo dopo che sia stato presentato e validato da AgID il metadata della P.A. richiedente, e dopo che quest'ultima abbia verificato in proprio la completa e corretta interazione da e verso gli Identity Provider, in accordo con la documentazione tecnica SPID.  

Poichè per la P.A in oggetto non è stata presentato sinora nessun metadata, la richiesta viene modificata d'ufficio in richiesta di validazione del metadata.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by MimmoDany** [comment]
Come è possibile verificare se tutto ok per proseguire con la parte amministrativa?
Grazie.
