### ISSUE TITLE
Aggiornamento metadati Istituto Zooprofilattico G. Caporale

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#598]
Salve, chiedo l'aggiornamento dei metadati per l'Istituto Zooprofilattico dell'Abruzzo e del Molise G. Caporale.

I metadat sono reperibili al seguente URL.

https://test.vetinfo.it/cas/metadata.xml

Grazie per la disponibilità.
Saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
