### ISSUE TITLE
Verifica metadata Comune di Caronno Pertusella

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#599]
Buongiorno,

Per conto del Comune di Caronno Pertusella

abbiamo predisposto i metadata e pubblicati all'URL

https://caronnopertusella.comune-online.it/serviziSPID/metadata.xml 

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_caronnopertusella-signed.zip](https://github.com/italia/spid/files/2518848/metadata_caronnopertusella-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per il comune di oggetto (presentato tramite la [issue 205](https://github.com/italia/spid/issues/205).

Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).

Staff Tecnico SPID
Agenzia per l'Italia Digitale
