### ISSUE TITLE
[Validazione metadata] Cigliano

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#6]
Buongiorno,
vorrei chiedere, gentilmente, a che punto si trova la validazione e deploy su Idp del metadata di Cigliano.
Dall'help desk (n° ticket X2R-GS4-...) mi segnala in lavorazione da giovedi u.s.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il metadata è stato deployato presso gli Identity Provider.

buona giornata

Staff Tecnico SPID
Agenzia per l'Italia Digitale

**Comment by Eduardo1977** [comment]
Grazie per la tempestività. In effetti, ora il task risulta "Risolto." Ci avvisa anche che 

> Il metadata è stato deployato presso gli Identity Provider

 . Adesso dobbiamo ancora attendere per riprovare? Al momento il collegamento non funziona con nessun Idp.

**Comment by AntonioGiovanniSchiavone** [comment]
Potrebbe dipendere da un errore sull'AuthnRequest.
Che messaggio viene restituito?
Può fornirci una copia dell'AuthnRequest inviata o la url del servizio?

Staff Tecnico SPID
Agenzia per l'Italia Digitale

**Comment by umbros** [comment]
Caricamento avvenuto,
ogni ulteriore supporto su altra issue

Umberto Rosini
Agenzia per l'Italia Digitale
