### ISSUE TITLE
Controllo metadata: Comunità Montana di Valle Camonica

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#60]
Buongiorno, per conto della Comunità Montana di Valle Camonica siamo richiedere il controllo del seguente metadata:
https://www.sportellotelematico.cmvallecamonica.bs.it/simplesaml/module.php/saml/sp/metadata.php/cmvallecamonica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
