### ISSUE TITLE
Verifica metadata Comune di Sondrio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#600]
Buongiorno,

Per conto del Comune di Sondrio

abbiamo predisposto i metadata e pubblicati all'URL

https://sondrio.comune-online.it/serviziSPID/metadata.xml 

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_sondrio-signed.zip](https://github.com/italia/spid/files/2524992/metadata_sondrio-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
