### ISSUE TITLE
Comune di Alatri - Errori con IdP TIM e Infocert

### ISSUE THREAD

**Issue by globogis** [italia/spid#601]
Buongiorno,
si riscontra un malfunzionamento dei servizi per il Comune di Alatri con gli Identity Provider TIM e Infocert ID. Il primo all'invio dell'AuthnRequest restituisce un errore 403, il secondo un errore generico "Formato richiesta non corretto".

Si richiede verso questi IdP un nuovo deploy dei metadati, non variati ed esposti all'endpoint https://sportellotelematico.comune.alatri.fr.it/simplesaml/module.php/saml/sp/metadata.php/alatri

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Gli Identity Provider hanno eseguito un ricaricamento del metadata del comune in oggetto.
Qualora il problema persistesse, si prega di fornire la url del servizio in questione in modo da poter effettuare delle analisi dettagliate.
