### ISSUE TITLE
Richiesta verifica metadati Comune di Preganziol

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#602]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Preganziol.
https://servizionline.comune.preganziol.tv.it/c026063/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
