### ISSUE TITLE
Richiesta verifica metadati Comune di Villa del Conte

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#603]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Villa del Conte.
https://www.comune.villa-del-conte.pd.it/c028101/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
