### ISSUE TITLE
Test interni con Spid

### ISSUE THREAD

**Issue by matteocontino** [italia/spid#606]
Salve a tutti.
Chiedo gentilmente che mi venga indicato dove reperire le informazioni per configurare un ambiente di test per i servizi spid.
Ci troviamo in ambiente windows. Linguaggio di programmazione .Net.

Ringrazio anticipatamente.
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
L'ambiente di test SPID  è disponibile:

- Come docker per l'installazione in locale presso una vostro ambiente di sviluppo ( https://github.com/italia/spid-testenv-docker ),
- Come ambiente online: ( Backend per il caricamento del metadata:  https://idp.spid.gov.it:8080,   Identity provider di test -  https://idp.spid.gov.it:9443, metadata idp -   https://idp.spid.gov.it:8080/assets/idp-metadata.xml). In questo caso è necessario preventivamente impostare l'alias da spid-testenv-identityserver verso  idp.spid.gov.it tramite file hosts
