### ISSUE TITLE
Richiesta verifica metadati Comune di Cordignano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#608]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Cordignano.
https://www.comune.cordignano.tv.it/c026022/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
