### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Castel Mella

### ISSUE THREAD

**Issue by globogis** [italia/spid#609]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.castelmella.bs.it/simplesaml/module.php/saml/sp/metadata.php/castelmella

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
