### ISSUE TITLE
Controllo metadata: comune di Verdellino

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#61]
Buongiorno, per conto del comune di Verdellino siamo a richiedere il controllo del metadata seguente:
https://sportellotelematico.comune.verdellino.bg.it/simplesaml/module.php/saml/sp/metadata.php/verdellino

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
