### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Besnate

### ISSUE THREAD

**Issue by globogis** [italia/spid#610]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportelloedilizia.comune.besnate.va.it/simplesaml/module.php/saml/sp/metadata.php/besnate

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
