### ISSUE TITLE
Validazione Metadata Comune di Romentino

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#611]
Buongiorno,
abbiamo inviato l'url del metadata a spid.tech@agid.gov.it per l'attivazione SPID presso il Comune di Romentino (NO).
Chiediamo, gentilmente, la validazione del metadata e deploy presso gli IdP.
Grazie

Cordiali saluti 

Servizi Locali S.p.A.

**Comment by Eduardo1977** [comment]
Buongiorno, a seguito delle problematiche segnalateci via mail, vi chiediamo, gentilmente, di validare il nuovo metadata

**Comment by Eduardo1977** [comment]
Buongiorno,
per l'attivazione SPID presso il Comune di Romentino (NO) chiediamo la validazione del metadata e il deploy presso gli IdP.
Abbiamo corretto il precedente ENTITYID, che riportava erroneamente http.
Scusate per la svista, speriamo fosse questo il problema. 
Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
