### ISSUE TITLE
Validazione metadata per comune di Cantù

### ISSUE THREAD

**Issue by andreafantini** [italia/spid#612]
Buongiorno,
si richiede la validazione dei metadata per il servizio WIFI del comune di Cantù e la relativa comunicazione di questi agli IDP autorizzati SPID.

I metadata sono disponibili a questo URL:

https://idpcgel.crs.lombardia.it/gelmetadata/13041

Rimaniamo in attesa di un vs. cordiale riscontro.
Saluti
Andrea Fantini
Caligoo SRL.

**Comment by andreafantini** [comment]
Grazie dell'informazione, sentiamo direttamente il Dott. Frigerio.
Una domanda: una volta che avremo i metadata aggiornati con il servizio aggiunto ripostiamo la richiesta su questa issue e via e-mail all'indirizzo : spid.tech@agid.gov.it ?

Grazie 
Cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera,
 si potete ripostare la richiesta su questa issue.
