### ISSUE TITLE
Richiesta controllo metadata - Comune di Settala (MI)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#614]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:

https://server-online.comune.settala.mi.it/c015210/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
