### ISSUE TITLE
Aggiornamento metadati SPID - Consorzio Informatica e Territorio srl

### ISSUE THREAD

**Issue by ale-rinaldi** [italia/spid#618]
Buongiorno,
in seguito a upgrade del servizio, si richiede l'aggiornamento dei metadati pubblicati per il Consorzio Informatica e Territorio srl (codice iPA: citsrl) con quelli pubblicati all'endpoint:

https://www.portaletelematico.it/simplesaml/module.php/saml/sp/metadata.php/spid

Si richiede di eseguire l'operazione con la massima urgenza in quanto l'utenza è al momento impossibilitata ad accedere.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
