### ISSUE TITLE
Importo voucher 18App superiore alla spesa

### ISSUE THREAD

**Issue by mari-sa** [italia/spid#619]
Salve, 
Vi scrivo per chiedervi cosa accade in caso di utilizzo, per acquisti TicketOne, di un buono superiore alla spesa. Il buono viene rimborsato? Grazie per l'attenzione. @psmiraglia-agid

**Comment by psmiraglia-agid** [comment]
Salve @mari-sa, questo e' un canale dedicato all'assistenza tecnica relativa all'integrazione e all'implementazione di SPID. Per ottenere informazioni relative alla 18App, la invito a consultare il sito https://www.18app.italia.it. Una buona giornata, Paolo.
