### ISSUE TITLE
Richiesta di validazione dei metadati - Unione Comuni Lombardi Bassa Bresciana Occidentale

### ISSUE THREAD

**Issue by globogis** [italia/spid#624]
Buongiorno,
per conto dell'Unione si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.unionecomunibbo.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
