### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Cornuda (TV)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#625]
Buongiorno,
per conto del COmune di Cornuda (TV) si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.cornuda.tv.it/spid/metadata.xml

**Comment by comuneweb** [comment]
Buongiorno,
abbiamo corretto il metadata secondo le Vs. indicazioni e ripubblicato all'indirizzo https://www.comune.cornuda.tv.it/spid/metadata.xml

Restiamo in attesa di vostre indicazioni.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
