### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Lodi

### ISSUE THREAD

**Issue by globogis** [italia/spid#626]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.lodi.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by globogis** [comment]
Buongiorno, è possibile avere riscontri?

**Comment by globogis** [comment]
Buongiorno, rinnovo cortesemente la presa in incarico dell'attività.

**Comment by globogis** [comment]
Buongiorno,
abbiamo generato i metadati congiunti con i servizi di Regione Lombardia, esposti all'endpoint:

https://sportellotelematico.comune.lodi.it/sites/default/files/spid-metadata/lodi-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
