### ISSUE TITLE
Verifica metadata Comune di Trenzano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#628]
Buongiorno,

Per conto del Comune di Trenzano
[metadata_trenzano-signed.zip](https://github.com/italia/spid/files/2586410/metadata_trenzano-signed.zip)
abbiamo predisposto i metadata e pubblicati all'URL

https://trenzano.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
