### ISSUE TITLE
Richiesta verifica metadati Comune di Santa Maria di Sala

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#629]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Santa Maria di Sala.
https://www.comune-santamariadisala.it/c027035/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
