### ISSUE TITLE
Richiesta verifica metadati Comune di Rive d'Arcano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#630]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Rive d'Arcano.
https://servizionline.comune.rivedarcano.ud.it/c030095/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
