### ISSUE TITLE
 Verifica metadata Comune di Casalmaggiore

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#632]
Buongiorno,

Per conto del Comune di Casalmaggiore

abbiamo predisposto i metadata e pubblicati all'URL

https://casalmaggiore.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_casalmaggiore-signed.zip](https://github.com/italia/spid/files/2594568/metadata_casalmaggiore-signed.zip)

**Comment by sfacondini** [comment]
Buongiorno,
abbiamo provveduto all'aggiornamento dei metadata  del primo SP accodando i nostri riferimenti 
Allego metadata aggiornato.
Cordiali saluti
Facondini Stefano 
Maggioli Spa
[metadata_casalmaggiore2SP_new-signed.zip](https://github.com/italia/spid/files/2652102/metadata_casalmaggiore2SP_new-signed.zip)

**Comment by sfacondini** [comment]
Sono pubblicati all'URL
https://casalmaggiore.comune-online.it/serviziSPID/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
