### ISSUE TITLE
Verifica Metadata  Comune di Monserrato

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#634]
Buongiorno,
per conto del Comune di Monserrato (CA) si richiede la verifica del metadata pubblicato su 
https://servizionline.comune.monserrato.ca.it/spid/metadata_monserrato-signed.xml 

Cordiali saluti,
Mariano Carta
Arionline srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
