### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Unione Comuni Lombardi Bassa Bresciana Occidentale 

### ISSUE THREAD

**Issue by globogis** [italia/spid#636]
L’unione richiede la verifica tecnica sull'implementazione di SPID (url metadati:
https://sportellotelematico.unionecomunibbo.it/simplesaml/module.php/saml/sp/metadata.php/spid), la convenzione e il file per la compilazione dell’elenco dei servizi attivi.

**Comment by globogis** [comment]
ERRATA CORRIGE: i metadati corretti sono esposti all'endpoint https://sportellotelematico.unionecomunibbo.it/sites/default/files/spid-metadata/unionebbo-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Closed in #699
