### ISSUE TITLE
Richiesta verifica metadati Comune di Marano Vicentino

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#637]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Marano Vicentino
https://www.comune.marano.vi.it/c024056/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
