### ISSUE TITLE
Richiesta controllo metadata - Comunità Montana Valle Seriana (BG) 

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#639]
Con la presente si richiede la verifica della validità del metadata presente all'url:

https://www.servizi.cmvalleseriana.bg.it/cmvalseriana/spid-metadata.xml

Il servizio in oggetto è stato realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
