### ISSUE TITLE
Controllo metadata Comune di Fiumicino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#64]
Buongiorno,
Per conto del Comune di Fiumicino, abbiamo predisposto i metadata e pubblicati sulla cartella
https://fiumicino.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_fiumicino-signed.zip](https://github.com/italia/spid/files/1802941/metadata_fiumicino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
