### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Ceccano (FR)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#640]
Buongiorno,

si richiede la verifica dei metadati per conto del Comune di Ceccano
http://comune.ceccano.fr.it/upload/n201597.xml

Grazie
We-COM Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
