### ISSUE TITLE
Richiesta controllo metadata - Comune di Gussago (BS)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#641]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:

https://www.comune.gussago.bs.it/c017081/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
