### ISSUE TITLE
Comunicazione URL metadata - I.C. Canneto sull'Oglio

### ISSUE THREAD

**Issue by rickygil** [italia/spid#642]
Salve,
vorrei chiedere la verifica dei metadata per i servizi SPID sul sito: www.iccanneto.edu.it.
URL Metadata: https://www.iccanneto.edu.it/spid/module.php/saml/sp/metadata.php/default-sp
Grazie,
Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
