### ISSUE TITLE
Agenzia del Demanio - nuovo IDP Lepida

### ISSUE THREAD

**Issue by mciccozzi** [italia/spid#643]
Per poter rilasciare gli aggiornamenti per il nuovo IDP Lepida, chiediamo, cortesemente, il consolidamento da parte di Lepida del metadata demanio disponibile all’indirizzo: 
https://sp.agenziademanio.it/metadata

Cordiali saluti
Maura Ciccozzi

**Comment by gianluca-casati-lepida** [comment]
Buongiorno, il service provider dell'agenzia del demanio era già stato configurato utilizzando i metadati presenti invece all'indirizzo https://ifte.agenziademanio.it/metadata, indirizzo trovato in un file contenente tutti i service provider integrati in SPID e fornito da @umbros.
Chiedo conferma che invece l'url corretto dei metadati è invece https://sp.agenziademanio.it/metadata, cosicchè possiamo aggiornare la configurazione

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

AgID ha già provveduto a comunicare a l'IdP Lepida le ultime versioni dei metadata di tutti i Service Provider attivi.
In particolare, per quanto riguarda l'Agenzia del Demanio, è stato comunicato il metadata notificato in data 21 Settembre 2018 tramite la [issue 524](https://github.com/italia/spid/issues/524).
La url https://sp.agenziademanio.it/metadata risulta essere un alias per l'indirizzo https://ifte.agenziademanio.it/metadata, o puntare ad una copia identica dello stesso metadata.
Stiamo verificando la corretta interazione fra SP ed IdP.
