### ISSUE TITLE
Verifica metadata Comune di Altopascio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#646]
Buongiorno,

Per conto del Comune di Altopascio

abbiamo predisposto i metadata e pubblicati all'URL

https://altopascio.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_altopascio-signed.zip](https://github.com/italia/spid/files/2614686/metadata_altopascio-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera, 
il file non risulta raggiungibile

**Comment by sfacondini** [comment]
Buonasera, 
il problema è stato risolto 
adesso il metadata è raggiungibile
cordiali saluti
Facondini Stefano 
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
