### ISSUE TITLE
Verifica metadata Comune di Concorezzo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#648]
Verifica metadata Comune di Concorezzo

Buongiorno,

Per conto del Comune di Concorezzo

abbiamo predisposto i metadata e pubblicati all'URL

https://concorezzo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_concorezzo-signed.zip](https://github.com/italia/spid/files/2614707/metadata_concorezzo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
