### ISSUE TITLE
Verifica metadata Comune di Ciriè

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#649]
Buongiorno,

Per conto del Comune di Ciriè

abbiamo predisposto i metadata e pubblicati all'URL

https://cirie.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_cirie-signed.zip](https://github.com/italia/spid/files/2614712/metadata_cirie-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
