### ISSUE TITLE
Comunicazione metadata Comune di Pian Camuno

### ISSUE THREAD

**Issue by dfranzoni** [italia/spid#65]
Buongiorno,
Per conto del Comune di Pian Camuno, abbiamo predisposto i metadata al seguente indirizzo:
https://idpcgel.crs.lombardia.it/gelmetadata/17142

Cordialmente
Davide Franzoni

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
