### ISSUE TITLE
Verifica metadata Comune di Cornate d'Adda

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#650]
Buongiorno,

Per conto del Comune di Cornate d'Adda

abbiamo predisposto i metadata e pubblicati all'URL

https://cornatedadda.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_cornatedadda-signed.zip](https://github.com/italia/spid/files/2614762/metadata_cornatedadda-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
