### ISSUE TITLE
Richiesta verifica metadati Comune di Sarego

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#654]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sarego.
https://www.sarego.gov.it/c024098/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
