### ISSUE TITLE
Verifica metadata Provincia di Lucca

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#656]
Buongiorno,

Per conto della Provincia di Lucca

abbiamo predisposto i metadata e pubblicati all'URL

https://lucca.provincia-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_luccaprovincia-signed.zip](https://github.com/italia/spid/files/2623679/metadata_luccaprovincia-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
