### ISSUE TITLE
Richiesta di aggiornamento metadati - Comune di Torbole Casaglia

### ISSUE THREAD

**Issue by globogis** [italia/spid#658]
Buongiorno,
in seguito ad aggiornamento del servizo, si richiede il deploy di questi metadati aggiornati per conto del Comune di Torbole Casaglia:

https://sportellotelematico.comune.torbole-casaglia.bs.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
