### ISSUE TITLE
INAIL errore Configurazione nuovo IDP LEPIDA

### ISSUE THREAD

**Issue by fquattropani-dxc** [italia/spid#659]
Salve,
abbiamo appena implementato le configurazioni LEPIDA sulla piattaforma SPID di INAIL, ma, da un primo test, riceviamo l'errore:
Formato richiesta non corretto - contattare il fornitore del servizio
sulla pagina:
https://id.lepida.it/idp/profile/SAML2/Redirect/SSO?
Già in fase di invio del nostro SAML di Authnrequest.
E' possibile sapere da parte di LEPIDA che cosa risulta errato nel nostro SAML?

Grazie mille.

Cordiali Saluti,
Fabio Massimo Quattropani

**Comment by gianluca-casati-lepida** [comment]
Buongiorno,
riesce a fornirci l'url di accesso al servizio in maniera tale da poter replicare il caso d'uso?
Grazie mille

> Salve,
> abbiamo appena implementato le configurazioni LEPIDA sulla piattaforma SPID di INAIL, ma, da un primo test, riceviamo l'errore:
> Formato richiesta non corretto - contattare il fornitore del servizio
> sulla pagina:
> https://id.lepida.it/idp/profile/SAML2/Redirect/SSO?
> Già in fase di invio del nostro SAML di Authnrequest.
> E' possibile sapere da parte di LEPIDA che cosa risulta errato nel nostro SAML?
> 
> Grazie mille.
> 
> Cordiali Saluti,
> Fabio Massimo Quattropani

Buongiorno,
riesce a fornirci l'url di accesso al servizio in maniera tale da poter replicare il caso d'uso?
Grazie mille

**Comment by fquattropani-dxc** [comment]
Salve,
Riporto l’url:


https://fwsspid.inail.it/affwebservices/public/saml2authnrequest?ProviderID=https://id.lepida.it/idp/shibboleth&AssertionConsumerServiceIndex=0&ForceAuthn=yes&NameQualifier=fwsspid.inail.it&AttributeConsumingServiceIndex=0


Grazie mille
Cordiali Saluti

**Comment by fquattropani-dxc** [comment]
Salve,
Riporto l’url:


https://fwsspid.inail.it/affwebservices/public/saml2authnrequest?ProviderID=https://id.lepida.it/idp/shibboleth&AssertionConsumerServiceIndex=0&ForceAuthn=yes&NameQualifier=fwsspid.inail.it&AttributeConsumingServiceIndex=0


Grazie mille
Cordiali Saluti

Fabio Massimo Quattropani
Global Delivery Organization - Software Services Italy

T +39 06-5487-4139

DXC Technology
Via Giamaica 7
Pomezia, Rome 00071,Italy
c/o INAIL Via S. Regina Degli Apostoli

dxc.technology<http://www.dxc.technology/> / Twitter<https://twitter.com/dxctechnology> / Facebook<https://www.facebook.com/DXCTechnology/> / LinkedIn<https://www.linkedin.com/company/dxctechnology>

**Comment by gianluca-casati-lepida** [comment]
Il problema è stato risolto.
