### ISSUE TITLE
Aggiornamento metadata Comune di Ostuni

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#66]
Buonasera,

chiederei l'aggiornamento dei metadata per i servizi online del Comune di Ostuni.
Come da istruzioni, comunicherò l'url tramite email a spid.tech@agid.gov.it

Grazie. Saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

**Comment by dgpadev** [comment]
Buongiorno,

segnalo che l'IdP Register non redirige all'Assertion Consumer Service indicato nei metadata, ma ad un ACS indicato in precedenza. 
Per tutti gli altri invece il funzionamento è corretto.

Grazie.
Saluti

**Comment by dgpadev** [comment]
Buongiorno,

segnalo che l'IdP Register redirige a volte al nuovo url, altre volte all'url precedente. Per gli altri IdP invece tutto ok.

Chiederei inoltre di aggiornare nuovamente i metadata per tutti gli IdP: sono stati modificate le Location di SingleLogoutService e AssertionConsumerService.

Grazie.

Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Riapro il ticket

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
