### ISSUE TITLE
Verifica metadata Comune di Avigliana

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#662]
Verifica metadata Comune di Avigliana

Buongiorno,

Per conto del Comune di Avigliana

abbiamo predisposto i metadata e pubblicati all'URL

https://avigliana.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_avigliana-signed.zip](https://github.com/italia/spid/files/2632847/metadata_avigliana-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
