### ISSUE TITLE
Verifica metadata Comune di Castagneto Carducci

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#663]
Buongiorno,

Per conto del Comune di Castagneto Carducci

abbiamo predisposto i metadata e pubblicati all'URL

https://castagnetocarducci.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_castagneto-signed.zip](https://github.com/italia/spid/files/2633020/metadata_castagneto-signed.zip)

**Comment by sfacondini** [comment]
Mi scuso per il refuso in sede di compilazione metadata provvediamo alla correzione
Grazie della segnalazione
Facondini Stefano 
Maggioli Spa
[metadata_castagneto-signed.zip](https://github.com/italia/spid/files/2636300/metadata_castagneto-signed.zip)

**Comment by sfacondini** [comment]
Buonasera, 
il problema è stato corretto
cordiali saluti
Facondini Stefano 
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
