### ISSUE TITLE
Verifica metadata Comune di Caltanisetta

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#664]
Buongiorno,

Per conto del Comune di Caltanisetta

abbiamo predisposto i metadata e pubblicati all'URL

https://caltanissetta.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
 
[metadata_caltanisetta-signed.zip](https://github.com/italia/spid/files/2633025/metadata_caltanisetta-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
