### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Abano Terme

### ISSUE THREAD

**Issue by globogis** [italia/spid#666]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sue.abanoterme.net/simplesaml/module.php/saml/sp/metadata.php/abanoterme

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
