### ISSUE TITLE
Richiesta di validazione dei metadati - Comuni di Dello e San Zeno Naviglio

### ISSUE THREAD

**Issue by globogis** [italia/spid#668]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.dellosanzenonaviglio.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera,
Il Comune di Dello ([Codice IPA c_d270](https://www.indicepa.gov.it/ricerca/n-dettaglioamministrazione.php?cod_amm=c_d270)) ed il comune di San Zeno Naviglio (([Codice IPA c_i412](https://www.indicepa.gov.it/ricerca/n-dettaglioamministrazione.php?cod_amm=c_i412)) risultano essere due Comuni distinti.

Poiché non è possibile stipulare una Convenzione ( e quindi un metadata ) a nome di più P.A., qualora due o più Comuni decidessero di creare una associazione informale ( ossia non costituita come Unione di Comuni, Comunità montana o altra tipo di associazione formale) per la condivisione di alcuni servizi, è necessario che uno dei predetti comuni si erga a "capofila" dell'associazione informale, svolgendo a proprio nome il percorso di adesione a SPID ed integrando nel proprio metadata, oltre ad eventuali servizi propri, anche i servizi dell'associazione informale. Analogamente, tramite Convenzione il  Comune capofila si assumerà gli oneri sia per eventuali servizi propri che per i servizi dell'associazione informale.

Nel caso specifico, poiché il dominio www.dellosanzenonaviglio.it è intestato al Comune di Dello, la soluzione più naturale sembra essere che sia questo Comune ad intraprendere il percorso di adesione a SPID  secondo quanto esposto precedentemente esposto.

**Comment by globogis** [comment]
Buongiorno,
vi confermo che il capofila sarà il Comune di Dello, infatti i metadati e il certificato in essi contenuto appartengono al Comune di Dello.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
