### ISSUE TITLE
controllo metadata Corpo Nazionale Vigili del Fuoco

### ISSUE THREAD

**Issue by VigilfuocoSpid** [italia/spid#670]
Si richiede nuova verifica del metadata aggiornato in data 30 Novembre 2018

Link per verifica
https://sso.vigilfuoco.it/spid/metadata-firmato.xml
grazie

**Comment by VigilfuocoSpid** [comment]
Si richiede nuova verifica del metadata aggiornato in data 30 Novembre 2018

Link per verifica
https://sso.vigilfuoco.it/spid/metadata-firmato.xml
grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
