### ISSUE TITLE
Verifica metadata Unione Comuni Lombarda San Giorgio e Bigarello

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#671]
Buongiorno,

Per conto dell' Unione Comuni Lombarda San Giorgio e Bigarello

abbiamo predisposto i metadata e pubblicati all'URL

https://sangiorgiobigarello.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_sangiorgiobigarello-signed.zip](https://github.com/italia/spid/files/2640368/metadata_sangiorgiobigarello-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
