### ISSUE TITLE
Verifica metadata Comune di  Borgo San Dalmazzo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#673]
Buongiorno,

Per conto del Comune di  Borgo San Dalmazzo

abbiamo predisposto i metadata e pubblicati all'URL

https://borgosandalmazzo.multeonline.it/serviziSPID/metadata.xml
i metadata sono stati aggiornati con l'aggiunta di un secondo SP
[metadata_borgosandalmazzo2SP_new-signed.zip](https://github.com/italia/spid/files/2640432/metadata_borgosandalmazzo2SP_new-signed.zip)

cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
