### ISSUE TITLE
Verifica metadata Comune di  Cuneo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#674]
Buongiorno,

Per conto del Comune di  Cuneo

abbiamo predisposto i metadata e pubblicati all'URL

https://cuneo.comune-online.it/serviziSPID/metadata.xml

si tratta di aggiunta di un secondo SP a metadata esistenti 

[metadata_cuneo2SP_new-signed.zip](https://github.com/italia/spid/files/2640469/metadata_cuneo2SP_new-signed.zip)
cordiali saluti

Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
