### ISSUE TITLE
Anomalia autenticazione IDP Poste  per SP Provincia di Lucca

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#675]
Buon pomeriggio,
recentemente sono stati validati i metadata della provincia di Lucca e dispiegati presso tutti gli IDP. (#656)
Risultano tutti correttamente funzionanti salvo Poste.
Il problema è tipico di un mancato recepimento dei metadata  per cui si richiedere un nuovo caricamento su questo IDP.
Cordiali saluti
Facondini Stefano 
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo predisposto un ricaricamento del metadata in oggetto. Qualora il problema persistesse, si prega di fornire il link al servizio in oggetto.
