### ISSUE TITLE
ATS Milano Città Metropolitana - problema metadata IdP

### ISSUE THREAD

**Issue by scubla88** [italia/spid#676]
Buongiorno,
stiamo riscontrando un problema con l'utilizzo di SPID di ATS Milano.
L'errore che viene dato alla selezione di qualsiasi IdP è il seguente:

https://spid.ats-milano.it/error?now=Tue%20Dec%20%204%2009%3A24%3A59%202018&requestURL=https%3A%2F%2Fspid.ats-milano.it%2Fiam%2FLogin&errorType=opensaml%3A%3Asaml2md%3A%3AMetadataException&errorText=Unable%20to%20locate%20metadata%20for%20identity%20provider%20(https%3A%2F%2Fposteid.poste.it)&entityID=https%3A%2F%2Fposteid.poste.it&eventType=Login

Ovvero: **Unable to locate metadata for identity provider**

Il metadata è disponibile all'indirizzo https://spid.ats-milano.it/metadata e non è stato modificato. Fino a ieri sera funzionava correttamente.

Riuscite a darci assistenza?

Grazie,
Fabio Scubla

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera,

Il mancato invio di un messaggio SAML di AuthnRequest e l'analisi dell'errore restituito al browser dal vostro sistema (che riportiamo nell'immagine allegata) , indicano che il problema evidenziato dipende dal mancato caricamento dei metadata degli Identity Provider da parte del vostro Service Provider, e non dal viceversa, come da voi supposto.

![atsmilano](https://user-images.githubusercontent.com/3876198/49458617-75c5b080-f7ed-11e8-83b3-ebf8f0805f0f.png)
