### ISSUE TITLE
Richiesta verifica metadati Comune di Volpago del Montello

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#677]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Volpago del Montello.
https://www.comune.volpago-del-montello.tv.it/c026093/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
