### ISSUE TITLE
Verifica metadata Comune di Lonigo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#678]
Buongiorno,

per conto del Comune di Lonigo

abbiamo predisposto i metadata e pubblicati all'URL

https://lonigo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli spa
[metadata_lonigo-signed.zip](https://github.com/italia/spid/files/2645006/metadata_lonigo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
