### ISSUE TITLE
Verifica metadata Comune di Cervaro

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#679]
Buongiorno,

per conto del Comune di Cervaro

abbiamo predisposto i metadata e pubblicati all'URL

https://cervaro.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
 
[metadata_cervaro-signed.zip](https://github.com/italia/spid/files/2645010/metadata_cervaro-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
