### ISSUE TITLE
Aggiornamento metadata Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#68]
Buongiorno
Si richiede l'aggiornamento dei metadata alla url
[https://spid.rupar.puglia.it/regione-puglia-metadata.xml](https://spid.rupar.puglia.it/regione-puglia-metadata.xml)

Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, 

effettuando una verifica sul protocollo  https  delle url dei SingleLogoutService,  abbiamo verificato un Certificate name mismatch sul dominio https://www.dms.puglia.it
Vi preghiamo di correggere l'errore.

**Comment by marangiom** [comment]
Salve
i certificati sono stati corretti.
Al momento su quel server non è presente il service provider, verrà installato e configurato a brevissimo da parte del fornitore del servizio; chiedo se è possibile comunque il deploy presso i gestori, per accorciare i tempi.
grazie
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
