### ISSUE TITLE
Richiesta verifica metadata del Comune di Arese

### ISSUE THREAD

**Issue by herald-si** [italia/spid#686]
Richiesta verifica metadata del Comune di Arese
Si chiede cortesemente la verifica del metadata del Comune di Arese, inviato per email.

Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Inviata mail con indicazioni sull'errore rilevato

**Comment by herald-si** [comment]
Inviata mail con link al nuovo metadata da verificare e deployare presso gli IdP.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
