### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Civitavecchia

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#69]
Buongiorno,
abbiamo condotto i test interni per il Comune di Civitavecchia con esito positivo
i servizi soggetti ad autenticazione sono erogati  dal portale:

https://civitavecchia.comune-online.it/c/portal/login

cordiali saluti
Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.
