### ISSUE TITLE
Richiesta verifica metadati Comune di Valdobbiadene

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#694]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Valdobbiadene.
https://www.comune.valdobbiadene.tv.it/c026087/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
