### ISSUE TITLE
Controllo metadata - Provincia di Asti

### ISSUE THREAD

**Issue by falbesano** [italia/spid#695]
Buongiorno,
per conto della Provincia di Asti, richiediamo la verifica dei metadati pubblicati all'url:
https://www.provincia.asti.it/system/attachments/attachment/attachment/51926/metadataSPID.xml

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
