### ISSUE TITLE
Mancato recepimento metadata SP Caronno Pertusella  da  IDP Lepida

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#697]
Buongiorno, 
i metadata del Comune di Caronno Pertusella approvati di recente #672 sono stati recepiti da tutti gli IDP 
salvo Lepida
Si richiede un nuovo dispiegamento presso Lepida
Cordiali Saluti
Facondini Stefano 
Maggioli Spa

**Comment by alessiotosi** [comment]
Buongiorno, 

l'SP del Comune di Caronno Pertusella è stato integrato presso il nostro idp in data 4 dicembre. 
Le chiederei cortesemente se ci potesse dare qualche dettaglio in più sul tipo di problema che riscontrate o anche il link di accesso al vostro SP in maniera tale da poter fare dei test. 

Cordiali saluti,
Alessio Tosi

**Comment by sfacondini** [comment]
Buongiorno, AGID ha approvato un nuovo metadata per Caronno Pertusella (con un secondo SP accodato al primo) il 10/12 quindi immagino che quello che avete acquisito in data 4/12 sia privo dei nuovi certificati.Il nuovo metadata ha lo stesso entityID ma aggiunge un nuovo certificato e nuovi endpointsL'errore è tipico del mancato recepimento del certificato.Impossibile stabilire l’autenticità della richiesta di autenticazione / Formato richiesta non correttoContattare il gestore del servzio Il nuovo metadata è in allegato  ed è scaricabile da:https://caronnopertusella.comune-online.it/serviziSPID/metadata.xmlpuò trovare i rifermenti su github   #672 cordiali saluti Facondini Stefano rea Portali ed e-GovernmentTel.: 0541.628399Mob. 329 0528602e-mail: sfacondini@maggioli.ithttp://www.maggioli.it/informatica/-----Alessio Tosi <notifications@github.com> ha scritto: -----A: italia/spid <spid@noreply.github.com>Da: Alessio Tosi <notifications@github.com>Data: 11/12/2018 12.37PMCc: sfacondini <sfacondini@maggioli.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/spid] Mancato recepimento metadata SP Caronno Pertusella  da  IDP Lepida (#697)Buongiorno,

l'SP del Comune di Caronno Pertusella è stato integrato presso il nostro idp in data 4 dicembre.

Le chiederei cortesemente se ci potesse dare qualche dettaglio in più sul tipo di problema che riscontrate o anche il link di accesso al vostro SP in maniera tale da poter fare dei test.

Cordiali saluti,

Alessio Tosi

**Comment by alessiotosi** [comment]
Buongiorno, 

grazie per il chiarimento. 

Abbiamo reintegrato il servizio con i metadata aggiornati, vi chiederei cortesemente di riprovare ora. 

Cordiali saluti,
Alessio Tosi

**Comment by sfacondini** [comment]
purtroppo rileviamo ancora il problemail portale non è ancora pubblicato per cui non riesco a girarle un URL di test allego però la request SAMLcordiali salutiFacondini Stefano  -----Alessio Tosi <notifications@github.com> ha scritto: -----A: italia/spid <spid@noreply.github.com>Da: Alessio Tosi <notifications@github.com>Data: 11/12/2018 03.00PMCc: sfacondini <sfacondini@maggioli.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/spid] Mancato recepimento metadata SP Caronno Pertusella  da  IDP Lepida (#697)Buongiorno,
grazie per il chiarimento.
Abbiamo reintegrato il servizio con i metadata aggiornati, vi chiederei cortesemente di riprovare ora.
Cordiali saluti,
Alessio Tosi
