### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Saronno

### ISSUE THREAD

**Issue by globogis** [italia/spid#698]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.saronno.va.it/simplesaml/module.php/saml/sp/metadata.php/saronno

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
