### ISSUE TITLE
Richiesta di validazione dei metadati - Unione Bassa Bresciana Occidentale

### ISSUE THREAD

**Issue by globogis** [italia/spid#699]
Buongiorno,
per conto dell'unione si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.suap.unionecomunibbo.it/simplesaml/module.php/saml/sp/metadata.php/unionebbo

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

In relazione alla richiesta in oggetto, la vostrta azienda ha già presentato un metadata per il comune di oggetto tramite la [issue 624](https://github.com/italia/spid/issues/624).

Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).

**Comment by globogis** [comment]
Buongiorno,
mi scuso per il disallineamento interno. I metadati corretti sono esposti all'endpoint https://sportellotelematico.unionecomunibbo.it/sites/default/files/spid-metadata/unionebbo-signed.xml

Grazie

**Comment by globogis** [comment]
Buongiorno,
ci sono novità in merito?
Grazie

**Comment by globogis** [comment]
Buongiorno,
ci sono novità in merito?
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
