### ISSUE TITLE
Nuova versione metadata Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#7]
Salve
Richiedo che venga caricata la nuova versione del metadata per la Regione Puglia.
E' stato integrato il SIT Puglia (Sistema Informativo Territoriale)  
grazie
Saluti
Marcello Marangio 

PS: segue mail a  spid.tech@agid.gov.it

**Comment by AntonioGiovanniSchiavone** [comment]
Metadata deployato presso gli IdP

**Comment by marangiom** [comment]
Salve
a seguito di nostre verifiche i nuovi metadati **NON** risultano deployati su:
sielte: errore n08
intesa: errore generico
namirial: errore 08
infocert: errore 08 con ritorno  su portale applicativo errato (cioè partendo dal servizio che stiamo testando l'errore di login viene comunicato ad un altro nostro portale; credo prenda il primo servizio dichiarato nei metadati)

potreste gentilmente verificare la situazione presso i gestori?
grazie
Saluti
