### ISSUE TITLE
Controllo metadata - Comune di Moretta

### ISSUE THREAD

**Issue by falbesano** [italia/spid#701]
Buongiorno,
per conto del Comune di Moretta, richiediamo la verifica dei metadati pubblicati all'url:
https://sportellodigitale.comune.moretta.cn.it/004143/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
