### ISSUE TITLE
Controllo Metadata ASL ROMA 4

### ISSUE THREAD

**Issue by theorematica** [italia/spid#702]
Buonasera,

per conto dell'ASL ROMA 4 si richiede la nuova validazione del metatada precedentemente approvato:
https://certificativaccinali.aslroma4.it/spid/wp-content/plugins/wp-spid-italia/lib/www/module.php/saml/sp/metadata.php/default-sp in quanto è stato aggiunto l'IDP Lepida.

Grazie.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
