### ISSUE TITLE
Richiesta aggiornamento metadati Provincia autonona di Trento

### ISSUE THREAD

**Issue by uffinformaticapat** [italia/spid#704]
Chiedo di comunicare agli idp che abbiamo aggiunto un nuovo servizio online. 
Il servizio si chiama <md:ServiceName xml:lang="it">Sistema integrato Agricoltura Provinciale</md:ServiceName> presente nei metadata

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
