### ISSUE TITLE
Richiesta aggiornamento metadata Comune di Caronno Pertusella

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#705]
Buon pomeriggio, 
causa un refuso nei metadata recentemente approvati del Comune di Caronno Pertusella #672 
chiediamo una nuova pubblicazione degli stessi
i metadata sono reperibili all'URL

https://caronnopertusella.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa

[metadata_caronnopertusella2SP_new-signed.zip](https://github.com/italia/spid/files/2672602/metadata_caronnopertusella2SP_new-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
