### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Stornara

### ISSUE THREAD

**Issue by globogis** [italia/spid#706]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:https://sportellotelematico.comune.stornara.fg.it/simplesaml/module.php/saml/sp/metadata.php/stornara

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
