### ISSUE TITLE
Richiesta verifica metadati Comune di Sanguinetto

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#709]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sanguinetto.
https://www.comune.sanguinetto.vr.it/c023072/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by damikael** [comment]
Richiesta presa in carico tramite email.
