### ISSUE TITLE
Modifica voce Registro Fornitori di servizi

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid#71]
Richiesta proveniente dalla Regione Autonoma della Sardegna

Buonasera,
per segnalarvi che nel registro della federazione SPID alla pagina https://registry.spid.gov.it/service-providers, l’entity name "Regione Sardegna" è errato.
Come indicato sul file metadata (disponibile su https://login.regione.sardegna.it/saml/metadata?entity ... ardegna.it) 
il nome corretto da indicare è "Regione Autonoma della Sardegna".
Saluti

**Comment by umbros** [comment]
Corretto
