### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Maser (TV)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#712]
Buongiorno,
per conto del Comune di Maser (TV) si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.maser.tv.it/spid/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Le url afferenti al dominio maser.comuneweb.it non sono raggiungibili. Conseguentemente non è possibile verificare la conformità con i requisiti previsti dall'[Avviso SPID n°1](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid_-_avviso_n1_-_sicurezza_canale_trasmissione_0.pdf).

**Comment by comuneweb** [comment]
Buongiorno,
ora le url sono raggiungibili.

**Comment by comuneweb** [comment]
Buongiorno Antonio,
posso avere indicazioni in merito alla verifica ed al deploy del metadati per il comune di maser?
grazie

**Comment by AntonioGiovanniSchiavone** [comment]
closed in #758
