### ISSUE TITLE
Richiesta verifica metadati Comune di Campolongo Maggiore

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#714]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Campolongo Maggiore.
https://www.comune.campolongo.ve.it/c027003/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
