### ISSUE TITLE
Verifica metadata Comune di Santa Teresa di Riva

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#716]
Buongiorno,

per conto del Comune di Santa Teresa di Riva

abbiamo predisposto i metadata e pubblicati all'URL

https://santateresadiriva.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa

[metadata_santateresadiriva-signed.zip](https://github.com/italia/spid/files/2686202/metadata_santateresadiriva-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
