### ISSUE TITLE
Verifica metadata Comune di Villanova Del Ghebbo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#717]
Buongiorno,

per conto del Comune di Villanova Del Ghebbo

abbiamo predisposto i metadata e pubblicati all'URL

https://villanovadelghebbo.comune-online.it/serviziSPID/metadata.xml
[matadata_villanovadelghebbo-signed.zip](https://github.com/italia/spid/files/2686212/matadata_villanovadelghebbo-signed.zip)

cordiali saluti

Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
