### ISSUE TITLE
 Verifica metadata Comune di Piossasco

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#718]
Buongiorno,

per conto del Comune di Piossasco

abbiamo predisposto i metadata e pubblicati all'URL

https://piossasco.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
[metadata_piossasco-signed.zip](https://github.com/italia/spid/files/2686218/metadata_piossasco-signed.zip)

Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
