### ISSUE TITLE
Richiesta di verifica dell'implementazione di SPID - PROVINCIA DI FOGGIA

### ISSUE THREAD

**Issue by prfg** [italia/spid#72]
Si richiede la verifica tecnica e convenzione dell'implementazione di SPID con il conseguente invio della convenzione da sottoscrivere per la PROVINCIA DI FOGGIA.  per il servizio pubblicato alla URL https://sportellotelematico.provincia.foggia.it/

**Comment by prfg** [comment]
Ci sono novità ?!?!

**Comment by prfg** [comment]
Buongiorno,
   non riesco a capire come mai non ho più ricevuto aggiornamenti. Ci sono problemi ? A che punto siamo con la verifica ?

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone puoi mandare la convenzione

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by prfg** [comment]
Dovrei ricevere la convenzione oppure devo scaricarla da qualche parte ?

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati via mail la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.

**Comment by AntonioGiovanniSchiavone** [comment]
Procedura Amministrativa conclusa
