### ISSUE TITLE
Verifica metadata Comune di Monteriggioni

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#720]
Buongiorno,

per conto del Comune di Monteriggioni

abbiamo predisposto i metadata e pubblicati all'URL

https://monteriggioni.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
[metadata_monteriggioni-signed.zip](https://github.com/italia/spid/files/2686270/metadata_monteriggioni-signed.zip)

Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
