### ISSUE TITLE
 Verifica metadata Comune di Olgiate Molgora

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#725]
Buongiorno,

per conto del Comune di Olgiate Molgora

abbiamo predisposto i metadata e pubblicati all'URL

https://olgiatemolgora.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_olgiatemolgora-signed.zip](https://github.com/italia/spid/files/2691433/metadata_olgiatemolgora-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
