### ISSUE TITLE
Verifica metadata Regione Puglia - URGENTE

### ISSUE THREAD

**Issue by marangiom** [italia/spid#727]
Salve
E' stato necessario un aggiornamento dei metadati per la scadenza del certificato di firma saml del portale della sanità, per cui adesso non è possibile accedere al portale via spid con tutti i gestori, tranne intesa e lepida.
I metadati sono scaricabili da https://spid.rupar.puglia.it/regione-puglia-metadata.xml
Vi prego di procedere al deploy con la massima urgenza
saluti
Marcello Marangio

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
