### ISSUE TITLE
Verifica metadata Comune di Casalmaggiore

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#728]
Buongiorno, 
con issue #632 abbiamo inviato la richiesta la verifica dei metadata del comune di Casalmaggiore 
A seguito di un malinteso con il comune  abbiamo in seguito modificato i metadata per tenere conto della presenza di un primo SP (Globo) seguendo la procedura ormai consolidata di salvaguardia di entityID, certificati, endpoints.
L'issue è fermo da diverso tempo  ci sono problemi?
Cordiali saluti
Facondini Stefano 
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Chiuso nella  issue #632
