### ISSUE TITLE
Richiesta validazione metadata Comune di Fiscaglia (FE)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#729]
Buongiorno,
per conto del Comune di Fiscaglia (FE) si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.fiscaglia.fe.it/spid/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
