### ISSUE TITLE
Comune di Matera - Errore Idp LEPIDA

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#730]
Buongiorno, segnaliamo il seguente errore con Idp Lepida. "Formato richiesta non corretto. Contattare il gestore del servizio."
Ha funzionato fin da subito da quando era stato aggiunto (quasi un mese fa). Il problema c'è da circa una settimana.
Restiamo in attesa di un riscontro.
Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buonasera,

l'orologio di sistema sembra essere circa un minuto indietro. 

Suggeriamo quindi di correggere le impostazioni dell'orologio di sistema del server in questione, eventualmente avvalendosi di un servizio di sincronizzazione basato su protocollo ntp, come quello fornito dall' [Istituto Nazionale di Ricerca Metrologica](https://www.inrim.it/node/643)

**Comment by Eduardo1977** [comment]
Buonasera,
abbiamo controllato l’orario del sistema sul server ed è corretto. Facciamo presente che con tutti gli altri Idp non ci sono problemi. Inoltre, sullo stesso server è attivo un altro SP (Comune di Romentino) che con Lepida funziona. 
Si potrebbe risolvere trasmettendo nuovamente il metadata di Matera a Lepida?
Restiamo in attesa di riscontro.
Grazie
