### ISSUE TITLE
Verifica metadata Unione Valdera

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#732]
Buongiorno,

per conto dell'Unione Valdera

abbiamo predisposto i metadata e pubblicati all'URL

https://unionevaldera.multeonline.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
[metadata_valdera-signed.zip](https://github.com/italia/spid/files/2698261/metadata_valdera-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
