### ISSUE TITLE
Richiesta verifica metadati Comune di Veggiano

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#735]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Veggiano.
https://servizionline.comune.veggiano.pd.it/c028096/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
