### ISSUE TITLE
Richiesta verifica metadati Unione di Comuni Retenus

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#736]
Buongiorno,
Si richiede la verifica dei metadati per conto del Unione di Comuni Retenus.
https://www.retenus.it/ae00729/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
