### ISSUE TITLE
Richiesta validazione metadata Comune di Tarquinia (VT)

### ISSUE THREAD

**Issue by SIC-Tarquinia** [italia/spid#737]
Buongiorno,
con la presente si comunica il link per la validazione e la pubblicazione del Metadata per il Comune di Tarquinia (VT):
https://www.comune.tarquinia.vt.it/cmsitarquinia/spid/metadata.xml

Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
le url degli attributi Location sono malformate.

**Comment by AntonioGiovanniSchiavone** [comment]
Riproposto in issue #740
