### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Landriano

### ISSUE THREAD

**Issue by globogis** [italia/spid#739]
Buongiorno,
per conto del Comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.landriano.pv.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
