### ISSUE TITLE
Richiesta validazione metadata Comune di Tarquinia (VT)

### ISSUE THREAD

**Issue by SIC-Tarquinia** [italia/spid#740]
Buongiorno,
con la presente si ritrasmette il link per la validazione e la pubblicazione del Metadata per il Comune di Tarquinia (VT):
https://www.comune.tarquinia.vt.it/cmsitarquinia/spid/metadata.xml

Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by SIC-Tarquinia** [comment]
Schiavone buongiorno. Volevo richiederLe un chiarimento; sul sito dell'AgID viene riportato quanto segue: 

Procedura amministrativa 

Per procedere alla firma della convenzione è necessaria, per ogni Service Provider, una verifica tecnica sull'implementazione di SPID. 
Per richiedere la verifica, invia un'email all' indirizzo spid.tech@agid.gov.it indicando le url dei servizi da validare. 
Dopo l'esito positivo della verifica, ti verrà inviata la documentazione che dovrai compilare e firmare. 
Una volta completata la procedura, devi inviare con una PEC tutta la documentazione all'indirizzo protocollo@pec.agid.gov.it. 
Entro pochi giorni riceverai la convenzione controfirmata. 

Non mi è ben chiaro, considerata la sua comunicazione in merito all'inoltro del Metadata agli IdP, se per la parte amministrativa dobbiamo comunque trasmettere un'ulteriore richiesta all'indirizzo spid.tech@agid.gov.it, oppure attendere che ci venga trasmessa la documentazione da compilare e firmare. 

Si resta in attesa di un cortese riscontro alla presente. 
Grazie 






Il Responsabile Ufficio [ http://trasparenza.comune.tarquinia.vt.it/archivio13_strutture_-1_1108.html | Sistema Informativo Comunale ] 
Marco Menegaldo 
P.zza G. Matteotti, 6 - 01016 Tarquinia (VT) 
Tel (+39) 0766 849.451 
e-mail: [ mailto:mmenegaldo@comune.tarquinia.vt.it | mmenegaldo@comune.tarquinia.vt.it ] 


**** Riservatezza **** 
In ottemperanza al Reg. UE 2016/679, in materia di protezione dei dati personali, le informazioni contenute in questo messaggio sono strettamente riservate ed esclusivamente indirizzate al destinatario indicato (oppure alla persona responsabile di rimetterlo al destinatario). Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di questo messaggio è vietato. Nel caso in cui aveste ricevuto questo messaggio per errore, vogliate cortesemente avvertire il mittente e distruggere il presente messaggio. Per l’informativa completa sulla sicurezza e sulle modalità di trattamento dei dati personali adottate dal titolare, si rimanda alla sezione “Trasparenza” > “Privacy e cookie policy”. Grazie 


Da: "Antonio Giovanni Schiavone" <notifications@github.com> 
A: "italia/spid" <spid@noreply.github.com> 
Cc: "SIC-Tarquinia" <informatica@tarquinia.net>, "Author" <author@noreply.github.com> 
Inviato: Lunedì, 7 gennaio 2019 18:10:20 
Oggetto: Re: [italia/spid] Richiesta validazione metadata Comune di Tarquinia (VT) (#740) 



Closed [ https://github.com/italia/spid/issues/740 | #740 ] .
