### ISSUE TITLE
Attivazione SPID Comune di Catania

### ISSUE THREAD

**Issue by RobMel** [italia/spid#741]
Si richiede l'apertura di una posizione SPID come service provider per i comuni di: Catania, Aci Castello, Biancavilla, Gravina di Catania e Milo.
Seguirà email con i metadata dal mittente sirio.candini@nexi.it.
Grazie
Roberto Melino

**Comment by AntonioGiovanniSchiavone** [comment]
I Metadata sono stati inoltrati verso gli IdP e da essi caricati.
