### ISSUE TITLE
 Verifica metadata Comune Sesto San Giovanni

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#745]
Buongiorno,

per conto del Comune Sesto San Giovanni

abbiamo aggiornato i metadata  per aggiunta di un secondo SP  e pubblicati all'URL

https://sestosangiovanni.comune-online.it/serviziSPID/metadata.xml

Buon anno
Facondini Stefano
Maggioli Spa

[metadata_sestosangiovanni2SP_new-signed.zip](https://github.com/italia/spid/files/2720300/metadata_sestosangiovanni2SP_new-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
