### ISSUE TITLE
Comunicazione metadata - Università di Bologna

### ISSUE THREAD

**Issue by cmezzett** [italia/spid#746]
* PA: Università di Bologna
   * comunicazione metadati

Buongiorno,

In seguito alla revisione dei nostri sistemi server abbiamo cambiato ambienti e modificato i metadati, oltre che all'indirizzo di pubblicazione che ora si trova qui:

http://spid.unibo.it/Metadata/FederationMetadata-signed.xml

Aggiungo anche in allegato.

[FederationMetadata-signed.xml.zip](https://github.com/italia/spid/files/2720571/FederationMetadata-signed.xml.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il metadata inviato non è compliant alle regole tecniche SPID;
gli errori riscontrati sono:

1)L'hash della firma sul metadata non combacia con il contenuto. Sull'account github dell'iniziativa Developers Italia è stato pubblicato un tool per la firma dei metadata per i sistemi operativi Linux e OSX : https://github.com/italia/spid-metadata-signer. Vi segnaliamo inoltre che alcuni Service Provider hanno utilizzato con successo un porting del citato tool per la piattaforma Windows sviluppato da terzi: https://github.com/ermannog/SPID-Metadata-Signer-Windows

Si prega di rifirmare il metadata e di comunicarne la disponibilità all'endpoint segnalato di quello corretto.

Staff Tecnico SPID
Agenzia per l'Italia Digitale

**Comment by cmezzett** [comment]
Metadati aggiornati:

http://spid.unibo.it/Metadata/FederationMetadata-signed.xml

anche in allegato.
Grazie
[federationmetadata-for-agid-signed.xml.gz](https://github.com/italia/spid/files/2952253/federationmetadata-for-agid-signed.xml.gz)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
