### ISSUE TITLE
Controllo metadata - Comune di Casale Monferrato

### ISSUE THREAD

**Issue by falbesano** [italia/spid#747]
Buongiorno,
per conto del Comune di Casale Monferrato, richiediamo la verifica dei metadata pubblicati all'url:
https://sportellodigitale.comune.casale-monferrato.al.it/006039/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
