### ISSUE TITLE
Verifica metadata Comune di Pistoia

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#748]
Buongiorno,

per conto del Comune di Pistoia

abbiamo predisposto i metadata e pubblicati all'URL

https://pistoia.comune-online.it/serviziSPID/metadata.xml
 si tratta di aggiunta di un secondo SP a metadata esistenti

Buon anno
Facondini Stefano
Maggioli Spa
[metadata_pistoia2SP_new-signed.zip](https://github.com/italia/spid/files/2721629/metadata_pistoia2SP_new-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
