### ISSUE TITLE
Verifica metadata Comune di Avezzano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#749]
Buongiorno,

per conto del Comune di Avezzano

abbiamo predisposto i metadata e pubblicati all'URL

https://avezzano.comune-online.it/serviziSPID/metadata.xml
si tratta di aggiunta di un secondo SP a metadata già esistenti

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_avezzano2SP_new-signed.zip](https://github.com/italia/spid/files/2721640/metadata_avezzano2SP_new-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
