### ISSUE TITLE
Problema IdP Poste - Comune di Casale Monferrato

### ISSUE THREAD

**Issue by falbesano** [italia/spid#751]
Buongiorno,
segnaliamo che l'IdP Poste sembra non aver ancora caricato i metadata del Comune di Casale Monferrato (di cui all'issue #747 ) poiché un tentativo di autenticazione ritorna l'errore "Formato richiesta non corretto - Contattare il gestore del servizio".
Tutti gli altri IdP funzionano correttamente.

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

L'IdP in questione adesso risponde correttamente alle AuthnRequest.
