### ISSUE TITLE
Utenti per fare i test con l'IDP di test https://idp.spid.gov.it:8080

### ISSUE THREAD

**Issue by AlessandroCimarelli** [italia/spid#752]
Salve,
stiamo provando a testare un service provider in php (https://github.com/italia/spid-php) con l'idp di test https://idp.spid.gov.it

Abbiamo creato il metadata del service provider sulla console https://idp.spid.gov.it:8080 e risulta uguale a quello presente sul service provider.

Abbiamo provato a creare degli utenti nel service provider sulla console https://idp.spid.gov.it:8080,  ma dopo aver fatto il submit delle informazioni dell'utente, non vengono valorizzati i campi in alto alla pagina ed è presente solo il pulsante cancella.

Se proviamo a cancellare ci presenta un errore.

Quando proviamo ad utilizzare il link IDP_TEST, presente sul Service Provider PHP, veniamo indirizzati alla pagina di login su https://idp.spid.gov.it/authenticationendpoint/login.do

Inseriamo le credenziali di un utente pubblico ma ci viene presentato il seguente errore

Something went wrong during the authentication process. Please try signing in again. 

Il nome del Service Provider configurato su https://idp.spid.gov.it:8080 è https://spid-sp.testsp.it

Potete darci supporto per capire dove è il problema?

Grazie in anticipo
Alessandro

**Comment by damikael** [comment]
Salve,
l'ambiente cui si fa riferimento è stato dismesso. Se occorrono informazioni su come utilizzare il nuovo ambiente di test, esposto sempre su http://idp.spid.gov.it, fare riferimento a quanto indicato in:
https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid
Se vengono riscontrate difficoltà nell'utilizzo di spid-php si prega di aprire una issue sul relativo repository. 
Grazie

Saluti
Michele
