### ISSUE TITLE
Errore di accesso IdP Namirial - Comune di Cinisello Balsamo

### ISSUE THREAD

**Issue by globogis** [italia/spid#753]
Buongiorno,
si riscontrano problemi nell'accesso tramite SPID al servizio https://suap.comune.cinisello-balsamo.mi.it , limitatamente all'IdP Namirial: all'invio della AuthnRequest l'errore restituito è ErrorCode nr10.

Si richiede cortesemente una verifica e se necessario un nuovo deploy dei metadati.

Grazie

**Comment by globogis** [comment]
Buongiorno,
ci sono novità in merito?
Grazie

**Comment by pernin** [comment]
Salve, sulla AuthnRequest ricevuta risulta come Issuer: https://suap.comune.cinisello-balsamo.mi.it

mentre invece nei metadata comunicati da AGID si ha che l'entityID è: https://idpcgel.crs.lombardia.it/gelmetadata/15077

Da qui scaturisce l'errore.

**Comment by globogis** [comment]
Buongiorno Luca,
la ringrazio per il riscontro, ma continuo ad avere delle perplessità in merito.
I metadati erano stati da noi comunicati a suo tempo tramite issue https://github.com/italia/spid/issues/101 , e non trovo altre issue successive di richiesta metadati, né siamo stati informati di richieste di aggiornamento pervenute per altre vie.

Inoltre, dai metadati esposti all'URL https://idpcgel.crs.lombardia.it/gelmetadata/15077 risulta che ai nostri servizi sia stato assegnato l'index 1. Con tutti gli altri IdP, però, la richiesta con index 0 (e ID "https://suap.comune.cinisello-balsamo.mi.it") l'autenticazione funziona correttamente. Sembrerebbe quindi che questi metadati siano in uso solamente da Namirial.

Chiederei dunque dei chiarimenti ad @umbros per capire se dobbiamo noi modificare EntityID e index, e gli altri IdP propagare questi metadati finora sconosciuti, o se anche Namirial debba utilizzare i metadati da noi trasmessi a suo tempo.

Grazie

**Comment by pernin** [comment]
I metadata ci sono stati comunicati in data 07/12/2018:
{
"ipaEntityCode": "c_c707",
"entityName": "Comune di Cinisello Balsamo",
"entityId": "https://idpcgel.crs.lombardia.it/gelmetadata/15077",
"metadataUrl": "https://registry.spid.gov.it/metadata/sp/spid-sp-c_c707.xml",
"metadataType": "test",
"notes": ""
}

Facciamo fede a questi inviatici da AgID, pertanto non corrispondendo l'Issuer con l'entityId ivi menzionato, la richiesta non viene accettata.
Posso mettermi in contatto con i tecnici che gestiscono i metadata per AgID se volete.

**Comment by globogis** [comment]
Certo, il comportamento che voi adottate è corretto, ma sembra che questi metadati non siano stati recepiti dagli altri IdP, né eravamo a conoscenza del loro aggiornamento. In questa fase, se noi modificassimo l'EntityID (e a questo punto anche l'index), l'accesso con Namirial funzionerebbe ma non quello con tutti gli altri IdP. Per questo preferisco attendere un riscontro da AgID.
Se avete modo di chiedere chiarimenti anche dal vostro lato, ve ne sarei grato.

Grazie

**Comment by globogis** [comment]
Update: l'amministrazione comunale ci conferma di aver trasmesso ad AgID la richiesta di aggiornamento dei metadati, in data 6/12, direttamente via mail. A questo punto proviamo a sostituire EntityID e service index e verificare che anche gli altri IdP abbiano recepito.

**Comment by pernin** [comment]
Ok.

**Comment by globogis** [comment]
Confermo che con la nuova configurazione tutto sta funzionando correttamente: evidentemente gli altri IdP al momento hanno deployato entrambi i metadati. Direi che è risolto.
La ringrazio per la collaborazione.

**Comment by pernin** [comment]
Si figuri.
