### ISSUE TITLE
Controllo metadata - Comune di Bricherasio

### ISSUE THREAD

**Issue by falbesano** [italia/spid#754]
Buongiorno,
per conto del Comune di Bricherasio, richiediamo la verifica dei metadata pubblicati all'url:
https://sportellodigitale.comune.bricherasio.to.it/001035/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
