### ISSUE TITLE
Problemi accesso tramite Lepida per Ospedali Riuniti di Ancona

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#756]
Salve, l'accesso ai servizi offerti dagli Ospedali Riuniti di Ancona tramite IdP Lepida non funziona.
L'authentication request viene rifiutata con il seguente messaggio: "Formato richiesta non corretto".
Sarebbe possibile capire cosa manca.
Grazie anticipatamente.

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo predisposto un ricaricamento del vostro metadata. Qualora entro la tarda di mattinata di Lunedì prossimo il problema non fosse risolto,  si prega di fornire, tramite mail a spid.tech@agid.gov.it,  un accesso al servizio in modo da svolgere più approfondite analisi.

**Comment by alessiotosi** [comment]
Buongiorno, 
in seguito all'aggiornamento del metadata il servizio è stato integrato correttamente sull'IpP LepidaID. 
Cordiali saluti,
Alessio Tosi

**Comment by fmartelli** [comment]
Confermo.
Grazie e buona giornata
