### ISSUE TITLE
 Open Richiesta Validazione metadati SPID per il Comune di Maser (TV)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#758]
Buongiorno,
per conto del Comune di Maser (TV) si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.maser.tv.it/spid/metadata.xml
grazie

_Originally posted by @comuneweb in https://github.com/italia/spid/issue_comments#issuecomment-453748714_

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
