### ISSUE TITLE
Richiesta verifica metadati Comune di  Montebelluna

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#760]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Montebelluna.
https://www.comune.montebelluna.tv.it/c026046/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
