### ISSUE TITLE
Problemi accesso tramite Lepida per IZSAM

### ISSUE THREAD

**Issue by fmartelli** [italia/spid#761]
Salve, l'accesso ai servizi offerti dall'Istituto Zooprofilattico dell'Abruzzo e del Molise tramite IdP Lepida non funziona.
L'authentication request viene rifiutata con il seguente messaggio: "Formato richiesta non corretto".

Sembrerebbe lo stesso problema di cui alla issue #756.

Grazie anticipatamente.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Abbiamo effettuato un ricaricamento del vostro metadata presso gli IdP. Qualora il problema si dovesse ancora manifesta, si prega di inviare all'indirizzo spid.tech@agid.gov.it la url del servizio in questione.
