### ISSUE TITLE
Validazione Metadata Comune di Altamura (BA)

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#763]
Buongiorno,
abbiamo inviato l'url del metadata a spid.tech@agid.gov.it per l'attivazione SPID presso il Comune di Altamura (BA).
Chiediamo, gentilmente, la validazione del metadata e deploy presso gli IdP.
Grazie

Cordiali saluti

Servizi Locali S.p.A.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
