### ISSUE TITLE
Richiesta verifica metadati Comune di Bosaro

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#764]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Bosaro.
https://servizionline.comune.bosaro.ro.it/c029007/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
