### ISSUE TITLE
richiesta di deploy dei nuovi metadati - Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#765]
Buongiorno
chiedo che vengano controllati e rideployati presso i gestori SPID i nuovi metadati della Regione Puglia disponibili su https://spid.rupar.puglia.it/regione-puglia-metadata.xml
grazie
saluti
Marcello Marangio
InnovaPuglia S.p.A.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
