### ISSUE TITLE
Errore logout con idp Poste

### ISSUE THREAD

**Issue by massimilianowosz** [italia/spid#77]
Buongiorno,
da questa mattina ottengo un errore in fase si logout (HTTP-Redirect) sui Comuni di Napoli, Cesano Maderno e Bastia Umbra per i quali ho implementato il servizio di SPID.

Una volta reindirizzati reindirizzati su https://posteid.poste.it/jod-fs/sloserviceredirect?SAMLResponse=.....
viene visualizzato l'errore:
**Formato richiesta non corretto - Contattare il gestore del servizio**

Fino a qualche ora fa era tutto funzionante.
Ho provato altri idp (es. TIMID) ed il logout funziona correttamente.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Provando ad accedere all'Identity Provider Poste dalle url:
https://demografici.comune.napoli.it/login/ 
https://sol.comune.cesano-maderno.mb.it/po/po_login.php

L'Identity Provider in questione sembra rispondere correttamente al messaggio di AuthnRequest.

**Comment by massimilianowosz** [comment]
Salve,
il login funzionava correttamente.
Il problema era in fase di logout ma adesso sembra sia stato risolto.
Grazie
