### ISSUE TITLE
comuni di Pistoia e Sesto San Giovanni mancata acquisizione nuovi metadata da IDP Poste e Lepida

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#771]
Buongiorno, 
a seguito del recente aggiornamento metadata per aggiunta di un secondo SP per i comuni di 
Pistoia e Sesto San Giovanni, 
[metadata_pistoia2SP_new-signed.zip](https://github.com/italia/spid/files/2777788/metadata_pistoia2SP_new-signed.zip)
[metadata_sestosangiovanni2SP_new-signed.zip](https://github.com/italia/spid/files/2777789/metadata_sestosangiovanni2SP_new-signed.zip)

i nuovi metadata sono sono stati recepiti da tutti gli SP salvo Poste e Lepida
Si richiede un nuovo dispiegamento

Cordiali saluti
Facondini Stefano 
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
I Metadata sono stati ricaricati dagli IdP . Qualora il problema persistesse si prega di indicare le url dei servizi in questione.
