### ISSUE TITLE
Comune di Avezzano mancato recepimento nuovi metadata IDP Poste

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#772]
Buongiorno,
a seguito del recente aggiornamento metadata per aggiunta di un secondo SP per il comune di
Avezzano, i nuovi metadata sono sono stati recepiti da tutti gli SP salvo Poste  
Si richiede un nuovo dispiegamento

Cordiali saluti
Facondini Stefano
Maggioli spa
[metadata_avezzano2SP_new-signed.zip](https://github.com/italia/spid/files/2777794/metadata_avezzano2SP_new-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato ricaricato dagli IdP . Qualora il problema persistesse si prega di indicare la url del servizio in questione.
