### ISSUE TITLE
Procedura amministrativa extranet.izsler.it

### ISSUE THREAD

**Issue by carmelofloridia** [italia/spid#773]
Buonasera,
in seguito alla vostra richiesta  (che ho riportato di sotto) abbiamo provveduto a configurare il servizio come richiesto.

Potete segnare come referente tecnico c.floridia@idsunitelm.it
Come referente amministrativo Mazza Domenico Nilo danilo.mazza@izsler.it

Come possiamo procedere per completare la verifica amministrativa
Distinti Saluti
Carmelo Florida

ECCO DI SEGUITO LA VOSTRA COMUNICAZIONE VIA MAIL
Da: Spid Tech [mailto:spid.tech@agid.gov.it] 
Inviato: mercoledì 21 novembre 2018 12:51
A: Carmelo Floridia <c.floridia@idsunitelm.it>
Cc: Antonio Biondo <a.biondo@glauco.it>
Oggetto: Re: Istituto zooprofilattico di Brescia - Procedura Amministrativa

Buongiorno,

In relazione alla vostra richiesta di verifica dell'implementazione per il sito https://extranet.izsler.it, al fine di eseguire tale verifica è necessario agganciare tale piattaforma di autenticazione al nostro tool di verifica dell'implementazione dei Service Provider.

Il nostro tool andrà agganciato alla stregua di un ulteriore Identity Provider, facendo riferimento al metadata disponibile alla url https://validator.spid.gov.it/metadata.xml, e predisponendo un'ulteriore voce all'interno dello SPID Button, che sarà utilizzata esclusivamente 
ai fini della validazione del servizio e che dovrà essere rimossa al termine della verifica da parte di AgID.

Inoltre, qualora la vostra piattaforma generi AuthRequest sia in HTTP-Post che in HTTP-Redirect, vi chiediamo di creare due voci nello SPID Button, una per ognuno dei due Binding.

Appena pronti, vi preghiamo di comunicarci tramite mail all'indirizzo spid.tech@agid.gov.it l'avvenuta configurazione del servizio secondo quanto indicato, in modo da poter iniziare le nostre analisi.

Sempre in tale mail vi chiediamo di indicare l'indirizzo del referente tecnico a cui inviare il report tecnico con l'esito della verifica e l'indirizzo del referente amministrativo a cui inviare, in caso di esito positivo della verifica , la documentazione per la conclusione della 
procedimento amministrativo.

Distinti Saluti,

Antonio Giovanni Schiavone
Staff Tecnico SPID 
Agenzia per l'Italia Digitale

**Comment by carmelofloridia** [comment]
Buongiorno, gradiremmo avere un aggiornamento sulla nostra situazione sulla verifica dell'implementazione per procedere con la procedura amministrativa.

**Comment by danilomazza** [comment]
Buonasera,
vi chiederei anch'io la cortesia di un aggiornamento: nonostante ripetuti solleciti la nostra adesione a SPID è ferma per una pratica burocratica e sono ormai sei mesi che attendiamo.
Abbiamo, con i nostri fornitori, impegnato risorse e dato dei tempi di realizzazione,ampiamente rispettati, ma non riusciamo a chiudere la procedura.

Ringraziando per l'attenzione gentilmente accordatami ed in attesa di un cortese cenno di riscontro, resto a disposizione per ogni approfondimento mi si vorrà richiedere.
Cordialmente,
Domenico Nilo Mazza

Dr. Ing. Domenico Nilo Mazza
Dirigente Responsabile Sistemi Informativi 
Istituto Zooprofilattico Sperimentale Lombardia ed Emilia Romagna
Telefono: +390302290647 Mobile: +393666205428 FAX: +390302290356
e-mail: danilo.mazza@izsler.it
Web: www.izsler.it
Sede Legale: via A.Bianchi 9 - 25124 Brescia  
Tel 03022901 - Fax 0302425251
