### ISSUE TITLE
[Aggiornamento Metadata] Comune di Cigliano (VC) 

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#775]
Buongiorno,
abbiamo predisposto un aggiornamento dei metadata già pubblicati.
Chiediamo, gentilmente, la validazione del metadata e deploy presso gli IdP.
L'url del metadata aggiornato è stato inviato a spid.tech@agid.gov.it.

Grazie

Cordiali saluti

Servizi Locali S.p.A.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
