### ISSUE TITLE
aggiornamento metadata Istituto Comprensivo R. Franceschi - Trezzano sul naviglio

### ISSUE THREAD

**Issue by pagolo** [italia/spid#776]
Rinnoviamo la richiesta di aggiornamento metadata per l'Istituto R. Franceschi di Trezzano sul Naviglio (issue #690), e inoltre per le seguenti scuole: icbrembatesopra.edu.it, icmapello.edu.it, icsolivelli.edu.it, iccastellucchio.edu.it, icspoloestlumezzane.edu.it (che hanno inviato richiesta tramite email a spid.tech@agid.gov.it).

Paolo Bozzo, Nadia Caprotti, Mario Varini
Comunità Drupal Porte Aperte sul Web

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
