### ISSUE TITLE
Verifica tecnica ARTI

### ISSUE THREAD

**Issue by lellomaverick** [italia/spid#777]
Buongiorno,
in data 23/01/19 abbiamo ricevuto risposta da SPID Tech dove ci viene indicato di inserire il Validator nella lista degli IdP presenti nello smart button (fatto) e c'è una seconda richiesta che non ho ben compreso:

"Inoltre, qualora la vostra piattaforma generi AuthRequest sia in HTTP-Post che in HTTP-Redirect, vi chiediamo di creare due voci nello SPID Button, una per ognuno dei due Binding."

Per offrire ai cittadini il nostro servizio di SPID ho usato l'sdk per PHP di @damikael 

Potete aiutarmi a capire meglio la richiesta?

**Comment by damikael** [comment]
Buongiorno @lellomaverick,

secondo le regole tecniche SPID, le AuthnRequest possono essere inviate in binding HTTP-Redirect o HTTP-POST. Simplesamlphp, sul quale spid-php è basato, permette entrambe le possibilità (tramite la configurazione nel file /metadata/saml20-idp-remote.php). Tuttavia nella fase di setup, la configurazione predefinita è in HTTP-Redirect, per tutti gli IdP. 
Pertanto, se si è eseguita una installazione standard, è sufficiente semplicemente esporre il bottone di collegamento al Validator in binding HTTP-Redirect, come previsto durante il setup.
