### ISSUE TITLE
Aggiornamento metadata Ordine dei giornalisti del lazio

### ISSUE THREAD

**Issue by filippoma** [italia/spid#778]
Salve,
si richiede l'aggiornamento del metadata:

https://albo.odg.roma.it/spid/metadata-odg-signed.xml

Grazie mille

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by filippoma** [comment]
Buongiorno,
grazie mille per l'intervento, però devo segnalare che il vecchio metadata continua a funzionare regolarmente, mentre il nuovo non funziona.
Volevo capire se gli idp mantengono entrambi i metadata come validi, e quindi potrebbe essere che ho sbagliato la configurazione sul nuovo sistema che ho implementato, oppure in realtà non è stato caricato correttamente.

Grazie mille.

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

il nuovo metadata è stato inviato in data 25/1 e nuovamente reinviato in data 30/1. 
Il vecchio metadata sarà disattivato a fine mese.
