### ISSUE TITLE
richiesta verifica tecnica e convenzione Comune di Fiumicino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#78]
Buongiorno,
abbiamo condotto i test interni per il Comune di Fiumicino con esito positivo
i servizi soggetti ad autenticazione sono erogati  dal portale:

https://fiumicino.comune-online.it

cordiali saluti
Facondini Stefano
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
Inviati la Convenzione SPID ed il file di descrizione dei servizi per la P.A. in questione.
