### ISSUE TITLE
Richiesta controllo metadata - Comune di Albano Laziale (RM)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#780]
Con la presente si richiede la verifica della validità del metadata presente all'url:

https://spid.comune.albanolaziale.rm.it/c058003/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernement Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
