### ISSUE TITLE
Verifica metadata Comune di Rescaldina 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#783]
Buongiorno,

per conto del Comune di Rescaldina

abbiamo predisposto i metadata e pubblicati all'URL

https://rescaldina.comune-online.it/serviziSPID/metadata.xml
[metadata_rescaldina-signed.zip](https://github.com/italia/spid/files/2807228/metadata_rescaldina-signed.zip)

cordiali saluti

Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
