### ISSUE TITLE
Verifica metadata Comune di Castiglione del Lago

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#784]
Buongiorno,

per conto del Comune di Castiglione del Lago

abbiamo predisposto i metadata pubblicati all'URL

https://castiglionedellago.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadada_castiglionedellago-signed.zip](https://github.com/italia/spid/files/2807238/metadada_castiglionedellago-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
