### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Castel d'Ario

### ISSUE THREAD

**Issue by globogis** [italia/spid#785]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.casteldario.mn.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
