### ISSUE TITLE
Comune di Calenzano - Errore di login con IdP Register

### ISSUE THREAD

**Issue by globogis** [italia/spid#787]
Buongiorno,
si segnala un'anomalia nell'interazione fra il servizio https://sportellotelematico.comune.calenzano.fi.it e l'IdP Register.
Essa sembra dipendere dal mancato deploy degli ultimi metadati forniti, dato che la risposta contiene un vecchio id dell'authentication source.

I metadati, non variati rispetto ai precedenti, sono esposti all'endpoint https://sportellotelematico.comune.calenzano.fi.it/simplesaml/module.php/saml/sp/metadata.php/spid . Si richiede cortesemente un nuovo deploy da parte dell'IdP.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
