### ISSUE TITLE
Richiesta verifica metadati Comune di Pieve di Soligo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#788]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Pieve di Soligo.
https://www.comune.pievedisoligo.tv.it/c026057/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
