### ISSUE TITLE
Richiesta verifica metadati Comune di Sona

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#789]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Sona.
https://www.comune.sona.vr.it/c023083/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
