### ISSUE TITLE
Controllo Metadata - Provincia di Cremona

### ISSUE THREAD

**Issue by giannibassiniprovincia** [italia/spid#79]
Buongiorno 
si richiede il controllo del seguente metadata della Provincia di Cremona:

https://idpcgel.crs.lombardia.it/gelmetadata/019

Cordiali Saluti
Gianni Bassini

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
