### ISSUE TITLE
Richiesta verifica metadati ARCEA

### ISSUE THREAD

**Issue by sistemainformativoARCEA** [italia/spid#792]
Buongiorno,

si richiede la verifica dei metadati per l'Agenzia della Regione Calabria per le Erogazioni in Agricoltura inviati alla casella di posta elettronica spid.tech@agid.gov.it

Grazie

Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Inviata via mail segnalazione degli errori riscontrati
