### ISSUE TITLE
Verifica metadata Comune di Spinea

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#794]
Buongiorno,

per conto del Comune di Spinea

abbiamo predisposto i metadata pubblicati all'URL

https://spinea.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
 
[metadata_spinea-signed.zip](https://github.com/italia/spid/files/2828664/metadata_spinea-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
