### ISSUE TITLE
Verifica metadata Comune di Taino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#795]
Buongiorno,

per conto del Comune di Taino

abbiamo predisposto i metadata pubblicati all'URL

https://taino.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_taino-signed.zip](https://github.com/italia/spid/files/2828802/metadata_taino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
