### ISSUE TITLE
pagina da "proteggere" con SPID

### ISSUE THREAD

**Issue by andy650429** [italia/spid#798]
Ciao
sono Andrea di Garda Uno SpA Gestore di SPL in provincia di Brescia.

Sto attendendo il termine della procedura tecnica e presto procederò con quella amministrativa.

Una volta completati i test come da specifiche di AgID, se ben intendo è sufficiente, una volta "flaggato" nel plugin l'attivazione del "login" e poi impostare le pagine da proteggere come "private"... è corretto?

Infine... una volta attivato lo SPID anche come amministratore dovrò entrare con SPID?

Grazie per le info...

A presto!

Andrea

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

si prega di esporre il quesito  in maniera più articolata e tecnicamente precisa all'indirizzo spid.tech@agid.gov.it
