### ISSUE TITLE
metadata comune di Gallarate aggiornati con ulteriori SP - anomalie alcuni IDP  

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#80]
Buongiorno,
riscontriamo anomalie su due IDP (Namirial e register.it) non sembra abbiano recepito i nuovi metadata con gli ulteriori SP; gli altri 6 IDP funzionano regolamente
Cordiali saluti
Facondini Stefano

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo predisposto il redeploy del metadata del Comune in oggetto, che sarà caricato dagli Identity Provider entro le ore 15. 

Qualora il problema persistesse, si prega di fornire le url dei servizi in questione

**Comment by sfacondini** [comment]
Buon pomeriggio,
il problema sussiste con i due IDP  (Namirial e register.it) 
i servizi sono erogati da questo URL:

https://gallarate.comune-online.it/c/portal/login
ricordo che si tratta di un caso di aggiunta di SP a metadata esistenti

cordiali saluti
Facondini Stefano

**Comment by umbros** [comment]
@sfacondini se seleziono namirial al link da te segnalato, vengo rediretto su https://linkmatesec.servizienti.it/LinkmateSec/?c=D869&spid=KO se riseleziono namirial funziona.

Potete verificare?

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by sfacondini** [comment]
Il link è corretto, il problema sembra legato alla gestione di INDEX in AssertionConsumerService  
Sono stati modificati i metadata con certificati aggiuntivi e ulteriori  AssertionConsumerService che non sembrano recepiti da 2 IDP (gli altri sono OK)
A riprova allego un test fatto esternamente al portale con INDEX 1 in questo caso non riconosce il nuovo certificato (index invece è ok)
![gallaratenamirial](https://user-images.githubusercontent.com/7039668/40834169-66658010-6590-11e8-8e48-712ec6bfb164.JPG)
Il rientro su https://linkmatesec.servizienti.it/LinkmateSec/?c=D869&spid=KO  è conseguenza dei valori di Index non riconosciuti

cordiali saluti
Facondini Stefano

**Comment by AntonioGiovanniSchiavone** [comment]
Tutti gli Idp rispondono correttamente alle AuthRequest provenienti dal Service Provider in oggetto
