### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Sommacampagna

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#800]
Buongiorno,
per conto del Comune di Sommacampagna si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.sommacampagna.vr.it/spid/metadata.xml

Grazie

**Comment by comuneweb** [comment]
buongiorno,
ci sono novità?

**Comment by comuneweb** [comment]
ci sono problemi su questa richiesta?

**Comment by AntonioGiovanniSchiavone** [comment]
closed in #920
