### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Monastier di Treviso

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#801]
Buongiorno,
per conto del Comune di Monastier di Treviso si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.monastierditreviso.tv.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
