### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Ormelle

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#802]
Buongiorno,
per conto del Comune di Ormelle si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.ormelle.tv.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
