### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Santa Giustina in Colle

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#803]
Buongiorno,
per conto del Comune di Santa Giustina in Colle si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comunesgcolle.pd.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
