### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Martellago

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#804]
Buongiorno,
per conto del Comune di Martellago si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.martellago.ve.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
