### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Cimadolmo

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#807]
Buongiorno,
per conto del Comune di Cimadolmo si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.cimadolmo.tv.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
