### ISSUE TITLE
Richiesta Validazione metadati SPID per l'istituto comprensivo di Verdellino

### ISSUE THREAD

**Issue by atodaro** [italia/spid#808]
Buongiorno,  si richiede la verifica e il deploy dei metadati esposti all'URL: https://icverdellino.edu.it/spid/module.php/saml/sp/metadata.php/default-sp

Il precedente dominio icverdellino.gov.it è stato migrato a novembre a icverdellino.edu.it

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
tentando di scaricare il metadata in oggetto si ottiene un ERRORE 403: Forbidden

**Comment by atodaro** [comment]
Da test effettuati da diversi device io riesco a scaricare senza problemi il file e confermo che non è presente alcun blocco per l'accesso al file sul server. Se necessario allego direttamente il file.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
