### ISSUE TITLE
Aggiornamento metadata Ordine dei giornalisti del lazio

### ISSUE THREAD

**Issue by filippoma** [italia/spid#811]
Buongiorno,
grazie mille per l'intervento, però devo segnalare che il vecchio metadata continua a funzionare regolarmente, mentre il nuovo non funziona.
Volevo capire se gli idp mantengono entrambi i metadata come validi, e quindi potrebbe essere che ho sbagliato la configurazione sul nuovo sistema che ho implementato, oppure in realtà non è stato caricato correttamente.

Grazie mille.

_Originally posted by @filippoma in https://github.com/italia/spid/issues/778#issuecomment-458876056_

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto in #778
