### ISSUE TITLE
L'accesso a www.passaportonline.poliziadistato.it tramite SPID fallisce con 'Unparseable date: "del"'

### ISSUE THREAD

**Issue by tiraboschi** [italia/spid#812]
* la pubblica amministrazione o soggetto privato per cui si richiede il supporto: Polizia di Stato
   * la label: malfunzionamento, impossibile accedere 
   * se la segnalazione è tecnica inserire una descrizione accurata del comportamento o dell'errore: provo ad accedere a www.passaportonline.poliziadistato.it con SPID (gestore TIM.it) ed ottengo
```
ERRORE
Si e' verificato un errore in fase di accesso tramite SPID. 
Unparseable date: "del"
Torna alla login
```
   * se la segnalazione è tecnica indicare se si riscontra in ambiente di test o con tutti o parte degli IDP in produzione (specificando quali): da comune cittadino con TIM.it sul portale di produzione per www.passaportonline.poliziadistato.it

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Dalla descrizione del problema, sembra che vi siano delle irregolarità nei dati associati alla sua Identità digitale. 
In particolare, sembra che venga fornita la stringa "del" al posto di una data.
Si prega di verificare:

- Il corretto funzionamento della sua identità SPID anche su altri portali (ad es. INPS, INAL, Agenzia entrate, etc ).
- Dal pannello di gestione della propria identità digitale presso il sito del suo Identity Provider, la correttezza del dati inseriti, con particolare riferimento alla eventuale erronea  presenza della stringa "del" in corrispondenza di date (ad esempio data rilascio / data scadenza del documento)

**Comment by tiraboschi** [comment]
Con tutti gli altri servizi con cui ho avuto modo di provare (INPS, portale tributi e portale sanità di Regione Lombardia) non ho mai avuto alcun problema.
Lato https://id.tim.it non vedo nulla di fuori posto (per quello che si vede lato interfaccia utente).
Il problema mi sembra riguardi specificatamente www.passaportonline.poliziadistato.it

**Comment by CiraciNicolo** [comment]
Problema presente anche con la mia utenza. Non capisco la chiusura di questo issue senza aspettare il riscontro reale dell'utente. 

L'unica cosa "strana" che è presente lato tim è che il campo "Emesso da" che precede il campo "data emissione" è un valore multi-line. Posso solo speculare che il parser lato "passaporto online" non prenda in considreazione valori multiline e "prende" il valore riga per riga anzichè controllare l'eventuale chiave presente.
