### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Fiuggi

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#813]
Buongiorno,
per conto del Comune di Fiuggi si richiede la verifica e il deploy dei metadati esposti all'URL:
http://www.comune.fiuggi.fr.it/comune/comune_action.php?ACTION=download&cod_modulo=3404 

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
