### ISSUE TITLE
Validazione file metadata Comune di Tarquinia

### ISSUE THREAD

**Issue by SIC-Tarquinia** [italia/spid#814]
Con apposita mail, è stato trasmesso il file metadata relativo al ns. Ente da validare nuovamente, a seguito di correzione, in quanto quello inviato precedentemente riportava la dicitura "Comuene di Tarquinia" invece che  "Comune di Tarquinia.
Si rappresenta che lo scrivente Ente è ancora in attesa di ricevere la documentazione da sottoscrivere per la Convenzione.
Si resta in attesa di un cortese riscontro alla presente.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
