### ISSUE TITLE
Comune di Lodi: errore di interazione con IdP Lepida e Poste

### ISSUE THREAD

**Issue by globogis** [italia/spid#815]
Buongiorno,
si riscontra un errore di interazione fra il servizio del Comune di Lodi https://sportellotelematico.comune.lodi.it e gli IdP Lepida e Poste. L'errore è il classico "Formato richiesta non corretto - Contattare il gestore del servizio".

Presumiamo che il problema sia dovuto a un mancato deploy degli ultimi metadati comunicati nella issue https://github.com/italia/spid/issues/626 : si richiede dunque una verifica ed eventualmente un nuovo deploy dei metadati, non variati ed esposti all'endpoint https://sportellotelematico.comune.lodi.it/sites/default/files/spid-metadata/lodi-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Gli idP in questione adesso rispondono correttamente alla AuthnRequest generate.
