### ISSUE TITLE
Verifica metadati con provider NAMIRIAL - Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#816]
Salve
gli utenti del gestore Namirial ci segnalano che stanno avendo problemi ad accedere al sistema giava.rsr.rupar.puglia.it. 
E' un sistema utilizzato su rete RUPAR protetta, per cui non raggiungibile dall'esterno ed è online da diverso tempo, integrato e funzionante con tutti gli altri gestori SPID.
Restituisce un errore 08: formato richiesta non corretto.

Allego  request e response appena generati

grazie
Saluti
[giava_request.xml.zip](https://github.com/italia/spid/files/2850696/giava_request.xml.zip)
[giava_response.xml.zip](https://github.com/italia/spid/files/2850703/giava_response.xml.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno, si prega di fornire la url del servizio in questione.

**Comment by marangiom** [comment]
Salve
la url di accesso è [https://giava.rsr.rupar.puglia.it/mmgpls/](https://giava.rsr.rupar.puglia.it/mmgpls/) ma come ho scritto è accessibile solo su SPC via rete rupar-puglia.
Saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato a pag. 8 del  [Regolamento recante le norme tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf), all'intenro dell'AUTHNREQUEST deve essere presente l'attributo ForceAuthn valorizzato a true nel caso si richieda livelli di autenticazione superiori a SPIDL1
