### ISSUE TITLE
Comune di Castelcovati: richiesta di aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#817]
Buongiorno,
per conto del Comune di Castelcovati, in seguito a un aggiornamento del servizio, si chiede di aggiornare i metadati al momento in produzione con quelli esposti all'endpoint: https://sportellotelematico.comune.castelcovati.bs.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
