### ISSUE TITLE
Richiesta verifica metadato Regione Sicilia - Dipartimento dell'Ambiente 

### ISSUE THREAD

**Issue by gaetanoromano** [italia/spid#818]
REGIONE SICILIA - ASSESSORATO DEL TERRITORIO E DELL'AMBIENTE
Buongiorno, 
si richiede la verifica e il deploy dei metadati esposti all'URL:

https://si-vvi.regione.sicilia.it/simplesaml/module.php/saml/sp/metadata.php/default-sp

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
L'indicazione degli errori rilevati è stata inviata via mail
