### ISSUE TITLE
Comune di Bergamo - Richiesta di aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#822]
Buongiorno,
si richiede l'aggiornamento dei metadati per il Comune di Bergamo con quelli esposti all'endpoint https://territorio.comune.bergamo.it/sites/default/files/spid-metadata/bergamo-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Come indicato a pag. 16 del Regolamento recante le norme tecniche SPID, ed ulteriormente specificato dall'Avviso SPID n°1, le comunicazioni fra Identity Provider e Service Provider (definite dagli elementi di tipo SingleLogoutService e AssertionConsumerService) devono avvenire tramite  protocollo HTTPS , avente algoritmo di crittografia TLS 1.2 o superiore. Dalle nostra analisi il dominio https://www.comune.bergamo.it/ Dalle nostre analisi il dominio http://www.arcea.it utilizza il protocollo crittografico TLS 1.0, non soddisfacente i requisiti previste dalle norme tecniche SPID. 

Si prega di correggere il problema evidenziato

**Comment by globogis** [comment]
Buongiorno,
il metadato riferito a https://www.comune.bergamo.it riguarda il nuovo sito istituzionale che verrà pubblicato settimana prossima in sostituzione di quello attuale. Tale servizio sarà accessibile tramite TLS 1.2. Stiamo trasmettendo già ora i metadati in modo che al momento dello switch il nuovo Portale sia già accessibile tramite SPID.
Grazie
