### ISSUE TITLE
Aggiornamento metadata Comune di Rosignano Marittimo per rinnovo certificati

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#829]
Buongiorno,

per conto del Comune di Rosignano Marittimo

abbiamo predisposto metadata con certificati aggiornati pubblicati all'URL

https://rosignanomarittimo.comune-online.it/serviziSPID/metadata.xml
[metadata_rosignanoAggCert-signed.zip](https://github.com/italia/spid/files/2869146/metadata_rosignanoAggCert-signed.zip)

cordiali saluti

Facondini Stefano
Maggioli Spa

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
