### ISSUE TITLE
Aggiornamento metadata Comune di Grugliasco per rinnovo certificati

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#830]
Buongiorno,

per conto del Comune di Grugliasco

abbiamo predisposto metadata con certificati aggiornati pubblicati all'URL

https://jcity.comune.grugliasco.to.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_grugliascoAggCert-signed.zip](https://github.com/italia/spid/files/2869152/metadata_grugliascoAggCert-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
