### ISSUE TITLE
Richiesta verifica Metadati Comune di Nulvi (SS)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#831]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Nulvi (SS)
https://www.comune.nulvi.ss.it/nulvi/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
