### ISSUE TITLE
Richiesta verifica Metadati Comune di Villagrande Strisaili (NU)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#832]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Villagrande Strisaili (NU)
https://www.comune.villagrandestrisaili.og.it/villagrande/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
