### ISSUE TITLE
Controllo metadata - Comune di Vernante

### ISSUE THREAD

**Issue by falbesano** [italia/spid#833]
Buongiorno,
per conto del Comune di Vernante, richiediamo la verifica dei metadata pubblicati all'url:
https://sportellodigitale.comune.vernante.cn.it/004239/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
