### ISSUE TITLE
Comunicazione metadata - Comune di Vinci

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#834]
Salve,
Chiediamo la validazione dei metadata per il Comune di Vinci
		
Come da istruzioni, comunichiamo l'url tramite email a spid.tech@agid.gov.it

cordiali saluti,
Datagraph SRL

**Comment by dgpadev** [comment]
Salve,
Siamo attesa dellla validazione dei metadata per il Comune di Vinci. I responsabili dell'ente hanno già comunicato via mail una richiesta di informazioni riguardo l'eterna attesa di questa attivazione. Ci sono problemi? qualcuno legge queste issue? è possibile avere notizie? siamo in grave ritardo con l'attivazione di questo portale e la mia azienza rischia di perdere la fornitura. Vi prego di darci un seguito al più presto.

Datagraph S.R.L.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
