### ISSUE TITLE
Richiesta verifica metadati Comune di Fratta Polesine

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#838]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Fratta Polesine.
https://servizionline.comune.frattapolesine.ro.it/c029024/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
