### ISSUE TITLE
Errore di accesso - Comune di Casazza

### ISSUE THREAD

**Issue by globogis** [italia/spid#84]
Buonasera,
nel mese di ottobre 2017 avevamo inviato, per conto del Comune di Casazza, una richiesta di validazione dei metadati tramite il vecchio helpdesk: https://sue.comune.casazza.bg.it/simplesaml/module.php/saml/sp/metadata.php/casazza

La validazione aveva avuto esito positivo come ripostato nel ticket: https://helpdesk.spid.gov.it/ticket.php?track=U2V-LDJ-6S4D&e=uff.tecnico%40comune.casazza.bg.it&Refresh=42951 . Il servizio risultava effettivamente funzionante.

Ad oggi, tuttavia, i tentativi di autenticazione dal servizio https://sue.comune.casazza.bg.it restituiscono un esito negativo, come se i metadati non fossero stati validati.

Chiedo dunque una verifica sullo stato dei metadati del Comune e, se applicabile, una nuova validazione degli stessi: l'endpoint è quello riportato sopra e non è variato.

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Abbiamo provveduto al ricaricamento del metadata presso gli IdP, che adesso sembrano rispondere all'AuthnRequest.
