### ISSUE TITLE
Richiesta verifica Metadata Comune di Cazzago San Martino

### ISSUE THREAD

**Issue by sofmir** [italia/spid#841]
Buongiorno,
si richiede la validazione dei metadati per conto del comune di Cazzago San Martino:
https://sportellotelematico.comune.cazzago.bs.it/sites/default/files/spid-metadata/cazzagosanmartino-signed.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
