### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Valmorea

### ISSUE THREAD

**Issue by globogis** [italia/spid#842]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.valmorea.co.it/simplesaml/module.php/saml/sp/metadata.php/spid

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
