### ISSUE TITLE
Richiesta verifica Metadati Comune di Villanovafranca (SU)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#844]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Villanovafranca (SU) https://www.comune.villanovafranca.ca.it/villanovafr/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
