### ISSUE TITLE
Richiesta verifica metadati Comune di Val Liona

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#847]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Val Liona.
https://www.comune.valliona.vi.it/c024123/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
