### ISSUE TITLE
Richiesta aggiornamento e verifica metadata comune di Selargius

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#849]
Buongiorno,
si richiede la sostituzione del metadata già inviato per il comune di Selargius, con il nuovo metadata pubblicato all'indirizzo 
https://portale.comune.selargius.ca.it/spid/metadata-selargius2019-signed.xml 
grazie,
Mariano Carta

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
