### ISSUE TITLE
Parametri di risposta

### ISSUE THREAD

**Issue by djimenezSimumak** [italia/spid#85]
Ciao!
Sto lavorando con php con una copia del tuo repository https://github.com/italia/spid-sp-simplesamlphp nell'ambiente di test "https://idp.spid.gov.it:8080/" e ho registrato un "Service Provider".
Il test di autenticazione funziona e nella risposta ricevo il parametro NameID. Ma non ho ottenuto la risposta per restituire tutti i parametri dell'utente. Come farebbe la configurazione per ottenere tutti i parametri?
È possibile inviare un parametro personalizzato e che la risposta contenga quel parametro così come è stato inviato?
Grazie mille

**Comment by globogis** [comment]
Ciao,
abbiamo avuto lo stesso problema perché non avevamo notato che, nell'IdP di test, l'index dell'AttributeConsumingService è valorizzato a 1, e non a 0 come solitamente accade in produzione.
Modificando questo parametro nella nostra chiamata abbiamo correttamente ricevuto tutti i dati.

**Comment by damikael** [comment]
Ciao,
come già indicato da @globogis occorre verificare che il valore specificato per l'AttributeConsumingServiceIndex sia pari a 1, che è il valore dell'index con il quale viene registrato di default l'AttributeConsumingService sull'IDP di test tramite la form di backoffice.

In SAML è possibile inviare parametri personalizzati e riceverli nella risposta attraverso il RelayState.

Con SimpleSAMLphp è possibile utilizzare il parametro ReturnTo, che permette di specificare l'url alla quale sarà reindirizzato l'utente dopo l'autenticazione, e codificare nella url i parametri personalizzati da inviare e ricevere.

`$auth->requireAuth(array(
    'ReturnTo' => 'https://sp.example.org?a=1&b=2'
));`
