### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Gavirate

### ISSUE THREAD

**Issue by globogis** [italia/spid#856]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.comune.gavirate.va.it/simplesaml/module.php/saml/sp/metadata.php/gavirate

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
