### ISSUE TITLE
Richiesta verifica metadati Comune di Vo

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#857]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Vo.
https://servizionline.comune.vo.pd.it/c028105/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
