### ISSUE TITLE
Richiesta di validazione del metadata: comune di Rodano

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#86]
Buongiorno, 
per conto del comune siamo a richiedere il controllo del seguente metadata:
https://sportellotelematico.comune.rodano.mi.it/simplesaml/module.php/saml/sp/metadata.php/rodano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
