### ISSUE TITLE
Aggiornamento metadata Comune di San Bonifacio per rinnovo certificati

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#864]
Buongiorno,

per conto del Comune di San Bonifacio
abbiamo predisposto metadata con certificati aggiornati pubblicati all'URL

https://sanbonifacio.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_sanbonifacioAGGCERT-signed.zip](https://github.com/italia/spid/files/2936610/metadata_sanbonifacioAGGCERT-signed.zip)

**Comment by sfacondini** [comment]
Buongiorno,
la richiesta di verifica  metadata per aggiornamento certificati è particolarmente  urgente 
cordiali saluti
Facondini Stefano

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato nell'esempio presente nell'[Avviso SPID n°6](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf) , gli elementi di tipo SingleLogoutService devono posti fra gli elementi KeyDescriptor e l'elemento NameIDFormat

**Comment by sfacondini** [comment]
Provvediamo alla modifica ma è lo stesso metadata in produzione solo con il certificato aggiornato 
cordiali saluti
Faondini Stefano

**Comment by sfacondini** [comment]
Buongiorno 
Abbiamo ripubblicato i metadata  corretti  sempre all'URL

https://sanbonifacio.comune-online.it/serviziSPID/metadata.xml

In precedenza abbiamo solo cambiato il certificato per cui l'anomalia probabilmente era già presente 
Purtroppo la cosa è urgente il comune è in produzione 
Cordiali saluti
[metadata_sanbonifacioAGGCERT-signed.zip](https://github.com/italia/spid/files/2977182/metadata_sanbonifacioAGGCERT-signed.zip)


Facondini Stefano 
Maggioli spa

**Comment by AntonioGiovanniSchiavone** [comment]
E' ancora presente un elemento SingleLogoutService in posizione erronea.

**Comment by sfacondini** [comment]
Buongiorno, 
abbiamo corretto i metadata e pubblicati all'URL 

https://sanbonifacio.comune-online.it/serviziSPID/metadata.xml

Purtroppo la cosa è urgente il comune è in produzione
Cordiali saluti
Facondini Stefano
Maggioli spa

[metadata_sanbonifacioAGGCERT-signed.zip](https://github.com/italia/spid/files/2983669/metadata_sanbonifacioAGGCERT-signed.zip)

**Comment by sfacondini** [comment]
Buongiorno
Abbiamo corretto e ripubblicato i metadata corretti sempre all'URL

https://sanbonifacio.comune-online.it/serviziSPID/metadata.xml

Purtroppo la cosa è urgente il comune è in produzione
Cordiali saluti

Facondini Stefano
Maggioli spa

[metadata_sanbonifacioAGGCERT-signed.zip](https://github.com/italia/spid/files/2983706/metadata_sanbonifacioAGGCERT-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
