### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Carpaneto Piacentino (PC)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#867]
Buongiorno,
per conto del Comune di Carpaneto Piacentino si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.carpaneto.pc.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
