### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Podenzano (PC)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#868]
Buongiorno,
per conto del Comune di Podenzano si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.podenzano.pc.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
