### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di San Giorgio Piacentino (PC)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#869]
Buongiorno,
per conto del Comune di San Giorgio Piacentino si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.sangiorgiopiacentino.pc.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
