### ISSUE TITLE
Richiesta di validazione del metadata: comune di Vimercate

### ISSUE THREAD

**Issue by GloboGitHub** [italia/spid#87]
Buongiorno,
per conto del comune siamo a richiedere il controllo del seguente metadata:
https://sportellotelematico.comune.vimercate.mb.it/simplesaml/module.php/saml/sp/metadata.php/vimercate

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per la P.A. di oggetto ( recuperabile all'indirizzo https://registry.spid.gov.it/metadata/sp/spid-sp-c_m052.xml ).
Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).
Per maggiori informazioni potete contattare il Dott. San Martino del Comune di Vimercate.

Staff Tecnico SPID
Agenzia per l'Italia Digitale

**Comment by globogis** [comment]
Buongiorno,
i metadati aggiornati sono disponibili all'endpoint https://sportellotelematico.comune.vimercate.mb.it/sites/default/files/spid-metadata/vimercate-signed.xml

Grazie

**Comment by globogis** [comment]
Buongiorno,
è sufficiente la soprastante comunicazione o devo procedere con l'apertura di una nuova issue?
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
