### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Gropparello (PC)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#870]
Buongiorno,
per conto del Comune di Gropparello si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.gropparello.pc.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
