### ISSUE TITLE
Richiesta Validazione metadati SPID per l'Unione Valnure e Valchero (PC)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#871]
Buongiorno,
per conto dell'Unione Vanure e Valchero si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.unionevalnurevalchero.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
