### ISSUE TITLE
Validazione metadata Comune di Cesate 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#872]
Buongiorno,

per conto del Comune di Cesate

abbiamo predisposto metadata e pubblicati all'URL

https://cesate.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa

[metadata_cesate-signed.zip](https://github.com/italia/spid/files/2940382/metadata_cesate-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
