### ISSUE TITLE
Validazione metadata Comune di Thiene 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#873]
Buongiorno,

per conto del Comune di Thiene

abbiamo predisposto metadata e pubblicati all'URL

https://thiene.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_thiene-signed.zip](https://github.com/italia/spid/files/2945516/metadata_thiene-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
