### ISSUE TITLE
Validazione metadata Comune di Schio

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#874]
Buongiorno,

per conto del Comune di Schio

abbiamo predisposto metadata e pubblicati all'URL

https://schio.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
 
[metadata_schio-signed.zip](https://github.com/italia/spid/files/2945523/metadata_schio-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
