### ISSUE TITLE
Richiesta verifica metadati Comune di Ariano nel Polesine

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#876]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Ariano nel Polesine.
https://servizionline.comune.arianonelpolesine.ro.it/c029002/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
