### ISSUE TITLE
"Richiesta verifica tecnica e convenzione per conto del comune di San Pellegrino"

### ISSUE THREAD

**Issue by Sanpellegrinoterme** [italia/spid#88]
(metadata:https://suap.sanpellegrinoterme.gov.it/simplesaml/module.php/saml/sp/met...)

**Comment by AntonioGiovanniSchiavone** [comment]
La url del metadata è stata ricopiata in maniera incompleta

**Comment by globogis** [comment]
Buongiorno,
l'URL completo è https://suap.sanpellegrinoterme.gov.it/simplesaml/module.php/saml/sp/metadata.php/sanpellegrinoterme

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
