### ISSUE TITLE
Validazione metadata Comune di Valli del Pasubio 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#884]
Buongiorno,

per conto del Comune di Valli del Pasubio

abbiamo predisposto metadata e pubblicati all'URL

https://vallidelpasubio.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_vallidelpasubio-signed.zip](https://github.com/italia/spid/files/2961782/metadata_vallidelpasubio-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
