### ISSUE TITLE
Validazione metadata Comune di Posina

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#885]
Buongiorno,

per conto del Comune di Posina

abbiamo predisposto metadata e pubblicati all'URL

https://posina.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_posina-signed.zip](https://github.com/italia/spid/files/2961790/metadata_posina-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
