### ISSUE TITLE
Validazione metadata Comune di Santorso 

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#886]
Buongiorno,

per conto del Comune di Santorso

abbiamo predisposto metadata e pubblicati all'URL

https://santorso.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_santorso-signed.zip](https://github.com/italia/spid/files/2961805/metadata_santorso-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
