### ISSUE TITLE
Validazione metadata Comune di San Vito di Leguzzano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#887]
Buongiorno,

per conto del Comune di San Vito di Leguzzano

abbiamo predisposto metadata e pubblicati all'URL

https://sanvitodileguzzano.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa

**Comment by sfacondini** [comment]
[metadata_sanvitodileguzzano-signed.zip](https://github.com/italia/spid/files/2961818/metadata_sanvitodileguzzano-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
