### ISSUE TITLE
Validazione metadata Comune di Torrebelvicino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#888]
Buongiorno,

per conto del Comune di Torrebelvicino

abbiamo predisposto metadata e pubblicati all'URL

https://torrebelvicino.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_torrebelvicino-signed.zip](https://github.com/italia/spid/files/2961828/metadata_torrebelvicino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
