### ISSUE TITLE
Aggiornamento metadata - Comune di Bassano del Grappa

### ISSUE THREAD

**Issue by lgiucastro-datanetwork** [italia/spid#889]
Buongiorno,
per conto del Comune di Bassano del Grappa
si richiede la verifica e l'aggiornamento del metadata al quale è stato aggiunto un nuovo servizio ed un nuovo set di attributi (AssertionConsumerService index="2" ; AttributeConsumingService index="1")
https://servizi.comune.bassano.vi.it/spid/metadata.xml

Cordiali saluti

Luca Giucastro
Datanet

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
