### ISSUE TITLE
Richiesta validazione metadati per conto del Comune di Dresano

### ISSUE THREAD

**Issue by globogis** [italia/spid#89]
Buongiorno,
si richiede per conto del Comune di Dresano la validazione dei metadati:
https://sportellotelematico.comune.dresano.mi.it/simplesaml/module.php/saml/sp/metadata.php/dresano

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
