### ISSUE TITLE
Validazione metadata Comune di Locorotondo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#890]
Buongiorno,

per conto del Comune di Locorotondo

abbiamo predisposto metadata e pubblicati all'URL

https://locorotondo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_locorotondo-signed.zip](https://github.com/italia/spid/files/2965949/metadata_locorotondo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
