### ISSUE TITLE
Validazione metadata Comune di Cassano d'Adda

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#891]
Buongiorno,

per conto del Comune di Cassano d'Adda

abbiamo aggiornato i metadata per aggiunta di un secondo SP e pubblicati all'URL

https://cassanodadda.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_cassanodadda2SP-signed.zip](https://github.com/italia/spid/files/2966007/metadata_cassanodadda2SP-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Come indicato dall'[Avviso SPID n°6](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf), non è corretto alternare ciclicamente i tag OrganizationName, OrganizationDisplayName e OrganizationURL, bensì occorre elencare nell'ordine:

- uno o più OrganizationName
- uno o più OrganizationDisplayName
- uno o più OrganizationURL

**Comment by AntonioGiovanniSchiavone** [comment]
Si chiude per mancato adeguamento alle indicazioni fornite entro 45 giorni
