### ISSUE TITLE
Richiesta validazione metadata - Comune di Aprica (SPID GEL)

### ISSUE THREAD

**Issue by sofmir** [italia/spid#894]
Buongiorno, si richiede la verifica del metadata per conto del Comune di Aprica
Nome ente: Comune di Aprica
Url metadata: https://idpcgel.crs.lombardia.it/gelmetadata/014004
Nuovo metadata
Contatto riferimento tecnico: francesca.lionetti@comune.aprica.so.it
[sign-metadata.zip](https://github.com/italia/spid/files/2970663/sign-metadata.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
