### ISSUE TITLE
Richiesta controllo metadata - Comune di Laterza (TA)

### ISSUE THREAD

**Issue by florens14** [italia/spid#895]
Con la presente,

si richiede la verifica della validità del metadata presente all'url: https://www.comune.laterza.ta.it/c073009/spid-metadata.xml

Servizio in oggetto è realizzato con E-Government HALLEY già validato in precedenza per altri Enti.

Resto in attesa di Vostro riscontro.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
