### ISSUE TITLE
Richiesta rivalidazione metadata Comune di Sarzana (già in esercizio)

### ISSUE THREAD

**Issue by sofmir** [italia/spid#896]
Buongiorno si richiede la rivalidazione del metadata per il Comune di Sarzana, già validato in precedenza, scaduto e rivalidato con nuovo certificato.

http://www.comunesarzana.gov.it/images/sarzana/comune/SPID/n201753.xml 

Nome ente; Comune di Sarzana
Url del metadata; http://www.comunesarzana.gov.it/images/sarzana/comune/SPID/n201753.xml 
Se si tratta di aggiornamento o nuovo metadata; AGGIORNAMENTO
Url del servizio al quale è presente in bottone “Entra con SPID” con il collegamento a SPID Validator;  https://cloud.urbi.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fcloud.urbi.it%2Furbi%2Fprogs%2Furp%2Fur1UR200.sto%3FDB_NAME%3Dn201753&SOLStwToken=3117251256461043&DB_NAME=n201753&Login_Message=

Contatto riferimento tecnico; antonio.paduano@comunesarzana.gov.it

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
