### ISSUE TITLE
Richiesta validazione metadata - Comune di Pasturo (SPID GEL)

### ISSUE THREAD

**Issue by sofmir** [italia/spid#899]
Buongiorno, si richiede la verifica del metadata per conto del Comune di Pasturo
Nome ente: Comune di Pasturo
Url metadata: https://idpcgel.crs.lombardia.it/gelmetadata/097065
Nuovo metadata
Contatto riferimento tecnico: info@comune.pasturo.lc.it

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
