### ISSUE TITLE
[Segnalazione anomalie] Comune di Cigliano

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#9]
Buongiorno,
dopo aver eseguito corretto gli errori, come ci avete indicato ieri, continuiamo ad avere problemi con i vari Idp tranne Namirial come è possibile verificare alla url già comunicata.

**Comment by umbros** [comment]
@Eduardo1977, mi mandi la request o la url del servizio che posso provare qui o sull'email spid.tech@agid.gov.it?
Grazie

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by Eduardo1977** [comment]
Ciao @umbros, la url di test del servizio l'avevo già mandata ieri a spid.tech@agid.gov.it.

**Comment by umbros** [comment]
Nell'AuthRequest sono presenti i seguente errori:
1) Nel caso in cui si richieda livelli di autenticazione superiori a SPIDL1 ( SPIDL2 o SPIDL3), l'attributo  ForceAuthn va valorizzato a "true"
2) l'avviso SPID n° 5 ( http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n5-regole-tecniche-errata-corrige.pdf ) ha introdotto alcune modifiche rispetto alle indicazioni espresse nel Regolamento recante le norme tecniche SPID.

In particolare, ha deprecato l'uso dei valori :

urn:oasis:names:tc:SAML:2.0:ac:classes: SpidL1
urn:oasis:names:tc:SAML:2.0:ac:classes: SpidL2
urn:oasis:names:tc:SAML:2.0:ac:classes: SpidL3

per l'indicazione del livello di autenticazione richiesto, sostituendoli rispettivamente con i valori:

https://www.spid.gov.it/SpidL1
https://www.spid.gov.it/SpidL2
https://www.spid.gov.it/SpidL3

**Comment by Eduardo1977** [comment]
Sono esattamente le modifiche che abbiamo fatto stamattina, come indicato nella mail che ci avevate inviato ieri. Adesso dopo le modifiche funziona solo per Namirial. 
Invece da quanto mi hai appena scritto è come se non l'avessimo fatte proprio.

**Comment by Eduardo1977** [comment]
Buongiorno, potremmo avere supporto per individuare il problema? Grazie

**Comment by umbros** [comment]
Ciao @Eduardo1977,
con TIM non risultano più esserci problemi.

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by Eduardo1977** [comment]
Ciao @umbros , si confermo. Adesso il dominio di default funziona con tutti gli IDP.
Invece, abbiamo problemi con l'altro dominio. Attendo qualche aiuto per la config shibb multi dominio. Grazie
