### ISSUE TITLE
Richiesta controllo metadata - Comune di Capriolo (BS) 

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#901]
Con la presente si richiede la verifica della validità del metadata presente all'url:

https://www.capriolo.org/c017038/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by HalleyInformatica** [comment]
Buongiorno,
si richiede un riscontro.
Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
