### ISSUE TITLE
Comunicazione metadata Città di Paderno Dugnano

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#903]
Salve,
Chiediamo la validazione dei metadata per la Città di Paderno Dugnano
Come da istruzioni, comunichiamo l'url tramite email a spid.tech@agid.gov.it
cordiali saluti,
Datagraph SRL

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
