### ISSUE TITLE
Validazione metadata Comune di Ciampino

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#905]
Buongiorno,

per conto del Comune di Ciampino

abbiamo predisposto metadata e pubblicati all'URL

https://ciampino.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_ciampino-signed.zip](https://github.com/italia/spid/files/2991316/metadata_ciampino-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
