### ISSUE TITLE
Richiesta verifica metadati Comune di Lusiana Conco

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#906]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Lusiana Conco.
https://www.comune.lusianaconco.vi.it/c024127/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
