### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Trebaseleghe

### ISSUE THREAD

**Issue by globogis** [italia/spid#908]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sue.comune.trebaseleghe.pd.it/simplesaml/module.php/saml/sp/metadata.php/trebaseleghe

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
