### ISSUE TITLE
Comune di Terracina: richiesta di aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#910]
Buongiorno,
a nome del Comune di Terracina chiediamo cortesemente di aggiornare i servizi attualmente in produzione secondo i metadati esposti all'endpoint https://sportellotelematico.comune.terracina.lt.it/sites/default/files/spid-metadata/terracina-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
