### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Avellino

### ISSUE THREAD

**Issue by globogis** [italia/spid#911]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://sportellotelematico.provincia.avellino.it/simplesaml/module.php/saml/sp/metadata.php/provavellino

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
