### ISSUE TITLE
Richiesta aggiornamento metadati SPID per l'Unione Valnure e Valchero (PC)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#912]
Buongiorno,
per conto dell'Unione Vanure e Valchero si richiede l'aggiornamento dei metadati esposti all'URL:
https://www.unionevalnurevalchero.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
