### ISSUE TITLE
Richiesta verifica metadati Comune di Maserada sul Piave

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#915]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Maserada sul Piave.
https://servizionline.comune.maserada.tv.it/c026040/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
