### ISSUE TITLE
Richiesta aggiornamento metadati SPID peril COmune di Vittorio Veneto (TV)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#916]
Buongiorno,
per conto del Comune di Vittorio Veneto si richiede l'aggiornamento dei metadati esposti all'URL:
https://www.comune.vittorio-veneto.tv.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

nell'aggiornamento dei dati è necessario mantenere il valore dell'entityID precedentemente definito per il comune in questione.

**Comment by comuneweb** [comment]
Buongiorno,
abbiamo modificato l'entityID da **https://www.vittorioveneto.gov.it** a **https://www.comune.vittorio-veneto.tv.it**  a seguito delle indicazioni di AgID del cambio politiche sul dominio .gov.

Dobbiamo per forza mantenere l'entityID anche se il nome a dominio dell'Ente è variato?

**Comment by AntonioGiovanniSchiavone** [comment]
Si, è necessario mantenere l'entityID precedentemente definito per il comune in questione.

**Comment by comuneweb** [comment]
Ho reimpostato

> entityID="https://www.vittorioveneto.gov.it" 

rigenerato i certificati e caricato il metadata aggiornato su:
https://www.comune.vittorio-veneto.tv.it/spid/metadata.xml

Gentilmente mi confermi che non dovremo fare nient'altro quando il domionio .gov non sarà più attivo (cioè fra pochi mesi).

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

Il valore dell'EntityID ha il ruolo di stringa identificativa all'interno della federazione (identificatore unico) e 
non ha una correlazione funzionale con l'esistenza della url. L'unico elemento che avrebbe correlazione funzionale sono le location delle AssertionConsumerService, qualora fossero correlate al dominio in questione. Poiché non siamo in questo caso, la disattivazione del dominio in questione non avrà effetti sulle funzionalità dei servizi del Comune in questione
