### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Massa Lubrense

### ISSUE THREAD

**Issue by globogis** [italia/spid#917]
Buongiorno,
per conto del comune si richiede la verifica e il deploy dei metadati esposti all'URL:
https://stu.comunemassalubrense.gov.it/simplesaml/module.php/saml/sp/metadata.php/massalubrense

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
