### ISSUE TITLE
Validazione Metadata Comune di Bitonto (BA)

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid#918]
Buongiorno,
chiediamo, gentilmente, la validazione del metadata per l'attivazione SPID presso il Comune di Bitonto (BA). L'url del metadata è stato inviato a spid.tech@agid.gov.it. 
Grazie

Cordiali saluti

Servizi Locali S.p.A.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
