### ISSUE TITLE
Nuova Richiesta Validazione metadati SPID per il Comune di Sommacampagna

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#920]
Buongiorno,
per conto del Comune di Sommacampagna si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comune.sommacampagna.vr.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

sui nostri sistemi risulta già presente un metadata per il comune di oggetto. Poichè per ogni P.A. è possibile definire un unico metadata, qualora sia necessario aggiungere ulteriori servizi, la loro descrizione va aggiunta al metadata già comunicato per la P.A. in questione, avendo cura di mantenere esattamente lo stesso valore dell' identificativo unico (EntityID).

**Comment by comuneweb** [comment]
Buongiorno,
è possibile avere l'URL di pubblicazione del metadata già presente?

L'Ente non ha consapevolezza della cosa, abbiamo fatto delle verifiche e l'unico servizio presente con autenticazione SPID e quello messo a disposizione da infocamere.
Non sappiamo però se il metadata è stato pubblicato da infocamere ad un proprio indirizzo.

Grazie

**Comment by comuneweb** [comment]
Buongiorno,

vi risottoponiamo questo metadata con tutti i servizi:
https://www.comune.sommacampagna.vr.it/spid/metadata.xml

In attesa di vostre,
Cordialmente

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
