### ISSUE TITLE
Richiesta verifica metadati Comune di Pieve del Grappa

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#923]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Pieve del Grappa.
https://www.comune.pievedelgrappa.tv.it/c026096/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
il Metadata è stato inoltrato verso gli IdP e da essi caricato.
