### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Villaga (VI) 

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#924]
Buongiorno,
per conto del Comune di Villaga si richiede la verifica e il deploy dei metadati esposti all'URL:
https://www.comunevillaga.vi.it/spid/metadata.xml

Grazie

**Comment by comuneweb** [comment]
Buongiorno,
ci sono novità/problemi in merito?

Grazie

**Comment by comuneweb** [comment]
Buongiorno,
è possibile avere un riscontro?

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
