### ISSUE TITLE
 Validazione metadata Comune di Bitonto

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#926]
Buongiorno,

per conto del Comune di Bitonto

abbiamo predispostoi  metadata per aggiunta di un secondo SP e pubblicati all'URL

https://bitonto.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa

[metadata_bitonto2SP-signed.zip](https://github.com/italia/spid/files/3017985/metadata_bitonto2SP-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Rispetto al metadata precedentemente comunicato per il comune in questione, vi è una discrepanza sul valore dell'entityID

**Comment by sfacondini** [comment]
Buongiorno,sono stati pubblicati nuovi metadata per il comune di Bitonto con endityID corretto Cordiali salutiFacondini Stefano Area Portali ed e-GovernmentTel.: 0541.628399Mob. 329 0528602e-mail: sfacondini@maggioli.ithttp://www.maggioli.it/informatica/ -----Antonio Giovanni Schiavone <notifications@github.com> ha scritto: -----A: italia/spid <spid@noreply.github.com>Da: Antonio Giovanni Schiavone <notifications@github.com>Data: 11/04/2019 05.54PMCc: sfacondini <sfacondini@maggioli.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/spid]  Validazione metadata Comune di Bitonto (#926)Buongiorno,

Rispetto al metadata precedentemente comunicato per il comune in questione, vi è una discrepanza sul valore dell'entityID

**Comment by sfacondini** [comment]
Integro la risposta via mail:
i metadata del comune di Bitonto sono pubblicati all'url:

https://bitonto.comune-online.it/serviziSPID/metadata.xml

cordiali saluti,
Facondini Stefano 
 




[metadata_bitonto2SP-signed.zip](https://github.com/italia/spid/files/3140904/metadata_bitonto2SP-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
