### ISSUE TITLE
Validazione metadata Comune di Oristano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#927]
Buongiorno,

per conto del Comune di Oristano

abbiamo predisposto metadata  e pubblicati all'URL

https://bitonto.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_oristano-signed.zip](https://github.com/italia/spid/files/3018146/metadata_oristano-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
