### ISSUE TITLE
Richiesta aggiornamento metadata Ordine dei giornalisti del Lazio

### ISSUE THREAD

**Issue by filippoma** [italia/spid#928]
Salve,
si richiede l'aggiornamento del metadata.

https://albo.odg.roma.it/spid-albo/module.php/saml/sp/metadata.php/service

Grazie mille

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.

**Comment by filippoma** [comment]
Salve,
come da voi suggerito ho usato la libreria spid di D'Amico, purtroppo ho riscontrato dei problemi.
L'idp poste mi da un'errore il seguente errore:
Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio

L'idp infocert mi restituisce meno attributi di quante ne vengono richiesti.

L'idp tim sulla risposta genera un'eccezione:
Validation with key #0 failed with exception: Unable to validate Signature
Apr 05 10:32:31 simplesamlphp ERROR [e883f44c77] SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Apr 05 10:32:31 simplesamlphp ERROR [e883f44c77] 1 /var/www/html/albo.odg.roma.it/rest/spid-albo/vendor/simplesamlphp/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler)


Potete verificare al seguente link:
https://albo.odg.roma.it/login-spid.php
