### ISSUE TITLE
Richiesta validazione servizio Comune di Ostuni

### ISSUE THREAD

**Issue by dgpadev** [italia/spid#93]
Buonasera,

chiederei la validazione per il Comune di Ostuni.
Invio tramite mail a spid.tech@agid.gov.it i dettagli per la validazione.

Grazie. Saluti,

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone puoi mandare la convenzione

Umberto Rosini
Agenzia per l'Italia Digitale

**Comment by dgpadev** [comment]
Salve,
Siamo in attesa della convenzione, ci sono novità?

**Comment by dgpadev** [comment]
Rinnovo la richiesta di chiarimenti.

**Comment by umbros** [comment]
Validazione OK @AntonioGiovanniSchiavone puoi mandare la convenzione

Umberto Rosini
Agenzia per l'Italia Digitale
