### ISSUE TITLE
Richiesta verifica Metadati Comune di Nurachi (OR)

### ISSUE THREAD

**Issue by halleysardegna** [italia/spid#930]
Buongiorno,
si richiede la verifica dei metadati per conto del Comune di Nurachi (OR)
https://sol.comune.nurachi.or.it/nurachi/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.
In attesa di un vostro riscontro, cordiali saluti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
