### ISSUE TITLE
Richiesta verifica tecnica e convenzione - Comune di Selargius (CA)

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/spid#938]
Buongiorno,
Con la presente si richiede la verifica tecnica sull'implementazione di SPID per il Comune di Selargius.

La url dei servizi da validare è la seguente:
https://portale.comune.selargius.ca.it/login.aspx 
Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Risposto via mail al referente del Comune

**Comment by Arionlinesrl** [comment]
Salve, abbiamo provveduto già a luglio ad adeguarci alle nuove modalità di richiesta della validazione, il comune ha inviato la mail come richiesto, ma non abbiamo ancora avuto risposta. L'attivazione per il comune di Selargius è appesa dal mese di marzo, e il cliente giustamente sollecita. 
Grazie,
Mariano Carta
