### ISSUE TITLE
Richiesta di validazione dei metadati - Comune di Ciciliano (RM)

### ISSUE THREAD

**Issue by wecomsrl** [italia/spid#939]
Buonasera,

si richiede la verifica dei metadati per conto del Comune di Ciciliano (RM):

http://www.comune.ciciliano.rm.it/upload/xml/wt00002794.xml

Grazie
We-COM Srl

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
