### ISSUE TITLE
Comune di Pomponesco - Richiesta di aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#940]
Buongiorno,
per conto del Comune di Pomponesco si richiede l'aggiornamento dei metadati attualmente pubblicati con quelli esposti all'endpoint: https://www.sportellotelematico-pomponescosabbioneta.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
