### ISSUE TITLE
Validazione metadata Comune di Agropoli

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#941]
Buongiorno,

per conto del Comune di Agropoli

abbiamo predisposto metadata  e pubblicati all'URL

https://agropoli.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_agropoli-signed.zip](https://github.com/italia/spid/files/3028767/metadata_agropoli-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
