### ISSUE TITLE
Validazione metadata Comunità Montana Alta Valtellina

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#942]
Buongiorno,

per conto della Comunità Montana Alta Valtellina

abbiamo predisposto metadata  e pubblicati all'URL

https://cmav.servizi-pa-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
[metadata_cmav-signed.zip](https://github.com/italia/spid/files/3028844/metadata_cmav-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
