### ISSUE TITLE
Richiesta utilizzo accesso tramite SPID preso proprio sito che eroga servizi agli studenti universitari

### ISSUE THREAD

**Issue by alessandropudduersucagliari** [italia/spid#943]
ENTE REGIONALE PER IL DIRITTO ALLO STUDIO UNIVERSITARIO di Cagliari
E.R.S.U. Cagliari

Il suddetto Ente Regionale chiede la possibilità di poter consentire agli studenti universitari utilizzatori del proprio sito 
https://www.ersucagliarionline.it/
di poter accedere ai servizi erogabili mediante SPID

Pertanto si chiede cortesemente di conoscere le modalità necessarie per l'attivazione di detto servizio.

Saluti

Alessandro Puddu

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

la documentazione tecnica e la descrizione del processo di adesione sono indicati sul sito ufficiale SPID nella [pagina dedicata ai Service Provider ](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid).

Per ulteriori informazioni tecniche inviare una mail spid.tech@agid.gov.it
