### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Fiorenzuola D'Arda (PI)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#944]
Buongiorno,
per conto del Comune di Fiorenzuola D'Arda si richiede la verifica e il deploy dei metadati esposti all'URL:
http://www.comune.fiorenzuola.pc.it/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Al fine di evitare potenziali disservizi, si prega di rimuove lo spazio all'interno dell'entityID.

**Comment by comuneweb** [comment]
Buongiorno,
Abbiamo effettuato la modifica indicata e aggiornato il metadati all'url :
http://www.comune.fiorenzuola.pc.it/spid/metadata.xml

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
Persiste il problema indicato

**Comment by comuneweb** [comment]
il problema è stato rimosso

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
