### ISSUE TITLE
Richiesta Validazione metadati SPID per l'Unione Comuni Montani Appennino Pistoiese (PT)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#945]
Buongiorno,
per conto dell'Unione Comuni Montani Appennino Pistoiese (PT) si richiede la verifica e il deploy dei metadati esposti all'URL:
http://www.ucap.info/spid/metadata.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
