### ISSUE TITLE
Controllo metadata Comune di Buggiano

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#95]
Buongiorno,
Per conto del Comune di Buggiano, abbiamo predisposto i metadata e pubblicati sulla cartella
https://buggiano.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
[metadata_buggiano-signed.zip](https://github.com/italia/spid/files/1832726/metadata_buggiano-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.
