### ISSUE TITLE
Nuovi metadati - Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#950]
Bunondì
richiedo che siano verificati e deployati i nuovi metadati della Regione Puglia disponibili su 
https://spid.rupar.puglia.it/regione-puglia-metadata.xml
grazie
saluti
Marcello Marangio
InnovaPuglia s.p.a.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
