### ISSUE TITLE
Comune di Sergnano - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#952]
Buongiorno,
per conto del Comune di Sergnano si richiede l'aggiornamento dei metadati con quelli esposti all'endpoint https://sportellotelematico.comune.sergnano.cr.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
