### ISSUE TITLE
Richiesta verifica e deploy metadati - Regione Puglia

### ISSUE THREAD

**Issue by marangiom** [italia/spid#964]
Salve
di richiede la verifica tecnica e il deploy presso i gestori dei nuovi metadati della Regione Puglia, disponibili su https://spid.rupar.puglia.it/regione-puglia-metadata.xml
grazie
saluti
Marcello Marangio

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,
come indicato nella [Tabella degli attributi SPID](https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/tabella_attributi_idp_v1_0.pdf), non esiste l'attributo SPID "countryOfBirth" , ma esiste l'attributo SPID "countyOfBirth"

**Comment by marangiom** [comment]
salve
ho provveduto all'aggiornamento
grazie
saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
