### ISSUE TITLE
Richiesta Validazione metadati SPID per il Comune di Silea (TV)

### ISSUE THREAD

**Issue by comuneweb** [italia/spid#967]
Buongiorno, 
per conto del Comune di Silea (TV) si richiede la verifica e il deploy dei metadati esposti all'URL: https://www.comune.silea.tv.it/spid/metadata.xml .

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
