### ISSUE TITLE
Verifica tecnica metadata e invio convenzione Comune di Melzo

### ISSUE THREAD

**Issue by DGaleazzi** [italia/spid#97]
Buongiorno, 
con la presente si richiede per il Comune di Melzo la verifica tecnica del metadata 
e l'invio della convenzione da sottoscrivere.
Il link al file metadata viene inviato tramite email a spid.tech@agid.gov.it.
Cordiali saluti

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Non ci risulta ancora pervenuta la url del metadata.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato deployato presso gli IdP e da essi caricato.

**Comment by DGaleazzi** [comment]
Buongiorno non abbiamo ancora ricevuto la convenzione da sottoscrivere.
