### ISSUE TITLE
CM Valle Trompia - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#970]
Buongiorno,
   per conto della CM Valle Trompia si richiede l'aggiornamento dei metadati attualmente deployati con quelli esposti all'endpoint: 

https://www.sportellotelematico.valletrompia.it/sites/default/files/spid-metadata/cmvalletrompia-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
