### ISSUE TITLE
Richiesta controllo metadata - Comune di Carobbio degli Angeli (BG) 

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#975]
Con la presente si richiede la verifica della validità del metadata presente all'url:

https://www.comune.carobbio.bg.it/c016055/spid-metadata.xml

Il servizio in oggetto è stato realizzato con eGovernement Halley già validato in precedenza per altri Enti.

In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
