### ISSUE TITLE
Comune di Calcio - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#978]
Buongiorno,
per conto del Comune di Calcio si chiede l'aggiornamento dei metadati con quelli esposti all'endpoint: https://sportellotelematico.comune.calcio.bg.it/simplesaml/module.php/saml/sp/metadata.php/spid

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
