### ISSUE TITLE
Richiesta verifica metadati Comune di Agugliaro

### ISSUE THREAD

**Issue by halleyveneto** [italia/spid#980]
Buongiorno,
Si richiede la verifica dei metadati per conto del Comune di Agugliaro.
https://www.comune.agugliaro.vi.it/c024001/spid-metadata.xml
Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri clienti.

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
