### ISSUE TITLE
Richiesta validazione metadati IACP di Napoli

### ISSUE THREAD

**Issue by lmilano76** [italia/spid#981]
Buongiorno,
Si richiede la verifica dei metadati per conto dello IACP di NAPOLI (Istituto Autonomo Case Popolari di Napoli).

https://www.iacp.napoli.it/wp-content/plugins/wp-spid-italia/lib/www/module.php/saml/sp/metadata.php/default-sp

Cordiali Saluti
Luigi Milano

**Comment by AntonioGiovanniSchiavone** [comment]
Buongiorno,

Il certificato del protocollo https del dominio iacp.napoli.it è [scaduto](https://www.ssllabs.com/ssltest/analyze.html?d=www.iacp.napoli.it)

**Comment by lmilano76** [comment]
Salve, abbiamo aggiornato il certificato.
Rimaniamo in attesa di un suo gentile riscontro.

Grazie
Luigi Milano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
