### ISSUE TITLE
Controllo metadata - Comune di La Loggia

### ISSUE THREAD

**Issue by falbesano** [italia/spid#983]
Buongiorno,
per conto del Comune di La Loggia, richiediamo la verifica dei metadata pubblicati all'url:
https://sportellodigitale.comune.laloggia.to.it/001127/spid/metadata

Grazie e cordiali saluti
Federico Albesano

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
