### ISSUE TITLE
Richiesta validazione metadata Comune di Calolziocorte - rinnovo metadata

### ISSUE THREAD

**Issue by sofmir** [italia/spid#990]
Nome ente: Comune di Calolziocorte
Url metadata: http://www.comune.calolziocorte.lc.it/index.php/docman/6238-n2002972904/file
Nuovo aggiornamento
Servizio SPID da validare: https://sol.lc-card.it/urbi/progs/urp/crsurlog.sto?Login_Service=https%3A%2F%2Fsol.lc-card.it%2Furbi%2Fprogs%2Furp%2Fur1UR101.sto%3FDB_NAME%3Dn200297%26StwEvent%3D103%26contesto%3DPR%26cod_ambito%3D0%26cod_macrotipo%3D15%26cod_tipo%3D4%26TORNA_ricercaParolaChiave%3D&SOLStwToken=7016802692481044&DB_NAME=n200297&Login_Message=
Contatto riferimento tecnico: ced@comune.calolziocorte.lc.it

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
