### ISSUE TITLE
Comune di Bergamo - Richiesta aggiornamento metadati

### ISSUE THREAD

**Issue by globogis** [italia/spid#991]
Buongiorno,
per conto del Comune di Bergamo si chiede l'aggiornamento dei metadati con i nuovi esposti all'endpoint, non variato, https://www.comune.bergamo.it/sites/default/files/spid-metadata/bergamo-signed.xml

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
