### ISSUE TITLE
Aggiornamento metadati SPID

### ISSUE THREAD

**Issue by ceddesenzano** [italia/spid#992]
Buongiorno,
la presente per richiedere la verifica del nostro metadata per l'aggiunta di un nuovo servizio.

Il metadata è disponibile all'indirizzo:
http://comune.desenzano.brescia.it/_system/xstandard/services/desenzanodelgarda.xml

Cordiali saluti

Margherita Sgalambro

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
