### ISSUE TITLE
 Validazione metadata Comune di Chiari

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#993]
Buongiorno,
per conto del  Comune di Chiari
abbiamo predisposto i metadata  e pubblicati all'URL:

https://chiari.comune-online.it/serviziSPID/metadata.xml

cordiali saluti

Facondini Stefano
Maggioli Spa
 
[metadata_chiari-signed.zip](https://github.com/italia/spid/files/3136986/metadata_chiari-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
--
