### ISSUE TITLE
Validazione metadata Comune di Pinerolo

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#994]
Buongiorno,
per conto del  Comune di Pinerolo

abbiamo predisposto metadata  e pubblicati all'URL

https://pinerolo.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa
 
[metadata_pinerolo-signed.zip](https://github.com/italia/spid/files/3136994/metadata_pinerolo-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
