### ISSUE TITLE
Validazione metadata Comune di Crema

### ISSUE THREAD

**Issue by sfacondini** [italia/spid#995]
Buongiorno,
per conto del  Comune di Crema

abbiamo predisposto metadata  e pubblicati all'URL

https://crema.comune-online.it/serviziSPID/metadata.xml

cordiali saluti
Facondini Stefano
Maggioli Spa

[metadata_crema-signed.zip](https://github.com/italia/spid/files/3137000/metadata_crema-signed.zip)

**Comment by AntonioGiovanniSchiavone** [comment]
Si prega di inviare una mail a spid.tech@agid.gov.it
