### ISSUE TITLE
Richiesta controllo metadata - Unione Dei Comuni Montani Amiata Grossetana (GR)

### ISSUE THREAD

**Issue by HalleyInformatica** [italia/spid#997]
Buongiorno,
con la presente si richiede la verifica della validità del metadata presente all'url:

https://egov.uc-amiata.gr.it/ucmagros/spid-metadata.xml

Il servizio in oggetto è realizzato con eGovernment Halley già validato in precedenza per altri Enti.
In attesa di un vostro riscontro, cordiali saluti.
Halley Informatica

**Comment by AntonioGiovanniSchiavone** [comment]
Il Metadata è stato inoltrato verso gli IdP e da essi caricato.
